# Generated by Django 2.1.2 on 2018-12-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='metric',
            field=models.CharField(choices=[('cpu_core_per_usage_hour', 'cpu_core_per_usage_hour'), ('cpu_core_per_request_hour', 'cpu_core_per_request_hour'), ('memory_gb_per_usage_hour', 'memory_gb_per_usage_hour'), ('memory_gb_per_request_hour', 'memory_gb_per_request_hour')], default='cpu_core_per_usage_hour', max_length=256),
        ),
    ]
