# Generated by Django 2.2 on 2019-04-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190305_2015'),
        ('rates', '0004_auto_20190301_1850'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='RateMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Provider')),
                ('rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rates.Rate')),
            ],
        ),
        migrations.RemoveField(
            model_name='rate',
            name='provider_uuid',
        ),
    ]
