# Generated by Django 3.1.2 on 2020-10-05 19:29
import uuid

import django.contrib.postgres.fields
import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations
from django.db import models

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:


class Migration(migrations.Migration):

    initial = True

    replaces = []

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostModel",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("description", models.TextField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("AWS", "AWS"),
                            ("OCP", "OCP"),
                            ("Azure", "Azure"),
                            ("GCP", "GCP"),
                            ("AWS-local", "AWS-local"),
                            ("Azure-local", "Azure-local"),
                            ("GCP-local", "GCP-local"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("rates", models.JSONField(default=dict)),
                ("markup", models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={"db_table": "cost_model", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="CostModelAudit",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operation", models.CharField(max_length=16)),
                ("audit_timestamp", models.DateTimeField()),
                (
                    "provider_uuids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), null=True, size=None),
                ),
                ("uuid", models.UUIDField()),
                ("name", models.TextField()),
                ("description", models.TextField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("AWS", "AWS"),
                            ("OCP", "OCP"),
                            ("Azure", "Azure"),
                            ("GCP", "GCP"),
                            ("AWS-local", "AWS-local"),
                            ("Azure-local", "Azure-local"),
                            ("GCP-local", "GCP-local"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_timestamp", models.DateTimeField()),
                ("updated_timestamp", models.DateTimeField()),
                ("rates", models.JSONField(default=dict)),
                ("markup", models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={"db_table": "cost_model_audit"},
        ),
        migrations.CreateModel(
            name="CostModelMap",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider_uuid", models.UUIDField(editable=False)),
                (
                    "cost_model",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="cost_models.costmodel"
                    ),
                ),
            ],
            options={"db_table": "cost_model_map", "ordering": ["-id"]},
        ),
        migrations.AddIndex(model_name="costmodel", index=models.Index(fields=["name"], name="name_idx")),
        migrations.AddIndex(
            model_name="costmodel", index=models.Index(fields=["source_type"], name="source_type_idx")
        ),
        migrations.AddIndex(
            model_name="costmodel", index=models.Index(fields=["updated_timestamp"], name="updated_timestamp_idx")
        ),
        migrations.AlterUniqueTogether(name="costmodelmap", unique_together={("provider_uuid", "cost_model")}),
        ###### begin customization; preserve this if you squash migrations ######
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION process_cost_model_audit() RETURNS TRIGGER AS $cost_model_audit$
                DECLARE
                    provider_uuids uuid[];
                BEGIN
                    --
                    -- Create a row in cost_model_audit to reflect the operation performed on cost_model,
                    -- make use of the special variable TG_OP to work out the operation.
                    --
                    IF (TG_OP = 'DELETE') THEN
                        provider_uuids := (SELECT array_agg(provider_uuid) FROM cost_model_map WHERE cost_model_id = OLD.uuid);
                        INSERT INTO cost_model_audit SELECT nextval('cost_model_audit_id_seq'), 'DELETE', now(), provider_uuids, OLD.*;
                        RETURN OLD;
                    ELSIF (TG_OP = 'UPDATE') THEN
                        provider_uuids := (SELECT array_agg(provider_uuid) FROM cost_model_map WHERE cost_model_id = NEW.uuid);
                        INSERT INTO cost_model_audit SELECT nextval('cost_model_audit_id_seq'), 'UPDATE', now(), provider_uuids, NEW.*;
                        RETURN NEW;
                    ELSIF (TG_OP = 'INSERT') THEN
                        provider_uuids := (SELECT array_agg(provider_uuid) FROM cost_model_map WHERE cost_model_id = NEW.uuid);
                        INSERT INTO cost_model_audit SELECT nextval('cost_model_audit_id_seq'), 'INSERT', now(), provider_uuids, NEW.*;
                        RETURN NEW;
                    END IF;
                    RETURN NULL; -- result is ignored since this is an AFTER trigger
                END;
            $cost_model_audit$ LANGUAGE plpgsql;

            CREATE TRIGGER cost_model_audit
            AFTER INSERT OR UPDATE OR DELETE ON cost_model
                FOR EACH ROW EXECUTE PROCEDURE process_cost_model_audit();
            """
        ),
        ###### end customization ######
    ]
