# Generated by Django 3.1.2 on 2020-10-05 19:29
import uuid

import django.contrib.postgres.fields
import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ("cost_models", "0001_initial_squashed_0018_auto_20200116_2048"),
        ("cost_models", "0002_auto_20200318_1233"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostModel",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("description", models.TextField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("AWS", "AWS"),
                            ("OCP", "OCP"),
                            ("Azure", "Azure"),
                            ("GCP", "GCP"),
                            ("AWS-local", "AWS-local"),
                            ("Azure-local", "Azure-local"),
                            ("GCP-local", "GCP-local"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("rates", models.JSONField(default=dict)),
                ("markup", models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={"db_table": "cost_model", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="CostModelAudit",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operation", models.CharField(max_length=16)),
                ("audit_timestamp", models.DateTimeField()),
                (
                    "provider_uuids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), null=True, size=None),
                ),
                ("uuid", models.UUIDField()),
                ("name", models.TextField()),
                ("description", models.TextField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("AWS", "AWS"),
                            ("OCP", "OCP"),
                            ("Azure", "Azure"),
                            ("GCP", "GCP"),
                            ("AWS-local", "AWS-local"),
                            ("Azure-local", "Azure-local"),
                            ("GCP-local", "GCP-local"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_timestamp", models.DateTimeField()),
                ("updated_timestamp", models.DateTimeField()),
                ("rates", models.JSONField(default=dict)),
                ("markup", models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={"db_table": "cost_model_audit"},
        ),
        migrations.CreateModel(
            name="CostModelMap",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider_uuid", models.UUIDField(editable=False)),
                (
                    "cost_model",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="cost_models.costmodel"
                    ),
                ),
            ],
            options={"db_table": "cost_model_map", "ordering": ["-id"]},
        ),
        migrations.AddIndex(model_name="costmodel", index=models.Index(fields=["name"], name="name_idx")),
        migrations.AddIndex(
            model_name="costmodel", index=models.Index(fields=["source_type"], name="source_type_idx")
        ),
        migrations.AddIndex(
            model_name="costmodel", index=models.Index(fields=["updated_timestamp"], name="updated_timestamp_idx")
        ),
        migrations.AlterUniqueTogether(name="costmodelmap", unique_together={("provider_uuid", "cost_model")}),
    ]
