# Generated by Django 2.1.2 on 2018-12-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='metric',
            field=models.CharField(choices=[('cpu_core_usage_per_hour', 'cpu_core_usage_per_hour'), ('cpu_core_request_per_hour', 'cpu_core_request_per_hour'), ('memory_gb_usage_per_hour', 'memory_gb_usage_per_hour'), ('memory_gb_request_per_hour', 'memory_gb_request_per_hour')], default='cpu_core_usage_per_hour', max_length=256),
        ),
    ]
