# Generated by Django 2.2.15 on 2020-08-31 15:57
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cost_models", "0002_auto_20200318_1233")]

    operations = [
        migrations.AddField(
            model_name="costmodel",
            name="tag_rates",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="costmodelaudit",
            name="tag_rates",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
