# Generated by Django 3.1.12 on 2021-06-11 18:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("cost_models", "0002_auto_20210318_1514")]

    operations = [
        migrations.AddField(
            model_name="costmodel",
            name="distribution",
            field=models.TextField(choices=[("memory", "memory"), ("cpu", "cpu")], null=True),
        ),
        migrations.AddField(
            model_name="costmodelaudit",
            name="distribution",
            field=models.TextField(choices=[("memory", "memory"), ("cpu", "cpu")], null=True),
        ),
    ]
