# Generated by Django 3.1.13 on 2021-09-02 13:23
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("cost_models", "0003_auto_20210615_2011")]

    operations = [
        migrations.AddField(
            model_name="costmodel",
            name="currency",
            field=models.TextField(
                choices=[
                    ("AUD", "AUD"),
                    ("CAD", "CAD"),
                    ("CHF", "CHF"),
                    ("CNY", "CNY"),
                    ("DKK", "DKK"),
                    ("EUR", "EUR"),
                    ("GBP", "GBP"),
                    ("HKD", "HKD"),
                    ("JPY", "JPY"),
                    ("NOK", "NOK"),
                    ("NZD", "NZD"),
                    ("SEK", "SEK"),
                    ("SGD", "SGD"),
                    ("USD", "USD"),
                    ("ZAR", "ZAR"),
                ],
                default="USD",
            ),
        ),
        migrations.AddField(
            model_name="costmodelaudit",
            name="currency",
            field=models.TextField(
                choices=[
                    ("AUD", "AUD"),
                    ("CAD", "CAD"),
                    ("CHF", "CHF"),
                    ("CNY", "CNY"),
                    ("DKK", "DKK"),
                    ("EUR", "EUR"),
                    ("GBP", "GBP"),
                    ("HKD", "HKD"),
                    ("JPY", "JPY"),
                    ("NOK", "NOK"),
                    ("NZD", "NZD"),
                    ("SEK", "SEK"),
                    ("SGD", "SGD"),
                    ("USD", "USD"),
                    ("ZAR", "ZAR"),
                ],
                default="USD",
            ),
        ),
    ]
