# Generated by Django 3.1.13 on 2021-09-03 15:59
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("cost_models", "0003_auto_20210615_2011")]

    operations = [
        migrations.AddField(model_name="costmodel", name="currency", field=models.TextField(default="USD")),
        migrations.AddField(model_name="costmodelaudit", name="currency", field=models.TextField(default="USD")),
    ]
