# Generated by Django 4.2.20 on 2025-05-07 10:42
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_models", "0007_net_stor_distribute_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costmodel",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("AWS", "AWS"),
                    ("OCP", "OCP"),
                    ("Azure", "Azure"),
                    ("GCP", "GCP"),
                    ("IBM", "IBM"),
                    ("AWS-local", "AWS-local"),
                    ("Azure-local", "Azure-local"),
                    ("GCP-local", "GCP-local"),
                    ("IBM-local", "IBM-local"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="costmodelaudit",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("AWS", "AWS"),
                    ("OCP", "OCP"),
                    ("Azure", "Azure"),
                    ("GCP", "GCP"),
                    ("IBM", "IBM"),
                    ("AWS-local", "AWS-local"),
                    ("Azure-local", "Azure-local"),
                    ("GCP-local", "GCP-local"),
                    ("IBM-local", "IBM-local"),
                ],
                max_length=50,
            ),
        ),
    ]
