# Generated by Django 2.2.4 on 2019-08-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_models', '0008_auto_20190812_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costmodel',
            name='source_type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('OCP', 'OCP'), ('AZURE', 'AZURE'), ('AWS-local', 'AWS-local'), ('OCP-local', 'OCP-local')], max_length=50),
        ),
    ]
