# Generated by Django 4.2.21 on 2025-06-13 13:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_models", "0008_alter_costmodel_source_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costmodel",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("AWS", "AWS"),
                    ("OCP", "OCP"),
                    ("Azure", "Azure"),
                    ("GCP", "GCP"),
                    ("AWS-local", "AWS-local"),
                    ("Azure-local", "Azure-local"),
                    ("GCP-local", "GCP-local"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="costmodelaudit",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("AWS", "AWS"),
                    ("OCP", "OCP"),
                    ("Azure", "Azure"),
                    ("GCP", "GCP"),
                    ("AWS-local", "AWS-local"),
                    ("Azure-local", "Azure-local"),
                    ("GCP-local", "GCP-local"),
                ],
                max_length=50,
            ),
        ),
    ]
