# Generated by Django 5.2.11 on 2026-03-12 09:18
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_models", "0009_alter_costmodel_source_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
                ),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("currency", models.TextField()),
                ("effective_start_date", models.DateField()),
                ("effective_end_date", models.DateField()),
                ("enabled", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("rates", models.JSONField()),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "price_list",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="price_list_name_idx"),
                    models.Index(
                        fields=["effective_start_date", "effective_end_date"],
                        name="price_list_validity_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceListCostModelMap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.PositiveIntegerField()),
                (
                    "cost_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_list_maps",
                        to="cost_models.costmodel",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_model_maps",
                        to="cost_models.pricelist",
                    ),
                ),
            ],
            options={
                "db_table": "price_list_cost_model_map",
                "ordering": ["priority"],
                "unique_together": {("price_list", "cost_model")},
            },
        ),
    ]
