# Generated by Django 2.2.4 on 2019-09-05 19:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_models', '0010_auto_20190827_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostModelAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=16)),
                ('audit_timestamp', models.DateTimeField()),
                ('provider_uuids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), null=True, size=None)),
                ('uuid', models.UUIDField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('source_type', models.CharField(choices=[('AWS', 'AWS'), ('OCP', 'OCP'), ('AZURE', 'AZURE'), ('AWS-local', 'AWS-local'), ('AZURE-local', 'AZURE-local')], max_length=50)),
                ('created_timestamp', models.DateTimeField()),
                ('updated_timestamp', models.DateTimeField()),
                ('rates', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'cost_model_audit',
            },
        ),
    ]
