# Generated by Django 2.2.4 on 2019-09-06 21:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_models', '0010_auto_20190827_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='costmodel',
            name='markups',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
