# Generated by Django 2.2.4 on 2019-09-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_models', '0011_costmodel_markups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costmodel',
            old_name='markups',
            new_name='markup',
        ),
    ]
