# Generated by Django 5.2.11 on 2026-04-06 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_models", "0011_migrate_cost_model_rates_to_price_lists"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("custom_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                ("metric", models.CharField(max_length=100)),
                ("metric_type", models.CharField(max_length=20)),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("Infrastructure", "Infrastructure"),
                            ("Supplementary", "Supplementary"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "default_rate",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                ("tag_key", models.CharField(blank=True, default="", max_length=253)),
                ("tag_values", models.JSONField(default=list)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_rows",
                        to="cost_models.pricelist",
                    ),
                ),
            ],
            options={
                "db_table": "cost_model_rate",
                "indexes": [
                    models.Index(fields=["price_list"], name="rate_price_list_idx"),
                    models.Index(fields=["custom_name"], name="rate_custom_name_idx"),
                    models.Index(fields=["metric"], name="rate_metric_idx"),
                ],
                "unique_together": {("price_list", "custom_name")},
            },
        ),
    ]
