# Generated by Django 2.2.4 on 2019-09-10 19:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_models', '0012_auto_20190905_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='costmodel',
            name='markup',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
