# Generated by Django 2.2.4 on 2019-09-10 20:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_models', '0013_costmodel_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='costmodelaudit',
            name='markup',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
