# Generated by Django 2.2.4 on 2019-09-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_models', '0014_costmodelaudit_markup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costmodel',
            name='source_type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('OCP', 'OCP'), ('AZURE', 'AZURE'), ('GCP', 'GCP'), ('AWS-local', 'AWS-local'), ('AZURE-local', 'AZURE-local'), ('GCP-local', 'GCP-local')], max_length=50),
        ),
        migrations.AlterField(
            model_name='costmodelaudit',
            name='source_type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('OCP', 'OCP'), ('AZURE', 'AZURE'), ('GCP', 'GCP'), ('AWS-local', 'AWS-local'), ('AZURE-local', 'AZURE-local'), ('GCP-local', 'GCP-local')], max_length=50),
        ),
    ]
