# Generated by Django 2.2.8 on 2019-12-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_models', '0016_auto_20190925_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costmodel',
            name='source_type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('OCP', 'OCP'), ('AZURE', 'AZURE'), ('GCP', 'GCP')], max_length=50),
        ),
        migrations.AlterField(
            model_name='costmodelaudit',
            name='source_type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('OCP', 'OCP'), ('AZURE', 'AZURE'), ('GCP', 'GCP')], max_length=50),
        ),
    ]
