# Generated by Django 2.2.8 on 2019-12-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_models', '0016_auto_20190925_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costmodel',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='costmodel',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='costmodel',
            index=models.Index(fields=['source_type'], name='source_type_idx'),
        ),
        migrations.AddIndex(
            model_name='costmodel',
            index=models.Index(fields=['updated_timestamp'], name='updated_timestamp_idx'),
        ),
    ]
