# Generated by Django 5.2.13 on 2026-04-27 10:58
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_models', '0013_normalize_rates_to_rate_table'),
        ('cost_models', '0016_rename_enabledcurrency_to_currencyconfig'),
    ]

    operations = [
    ]
