CREATE TABLE IF NOT EXISTS hive.{{schema | sqlsafe}}.managed_gcp_openshift_daily_temp
(
    row_uuid varchar,
    invoice_month varchar,
    account_id varchar,
    project_id varchar,
    usage_start timestamp(3),
    data_transfer_direction varchar,
    service_id varchar,
    sku_id varchar,
    system_labels varchar,
    labels varchar,
    cost_type varchar,
    region varchar,
    resource_name varchar,
    instance_type varchar,
    project_name varchar,
    service_description varchar,
    service_alias varchar,
    sku_description varchar,
    sku_alias varchar,
    unit varchar,
    usage_amount double,
    currency varchar,
    unblended_cost double,
    credit_amount double,
    resource_global_name varchar,
    resource_id_matched boolean,
    matched_tag varchar,
    ocp_source varchar,
    source varchar,
    year varchar,
    month varchar,
    day varchar
) WITH(
    format = 'PARQUET',
    partitioned_by=ARRAY['ocp_source', 'source', 'year', 'month', 'day']
);

CREATE TABLE IF NOT EXISTS hive.{{schema | sqlsafe}}.managed_gcp_uuid_temp
(
    row_uuid varchar,
    invoice_month varchar,
    billing_account_id varchar,
    project_id varchar,
    usage_start_time timestamp(3),
    service_id varchar,
    sku_id varchar,
    system_labels varchar,
    labels varchar,
    cost_type varchar,
    location_region varchar,
    resource_name varchar,
    project_name varchar,
    service_description varchar,
    sku_description varchar,
    usage_pricing_unit varchar,
    usage_amount_in_pricing_units double,
    currency varchar,
    cost double,
    daily_credits double,
    resource_global_name varchar,
    source varchar,
    year varchar,
    month varchar,
    day varchar
) WITH(
    format = 'PARQUET',
    partitioned_by=ARRAY['source', 'year', 'month', 'day']
);

DELETE FROM hive.{{schema | sqlsafe}}.managed_gcp_uuid_temp
WHERE source = {{cloud_provider_uuid}}
        AND year = {{year}}
        AND month = {{month}}
;

-- Populate the possible rows of GCP data assigning a uuid to each row
INSERT INTO hive.{{schema | sqlsafe}}.managed_gcp_uuid_temp (
    row_uuid,
    invoice_month,
    billing_account_id,
    project_id,
    usage_start_time,
    service_id,
    sku_id,
    system_labels,
    labels,
    cost_type,
    location_region,
    resource_name,
    project_name,
    service_description,
    sku_description,
    usage_pricing_unit,
    usage_amount_in_pricing_units,
    currency,
    cost,
    daily_credits,
    resource_global_name,
    source,
    year,
    month,
    day
)
SELECT cast(uuid() as varchar) as row_uuid,
    gcp.invoice_month,
    gcp.billing_account_id,
    gcp.project_id,
    gcp.usage_start_time,
    gcp.service_id,
    gcp.sku_id,
    gcp.system_labels,
    gcp.labels,
    gcp.cost_type,
    gcp.location_region,
    gcp.resource_name,
    gcp.project_name,
    gcp.service_description,
    gcp.sku_description,
    gcp.usage_pricing_unit,
    gcp.usage_amount_in_pricing_units,
    gcp.currency,
    gcp.cost,
    gcp.daily_credits,
    gcp.resource_global_name,
    gcp.source as source,
    gcp.year,
    gcp.month,
    cast(day(gcp.usage_start_time) as varchar) as day
FROM hive.{{schema | sqlsafe}}.gcp_line_items_daily AS gcp
WHERE gcp.source = {{cloud_provider_uuid}}
    AND gcp.year = {{year}}
    AND gcp.month= {{month}}
    AND gcp.usage_start_time >= {{start_date}}
    AND gcp.usage_start_time < date_add('day', 1, {{end_date}});

CREATE TABLE IF NOT EXISTS hive.{{schema | sqlsafe}}.managed_reporting_ocpgcpcostlineitem_project_daily_summary_temp
(
    row_uuid varchar,
    cluster_id varchar,
    cluster_alias varchar,
    data_source varchar,
    namespace varchar,
    node varchar,
    persistentvolumeclaim varchar,
    persistentvolume varchar,
    storageclass varchar,
    pod_labels varchar,
    resource_name varchar,
    resource_id varchar,
    usage_start timestamp,
    usage_end timestamp,
    account_id varchar,
    project_id varchar,
    project_name varchar,
    instance_type varchar,
    service_id varchar,
    service_alias varchar,
    sku_id varchar,
    sku_alias varchar,
    region varchar,
    unit varchar,
    usage_amount double,
    currency varchar,
    invoice_month varchar,
    credit_amount double,
    unblended_cost double,
    markup_cost double,
    project_markup_cost double,
    pod_cost double,
    pod_credit double,
    pod_effective_usage_cpu_core_hours double,
    pod_effective_usage_memory_gigabyte_hours double,
    node_capacity_cpu_core_hours double,
    node_capacity_memory_gigabyte_hours double,
    volume_labels varchar,
    tags varchar,
    cost_category_id int,
    project_rank integer,
    data_source_rank integer,
    resource_id_matched boolean,
    matched_tag varchar,
    source varchar,
    ocp_source varchar,
    year varchar,
    month varchar
) WITH(format = 'PARQUET', partitioned_by=ARRAY['source', 'ocp_source', 'year', 'month'])
;

-- Now create our proper table if it does not exist
CREATE TABLE IF NOT EXISTS hive.{{schema | sqlsafe}}.managed_reporting_ocpgcpcostlineitem_project_daily_summary
(
    row_uuid varchar,
    cluster_id varchar,
    cluster_alias varchar,
    data_source varchar,
    namespace varchar,
    node varchar,
    persistentvolumeclaim varchar,
    persistentvolume varchar,
    storageclass varchar,
    pod_labels varchar,
    resource_id varchar,
    usage_start timestamp,
    usage_end timestamp,
    account_id varchar,
    project_id varchar,
    project_name varchar,
    instance_type varchar,
    service_id varchar,
    service_alias varchar,
    data_transfer_direction varchar,
    sku_id varchar,
    sku_alias varchar,
    region varchar,
    unit varchar,
    usage_amount double,
    currency varchar,
    invoice_month varchar,
    credit_amount double,
    unblended_cost double,
    markup_cost double,
    project_markup_cost double,
    pod_cost double,
    pod_credit double,
    node_capacity_cpu_core_hours double,
    node_capacity_memory_gigabyte_hours double,
    volume_labels varchar,
    tags varchar,
    cost_category_id int,
    project_rank integer,
    data_source_rank integer,
    resource_id_matched boolean,
    matched_tag varchar,
    source varchar,
    ocp_source varchar,
    year varchar,
    month varchar,
    day varchar
) WITH(format = 'PARQUET', partitioned_by=ARRAY['source', 'ocp_source', 'year', 'month', 'day'])
;
