from django.db import models


class CustomerTotalData(models.Model):
    class Meta:
        db_table = "__customer_total_data"
        ordering = ["date"]

    date = models.DateField(unique=True)
    total_aws_unblended_cost = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_aws_calculated_amortized_cost = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_azure_pretax_cost = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_gcp_unblended_cost = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_gcp_total = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_oci_total = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_total_infrastructure_raw_cost = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_total_cost_model_costs = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_infra_total_cost_model = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_infra_cost_model_cpu_cost = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_infra_cost_model_memory_cost = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_infra_cost_model_volume_cost = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_sup_total_cost_model = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_sup_cost_model_cpu_cost = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_sup_cost_model_memory_cost = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_sup_cost_model_volume_cost = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_cluster_count = models.IntegerField(null=True)
    total_node_count = models.IntegerField(null=True)
    total_infra_node_count = models.IntegerField(null=True)
    total_control_plane_node_count = models.IntegerField(null=True)
    total_worker_node_count = models.IntegerField(null=True)
    total_infra_node_cpu_cores = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_control_plane_node_cpu_cores = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_worker_node_cpu_cores = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_infra_node_mem_gb = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_control_plane_node_mem_gb = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_worker_node_mem_gb = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_pvc_count = models.IntegerField(null=True)
    total_cluster_capacity_cores = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_cluster_capacity_core_hours = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_cluster_capacity_memory_gb = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_cluster_capacity_memory_gb_hours = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_volume_request_gb = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_volume_request_gb_mo = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_pvc_capacity_gb = models.DecimalField(decimal_places=2, max_digits=33, null=True)
    total_pvc_capacity_gb_mo = models.DecimalField(decimal_places=2, max_digits=33, null=True)
