codecov:
  notify:
    require_ci_to_pass: yes
  strict_yaml_branch: master  # only use the latest copy on master branch

coverage:
  precision: 1
  round: nearest
  range: "80...100"

  status:
    project:
      default:
        target: 90
    patch:
      default:
        target: 90
        threshold: 5
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
