FROM quay.io/cloudservices/ubi-trino:348-001

ARG USER_ID=1000

USER root

RUN groupadd -g ${USER_ID} trino \
    && useradd -m -s /bin/bash -g ${USER_ID} -u ${USER_ID} -G root trino \
    && chmod g+rwx /opt

USER trino

RUN umask u=rwx,g=rwx,o=rx
