FROM python:3.6-alpine
ENV PYTHONUNBUFFERED 1

RUN apk add --no-cache --virtual .build-deps \
    ca-certificates gcc postgresql-dev linux-headers musl-dev \
    libffi-dev jpeg-dev zlib-dev git

ADD Pipfile /Pipfile
ADD Pipfile.lock /Pipfile.lock

RUN pip install --upgrade pip
RUN pip install pipenv
RUN pip install pipenv-to-requirements
RUN pipenv run pipenv_to_requirements -f
RUN pip install -r requirements.txt
