line-length = 119
target-version = "py311"

extend-exclude=["**/migrations/*.py"]

[format]


[lint]
# F https://docs.astral.sh/ruff/rules/#pyflakes-f
# E, W https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
# C90 https://docs.astral.sh/ruff/rules/#mccabe-c90
# UP https://docs.astral.sh/ruff/rules/#pyupgrade-up
select = ["F", "E", "W", "C90", "UP"]
# extend-select = ["UP"]

[lint.per-file-ignores]
# Ignore `F401` (unused import) in all `__init__.py`, `models.py`, and `views.py` files.
"**/__init__.py" = ["F401"]
"**/models.py" = ["F401"]
"**/views.py" = ["F401"]

[lint.isort]
case-sensitive = false
force-single-line = true
known-first-party = ["koku", "api", "common", "cost_models", "forecast", "hcs", "kafka_utils", "key_metrics", "masu", "providers", "reporting", "reporting_common", "sources", "subs"]
no-lines-before = ["future", "standard-library"]
order-by-type = false
