# Generated by Django 3.1.13 on 2021-08-15 18:51
import django.db.models.deletion
from django.db import migrations
from django.db import models

from currency.common import load_currencies_from_file


def populate_currencies(apps, schema_editor):
    CurrencyOptions = apps.get_model("currency", "CurrencyOptions")
    for currency in load_currencies_from_file():
        CurrencyOptions.objects.create(
            code=currency.get("code"),
            name=currency.get("name"),
            symbol=currency.get("symbol"),
            description=currency.get("description"),
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [("api", "0048_new_partition_manager_func")]

    operations = [
        migrations.CreateModel(
            name="CurrencyOptions",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=150)),
                ("symbol", models.CharField(max_length=150)),
                ("description", models.TextField()),
            ],
            options={"db_table": "currency_options", "ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="CurrencySettings",
            fields=[
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.customer",
                    ),
                ),
                ("currency_code", models.ForeignKey(on_delete=models.SET("USD"), to="currency.currencyoptions")),
            ],
            options={"db_table": "currency_settings", "ordering": ["currency_code"]},
        ),
        migrations.RunPython(populate_currencies),
    ]
