# Generated by Django 2.0.4 on 2018-04-27 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
