# Generated by Django 2.0.4 on 2018-05-09 18:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180509_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(default=uuid.UUID('b87621e4-d528-431e-b4ae-5b87d1c102b7'), editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('394ecc0b-d5bb-4475-82a0-2257aadf7757'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.User'),
        ),
    ]
