# Generated by Django 2.1.2 on 2018-10-08 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180926_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='authentication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.ProviderAuthentication'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='billing_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.ProviderBillingSource'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Customer'),
        ),
    ]
