# Generated by Django 2.1.2 on 2018-10-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181008_1819'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together={('authentication', 'billing_source')},
        ),
    ]
