# Generated by Django 2.1.2 on 2018-11-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181109_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
