# Generated by Django 2.1.5 on 2019-03-05 20:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181213_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preference',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
