# Generated by Django 2.0.5 on 2018-05-22 22:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'ordering': ['preference']},
        ),
        migrations.AddField(
            model_name='userpreference',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='name',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
