# Generated by Django 2.2 on 2019-05-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('api', '0008_auto_20190305_2015'),
        ('api', '0001_initial_squashed_0008_auto_20190305_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Ready'), (33, 'Warning'), (98, 'Disabled: Error'), (99, 'Disabled: Admin')], default=0)),
                ('last_message', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('retries', models.IntegerField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Provider')),
            ],
        ),
    ]
