# Generated by Django 2.2.1 on 2019-05-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_providerstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostModelMetricsMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('AWS', 'AWS'), ('OCP', 'OCP'), ('AWS-local', 'AWS-local'), ('OCP-local', 'OCP-local')], max_length=50)),
                ('metric', models.CharField(choices=[('cpu_core_usage_per_hour', 'cpu_core_usage_per_hour'), ('cpu_core_request_per_hour', 'cpu_core_request_per_hour'), ('memory_gb_usage_per_hour', 'memory_gb_usage_per_hour'), ('memory_gb_request_per_hour', 'memory_gb_request_per_hour'), ('storage_gb_usage_per_month', 'storage_gb_usage_per_month'), ('storage_gb_request_per_month', 'storage_gb_request_per_month')], max_length=256)),
                ('ui_metric', models.CharField(max_length=256)),
                ('ui_measurement', models.CharField(max_length=256)),
                ('ui_measurement_unit', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'cost_models_metrics_map',
                'unique_together': {('source_type', 'metric')},
            },
        ),
    ]
