# Generated by Django 2.2.9 on 2020-02-04 16:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0010_auto_20200128_2138")]

    operations = [
        migrations.AlterUniqueTogether(
            name="provider", unique_together={("authentication", "billing_source", "customer")}
        )
    ]
