# Generated by Django 2.2.1 on 2019-05-30 19:35
import json
import pkgutil

from django.db import migrations, models

def load_openshift_metric_map(apps, schema_editor):
    """Load AWS Cost Usage report to database mapping."""
    CostModelMetricsMap = apps.get_model('api', 'CostModelMetricsMap')

    data = pkgutil.get_data('api',
                            'metrics/data/cost_models_metric_map.json')

    data = json.loads(data)

    for entry in data:
        map = CostModelMetricsMap(**entry)
        map.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_costmodelmetricsmap'),
    ]

    operations = [
        migrations.RunPython(load_openshift_metric_map),
    ]
