# Generated by Django 2.2.10 on 2020-02-25 20:22
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0011_auto_20200204_1647")]

    operations = [migrations.DeleteModel(name="UserPreference")]
