# Generated by Django 2.2.4 on 2019-08-12 18:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190723_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerauthentication',
            name='credentials',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='providerbillingsource',
            name='data_source',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='costmodelmetricsmap',
            name='source_type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('OCP', 'OCP'), ('AZURE', 'AZURE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('OCP', 'OCP'), ('AZURE', 'AZURE')], default='AWS', max_length=50),
        ),
        migrations.AlterField(
            model_name='providerauthentication',
            name='provider_resource_name',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='providerbillingsource',
            name='bucket',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddConstraint(
            model_name='providerauthentication',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('provider_resource_name', None), ('credentials', {})), _negated=True), name='credentials_and_resource_name_both_null'),
        ),
        migrations.AddConstraint(
            model_name='providerauthentication',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(_negated=True, provider_resource_name=None), models.Q(_negated=True, credentials={})), _negated=True), name='credentials_and_resource_name_both_not_null'),
        ),
        migrations.AddConstraint(
            model_name='providerbillingsource',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('bucket', None), ('data_source', {})), _negated=True), name='bucket_and_data_source_both_null'),
        ),
        migrations.AddConstraint(
            model_name='providerbillingsource',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(_negated=True, bucket=None), models.Q(_negated=True, data_source={})), _negated=True), name='bucket_and_data_source_both_not_null'),
        ),
    ]
