# Generated by Django 2.2.3 on 2019-08-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190723_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerstatus',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
