# Generated by Django 2.2.10 on 2020-02-26 19:53
import json
import pkgutil

from django.db import migrations
from django.db import models


def reload_cost_model_metric_map(apps, schema_editor):
    """Load cost model metrics."""
    CostModelMetricsMap = apps.get_model("api", "CostModelMetricsMap")
    CostModelMetricsMap.objects.all().delete()

    data = pkgutil.get_data("api", "metrics/data/cost_models_metric_map.json")

    data = json.loads(data)

    for entry in data:
        map = CostModelMetricsMap(**entry)
        map.save()


class Migration(migrations.Migration):

    dependencies = [("api", "0012_auto_20200225_2022")]

    operations = [
        migrations.AddField(
            model_name="costmodelmetricsmap",
            name="default_cost_type",
            field=models.TextField(
                choices=[("Infrastructure", "Infrastructure"), ("Supplementary", "Supplementary")], null=True
            ),
        ),
        migrations.RunPython(reload_cost_model_metric_map),
    ]
