# Generated by Django 2.2.10 on 2020-02-26 19:53
import json
import pkgutil

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0012_auto_20200225_2022")]

    operations = [
        migrations.AddField(
            model_name="costmodelmetricsmap",
            name="default_cost_type",
            field=models.TextField(
                choices=[("Infrastructure", "Infrastructure"), ("Supplementary", "Supplementary")], null=True
            ),
        )
    ]
