# Generated by Django 2.2.10 on 2020-03-04 16:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0013_auto_20200226_1953")]

    operations = [
        migrations.AlterModelOptions(name="sources", options={"ordering": ["name"]}),
        migrations.AddField(model_name="sources", name="provider_linked", field=models.BooleanField(default=False)),
    ]
