# Generated by Django 2.0.5 on 2018-06-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_costentrystatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costentrystatus',
            name='customer',
        ),
        migrations.AddField(
            model_name='costentrystatus',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Provider'),
        ),
    ]
