# Generated by Django 2.0.6 on 2018-06-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_costusagereportstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costusagereportstatus',
            name='provider',
        ),
        migrations.DeleteModel(
            name='CostUsageReportStatus',
        ),
    ]
