# Generated by Django 2.1 on 2018-08-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180614_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('Local', 'Local')], default='AWS', max_length=50),
        ),
    ]
