# Generated by Django 2.2.11 on 2020-03-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200311_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sources',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='provider',
            name='id',
        ),
        migrations.AlterField(
            model_name='sources',
            name='koku_uuid',
            field=models.CharField(max_length=512, null=True, unique=True),
        ),
    ]
