# Generated by Django 2.0.5 on 2018-06-06 19:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180606_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='costentrystatus',
            name='etag',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
