# Generated by Django 2.1 on 2018-08-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180802_1911'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpreference',
            unique_together={('name', 'user')},
        ),
    ]
