# Generated by Django 2.1 on 2018-08-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180802_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('AWS', 'AWS')], default='AWS', max_length=50),
        ),
    ]
