# Generated by Django 2.1 on 2018-09-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180815_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
