# Generated by Django 2.1 on 2018-09-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180815_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='report_processed',
            field=models.BooleanField(default=False),
        ),
    ]
