# Generated by Django 2.2.11 on 2020-03-26 01:02
import json
import pkgutil

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0017_delete_cloudaccount")]

    operations = []
