# Generated by Django 2.2.4 on 2019-09-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190827_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('source_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('source_type', models.CharField(max_length=50)),
                ('authentication', models.CharField(max_length=128)),
                ('billing_source', models.CharField(max_length=128, null=True)),
                ('koku_uuid', models.CharField(max_length=512, null=True)),
                ('auth_header', models.CharField(max_length=512, null=True)),
            ],
            options={
                'db_table': 'api_sources',
            },
        ),
    ]
