# Generated by Django 2.1 on 2018-09-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='report_processed',
            field=models.BooleanField(default=False),
        ),
    ]
