# Generated by Django 2.2.4 on 2019-09-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190827_1536'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='providerbillingsource',
            name='bucket_and_data_source_both_not_null',
        ),
        migrations.AddConstraint(
            model_name='providerbillingsource',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(models.Q(('bucket', None), ('bucket', ''), _connector='OR'), _negated=True), models.Q(_negated=True, data_source={})), _negated=True), name='bucket_and_data_source_both_not_null'),
        ),
    ]
