# Generated by Django 2.1 on 2018-09-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_provider_setup_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('AWS-local', 'AWS-local')], default='AWS', max_length=50),
        ),
    ]
