# Generated by Django 2.2.12 on 2020-08-06 18:17
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0020_sources_out_of_order_delete")]

    operations = [migrations.DeleteModel(name="ProviderStatus")]
