# Generated by Django 2.2.11 on 2020-04-20 21:05
import os
from importlib.machinery import SourceFileLoader

from django.db import connection
from django.db import migrations

curr_path = os.path.abspath(__file__).split(os.path.sep)
mod_path = os.path.join(
    os.path.sep, *curr_path[: curr_path.index("koku") + 1], "scripts", "set_autovacuum_table_parameter.py"
)

loader = SourceFileLoader("koku_autovacuum", mod_path)
koku_autovacuum = loader.load_module()


def set_autovacuum_wrapper(apps, schema_editor):
    koku_autovacuum.django_set_autovacuum_scale_factor(connection)


class Migration(migrations.Migration):

    dependencies = [("api", "0020_sources_out_of_order_delete")]

    operations = [migrations.RunPython(code=set_autovacuum_wrapper)]
