# Generated by Django 2.2.4 on 2019-09-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='authentication',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sources',
            name='billing_source',
            field=models.TextField(null=True),
        ),
    ]
