# Generated by Django 2.2.4 on 2019-09-18 17:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='authentication',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sources',
            name='billing_source',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
