# Generated by Django 2.2.13 on 2020-08-03 17:36
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0020_sources_out_of_order_delete")]

    operations = [
        migrations.RemoveConstraint(
            model_name="providerauthentication", name="credentials_and_resource_name_both_null"
        ),
        migrations.RemoveConstraint(model_name="providerbillingsource", name="bucket_and_data_source_both_null"),
        migrations.RemoveField(model_name="providerauthentication", name="provider_resource_name"),
        migrations.RemoveField(model_name="providerbillingsource", name="bucket"),
        migrations.AlterField(
            model_name="providerauthentication",
            name="credentials",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="providerbillingsource",
            name="data_source",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
