# Generated by Django 2.2.15 on 2020-08-12 19:45
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0021_delete_providerstatus")]

    operations = [
        migrations.RunSQL(
            """
            UPDATE api_provider SET billing_source_id = (SELECT id FROM api_providerbillingsource WHERE data_source = '{"bucket": ""}'::jsonb) WHERE billing_source_id = (SELECT id FROM api_providerbillingsource WHERE bucket = '' and data_source = '{}'::jsonb);
            DELETE FROM api_providerbillingsource WHERE data_source = '{"bucket": ""}'::jsonb;
            UPDATE api_providerbillingsource SET data_source = jsonb_build_object('bucket', bucket) WHERE data_source = '{}'::jsonb;
            UPDATE api_providerauthentication SET credentials = jsonb_build_object('provider_resource_name', provider_resource_name) WHERE credentials = '{}'::jsonb;
            """
        ),
        migrations.RemoveConstraint(
            model_name="providerauthentication", name="credentials_and_resource_name_both_null"
        ),
        migrations.RemoveConstraint(model_name="providerbillingsource", name="bucket_and_data_source_both_null"),
        migrations.RemoveField(model_name="providerauthentication", name="provider_resource_name"),
        migrations.RemoveField(model_name="providerbillingsource", name="bucket"),
        migrations.AlterField(
            model_name="providerauthentication",
            name="credentials",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, unique=True),
        ),
        migrations.AlterField(
            model_name="providerbillingsource",
            name="data_source",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, unique=True),
        ),
    ]
