# Generated by Django 2.2.15 on 2020-08-12 19:45
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0021_delete_providerstatus")]

    operations = [
        migrations.RunSQL(
            """
                UPDATE
                    api_provider
                SET
                    billing_source_id =
                    (
                        SELECT
                            id
                        FROM
                            api_providerbillingsource
                        WHERE
                            bucket = ''
                            and data_source = '{}'::jsonb
                    )
                WHERE
                    billing_source_id =
                    (
                        SELECT
                            id
                        FROM
                            api_providerbillingsource
                        WHERE
                            data_source = '{"bucket": ""}'::jsonb
                    )
                ;

                DELETE
                FROM
                    api_providerbillingsource
                WHERE
                    data_source = '{"bucket": ""}'::jsonb;

                UPDATE
                    api_providerbillingsource
                SET
                    data_source = jsonb_build_object('bucket', bucket)
                WHERE
                    data_source = '{}'::jsonb
                    AND bucket != '';

                UPDATE
                    api_providerauthentication
                SET
                    credentials = jsonb_build_object('provider_resource_name', provider_resource_name)
                WHERE
                    credentials = '{}'::jsonb;

                UPDATE
                    api_providerauthentication apa
                SET
                    credentials = credentials - 'provider_resource_name' || jsonb_build_object('role_arn', credentials->'provider_resource_name')
                FROM
                    api_provider ap
                WHERE
                    apa.id = ap.authentication_id
                    AND ap.type = 'AWS';

                UPDATE
                    api_providerauthentication apa
                SET
                    credentials = credentials - 'provider_resource_name' || jsonb_build_object('cluster_id', credentials->'provider_resource_name')
                FROM
                    api_provider ap
                WHERE
                    apa.id = ap.authentication_id
                    AND ap.type = 'OCP';
            """
        )
    ]
