# Generated by Django 2.2.15 on 2020-08-24 17:59
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0023_auto_20200820_2314")]

    operations = [
        migrations.RunSQL(
            """
            UPDATE
                api_sources
            SET
                authentication =  authentication - 'resource_name' || jsonb_build_object('credentials', jsonb_build_object('role_arn', authentication->'resource_name'))
            WHERE
                source_type = 'AWS' AND authentication->'resource_name' IS NOT NULL;
            UPDATE
                api_sources
            SET
                billing_source =  billing_source - 'bucket' || jsonb_build_object('data_source', jsonb_build_object('bucket', billing_source->'bucket'))
            WHERE
                source_type = 'AWS' AND billing_source->'bucket' IS NOT NULL;

            UPDATE
                api_sources
            SET
                authentication =  authentication - 'resource_name' || jsonb_build_object('credentials', jsonb_build_object('cluster_id', authentication->'resource_name'))
            WHERE
                source_type = 'OCP' AND authentication->'resource_name' IS NOT NULL;
            """
        )
    ]
