# Generated by Django 2.2.4 on 2019-10-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190925_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='endpoint_id',
            field=models.IntegerField(null=True),
        ),
    ]
