# Generated by Django 2.2.4 on 2019-10-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_sources_endpoint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='pending_update',
            field=models.BooleanField(default=False),
        ),
    ]
