# Generated by Django 2.2.4 on 2019-10-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20191008_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerstatus',
            name='provider_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunSQL(
            """
                UPDATE api_providerstatus AS ps
                    SET provider_uuid = p.uuid
                FROM api_provider AS p
                WHERE p.id = ps.provider_id
            """
        ),
        migrations.RemoveField(
            model_name='providerstatus',
            name='provider',
        ),
    ]
