# Generated by Django 2.2.15 on 2020-09-21 20:16
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0028_public_function_update")]

    operations = [migrations.RunSQL('create extension if not exists "uuid-ossp" SCHEMA public')]
