# Generated by Django 3.1.2 on 2020-10-14 12:24
import os

from django.db import migrations

from koku import migration_sql_helpers as msh


def apply_clone_schema(apps, schema_editor):
    path = msh.find_db_functions_dir()
    msh.apply_sql_file(schema_editor, os.path.join(path, "clone_schema.sql"), literal_placeholder=True)


class Migration(migrations.Migration):

    dependencies = [("api", "0030_auto_20201007_1403")]

    operations = [migrations.RunPython(code=apply_clone_schema)]
