# Generated by Django 2.2.4 on 2019-10-22 16:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20191022_1602'),
        ('reporting_common', '0019_auto_20191022_1602')
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'ALTER TABLE api_provider DROP CONSTRAINT api_provider_pkey'
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='provider',
                    name='id',
                ),
            ]
        ),
        migrations.AlterField(
            model_name='provider',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
