# Generated by Django 3.1.2 on 2020-10-30 19:22
import os

from django.db import migrations

from koku import migration_sql_helpers as msh


def apply_presto_del_trigger_func(apps, schema_editor):
    path = msh.find_db_functions_dir()
    msh.apply_sql_file(schema_editor, os.path.join(path, "presto_delete_trigger_func.sql"))


class Migration(migrations.Migration):

    dependencies = [("api", "0031_clone_schema")]

    operations = [migrations.RunPython(code=apply_presto_del_trigger_func)]
