# Generated by Django 3.1.3 on 2020-12-16 20:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0032_presto_delete_log_trigger_func")]

    operations = [
        migrations.AlterField(model_name="sources", name="account_id", field=models.TextField(null=True)),
        migrations.AlterField(model_name="sources", name="koku_uuid", field=models.TextField(null=True, unique=True)),
        migrations.AlterField(model_name="sources", name="name", field=models.TextField(null=True)),
        migrations.AlterField(model_name="sources", name="source_type", field=models.TextField()),
    ]
