# Generated by Django 3.1.3 on 2021-01-15 15:32
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0033_sources_name_text")]

    operations = [migrations.RemoveField(model_name="sources", name="endpoint_id")]
