# Generated by Django 3.1.5 on 2021-01-14 16:23
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0033_sources_name_text")]

    operations = [
        migrations.AlterField(model_name="provider", name="name", field=models.TextField()),
        migrations.AlterField(
            model_name="provider",
            name="type",
            field=models.TextField(
                choices=[
                    ("AWS", "AWS"),
                    ("OCP", "OCP"),
                    ("Azure", "Azure"),
                    ("GCP", "GCP"),
                    ("AWS-local", "AWS-local"),
                    ("Azure-local", "Azure-local"),
                    ("GCP-local", "GCP-local"),
                ],
                default="AWS",
            ),
        ),
    ]
