# Generated by Django 3.1.3 on 2020-12-16 21:27
import os

from django.db import migrations

from koku import migration_sql_helpers as msh


def apply_public_func_updates(apps, schema_editor):
    path = msh.find_db_functions_dir()
    for funcfile in (
        # trigger func is the same as original apply (interface not changed) but does not have the drop in the file.
        "reapply_partitioned_tables_manage_trigger_function.sql",
        # Drop/create here is not being used in triggers as of this migration.
        "clone_schema.sql",
    ):
        msh.apply_sql_file(schema_editor, os.path.join(path, funcfile), literal_placeholder=True)


class Migration(migrations.Migration):

    dependencies = [("api", "0034_remove_sources_endpoint_id")]

    operations = [migrations.RunPython(code=apply_public_func_updates)]
