# Generated by Django 3.1.6 on 2021-02-08 15:18
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0035_reapply_partition_and_clone_func")]

    operations = [
        migrations.AlterField(
            model_name="sources",
            name="name",
            field=models.TextField(
                max_length=256, null=True, validators=[django.core.validators.MaxLengthValidator(256)]
            ),
        )
    ]
