# Generated by Django 2.2.6 on 2019-11-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20191113_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='source_uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
