# Generated by Django 3.1.7 on 2021-02-23 21:36
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0036_reapply_check_migrations_func")]

    operations = [
        migrations.AlterField(
            model_name="sources",
            name="name",
            field=models.TextField(
                max_length=256, null=True, validators=[django.core.validators.MaxLengthValidator(256)]
            ),
        )
    ]
