# Generated by Django 2.2.6 on 2019-11-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20191120_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='source_uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
