# Generated by Django 3.1.7 on 2021-03-04 17:19
from django.db import migrations

from koku.database import install_migrations_dbfunc


def drop_old_app_needs_migrations_func(apps, schema_editor):
    conn = schema_editor.connection
    cur = conn.cursor()
    cur.execute("""drop function if exists app_needs_migrations(jsonb, boolean);""")


class Migration(migrations.Migration):

    dependencies = [("api", "0037_auto_20210223_2136")]

    operations = [migrations.RunPython(code=drop_old_app_needs_migrations_func)]
