# Generated by Django 2.2.4 on 2019-11-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_sources_source_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costmodelmetricsmap',
            name='metric',
            field=models.CharField(choices=[('cpu_core_usage_per_hour', 'cpu_core_usage_per_hour'), ('cpu_core_request_per_hour', 'cpu_core_request_per_hour'), ('memory_gb_usage_per_hour', 'memory_gb_usage_per_hour'), ('memory_gb_request_per_hour', 'memory_gb_request_per_hour'), ('storage_gb_usage_per_month', 'storage_gb_usage_per_month'), ('storage_gb_request_per_month', 'storage_gb_request_per_month'), ('node_cost_per_month', 'node_cost_per_month')], max_length=256),
        ),
    ]
