# Generated by Django 3.1.7 on 2021-03-29 15:57
import os
import sys

from django.db import migrations

from koku import migration_sql_helpers as msh


def apply_public_function_updates(apps, schema_editor):
    path = msh.find_db_functions_dir()
    for funcfile in ("array_subtract_func.sql",):
        msh.apply_sql_file(schema_editor, os.path.join(path, funcfile))


class Migration(migrations.Migration):

    dependencies = [("api", "0040_auto_20210318_1514")]

    operations = [migrations.RunPython(code=apply_public_function_updates)]
