# Generated by Django 2.2.9 on 2020-01-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_sources_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerinfrastructuremap',
            name='infrastructure_type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('AZURE', 'AZURE'), ('GCP', 'GCP'), ('AWS-local', 'AWS-local'), ('AZURE-local', 'AZURE-local'), ('GCP-local', 'GCP-local')], max_length=50, null=True),
        ),
    ]
