# Generated by Django 3.1.3 on 2020-12-16 21:27
import os

from django.db import migrations

from koku import migration_sql_helpers as msh


def apply_public_clone_func_update(apps, schema_editor):
    path = msh.find_db_functions_dir()
    msh.apply_sql_file(schema_editor, os.path.join(path, "clone_schema.sql"), literal_placeholder=True)


class Migration(migrations.Migration):

    dependencies = [("api", "0041_array_subtract_dbfunc")]

    operations = [migrations.RunPython(code=apply_public_clone_func_update)]
