# Generated by Django 3.1.7 on 2021-04-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_reapply_clone_func'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
