# Generated by Django 3.1.7 on 2021-04-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_sources_in_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sources',
            name='in_progress',
        ),
    ]
