# Generated by Django 3.1.7 on 2021-04-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_sources_push_status_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sources',
            name='push_status_update',
        ),
    ]
