# Generated by Django 3.1.10 on 2021-05-13 21:31
import logging

from django.db import migrations


LOG = logging.getLogger(__name__)


def no_op(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("api", "0044_auto_20210505_1747")]

    operations = [migrations.RunPython(no_op)]
