# Generated by Django 3.1.8 on 2021-05-06 17:55
import os

from django.db import migrations

from koku import migration_sql_helpers as msh


def apply_public_clone_func_update(apps, schema_editor):
    path = msh.find_db_functions_dir()
    for filename in ("read_schema.sql", "create_schema.sql"):
        msh.apply_sql_file(schema_editor, os.path.join(path, filename), literal_placeholder=True)


class Migration(migrations.Migration):

    dependencies = [("api", "0044_auto_20210505_1747")]

    operations = [migrations.RunPython(code=apply_public_clone_func_update)]
