# Generated by Django 3.1.10 on 2021-05-21 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_update_django_migration_sequences'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('aud', 'AUD'), ('cad', 'CAD'), ('chf', 'CHF'), ('cny', 'CNY'), ('dkk', 'DKK'), ('eur', 'EUR'), ('gbp', 'GBP'), ('hkd', 'HKD'), ('jpy', 'JPY'), ('nok', 'NOK'), ('nzd', 'NZD'), ('sek', 'SEK'), ('sgd', 'SGD'), ('usd', 'USD'), ('zar', 'ZAR')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchangeRate', models.FloatField()),
                ('endingCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_item', to='api.currencycodes')),
                ('startingCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_item', to='api.currencycodes')),
            ],
        ),
    ]
