# Generated by Django 3.1.10 on 2021-05-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20210525_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencycodes',
            name='name',
            field=models.CharField(choices=[('aud', 'AUD'), ('cad', 'CAD'), ('chf', 'CHF'), ('cny', 'CNY'), ('dkk', 'DKK'), ('eur', 'EUR'), ('gbp', 'GBP'), ('hkd', 'HKD'), ('jpy', 'JPY'), ('nok', 'NOK'), ('nzd', 'NZD'), ('sek', 'SEK'), ('sgd', 'SGD'), ('usd', 'USD'), ('zar', 'ZAR')], max_length=100, unique=True),
        ),
    ]
