# Generated by Django 3.1.13 on 2021-09-24 19:56
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0049_auto_20210818_2208")]

    operations = [
        migrations.CreateModel(
            name="CurrencyCodes",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("aud", "AUD"),
                            ("cad", "CAD"),
                            ("chf", "CHF"),
                            ("cny", "CNY"),
                            ("dkk", "DKK"),
                            ("eur", "EUR"),
                            ("gbp", "GBP"),
                            ("hkd", "HKD"),
                            ("jpy", "JPY"),
                            ("nok", "NOK"),
                            ("nzd", "NZD"),
                            ("sek", "SEK"),
                            ("sgd", "SGD"),
                            ("usd", "USD"),
                            ("zar", "ZAR"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExchangeRates",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exchangeRate", models.JSONField(default=dict)),
                (
                    "baseCurrency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="column_item", to="api.currencycodes"
                    ),
                ),
            ],
        ),
    ]
