# Generated by Django 3.1.13 on 2021-09-30 21:25
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0050_exchangerates")]

    operations = [
        migrations.RenameField(model_name="exchangerates", old_name="baseCurrency", new_name="base_currency")
    ]
