# Generated by Django 3.1.13 on 2022-01-06 19:16
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0050_exchangerates")]

    operations = [
        migrations.AddField(
            model_name="sources",
            name="provider",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="api.provider"),
        ),
        migrations.RunSQL("UPDATE public.api_sources SET provider_id = koku_uuid::uuid"),
    ]
