# Generated by Django 3.1.13 on 2021-11-12 21:04
import os
import re

from django.db import migrations

from koku.migration_sql_helpers import find_db_functions_dir


def reapply_partition_manager_func(apps, schema_editor):
    func_file = "partitioned_manager_trigger_function.sql"
    func_path = os.path.join(find_db_functions_dir(), func_file)
    func_sql = open(func_path, "rt").read()
    func_sql = re.sub(r"DROP FUNCTION IF EXISTS.+", "-- THE DROP HAS BEEN ERASED --", func_sql)
    func_sql = func_sql.replace("%", "%%")

    with schema_editor.connection.cursor() as cur:
        cur.execute(func_sql)


class Migration(migrations.Migration):

    dependencies = [("api", "0050_exchangerates")]

    operations = [migrations.RunPython(code=reapply_partition_manager_func, reverse_code=migrations.RunPython.noop)]
