# Generated by Django 3.1.13 on 2022-01-07 16:23
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0051_reapply_partition_trigger_func")]

    operations = [
        migrations.AddField(
            model_name="sources",
            name="provider",
            field=models.ForeignKey(
                db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="api.provider"
            ),
        ),
        migrations.RunSQL("UPDATE public.api_sources SET provider_id = koku_uuid::uuid"),
    ]
