# Generated by Django 3.1.14 on 2022-02-07 19:18
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0052_sources_provider")]

    operations = [
        migrations.AddField(
            model_name="provider", name="additional_context", field=models.JSONField(default=dict, null=True)
        ),
        migrations.AddField(
            model_name="sources", name="additional_context", field=models.JSONField(default=dict, null=True)
        ),
    ]
