# Generated by Django 3.2.12 on 2022-03-30 14:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_reapply_clone_schema_func"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("username", "customer")},
        ),
    ]
