# Generated by Django 3.2.13 on 2022-06-01 14:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_reapply_clone_schema_func"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="org_id",
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="sources",
            name="org_id",
            field=models.TextField(null=True),
        ),
    ]
