# Generated by Django 3.2.19 on 2023-07-06 08:30
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_alter_tenant_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="polling_timestamp",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
