# Generated by Django 3.2.19 on 2023-07-11 16:19
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_provider_polling_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="large_customer",
            field=models.BooleanField(default=False),
        ),
    ]
