# Generated by Django 3.2.22 on 2023-12-05 14:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_provider_polling_timestamp"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="providerinfrastructuremap",
            unique_together={("infrastructure_type", "infrastructure_provider")},
        ),
    ]
