# Generated by Django 4.2.10 on 2024-02-21 19:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_alter_providerinfrastructuremap_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerinfrastructuremap",
            name="infrastructure_account",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="providerinfrastructuremap",
            name="infrastructure_region",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
