# Generated by Django 4.2.11 on 2024-07-16 18:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_remove_infra_map_account_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="data_valid",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
