# Generated by Django 4.2.20 on 2025-05-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_exchangerates_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('OCP', 'OCP'), ('Azure', 'Azure'), ('GCP', 'GCP'), ('OCI', 'OCI'), ('AWS-local', 'AWS-local'), ('Azure-local', 'Azure-local'), ('GCP-local', 'GCP-local'), ('OCI-local', 'OCI-local')], default='AWS', max_length=50),
        ),
        migrations.AlterField(
            model_name='providerinfrastructuremap',
            name='infrastructure_type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('Azure', 'Azure'), ('GCP', 'GCP'), ('OCI', 'OCI'), ('AWS-local', 'AWS-local'), ('Azure-local', 'Azure-local'), ('GCP-local', 'GCP-local'), ('OCI-local', 'OCI-local')], max_length=50),
        ),
    ]
