# Generated by Django 4.2.15 on 2024-11-29 17:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_alter_exchangerates_currency_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="large",
            field=models.BooleanField(default=False),
        ),
    ]
