# Generated by Django 4.2.15 on 2025-05-16 09:22
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_alter_provider_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="test_migration",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
