# Generated by Django 4.2.23 on 2025-07-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_provider_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerates',
            name='currency_type',
            field=models.CharField(blank=True, choices=[('aud', 'AUD'), ('brl', 'BRL'), ('cad', 'CAD'), ('chf', 'CHF'), ('cny', 'CNY'), ('czk', 'CZK'), ('dkk', 'DKK'), ('eur', 'EUR'), ('gbp', 'GBP'), ('hkd', 'HKD'), ('inr', 'INR'), ('jpy', 'JPY'), ('nok', 'NOK'), ('nzd', 'NZD'), ('sek', 'SEK'), ('sgd', 'SGD'), ('usd', 'USD'), ('zar', 'ZAR')], max_length=5),
        ),
    ]
