# Generated by Django 4.2.27 on 2026-04-13 12:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_exchangerates_currency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='updated_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
