# Generated by Django 4.2.27 on 2026-04-13 12:17
from django.db import migrations
from django.db import models
from django.utils import timezone


def backfill_updated_timestamp(apps, schema_editor):
    """Set updated_timestamp to now() for all existing rows so the UI never shows a blank field."""
    Sources = apps.get_model("api", "Sources")
    Sources.objects.filter(updated_timestamp__isnull=True).update(updated_timestamp=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0070_alter_exchangerates_currency_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sources",
            name="updated_timestamp",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(backfill_updated_timestamp, migrations.RunPython.noop),
    ]
