# Generated by Django 5.2 on 2026-06-03
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0071_sources_updated_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerates",
            name="currency_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aed", "AED"),
                    ("aud", "AUD"),
                    ("brl", "BRL"),
                    ("cad", "CAD"),
                    ("chf", "CHF"),
                    ("cny", "CNY"),
                    ("czk", "CZK"),
                    ("dkk", "DKK"),
                    ("eur", "EUR"),
                    ("gbp", "GBP"),
                    ("ghs", "GHS"),
                    ("hkd", "HKD"),
                    ("inr", "INR"),
                    ("jpy", "JPY"),
                    ("ngn", "NGN"),
                    ("nok", "NOK"),
                    ("nzd", "NZD"),
                    ("sar", "SAR"),
                    ("sek", "SEK"),
                    ("sgd", "SGD"),
                    ("twd", "TWD"),
                    ("usd", "USD"),
                    ("zar", "ZAR"),
                ],
                max_length=5,
            ),
        ),
    ]
