# Generated by Django 5.2.13 on 2026-04-28 14:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0071_sources_updated_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerates",
            name="currency_type",
            field=models.CharField(max_length=5),
        ),
    ]
