apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: koku-secrets
objects:
- apiVersion: v1
  data:
    aws-credentials: ${AWS_CREDENTIALS_EPH}
  kind: Secret
  metadata:
    name: koku-aws
  stringData:
    aws_access_key_id: ${AWS_ACCESS_KEY_ID_EPH}
    aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY_EPH}
    role_arn: ${AWS_ASSUME_ROLE_ARN}
- apiVersion: v1
  data:
    gcp-credentials: ${GCP_CREDENTIALS_EPH}
  kind: Secret
  metadata:
    name: koku-gcp
- apiVersion: v1
  data:
    oci-config: ${OCI_CONFIG_EPH}
    oci-credentials: ${OCI_CREDENTIALS_EPH}
  kind: Secret
  metadata:
    name: koku-oci

parameters:
- name: AWS_CREDENTIALS_EPH
  description: base64 encoded value containing the [default] profile with aws_access_key_id and aws_secret_access_key
  displayName: AWS credentials file
  required: true
- name: AWS_ACCESS_KEY_ID_EPH
  description: plaintext aws_access_key_id
  required: true
- name: AWS_SECRET_ACCESS_KEY_EPH
  description: plaintext aws_secret_access_key
  required: true
- name: GCP_CREDENTIALS_EPH
  description: base64 encoded json containing GCP creds
  displayName: GCP Credentials
  required: true
- name: OCI_CREDENTIALS_EPH
  description: base64 encoded oci credentials
  displayName: OCI Credentials
  required: true
- name: OCI_CONFIG_EPH
  description: base64 encoded oci config
  displayName: OCI Config
  required: true
- name: AWS_ASSUME_ROLE_ARN
  value: arn:aws:iam::589173575009:role/limited-glue-role
