-- OCP ON ALL DAILY SUMMARY PROCESSING (AWS DATA)
INSERT
  INTO reporting_ocpallcostlineitem_daily_summary (
           id,
           source_type,
           cluster_id,
           cluster_alias,
           namespace,
           node,
           resource_id,
           usage_start,
           usage_end,
           usage_account_id,
           account_alias_id,
           product_code,
           product_family,
           instance_type,
           region,
           availability_zone,
           tags,
           usage_amount,
           unit,
           unblended_cost,
           markup_cost,
           currency_code,
           shared_projects,
           source_uuid
       )
SELECT uuid_generate_v4(),
       'AWS'::text AS source_type,
       aws.cluster_id,
       max(aws.cluster_alias),
       aws.namespace,
       aws.node,
       aws.resource_id,
       aws.usage_start,
       aws.usage_end,
       max(aws.usage_account_id),
       aws.account_alias_id,
       aws.product_code,
       aws.product_family,
       aws.instance_type,
       aws.region,
       aws.availability_zone,
       aws.tags,
       sum(aws.usage_amount),
       max(aws.unit),
       sum(aws.unblended_cost),
       sum(aws.markup_cost),
       max(aws.currency_code),
       max(aws.shared_projects),
       {{source_uuid}}::uuid
  FROM reporting_ocpawscostlineitem_daily_summary AS aws
 WHERE aws.usage_start >= {{start_date}}::date
   AND aws.usage_start <= {{end_date}}::date
   AND aws.source_uuid = {{source_uuid}}::uuid
 GROUP
    BY aws.cluster_id,
       aws.namespace,
       aws.node,
       aws.resource_id,
       aws.usage_start,
       aws.usage_end,
       aws.account_alias_id,
       aws.product_code,
       aws.product_family,
       aws.instance_type,
       aws.region,
       aws.availability_zone,
       aws.tags;
