# Generated by Django 2.2.4 on 2019-10-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the attribute', max_length=255)),
                ('value', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
