# Generated by Django 2.2.4 on 2019-10-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='updated_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
