# Copyright 2018 Red Hat, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
"""Reporting Common init."""
import os

package_directory = os.path.dirname(os.path.abspath(__file__))

REPORT_COLUMN_MAP = [
    {
        "database_column": "billing_resource",
        "database_table": "reporting_awscostentrybill",
        "provider_column_name": "bill/BillingEntity",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "bill_type",
        "database_table": "reporting_awscostentrybill",
        "provider_column_name": "bill/BillType",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "payer_account_id",
        "database_table": "reporting_awscostentrybill",
        "provider_column_name": "bill/PayerAccountId",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "billing_period_start",
        "database_table": "reporting_awscostentrybill",
        "provider_column_name": "bill/BillingPeriodStartDate",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "billing_period_end",
        "database_table": "reporting_awscostentrybill",
        "provider_column_name": "bill/BillingPeriodEndDate",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "invoice_id",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "bill/InvoiceId",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "line_item_type",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/LineItemType",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "usage_account_id",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/UsageAccountId",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "usage_start",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/UsageStartDate",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "usage_end",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/UsageEndDate",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "product_code",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/ProductCode",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "usage_type",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/UsageType",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "operation",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/Operation",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "availability_zone",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/AvailabilityZone",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "resource_id",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/ResourceId",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "usage_amount",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/UsageAmount",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "normalization_factor",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/NormalizationFactor",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "normalized_usage_amount",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/NormalizedUsageAmount",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "currency_code",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/CurrencyCode",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "unblended_rate",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/UnblendedRate",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "unblended_cost",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/UnblendedCost",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "blended_rate",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/BlendedRate",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "blended_cost",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/BlendedCost",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "tax_type",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "lineItem/TaxType",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "public_on_demand_cost",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "pricing/publicOnDemandCost",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "public_on_demand_rate",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "pricing/publicOnDemandRate",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "term",
        "database_table": "reporting_awscostentrypricing",
        "provider_column_name": "pricing/term",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "unit",
        "database_table": "reporting_awscostentrypricing",
        "provider_column_name": "pricing/unit",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "sku",
        "database_table": "reporting_awscostentryproduct",
        "provider_column_name": "product/sku",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "product_name",
        "database_table": "reporting_awscostentryproduct",
        "provider_column_name": "product/ProductName",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "product_family",
        "database_table": "reporting_awscostentryproduct",
        "provider_column_name": "product/productFamily",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "service_code",
        "database_table": "reporting_awscostentryproduct",
        "provider_column_name": "product/servicecode",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "region",
        "database_table": "reporting_awscostentryproduct",
        "provider_column_name": "product/region",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "instance_type",
        "database_table": "reporting_awscostentryproduct",
        "provider_column_name": "product/instanceType",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "memory",
        "database_table": "reporting_awscostentryproduct",
        "provider_column_name": "product/memory",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "memory_unit",
        "database_table": "reporting_awscostentryproduct",
        "provider_column_name": "product/memory_unit",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "vcpu",
        "database_table": "reporting_awscostentryproduct",
        "provider_column_name": "product/vcpu",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "reservation_arn",
        "database_table": "reporting_awscostentryreservation",
        "provider_column_name": "reservation/ReservationARN",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "number_of_reservations",
        "database_table": "reporting_awscostentryreservation",
        "provider_column_name": "reservation/NumberOfReservations",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "units_per_reservation",
        "database_table": "reporting_awscostentryreservation",
        "provider_column_name": "reservation/UnitsPerReservation",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "start_time",
        "database_table": "reporting_awscostentryreservation",
        "provider_column_name": "reservation/StartTime",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "end_time",
        "database_table": "reporting_awscostentryreservation",
        "provider_column_name": "reservation/EndTime",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "reservation_amortized_upfront_fee",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "reservation/AmortizedUpfrontFeeForBillingPeriod",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "reservation_amortized_upfront_cost_for_usage",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "reservation/AmortizedUpfrontCostForUsage",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "reservation_recurring_fee_for_usage",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "reservation/RecurringFeeForUsage",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "reservation_unused_quantity",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "reservation/UnusedQuantity",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "reservation_unused_recurring_fee",
        "database_table": "reporting_awscostentrylineitem",
        "provider_column_name": "reservation/UnusedRecurringFee",
        "report_type": "AWS-CUR",
        "provider_type": "AWS",
    },
    {
        "database_column": "instance_id",
        "database_table": "reporting_azurecostentryproductservice",
        "provider_column_name": "InstanceId",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "resource_location",
        "database_table": "reporting_azurecostentryproductservice",
        "provider_column_name": "ResourceLocation",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "consumed_service",
        "database_table": "reporting_azurecostentryproductservice",
        "provider_column_name": "ConsumedService",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "resource_type",
        "database_table": "reporting_azurecostentryproductservice",
        "provider_column_name": "ResourceType",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "resource_group",
        "database_table": "reporting_azurecostentryproductservice",
        "provider_column_name": "ResourceGroup",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "additional_info",
        "database_table": "reporting_azurecostentryproductservice",
        "provider_column_name": "AdditionalInfo",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "service_tier",
        "database_table": "reporting_azurecostentryproductservice",
        "provider_column_name": "ServiceTier",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "service_name",
        "database_table": "reporting_azurecostentryproductservice",
        "provider_column_name": "ServiceName",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "service_info1",
        "database_table": "reporting_azurecostentryproductservice",
        "provider_column_name": "ServiceInfo1",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "service_info2",
        "database_table": "reporting_azurecostentryproductservice",
        "provider_column_name": "ServiceInfo2",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "meter_id",
        "database_table": "reporting_azuremeter",
        "provider_column_name": "MeterId",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "meter_name",
        "database_table": "reporting_azuremeter",
        "provider_column_name": "MeterName",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "meter_category",
        "database_table": "reporting_azuremeter",
        "provider_column_name": "MeterCategory",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "currency",
        "database_table": "reporting_azuremeter",
        "provider_column_name": "Currency",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "meter_subcategory",
        "database_table": "reporting_azuremeter",
        "provider_column_name": "MeterSubcategory",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "meter_region",
        "database_table": "reporting_azuremeter",
        "provider_column_name": "MeterRegion",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "resource_rate",
        "database_table": "reporting_azuremeter",
        "provider_column_name": "UsageRate",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "unit_of_measure",
        "database_table": "reporting_azuremeter",
        "provider_column_name": "UnitOfMeasure",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "subscription_guid",
        "database_table": "reporting_azurecostentrylineitem_daily",
        "provider_column_name": "SubscriptionGuid",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "tags",
        "database_table": "reporting_azurecostentrylineitem_daily",
        "provider_column_name": "Tags",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "usage_date",
        "database_table": "reporting_azurecostentrylineitem_daily",
        "provider_column_name": "UsageDateTime",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "usage_quantity",
        "database_table": "reporting_azurecostentrylineitem_daily",
        "provider_column_name": "UsageQuantity",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "pretax_cost",
        "database_table": "reporting_azurecostentrylineitem_daily",
        "provider_column_name": "PreTaxCost",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "offer_id",
        "database_table": "reporting_azurecostentrylineitem_daily",
        "provider_column_name": "OfferId",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE",
    },
    {
        "database_column": "cluster_id",
        "database_table": "reporting_ocpusagereportperiod",
        "provider_column_name": "cluster_id",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "report_period_start",
        "database_table": "reporting_ocpusagereportperiod",
        "provider_column_name": "report_period_start",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "report_period_end",
        "database_table": "reporting_ocpusagereportperiod",
        "provider_column_name": "report_period_end",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "interval_start",
        "database_table": "reporting_ocpusagereport",
        "provider_column_name": "interval_start",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "interval_end",
        "database_table": "reporting_ocpusagereport",
        "provider_column_name": "interval_end",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "namespace",
        "database_table": "reporting_ocpusagelineitem",
        "provider_column_name": "namespace",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "pod",
        "database_table": "reporting_ocpusagelineitem",
        "provider_column_name": "pod",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "node",
        "database_table": "reporting_ocpusagelineitem",
        "provider_column_name": "node",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "pod_usage_cpu_core_seconds",
        "database_table": "reporting_ocpusagelineitem",
        "provider_column_name": "pod_usage_cpu_core_seconds",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "pod_request_cpu_core_seconds",
        "database_table": "reporting_ocpusagelineitem",
        "provider_column_name": "pod_request_cpu_core_seconds",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "pod_limit_cpu_core_seconds",
        "database_table": "reporting_ocpusagelineitem",
        "provider_column_name": "pod_limit_cpu_core_seconds",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "pod_usage_memory_byte_seconds",
        "database_table": "reporting_ocpusagelineitem",
        "provider_column_name": "pod_usage_memory_byte_seconds",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "pod_request_memory_byte_seconds",
        "database_table": "reporting_ocpusagelineitem",
        "provider_column_name": "pod_request_memory_byte_seconds",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "pod_limit_memory_byte_seconds",
        "database_table": "reporting_ocpusagelineitem",
        "provider_column_name": "pod_limit_memory_byte_seconds",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "node_capacity_cpu_cores",
        "database_table": "reporting_ocpusagelineitem",
        "provider_column_name": "node_capacity_cpu_cores",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "node_capacity_cpu_core_seconds",
        "database_table": "reporting_ocpusagelineitem",
        "provider_column_name": "node_capacity_cpu_core_seconds",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "node_capacity_memory_bytes",
        "database_table": "reporting_ocpusagelineitem",
        "provider_column_name": "node_capacity_memory_bytes",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "node_capacity_memory_byte_seconds",
        "database_table": "reporting_ocpusagelineitem",
        "provider_column_name": "node_capacity_memory_byte_seconds",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "resource_id",
        "database_table": "reporting_ocpusagelineitem",
        "provider_column_name": "resource_id",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "pod_labels",
        "database_table": "reporting_ocpusagelineitem",
        "provider_column_name": "pod_labels",
        "report_type": "OCP-CPU-MEM",
        "provider_type": "OCP",
    },
    {
        "database_column": "pod",
        "database_table": "reporting_ocpstoragelineitem",
        "provider_column_name": "pod",
        "report_type": "OCP-STORAGE",
        "provider_type": "OCP",
    },
    {
        "database_column": "namespace",
        "database_table": "reporting_ocpstoragelineitem",
        "provider_column_name": "namespace",
        "report_type": "OCP-STORAGE",
        "provider_type": "OCP",
    },
    {
        "database_column": "persistentvolumeclaim",
        "database_table": "reporting_ocpstoragelineitem",
        "provider_column_name": "persistentvolumeclaim",
        "report_type": "OCP-STORAGE",
        "provider_type": "OCP",
    },
    {
        "database_column": "persistentvolume",
        "database_table": "reporting_ocpstoragelineitem",
        "provider_column_name": "persistentvolume",
        "report_type": "OCP-STORAGE",
        "provider_type": "OCP",
    },
    {
        "database_column": "storageclass",
        "database_table": "reporting_ocpstoragelineitem",
        "provider_column_name": "storageclass",
        "report_type": "OCP-STORAGE",
        "provider_type": "OCP",
    },
    {
        "database_column": "persistentvolumeclaim_capacity_bytes",
        "database_table": "reporting_ocpstoragelineitem",
        "provider_column_name": "persistentvolumeclaim_capacity_bytes",
        "report_type": "OCP-STORAGE",
        "provider_type": "OCP",
    },
    {
        "database_column": "persistentvolumeclaim_capacity_byte_seconds",
        "database_table": "reporting_ocpstoragelineitem",
        "provider_column_name": "persistentvolumeclaim_capacity_byte_seconds",
        "report_type": "OCP-STORAGE",
        "provider_type": "OCP",
    },
    {
        "database_column": "volume_request_storage_byte_seconds",
        "database_table": "reporting_ocpstoragelineitem",
        "provider_column_name": "volume_request_storage_byte_seconds",
        "report_type": "OCP-STORAGE",
        "provider_type": "OCP",
    },
    {
        "database_column": "persistentvolumeclaim_usage_byte_seconds",
        "database_table": "reporting_ocpstoragelineitem",
        "provider_column_name": "persistentvolumeclaim_usage_byte_seconds",
        "report_type": "OCP-STORAGE",
        "provider_type": "OCP",
    },
    {
        "database_column": "persistentvolume_labels",
        "database_table": "reporting_ocpstoragelineitem",
        "provider_column_name": "persistentvolume_labels",
        "report_type": "OCP-STORAGE",
        "provider_type": "OCP",
    },
    {
        "database_column": "persistentvolumeclaim_labels",
        "database_table": "reporting_ocpstoragelineitem",
        "provider_column_name": "persistentvolumeclaim_labels",
        "report_type": "OCP-STORAGE",
        "provider_type": "OCP",
    },
    {
        "database_column": "node",
        "database_table": "reporting_ocpnodelabellineitem",
        "provider_column_name": "node",
        "report_type": "OCP-NODE-LABELS",
        "provider_type": "OCP",
    },
    {
        "database_column": "node_labels",
        "database_table": "reporting_ocpnodelabellineitem",
        "provider_column_name": "node_labels",
        "report_type": "OCP-NODE-LABELS",
        "provider_type": "OCP",
    },
    {
        "database_column": "project_id",
        "database_table": "reporting_gcpproject",
        "provider_column_name": "Project ID",
        "report_type": "GCP",
        "provider_type": "GCP",
    },
    {
        "database_column": "account_id",
        "database_table": "reporting_gcpproject",
        "provider_column_name": "Account ID",
        "report_type": "GCP",
        "provider_type": "GCP",
    },
    {
        "database_column": "project_number",
        "database_table": "reporting_gcpproject",
        "provider_column_name": "Project Number",
        "report_type": "GCP",
        "provider_type": "GCP",
    },
    {
        "database_column": "project_name",
        "database_table": "reporting_gcpproject",
        "provider_column_name": "Project Name",
        "report_type": "GCP",
        "provider_type": "GCP",
    },
    {
        "database_column": "project_labels",
        "database_table": "reporting_gcpproject",
        "provider_column_name": "Project Labels",
        "report_type": "GCP",
        "provider_type": "GCP",
    },
    {
        "database_column": "line_item_type",
        "database_table": "reporting_gcpcostentrylineitemdaily",
        "provider_column_name": "Line Item",
        "report_type": "GCP",
        "provider_type": "GCP",
    },
    {
        "database_column": "start_time",
        "database_table": "reporting_gcpcostentrylineitemdaily",
        "provider_column_name": "Start Time",
        "report_type": "GCP",
        "provider_type": "GCP",
    },
    {
        "database_column": "end_time",
        "database_table": "reporting_gcpcostentrylineitemdaily",
        "provider_column_name": "End Time",
        "report_type": "GCP",
        "provider_type": "GCP",
    },
    {
        "database_column": "measurement_type",
        "database_table": "reporting_gcpcostentrylineitemdaily",
        "provider_column_name": "Measurement1",
        "report_type": "GCP",
        "provider_type": "GCP",
    },
    {
        "database_column": "consumption",
        "database_table": "reporting_gcpcostentrylineitemdaily",
        "provider_column_name": "Measurement1 Total Consumption",
        "report_type": "GCP",
        "provider_type": "GCP",
    },
    {
        "database_column": "unit",
        "database_table": "reporting_gcpcostentrylineitemdaily",
        "provider_column_name": "Measurement1 Units",
        "report_type": "GCP",
        "provider_type": "GCP",
    },
    {
        "database_column": "cost",
        "database_table": "reporting_gcpcostentrylineitemdaily",
        "provider_column_name": "Cost",
        "report_type": "GCP",
        "provider_type": "GCP",
    },
    {
        "database_column": "currency",
        "database_table": "reporting_gcpcostentrylineitemdaily",
        "provider_column_name": "Currency",
        "report_type": "GCP",
        "provider_type": "GCP",
    },
    {
        "database_column": "description",
        "database_table": "reporting_gcpcostentrylineitemdaily",
        "provider_column_name": "Description",
        "report_type": "GCP",
        "provider_type": "GCP",
    },
]
