INSERT INTO reporting_awscostentrylineitem_daily_summary (
    usage_start,
    usage_end,
    usage_account_id,
    availability_zone,
    --resource_ids,
    product_code,
    usage_amount,
    normalization_factor,
    normalized_usage_amount,
    currency_code,
    unblended_rate,
    unblended_cost,
    blended_rate,
    blended_cost,
    public_on_demand_cost,
    public_on_demand_rate
)
SELECT usage_start,
    usage_end,
    cast(usage_account_id AS varchar(50)),
    cast(availability_zone AS varchar(50)),
    --resource_ids,
    cast(product_code AS varchar(50)),
    cast(usage_amount AS decimal(24,9)),
    normalization_factor,
    normalized_usage_amount,
    cast(currency_code AS varchar(10)),
    cast(unblended_rate AS decimal(24,9)),
    cast(unblended_cost AS decimal(24,9)),
    cast(blended_rate AS decimal(24,9)),
    cast(blended_cost AS decimal(24,9)),
    cast(public_on_demand_cost AS decimal(24,9)),
    cast(public_on_demand_rate AS decimal(24,9))
FROM hive.{{schema | sqlsafe}}.presto_aws_daily_summary_{{uuid | sqlsafe}}
