apiVersion: v1
kind: Template
metadata:
  name: rdsexporter-template
  annotations:
    openshift.io/display-name: 'RDS Exporter'
    openshift.io/description: 'Prometheus exporter for AWS RDS'
    openshift.io/long-description: 'This template defines resources to export monitoring and metrics data from AWS Cloudwatch about your RDS instances to Prometheus.'
labels:
  app: rdsexporter
  template: rdsexporter-template
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: rdsexporter
      template: rdsexporter-template
    name: ${NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    strategy:
      activeDeadlineSeconds: 21600
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 300
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
        - env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: aws-access-key-id
                name: ${NAME}
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: aws-secret-access-key
                name: ${NAME}
          image: ${NAMESPACE}/${NAME}:latest
          imagePullPolicy: Always
          name: rdsexporter
          ports:
          - containerPort: 9042
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
          namespace: ${NAMESPACE}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/path: /basic
      prometheus.io/port: "9041"
      prometheus.io/scrape: "true"
    labels:
      app: rdsexporter
      template: rdsexporter-template
    name: ${NAME}-basic
  spec:
    ports:
    - name: 9041-tcp
      port: 9041
      protocol: TCP
      targetPort: 9042
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/path: /enhanced
      prometheus.io/port: "9042"
      prometheus.io/scrape: "true"
    labels:
      app: rdsexporter
      template: rdsexporter-template
    name: ${NAME}-enhanced
  spec:
    ports:
    - name: 9042-tcp
      port: 9042
      protocol: TCP
      targetPort: 9042
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: rdsexporter
      template: rdsexporter-template
    name: ${NAME}
  spec:
    failedBuildsHistoryLimit: 5
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    resources:
      requests:
        memory: ${BUILD_MEMORY_REQUEST}
      limits:
        memory: ${BUILD_MEMORY_LIMIT}
    runPolicy: Serial
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
          - name: RDS_EXPORTER_CONFIG
            valueFrom:
              configMapKeyRef:
                name: ${NAME}
                key: rdsexporter-config
                optional: false
        from:
          kind: ImageStreamTag
          name: go-toolset-7-centos7:latest
          namespace: ${NAMESPACE}
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: rdsexporter
      template: rdsexporter-template
    name: ${NAME}
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: rdsexporter
      template: rdsexporter-template
    annotations:
      template.openshift.io/expose-aws_access_key_id: "{.data['aws-access-key-id']}"
      template.openshift.io/expose-aws_secret_access_key: "{.data['aws-secret-access-key']}"
    name: ${NAME}
  stringData:
    aws-access-key-id: ${AWS_ACCESS_KEY_ID}
    aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: rdsexporter
      template: rdsexporter-template
    name: ${NAME}
  data:
    rdsexporter-config: ${RDS_EXPORTER_CONFIG}
parameters:
- description: The name assigned to all frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: rdsexporter
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: rdsexporter
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/project-koku/koku.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
- description: Set this to the relative path to your project if it is not in the root
    of your repository.
  displayName: Context Directory
  name: CONTEXT_DIR
  value: openshift/rdsexporter
- description: AWS Access Key ID
  displayName: AWS Access Key ID
  from: ${AWS_ACCESS_KEY_ID}
  name: AWS_ACCESS_KEY_ID
- description: AWS Secret Access Key
  displayName: AWS Secret Access Key
  from: ${AWS_SECRET_ACCESS_KEY}
  name: AWS_SECRET_ACCESS_KEY
- description: Github trigger secret.  A difficult to guess string encoded as part of the webhook URL.  Not encrypted.
  displayName: GitHub Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
- description: JSON string representing config for rdsexporter. Deployed as config.yaml during build.
  displayName: Config file JSON
  name: RDS_EXPORTER_CONFIG
- description: Initial amount of memory the build container will request.
  displayName: Build Memory Request
  name: BUILD_MEMORY_REQUEST
  required: true
  value: 512Mi
- description: Maximum amount of memory the build container can use.
  displayName: Build Memory Limit
  name: BUILD_MEMORY_LIMIT
  required: true
  value: 1Gi
