local:
  cost_management:
    use_sources: False
    ocp_dir: /var/tmp/masu/insights_local
    aws_dir: /tmp/local_bucket
    azure_dir: /tmp/local_container
    gcp_dir: /tmp/gcp_local_bucket
    service_objects:
      masu:
        config:
          path: api/cost-management/v1
          port: 5042
          hostname: localhost
          scheme: http
  SOURCES:
    service_objects:
      sources:
        config:
          path: "api/v1.0"
          hostname: localhost
          port: 3000
          scheme: http
  main:
    hostname: localhost:8000
    scheme: http
  http:
    default_auth_type: identity
  users:
    default:
      identity:
        account_number: "10001"
        type: "User"
        user:
          username: "user_dev"
          email: "user_dev@foo.com"
          first_name: "User"
          last_name: "Dev"
          is_active: true
          is_org_admin: true
          is_internal: false
          locale: "en_US"
        internal:
          org_id: "10001"
          auth_type: "basic-auth"
          auth_time: 6300
      entitlements:
        hybrid_cloud:
          is_entitled: true
        insights:
          is_entitled: true
        openshift:
          is_entitled: true
        smart_management:
          is_entitled: true
        cost_management:
          is_entitled: true
