CREATE TABLE IF NOT EXISTS hive.{{schema | sqlsafe}}.managed_aws_uuid_temp (
    row_uuid varchar,
    lineitem_resourceid varchar,
    lineitem_usagestartdate timestamp(3),
    bill_payeraccountid varchar,
    lineitem_usageaccountid varchar,
    lineitem_legalentity varchar,
    lineitem_lineitemdescription varchar,
    bill_billingentity varchar,
    lineitem_productcode varchar,
    lineitem_availabilityzone varchar,
    lineitem_lineitemtype varchar,
    lineitem_usagetype varchar,
    lineitem_operation varchar,
    product_productfamily varchar,
    product_operatingsystem varchar,
    product_instancetype varchar,
    product_region varchar,
    pricing_unit varchar,
    resourcetags varchar,
    costcategory varchar,
    lineitem_usageamount double,
    lineitem_normalizationfactor double,
    lineitem_normalizedusageamount double,
    lineitem_currencycode varchar,
    lineitem_unblendedrate double,
    lineitem_unblendedcost double,
    lineitem_blendedrate double,
    lineitem_blendedcost double,
    pricing_publicondemandcost double,
    pricing_publicondemandrate double,
    savingsplan_savingsplaneffectivecost double,
    bill_invoiceid varchar,
    product_productname varchar,
    product_vcpu varchar,
    product_memory varchar,
    source varchar,
    year varchar,
    month varchar,
    day varchar
) WITH(format = 'PARQUET', partitioned_by=ARRAY['source', 'year', 'month', 'day'])
;

DELETE FROM hive.{{schema | sqlsafe}}.managed_aws_uuid_temp
WHERE source = {{cloud_provider_uuid}}
    AND year = {{year}}
    AND month= {{month}};

INSERT INTO hive.{{schema | sqlsafe}}.managed_aws_uuid_temp (
    row_uuid,
    lineitem_resourceid,
    lineitem_usagestartdate,
    bill_payeraccountid,
    lineitem_usageaccountid,
    lineitem_legalentity,
    lineitem_lineitemdescription,
    bill_billingentity,
    lineitem_productcode,
    lineitem_availabilityzone,
    lineitem_lineitemtype,
    lineitem_usagetype,
    lineitem_operation,
    product_productfamily,
    product_operatingsystem,
    product_instancetype,
    product_region,
    pricing_unit,
    resourcetags,
    costcategory,
    lineitem_usageamount,
    lineitem_normalizationfactor,
    lineitem_normalizedusageamount,
    lineitem_currencycode,
    lineitem_unblendedrate,
    lineitem_unblendedcost,
    lineitem_blendedrate,
    lineitem_blendedcost,
    pricing_publicondemandcost,
    pricing_publicondemandrate,
    savingsplan_savingsplaneffectivecost,
    bill_invoiceid,
    product_productname,
    product_vcpu,
    product_memory,
    source,
    year,
    month,
    day
)
SELECT
    cast(uuid() as varchar) as row_uuid,
    lineitem_resourceid,
    lineitem_usagestartdate,
    bill_payeraccountid,
    lineitem_usageaccountid,
    lineitem_legalentity,
    lineitem_lineitemdescription,
    bill_billingentity,
    lineitem_productcode,
    lineitem_availabilityzone,
    lineitem_lineitemtype,
    lineitem_usagetype,
    lineitem_operation,
    product_productfamily,
    product_operatingsystem,
    product_instancetype,
    product_region,
    pricing_unit,
    resourcetags,
    costcategory,
    lineitem_usageamount,
    lineitem_normalizationfactor,
    lineitem_normalizedusageamount,
    lineitem_currencycode,
    lineitem_unblendedrate,
    lineitem_unblendedcost,
    lineitem_blendedrate,
    lineitem_blendedcost,
    pricing_publicondemandcost,
    pricing_publicondemandrate,
    savingsplan_savingsplaneffectivecost,
    bill_invoiceid,
    product_productname,
    product_vcpu,
    product_memory,
    source,
    year,
    month,
    cast(day(lineitem_usagestartdate) as varchar) as day
FROM hive.{{schema | sqlsafe}}.aws_line_items_daily
WHERE source = {{cloud_provider_uuid}}
    AND year = {{year}}
    AND month= {{month}}
    AND lineitem_usagestartdate >= {{start_date}}
    AND lineitem_usagestartdate < date_add('day', 1, {{end_date}});
