CREATE TABLE IF NOT EXISTS hive.{{schema | sqlsafe}}.managed_aws_openshift_daily_temp
(
    row_uuid varchar,
    resource_id varchar,
    product_code varchar,
    usage_start timestamp(3),
    usage_account_id varchar,
    availability_zone varchar,
    product_family varchar,
    instance_type varchar,
    region varchar,
    unit varchar,
    tags varchar,
    aws_cost_category varchar,
    data_transfer_direction varchar,
    usage_amount double,
    currency_code varchar,
    unblended_cost double,
    blended_cost double,
    savingsplan_effective_cost double,
    calculated_amortized_cost double,
    resource_id_matched boolean,
    matched_tag varchar,
    source varchar,
    ocp_source varchar,
    year varchar,
    month varchar,
    day varchar
) WITH(format = 'PARQUET', partitioned_by=ARRAY['source', 'ocp_source', 'year', 'month', 'day'])
;

CREATE TABLE IF NOT EXISTS hive.{{schema | sqlsafe}}.managed_reporting_ocpawscostlineitem_project_daily_summary_temp
(
    row_uuid varchar,
    cluster_id varchar,
    cluster_alias varchar,
    data_source varchar,
    namespace varchar,
    node varchar,
    persistentvolumeclaim varchar,
    persistentvolume varchar,
    storageclass varchar,
    resource_id varchar,
    usage_start timestamp,
    usage_end timestamp,
    product_code varchar,
    product_family varchar,
    instance_type varchar,
    usage_account_id varchar,
    availability_zone varchar,
    region varchar,
    unit varchar,
    usage_amount double,
    currency_code varchar,
    unblended_cost double,
    markup_cost double,
    blended_cost double,
    markup_cost_blended double,
    savingsplan_effective_cost double,
    markup_cost_savingsplan double,
    calculated_amortized_cost double,
    markup_cost_amortized double,
    pod_cost double,
    project_markup_cost double,
    pod_effective_usage_cpu_core_hours double,
    pod_effective_usage_memory_gigabyte_hours double,
    node_capacity_cpu_core_hours double,
    node_capacity_memory_gigabyte_hours double,
    pod_labels varchar,
    volume_labels varchar,
    tags varchar,
    aws_cost_category varchar, -- AWS Cost category
    cost_category_id int, -- Internal OpenShift category ID
    project_rank integer,
    data_source_rank integer,
    resource_id_matched boolean,
    matched_tag varchar,
    source varchar,
    ocp_source varchar,
    year varchar,
    month varchar,
    day varchar
) WITH(format = 'PARQUET', partitioned_by=ARRAY['source', 'ocp_source', 'year', 'month', 'day'])
;

CREATE TABLE IF NOT EXISTS hive.{{schema | sqlsafe}}.managed_reporting_ocpawscostlineitem_project_daily_summary
(
    row_uuid varchar,
    cluster_id varchar,
    cluster_alias varchar,
    data_source varchar,
    namespace varchar,
    node varchar,
    persistentvolumeclaim varchar,
    persistentvolume varchar,
    storageclass varchar,
    resource_id varchar,
    usage_start timestamp,
    usage_end timestamp,
    product_code varchar,
    product_family varchar,
    instance_type varchar,
    usage_account_id varchar,
    account_alias_id integer,
    availability_zone varchar,
    region varchar,
    unit varchar,
    usage_amount double,
    data_transfer_direction varchar,
    currency_code varchar,
    unblended_cost double,
    markup_cost double,
    blended_cost double,
    markup_cost_blended double,
    savingsplan_effective_cost double,
    markup_cost_savingsplan double,
    calculated_amortized_cost double,
    markup_cost_amortized double,
    pod_cost double,
    project_markup_cost double,
    pod_labels varchar,
    tags varchar,
    aws_cost_category varchar,
    cost_category_id int,
    project_rank integer,
    data_source_rank integer,
    resource_id_matched boolean,
    matched_tag varchar,
    source varchar,
    ocp_source varchar,
    year varchar,
    month varchar,
    day varchar
) WITH(format = 'PARQUET', partitioned_by=ARRAY['source', 'ocp_source', 'year', 'month', 'day'])
;

CREATE TABLE IF NOT EXISTS hive.{{schema | sqlsafe}}.managed_aws_openshift_disk_capacities_temp
(
    resource_id varchar,
    capacity integer,
    usage_start timestamp,
    ocp_source varchar,
    year varchar,
    month varchar
) WITH(format = 'PARQUET', partitioned_by=ARRAY['ocp_source', 'year', 'month']);
