# Generated by Django 2.1 on 2018-09-25 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostUsageReportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=128, unique=True)),
                ('cursor_position', models.PositiveIntegerField()),
                ('last_completed_datetime', models.DateTimeField(null=True)),
                ('last_started_datetime', models.DateTimeField(null=True)),
                ('etag', models.CharField(max_length=64, null=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='RegionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=32, unique=True)),
                ('region_name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'region_mapping',
            },
        ),
        migrations.CreateModel(
            name='ReportColumnMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('AWS', 'AWS'), ('OCP', 'OCP')], default='AWS', max_length=50)),
                ('provider_column_name', models.CharField(max_length=128, unique=True)),
                ('database_table', models.CharField(max_length=50)),
                ('database_column', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SIUnitScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=12, unique=True)),
                ('prefix_symbol', models.CharField(max_length=1)),
                ('multiplying_factor', models.DecimalField(decimal_places=24, max_digits=49)),
            ],
            options={
                'db_table': 'si_unit_scale',
            },
        ),
    ]
