# Generated by Django 2.0.5 on 2018-06-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportColumnMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('AWS', 'AWS')], default='AWS', max_length=50)),
                ('provider_column_name', models.CharField(max_length=128, unique=True)),
                ('database_table', models.CharField(max_length=50)),
                ('database_column', models.CharField(max_length=128)),
            ],
        ),
    ]
