# Generated by Django 3.1.7 on 2021-04-12 17:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting_common", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="costusagereportmanifest",
            name="s3_csv_cleared",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="costusagereportmanifest",
            name="s3_parquet_cleared",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
