# Generated by Django 2.0.5 on 2018-06-08 16:47
import json
import pkgutil

from django.db import migrations


def load_report_map_data(apps, schema_editor):
    """Load AWS Cost Usage report to database mapping."""
    ReportColumnMap = apps.get_model('reporting_common', 'ReportColumnMap')

    data = pkgutil.get_data('reporting_common',
                            'data/aws_report_column_map.json')

    data = json.loads(data)

    for entry in data:
        map = ReportColumnMap(**entry)
        map.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_report_map_data)
    ]
