# Generated by Django 2.1.2 on 2018-11-27 20:46
import json
import pkgutil

from django.db import migrations


def update_pod_limit_memory_bytes(apps, schema_editor):
    """Update pod_limit_memory_bytes database mapping."""
    ReportColumnMap = apps.get_model('reporting_common', 'ReportColumnMap')
    pod_limit_memory_bytes = ReportColumnMap.objects.filter(database_column='pod_limit_memory_bytes')

    for entry in pod_limit_memory_bytes:
        entry.database_column = 'pod_limit_memory_byte_seconds'
        entry.provider_column_name = 'pod_limit_memory_byte_seconds'
        entry.save()

def update_pod_limit_cpu_cores(apps, schema_editor):
    """Update pod_limit_cpu_cores database mapping."""
    ReportColumnMap = apps.get_model('reporting_common', 'ReportColumnMap')
    pod_limit_cpu_cores = ReportColumnMap.objects.filter(database_column='pod_limit_cpu_cores')

    for entry in pod_limit_cpu_cores:
        entry.database_column = 'pod_limit_cpu_core_seconds'
        entry.provider_column_name = 'pod_limit_cpu_core_seconds'
        entry.save()

def update_report_map_data(apps, schema_editor):
    """Update report to database mapping."""
    update_pod_limit_memory_bytes(apps, schema_editor)
    update_pod_limit_cpu_cores(apps, schema_editor)

class Migration(migrations.Migration):

    dependencies = [
        ('reporting_common', '0004_auto_20181003_1859'),
    ]

    operations = [
            migrations.RunPython(update_report_map_data),
    ]
