# Generated by Django 2.1.2 on 2018-11-27 20:46
import json
import pkgutil

from django.db import migrations


def reload_ocp_map(apps, schema_editor):
    """Update report to database mapping."""
    ReportColumnMap = apps.get_model('reporting_common', 'ReportColumnMap')
    ocp_items = ReportColumnMap.objects.filter(provider_type='OCP')
    ocp_items.delete()

    data = pkgutil.get_data('reporting_common',
                            'data/ocp_report_column_map.json')

    data = json.loads(data)

    for entry in data:
        map = ReportColumnMap(**entry)
        map.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reporting_common', '0004_auto_20181003_1859'),
    ]

    operations = [
            migrations.RunPython(reload_ocp_map),
    ]
