# Generated by Django 2.0.7 on 2018-08-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_common', '0005_auto_20180725_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=32, unique=True)),
                ('region_name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'region_mapping',
            },
        ),
    ]
