# Generated by Django 2.1 on 2018-09-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_common', '0007_auto_20180808_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcolumnmap',
            name='provider_type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('AWS-local', 'AWS-local')], default='AWS', max_length=50),
        ),
    ]
