# Generated by Django 2.2 on 2019-04-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190305_2015'),
        #('reporting_common', '0007_auto_20190208_0316'),
        ('reporting_common', '0001_initial_squashed_0007_auto_20190208_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costusagereportmanifest',
            name='assembly_id',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='costusagereportmanifest',
            unique_together={('provider', 'assembly_id')},
        ),
    ]
