# Generated by Django 2.2.4 on 2019-08-20 15:13

import json
import pkgutil

from django.db import migrations


def load_azure_report_map_data(apps, schema_editor):
    """Load Azure Usage report to database mapping."""
    ReportColumnMap = apps.get_model('reporting_common', 'ReportColumnMap')

    data = pkgutil.get_data('reporting_common',
                            'data/azure_report_column_map.json')

    data = json.loads(data)

    for entry in data:
        del entry['report_type']
        if entry['database_table'] == "reporting_ocpstoragelineitem":
            continue
        map = ReportColumnMap(**entry)
        map.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reporting_common', '0013_auto_20190823_1442'),
    ]

    operations = [
        migrations.RunPython(
            code=load_azure_report_map_data,
        ),
    ]
