# Generated by Django 2.2.4 on 2019-08-29 20:53
import json
import pkgutil

from django.db import migrations

def reload_azure_map(apps, schema_editor):
    """Update report to database mapping."""
    ReportColumnMap = apps.get_model('reporting_common', 'ReportColumnMap')
    azure_items = ReportColumnMap.objects.filter(provider_type='AZURE')
    azure_items.delete()

    data = pkgutil.get_data('reporting_common',
                            'data/azure_report_column_map.json')

    data = json.loads(data)

    for entry in data:
        map = ReportColumnMap(**entry)
        map.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reporting_common', '0015_auto_20190827_1536'),
    ]

    operations = [
        migrations.RunPython(
            code=reload_azure_map,
        ),
    ]
