# Generated by Django 2.2.9 on 2020-01-21 22:25
import json
import pkgutil

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    replaces = []

    dependencies = [
        ("reporting_common", "0001_initial_squashed_0007_auto_20190208_0316_squashed_0019_auto_20191022_1602")
    ]

    operations = []
