# Generated by Django 2.2.4 on 2019-10-22 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_common', '0019_auto_20191022_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='costusagereportmanifest',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Provider'),
        ),
        migrations.AlterUniqueTogether(
            name='costusagereportmanifest',
            unique_together={('provider', 'assembly_id')},
        ),
        migrations.RunSQL(
            """
                UPDATE reporting_common_costusagereportmanifest
                    SET provider_id = provider_uuid
            """
        ),
    ]
