# Generated by Django 2.2.11 on 2020-04-07 16:04
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting_common", "0020_auto_20191022_1620_squashed_0025_auto_20200116_2048")]

    operations = [migrations.DeleteModel(name="ReportColumnMap")]
