# Generated by Django 2.2.4 on 2019-10-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_common', '0021_auto_20191022_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costusagereportmanifest',
            name='provider',
            field=models.ForeignKey(db_column='provider_uuid', on_delete=django.db.models.deletion.CASCADE, to='api.Provider'),
        ),
    ]
