# Generated by Django 2.2.4 on 2019-10-09 18:17
import json
import pkgutil

from django.db import migrations

def load_gcp_column_map(apps, schema_editor):
    """Load GCP column map to database mapping."""
    ReportColumnMap = apps.get_model('reporting_common', 'ReportColumnMap')
    ReportColumnMap.objects.filter(provider_type='GCP').delete()

    data = pkgutil.get_data('reporting_common',
                            'data/gcp_report_column_map.json')

    data = json.loads(data)

    for entry in data:
        map = ReportColumnMap(**entry)
        map.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_common', '0021_auto_20191022_1635'),
    ]

    operations = [
        migrations.RunPython(
            code=load_gcp_column_map,
        ),
    ]
