# Generated by Django 2.2.12 on 2020-05-12 15:18
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting_common", "0022_auto_20200505_1707")]

    operations = [migrations.DeleteModel(name="SIUnitScale")]
