# Generated by Django 2.2.12 on 2020-06-16 15:02
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting_common", "0023_delete_siunitscale")]

    operations = [
        migrations.RemoveField(model_name="costusagereportmanifest", name="num_processed_files"),
        migrations.RemoveField(model_name="costusagereportmanifest", name="task"),
    ]
