# Generated by Django 2.2.8 on 2019-12-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_common', '0024_costusagereportmanifest_manifest_completed_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcolumnmap',
            name='provider_type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('OCP', 'OCP'), ('AZURE', 'AZURE'), ('GCP', 'GCP')], default='AWS', max_length=50),
        ),
    ]
