# Generated by Django 2.2.12 on 2020-08-12 18:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting_common", "0025_remove_costusagereportmanifest_task")]

    operations = [
        migrations.AddField(
            model_name="costusagereportmanifest",
            name="manifest_modified_datetime",
            field=models.DateTimeField(null=True),
        )
    ]
