# Generated by Django 3.1.12 on 2021-07-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_common', '0028_costusagereportmanifest_operator_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='costusagereportmanifest',
            name='cluster_channel',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='costusagereportmanifest',
            name='operator_certified',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='costusagereportmanifest',
            name='operator_errors',
            field=models.JSONField(null=True),
        ),
    ]
