# Generated by Django 3.1.12 on 2021-07-29 19:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting_common", "0028_costusagereportmanifest_operator_version")]

    operations = [
        migrations.AddField(
            model_name="costusagereportmanifest", name="cluster_channel", field=models.TextField(null=True)
        ),
        migrations.AddField(
            model_name="costusagereportmanifest", name="operator_airgapped", field=models.BooleanField(null=True)
        ),
        migrations.AddField(
            model_name="costusagereportmanifest", name="operator_certified", field=models.BooleanField(null=True)
        ),
        migrations.AddField(
            model_name="costusagereportmanifest",
            name="operator_errors",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
