# Generated by Django 3.1.12 on 2021-08-04 19:24
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting_common", "0029_costusagereportmanifest_operator_info")]

    operations = [
        migrations.AddField(model_name="costusagereportmanifest", name="cluster_id", field=models.TextField(null=True))
    ]
