# Generated by Django 3.1.13 on 2021-09-22 20:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting_common", "0030_costusagereportmanifest_cluster_id")]

    operations = [
        migrations.AddField(
            model_name="costusagereportmanifest", name="export_time", field=models.DateTimeField(null=True)
        )
    ]
