# Generated by Django 3.1.13 on 2021-09-13 23:45
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting_common", "0030_costusagereportmanifest_cluster_id")]

    operations = [
        migrations.AddField(model_name="costusagereportmanifest", name="TEST_ID", field=models.TextField(null=True))
    ]
