# Generated by Django 3.2.19 on 2023-06-13 19:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0032_costusagereportmanifest_last_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="costusagereportmanifest",
            name="report_tracker",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
