# Generated by Django 3.2.14 on 2022-08-03 13:01
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0032_costusagereportmanifest_last_reports"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="costusagereportmanifest",
            options={"ordering": ["-manifest_creation_datetime"]},
        ),
    ]
