# Generated by Django 3.2.20 on 2023-07-06 19:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0033_costusagereportmanifest_reports_tracker"),
    ]

    operations = [
        migrations.AddField(
            model_name="costusagereportmanifest",
            name="operator_daily_reports",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="costusagereportmanifest",
            name="s3_parquet_cleared_tracker",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
