# Generated by Django 3.2.14 on 2022-08-03 15:52
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0033_alter_costusagereportmanifest_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="costusagereportmanifest",
            options={},
        ),
    ]
