# Generated by Django 3.2.19 on 2023-07-27 18:07
from django.db import migrations
from django.db import models


def update_s3_to_be_cleared(apps, schema_editor):
    ManifestTable = apps.get_model("reporting_common", "costusagereportmanifest")

    ManifestTable.objects.update(s3_parquet_cleared=False)


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0034_costusagereportmanifest_operator_daily_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costusagereportmanifest",
            name="s3_parquet_cleared",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.RunPython(update_s3_to_be_cleared),
    ]
