# Generated by Django 3.2.19 on 2023-07-27 18:07
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0034_costusagereportmanifest_operator_daily_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costusagereportmanifest",
            name="s3_parquet_cleared",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="costusagereportmanifest",
            name="daily_archive_start_date",
            field=models.DateTimeField(null=True),
        ),
    ]
