# Generated by Django 3.2.23 on 2024-01-29 16:04
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0035_alter_costusagereportmanifest_s3_parquet_cleared"),
    ]

    operations = [
        migrations.AddField(
            model_name="costusagereportmanifest",
            name="creation_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="costusagereportmanifest",
            name="export_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="costusagereportmanifest",
            name="completed_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="costusagereportmanifest",
            name="state",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name="costusagereportstatus",
            name="started_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="costusagereportstatus",
            name="completed_datetime",
            field=models.DateTimeField(null=True),
        ),
    ]
