# Generated by Django 3.2.23 on 2024-01-26 14:02
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0035_alter_costusagereportmanifest_s3_parquet_cleared"),
    ]

    operations = [
        migrations.RenameField(
            model_name="costusagereportmanifest",
            old_name="manifest_completed_datetime",
            new_name="completed_datetime",
        ),
        migrations.RenameField(
            model_name="costusagereportmanifest",
            old_name="manifest_creation_datetime",
            new_name="creation_datetime",
        ),
        migrations.RenameField(
            model_name="costusagereportmanifest",
            old_name="manifest_modified_datetime",
            new_name="export_datetime",
        ),
        migrations.RenameField(
            model_name="costusagereportstatus",
            old_name="last_completed_datetime",
            new_name="completed_datetime",
        ),
        migrations.RenameField(
            model_name="costusagereportstatus",
            old_name="last_started_datetime",
            new_name="started_datetime",
        ),
        migrations.RemoveField(
            model_name="costusagereportmanifest",
            name="export_time",
        ),
        migrations.RemoveField(
            model_name="costusagereportmanifest",
            name="last_reports",
        ),
    ]
