# Generated by Django 3.2.20 on 2023-09-01 17:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0035_alter_costusagereportmanifest_s3_parquet_cleared"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costusagereportmanifest",
            name="daily_archive_start_date",
        ),
        migrations.AlterField(
            model_name="costusagereportmanifest",
            name="s3_parquet_cleared",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
