# Generated by Django 3.2.23 on 2024-01-29 16:18
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0037_manifest_report_data_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costusagereportmanifest",
            name="export_time",
        ),
        migrations.RemoveField(
            model_name="costusagereportmanifest",
            name="last_reports",
        ),
        migrations.RemoveField(
            model_name="costusagereportmanifest",
            name="manifest_completed_datetime",
        ),
        migrations.RemoveField(
            model_name="costusagereportmanifest",
            name="manifest_creation_datetime",
        ),
        migrations.RemoveField(
            model_name="costusagereportmanifest",
            name="manifest_modified_datetime",
        ),
        migrations.RemoveField(
            model_name="costusagereportstatus",
            name="last_completed_datetime",
        ),
        migrations.RemoveField(
            model_name="costusagereportstatus",
            name="last_started_datetime",
        ),
    ]
