# Generated by Django 3.2.23 on 2024-02-08 17:59
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0037_manifest_report_data_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="costusagereportstatus",
            name="celery_task_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="costusagereportstatus",
            name="failed_status",
            field=models.IntegerField(
                choices=[(3, "Downloading"), (4, "Processing"), (5, "OCP-Cloud-Processing")], null=True
            ),
        ),
        migrations.AddField(
            model_name="costusagereportstatus",
            name="status",
            field=models.IntegerField(
                choices=[
                    (3, "Downloading"),
                    (4, "Processing"),
                    (5, "Ocp Cloud Processing"),
                    (1, "Done"),
                    (2, "Failed"),
                ],
                default=3,
            ),
        ),
    ]
