# Generated by Django 4.2.10 on 2024-02-22 17:49
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0039_auto_20240213_1715"),
    ]

    operations = [
        migrations.CreateModel(
            name="DelayedCeleryTasks",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_name", models.CharField(max_length=255)),
                ("task_args", models.JSONField()),
                ("task_kwargs", models.JSONField()),
                ("timeout_timestamp", models.DateTimeField()),
                ("provider_uuid", models.UUIDField()),
                ("queue_name", models.CharField(max_length=255)),
                ("metadata", models.JSONField(default=dict, null=True)),
            ],
            options={
                "db_table": "delayed_celery_tasks",
            },
        ),
    ]
