# Generated by Django 4.2.11 on 2024-05-06 14:07
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0040_delayedcelerytasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="AzureStorageCapacity",
            fields=[
                ("product_substring", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("capacity", models.FloatField(default=0)),
            ],
        ),
    ]
