# Generated by Django 4.2.11 on 2024-05-06 21:09
from django.db import migrations
from django.db import models


def populate_azure_storage_capacity(apps, schema_editor):
    AzureStorageCapacity = apps.get_model("reporting_common", "AzureStorageCapacity")
    initial_values = [
        ("P1", 4),
        ("P2", 8),
        ("P3", 16),
        ("P4", 32),
        ("P6", 64),
        ("P10", 128),
        ("P15", 256),
        ("P20", 512),
        ("P30", 1024),
        ("P40", 2048),
        ("P50", 4096),
        ("P60", 8192),
        ("P70", 16384),
        ("P80", 32767),
        ("S4", 32),
        ("S6", 64),
        ("S10", 128),
        ("S15", 256),
        ("S20", 512),
        ("S30", 1024),
        ("S40", 2048),
        ("S50", 4096),
        ("S60", 8192),
        ("S70", 16384),
        ("S80", 32767),
        ("E1", 4),
        ("E2", 8),
        ("E3", 16),
        ("E4", 32),
        ("E6", 64),
        ("E10", 128),
        ("E15", 256),
        ("E20", 512),
        ("E30", 1024),
        ("E40", 2048),
        ("E50", 4096),
        ("E60", 8192),
        ("E70", 16384),
        ("E80", 32767),
    ]
    objects_to_create = [
        AzureStorageCapacity(product_substring=substring, capacity=capacity) for substring, capacity in initial_values
    ]
    AzureStorageCapacity.objects.bulk_create(objects_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0040_delayedcelerytasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="AzureStorageCapacity",
            fields=[
                ("product_substring", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("capacity", models.IntegerField()),
            ],
        ),
        migrations.RunPython(populate_azure_storage_capacity),
    ]
