# Generated by Django 4.2.11 on 2024-05-07 13:05
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0041_azurestoragecapacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="azurestoragecapacity",
            name="capacity",
            field=models.IntegerField(),
        ),
    ]
