# Generated by Django 4.2.21 on 2025-06-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_common', '0042_alter_costusagereportmanifest_s3_parquet_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskcapacity',
            name='provider_type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('Azure', 'Azure'), ('GCP', 'GCP'), ('AWS-local', 'AWS-local'), ('Azure-local', 'Azure-local'), ('GCP-local', 'GCP-local')], max_length=50),
        ),
    ]
