# Generated by Django 5.2.14 on 2026-05-15 14:54
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0044_alter_diskcapacity_provider_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="diskcapacity",
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name="diskcapacity",
            table="reporting_common_diskcapacity",
        ),
    ]
