# Generated by Django 5.2.15 on 2026-10-09 13:19
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting_common", "0046_manifest_provider_created_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngressStagingPayload",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_id", models.CharField(max_length=255, unique=True)),
                ("payload", models.JSONField(null=True)),
                ("claim_token", models.UUIDField(null=True)),
                ("enqueued_at", models.DateTimeField(null=True)),
                ("reconciled_at", models.DateTimeField(null=True)),
                ("s3_key", models.TextField(null=True)),
                ("org_id", models.CharField(max_length=36, null=True)),
                ("cluster_id", models.TextField(null=True)),
                ("assembly_id", models.TextField(null=True)),
                ("account", models.CharField(max_length=150, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("attempts", models.IntegerField(default=0, null=True)),
                ("last_error", models.TextField(null=True)),
                ("stored_at", models.DateTimeField(null=True)),
                ("claimed_at", models.DateTimeField(null=True)),
                ("not_before", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "reporting_common_ingress_staging_payload",
                "indexes": [
                    models.Index(fields=["state", "not_before"], name="ingress_staging_claim_idx"),
                    models.Index(fields=["state", "claimed_at"], name="ingress_staging_lease_idx"),
                    models.Index(fields=["state", "stored_at"], name="ingress_staging_stored_at_idx"),
                ],
            },
        ),
    ]
