{
 "title": "Cost Management - Trino",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": "hccm-stage,hccm-prod" }
  ]
 },
 "panels": [
  { "title": "Trino Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "No. Workers",
   "type": "singlestat",
   "description": "Number of heartbeats from active workers.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max (trino_heartbeatdetector_activecount{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Cluster-wide Distributed Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "trino_memory_clustermemorypool_general_freedistributedbytes{namespace=\"$namespace\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "trino_memory_clustermemorypool_general_reserveddistributedbytes{namespace=\"$namespace\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "trino_memory_clustermemorypool_general_reservedrevocabledistributedbytes{namespace=\"$namespace\"}",
     "legendFormat": "Revokable Reserved"
    },
    {
     "expr": "trino_memory_clustermemorypool_general_totaldistributedbytes{namespace=\"$namespace\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "singlestat",
   "description": "Number of coordinators and workers.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max (trino_memory_clustermemorypool_general_nodes{namespace=\"$namespace\"})"
    }
   ]
  },
  { "title": "Trino Query Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Query Status",
   "type": "graph",
   "description": "Rate of queries in a particular state",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(trino_execution_querymanager_abandonedqueries_totalcount_total{namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "abandoned"
    },
    {
     "expr": "increase(trino_execution_querymanager_canceledqueries_totalcount_total{namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "canceled"
    },
    {
     "expr": "increase(trino_execution_querymanager_completedqueries_totalcount_total{namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "completed"
    },
    {
     "expr": "increase(trino_execution_querymanager_failedqueries_totalcount_total{namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "failed"
    },
    {
     "expr": "increase(trino_execution_querymanager_startedqueries_totalcount_total{namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "started"
    },
    {
     "expr": "increase(trino_execution_querymanager_submittedqueries_totalcount_total{namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "submitted"
    }
   ]
  },
  {
   "title": "Query Failures",
   "type": "graph",
   "description": "Rates of query failures",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(trino_execution_querymanager_externalfailures_totalcount_total{namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "external"
    },
    {
     "expr": "increase(trino_execution_querymanager_insufficientresourcesfailures_totalcount_total{namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "insufficient resources"
    },
    {
     "expr": "increase(trino_execution_querymanager_usererrorfailures_totalcount_total{namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "user error"
    },
    {
     "expr": "increase(trino_execution_querymanager_internalfailures_totalcount_total{namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "internal"
    }
   ]
  },
  {
   "title": "Query Execution Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trino_execution_querymanager_executiontime_alltime_avg_seconds{namespace=\"$namespace\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "trino_execution_querymanager_executiontime_alltime_min_seconds{namespace=\"$namespace\"}",
     "legendFormat": "min"
    },
    {
     "expr": "trino_execution_querymanager_executiontime_alltime_max_seconds{namespace=\"$namespace\"}",
     "legendFormat": "max"
    },
    {
     "expr": "increase(trino_execution_querymanager_executiontime_alltime_seconds{namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Query Queued Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trino_execution_querymanager_queuedtime_alltime_avg_seconds{namespace=\"$namespace\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "trino_execution_querymanager_queuedtime_alltime_min_seconds{namespace=\"$namespace\"}",
     "legendFormat": "min"
    },
    {
     "expr": "trino_execution_querymanager_queuedtime_alltime_max_seconds{namespace=\"$namespace\"}",
     "legendFormat": "max"
    },
    {
     "expr": "increase(trino_execution_querymanager_queuedtime_alltime_seconds{namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  { "title": "Trino JVM & Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "JVM threads per pod",
   "type": "graph",
   "description": "Live JVM threads per Trino pod. Pods have a 4,096 process/thread limit (OpenShift podPidsLimit); a worker that reaches it dies with 'unable to create native thread'.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\", job=~\"trino-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "graph",
   "description": "Container restarts per Trino pod (10 m window).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"trino-.*\"}[10m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM heap used / max per pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=\"$namespace\", job=~\"trino-.*\", area=\"heap\"}",
     "legendFormat": "used {{pod}}"
    },
    {
     "expr": "max(jvm_memory_max_bytes{namespace=\"$namespace\", job=\"trino-worker\", area=\"heap\"})",
     "legendFormat": "max (worker -Xmx)"
    }
   ]
  },
  {
   "title": "Container memory working set / limit",
   "type": "graph",
   "description": "Includes off-heap memory (threads, buffers, code cache). The kernel OOM-kills the pod at the limit.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (pod) (container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"trino-.*\", container=~\"trino-.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"trino-worker-.*\", resource=\"memory\"})",
     "legendFormat": "limit (worker)"
    }
   ]
  },
  {
   "title": "CPU usage per pod (cores)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"trino-.*\", container=~\"trino-.*\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Tasks created per worker (per second)",
   "type": "graph",
   "description": "Task churn per worker; compare with thread counts to tell load from per-pod leaks.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(trino_execution_sqltaskmanager_createdtasks_totalcount_total{namespace=\"$namespace\", job=\"trino-worker\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}