{
 "title": "Cost Management - Presto",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Presto Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "No. Workers",
   "type": "singlestat",
   "description": "Number of heartbeats from active workers.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "presto_heartbeatdetector_activecount{kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Cluster-wide Distributed Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "presto_memory_clustermemorypool_general_freedistributedbytes{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "presto_memory_clustermemorypool_general_reserveddistributedbytes{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "presto_memory_clustermemorypool_reserved_reservedrevocabledistributedbytes{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "Revokable Reserved"
    },
    {
     "expr": "presto_memory_clustermemorypool_general_totaldistributedbytes{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "singlestat",
   "description": "Number of coordinators and workers.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "presto_memory_clustermemorypool_general_nodes{kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  { "title": "Presto Query Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Query Status",
   "type": "graph",
   "description": "Rate of queries in a particular state",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(presto_execution_querymanager_abandonedqueries_totalcount_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "abandoned"
    },
    {
     "expr": "increase(presto_execution_querymanager_canceledqueries_totalcount_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "canceled"
    },
    {
     "expr": "increase(presto_execution_querymanager_completedqueries_totalcount_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "completed"
    },
    {
     "expr": "increase(presto_execution_querymanager_failedqueries_totalcount_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "failed"
    },
    {
     "expr": "increase(presto_execution_querymanager_startedqueries_totalcount_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "started"
    },
    {
     "expr": "increase(presto_execution_querymanager_submittedqueries_totalcount_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "submitted"
    }
   ]
  },
  {
   "title": "Query Failures",
   "type": "graph",
   "description": "Rates of query failures",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(presto_execution_querymanager_externalfailures_totalcount_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "external"
    },
    {
     "expr": "increase(presto_execution_querymanager_insufficientresourcesfailures_totalcount_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "insufficient resources"
    },
    {
     "expr": "increase(presto_execution_querymanager_usererrorfailures_totalcount_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "user error"
    },
    {
     "expr": "increase(presto_execution_querymanager_internalfailures_totalcount_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "internal"
    }
   ]
  },
  {
   "title": "Query Execution Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "presto_execution_querymanager_executiontime_alltime_avg_seconds{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "presto_execution_querymanager_executiontime_alltime_min_seconds{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "min"
    },
    {
     "expr": "presto_execution_querymanager_executiontime_alltime_max_seconds{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "max"
    },
    {
     "expr": "increase(presto_execution_querymanager_executiontime_alltime_seconds{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "current [{{ controller_revision_hash }}]"
    }
   ]
  },
  {
   "title": "Query Queued Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "presto_execution_querymanager_queuedtime_alltime_avg_seconds{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "presto_execution_querymanager_queuedtime_alltime_min_seconds{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "min"
    },
    {
     "expr": "presto_execution_querymanager_queuedtime_alltime_max_seconds{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "max"
    },
    {
     "expr": "increase(presto_execution_querymanager_queuedtime_alltime_seconds{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "current [{{ controller_revision_hash }}]"
    }
   ]
  },
  { "title": "Hive Metastore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "AWS S3 Requests/Retries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(presto_hive_s3_prestos3filesystem_awsrequestcount_totalcount_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "requests [{{ controller_revision_hash }}]"
    },
    {
     "expr": "increase(presto_hive_s3_prestos3filesystem_awsretrycount_totalcount_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "retries [{{ controller_revision_hash }}]"
    }
   ]
  },
  {
   "title": "AWS S3 Exceptions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(presto_hive_s3_prestos3filesystem_awsabortedexceptions_totalcount_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "aborted [{{ controller_revision_hash }}]"
    },
    {
     "expr": "increase(presto_hive_s3_prestos3filesystem_awsthrottleexceptions_totalcount_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "throttled [{{ controller_revision_hash }}]"
    },
    {
     "expr": "increase(presto_hive_s3_prestos3filesystem_socketexceptions_totalcount_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "socket [{{ controller_revision_hash }}]"
    },
    {
     "expr": "increase(presto_hive_s3_prestos3filesystem_sockettimeoutexceptions_totalcount_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "socket timeout [{{ controller_revision_hash }}]"
    }
   ]
  },
  {
   "title": "AWS Network Latency (AVG)",
   "type": "graph",
   "description": "Average response times for AWS client requests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "presto_hive_s3_prestos3filesystem_awsclientexecutetime_alltime_avg_seconds{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "avg. client execution [{{ controller_revision_hash }}]"
    },
    {
     "expr": "presto_hive_s3_prestos3filesystem_awsrequesttime_alltime_avg_seconds{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "avg. request [{{ controller_revision_hash }}]"
    }
   ]
  }
 ]
}