{
 "title": "Cost Management - PostgreSQL",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kubernetes_namespace)"
   },
   { "name": "Datasource", "label": "Datasource" }
  ]
 },
 "panels": [
  {
   "title": "Row Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (increase(pg_stat_database_tup_deleted{kubernetes_namespace='$namespace', datname='koku'}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "deleted",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum by (datname) (increase(pg_stat_database_tup_fetched{kubernetes_namespace='$namespace', datname='koku'}[1m]))",
     "legendFormat": "fetched"
    },
    {
     "expr": "sum by (datname) (increase(pg_stat_database_tup_inserted{kubernetes_namespace='$namespace', datname='koku'}[1m]))",
     "legendFormat": "inserted"
    },
    {
     "expr": "sum by (datname) (increase(pg_stat_database_tup_updated{kubernetes_namespace='$namespace', datname='koku'}[1m]))",
     "legendFormat": "updated"
    },
    {
     "expr": "sum by (datname) (increase(pg_stat_database_tup_returned{kubernetes_namespace='$namespace', datname='koku'}[1m]))",
     "legendFormat": "returned"
    }
   ]
  },
  {
   "title": "Max Tx Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "clockms" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (increase(pg_stat_activity_max_tx_duration{kubernetes_namespace=\"$namespace\", datname=\"koku\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Background writer activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (increase(pg_stat_bgwriter_checkpoint_sync_time{kubernetes_namespace='$namespace'}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "sync time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum by (datname) (increase(pg_stat_bgwriter_checkpoint_write_time{kubernetes_namespace='$namespace'}[1m]))",
     "legendFormat": "write time"
    }
   ]
  },
  {
   "title": "Lock Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{kubernetes_namespace='$namespace', datname='koku'})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DB Conflicts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_database_conflicts_confl_bufferpin{kubernetes_namespace='$namespace', datname='koku'})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "bufferpin",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum by (datname) (pg_stat_database_conflicts_confl_deadlock{kubernetes_namespace='$namespace', datname='koku'})",
     "legendFormat": "deadlock"
    },
    {
     "expr": "sum by (datname) (pg_stat_database_conflicts_confl_lock{kubernetes_namespace='$namespace', datname='koku'})",
     "legendFormat": "lock"
    },
    {
     "expr": "sum by (datname) (pg_stat_database_conflicts_confl_snapshot{kubernetes_namespace='$namespace', datname='koku'})",
     "legendFormat": "snapshot"
    },
    {
     "expr": "sum by (datname) (pg_stat_database_conflicts_confl_tablespace{kubernetes_namespace='$namespace', datname='koku'})",
     "legendFormat": "tablespace"
    }
   ]
  },
  {
   "title": "DB Block Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (increase(pg_stat_database_blks_hit{kubernetes_namespace='$namespace', datname='koku'}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffer cache hits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum by (datname) (increase(pg_stat_database_blks_read{kubernetes_namespace='$namespace', datname='koku'}[1m]))",
     "legendFormat": "block reads"
    }
   ]
  }
 ]
}