# Generated by Django 2.0.5 on 2018-05-24 18:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSCostEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_start', models.DateTimeField()),
                ('interval_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AWSCostEntryBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_resource', models.CharField(default='aws', max_length=50)),
                ('bill_type', models.CharField(max_length=50)),
                ('payer_account_id', models.CharField(max_length=50)),
                ('billing_period_start', models.DateTimeField()),
                ('billing_period_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AWSCostEntryLineItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField()),
                ('invoice_id', models.CharField(max_length=63)),
                ('line_item_type', models.CharField(max_length=50)),
                ('usage_account_id', models.CharField(max_length=50)),
                ('usage_start', models.DateTimeField()),
                ('usage_end', models.DateTimeField()),
                ('product_code', models.CharField(max_length=50)),
                ('usage_type', models.CharField(max_length=50)),
                ('operation', models.CharField(max_length=50)),
                ('availability_zone', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=50)),
                ('usage_amount', models.PositiveIntegerField()),
                ('normalization_factor', models.PositiveIntegerField()),
                ('normalized_usage_amount', models.PositiveIntegerField()),
                ('currency_code', models.CharField(max_length=10)),
                ('unblended_rate', models.FloatField()),
                ('unblended_cost', models.FloatField()),
                ('blended_rate', models.FloatField()),
                ('blended_cost', models.FloatField()),
                ('tax_type', models.TextField()),
                ('cost_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.AWSCostEntry')),
                ('cost_entry_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.AWSCostEntryBill')),
            ],
        ),
        migrations.CreateModel(
            name='AWSCostEntryPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_on_demand_cost', models.FloatField()),
                ('public_on_demand_rate', models.FloatField()),
                ('term', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=24)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.AWSCostEntryLineItem')),
            ],
        ),
        migrations.CreateModel(
            name='AWSCostEntryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=128, unique=True)),
                ('product_name', models.CharField(max_length=63)),
                ('product_family', models.CharField(max_length=150)),
                ('service_code', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('instance_type', models.CharField(max_length=50)),
                ('memory', models.PositiveIntegerField()),
                ('vcpu', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AWSCostEntryReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_arn', models.TextField(unique=True)),
                ('availability_zone', models.CharField(max_length=50)),
                ('number_of_reservations', models.PositiveIntegerField()),
                ('units_per_reservation', models.PositiveIntegerField()),
                ('amortized_upfront_fee', models.FloatField()),
                ('amortized_upfront_cost_for_usage', models.FloatField()),
                ('recurring_fee_for_usage', models.FloatField()),
                ('unused_quantity', models.PositiveIntegerField()),
                ('unused_recurring_fee', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='awscostentrylineitem',
            name='cost_entry_pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.AWSCostEntryPricing'),
        ),
        migrations.AddField(
            model_name='awscostentrylineitem',
            name='cost_entry_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.AWSCostEntryProduct'),
        ),
        migrations.AddField(
            model_name='awscostentrylineitem',
            name='cost_entry_reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.AWSCostEntryReservation'),
        ),
        migrations.AddField(
            model_name='awscostentry',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.AWSCostEntryBill'),
        ),
    ]
