# Generated by Django 2.0.6 on 2018-06-15 17:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awscostentrypricing',
            name='line_item',
        ),
        migrations.AddField(
            model_name='awscostentryproduct',
            name='memory_unit',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='availability_zone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='blended_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='blended_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='cost_entry_pricing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reporting.AWSCostEntryPricing'),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='cost_entry_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reporting.AWSCostEntryProduct'),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='cost_entry_reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reporting.AWSCostEntryReservation'),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='invoice_id',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='normalization_factor',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='normalized_usage_amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='operation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='resource_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='tax_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='unblended_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='unblended_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='usage_amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='usage_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrypricing',
            name='term',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrypricing',
            name='unit',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryproduct',
            name='instance_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryproduct',
            name='memory',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryproduct',
            name='product_family',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryproduct',
            name='product_name',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryproduct',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryproduct',
            name='service_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryproduct',
            name='sku',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='awscostentryproduct',
            name='vcpu',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryreservation',
            name='amortized_upfront_cost_for_usage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryreservation',
            name='amortized_upfront_fee',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryreservation',
            name='availability_zone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryreservation',
            name='number_of_reservations',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryreservation',
            name='recurring_fee_for_usage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryreservation',
            name='units_per_reservation',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryreservation',
            name='unused_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryreservation',
            name='unused_recurring_fee',
            field=models.FloatField(null=True),
        ),
    ]
