# Generated by Django 2.0.6 on 2018-06-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20180615_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='blended_cost',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='blended_rate',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='normalization_factor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='normalized_usage_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='unblended_cost',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='unblended_rate',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='usage_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrypricing',
            name='public_on_demand_cost',
            field=models.DecimalField(decimal_places=9, max_digits=17),
        ),
        migrations.AlterField(
            model_name='awscostentrypricing',
            name='public_on_demand_rate',
            field=models.DecimalField(decimal_places=9, max_digits=17),
        ),
        migrations.AlterField(
            model_name='awscostentryreservation',
            name='amortized_upfront_cost_for_usage',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryreservation',
            name='amortized_upfront_fee',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryreservation',
            name='recurring_fee_for_usage',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryreservation',
            name='unused_recurring_fee',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
    ]
