# Generated by Django 2.1 on 2018-08-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20180619_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscostentrylineitem',
            name='hash',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='awscostentrylineitem',
            unique_together={('hash', 'cost_entry')},
        ),
    ]
