# Generated by Django 2.1 on 2018-10-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20180928_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscostentrybill',
            name='finalized_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='awscostentrybill',
            name='summary_data_creation_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='awscostentrybill',
            name='summary_data_updated_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
