# Generated by Django 2.1 on 2018-08-16 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_auto_20180807_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscostentryreservation',
            name='cost_entry_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reporting.AWSCostEntryBill'),
        ),
        migrations.AlterField(
            model_name='awscostentryproduct',
            name='sku',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryreservation',
            name='reservation_arn',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='awscostentryproduct',
            unique_together={('sku', 'product_name', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='awscostentryreservation',
            unique_together={('reservation_arn', 'cost_entry_bill')},
        ),
    ]
