# Generated by Django 2.1.2 on 2018-10-08 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_auto_20181003_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscostentrylineitemaggregates',
            name='account_alias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reporting.AWSAccountAlias'),
        ),
    ]
