# Generated by Django 2.1 on 2018-08-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_auto_20180807_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awscostentryreservation',
            name='amortized_upfront_cost_for_usage',
        ),
        migrations.RemoveField(
            model_name='awscostentryreservation',
            name='amortized_upfront_fee',
        ),
        migrations.RemoveField(
            model_name='awscostentryreservation',
            name='availability_zone',
        ),
        migrations.RemoveField(
            model_name='awscostentryreservation',
            name='recurring_fee_for_usage',
        ),
        migrations.RemoveField(
            model_name='awscostentryreservation',
            name='unused_quantity',
        ),
        migrations.RemoveField(
            model_name='awscostentryreservation',
            name='unused_recurring_fee',
        ),
        migrations.AddField(
            model_name='awscostentrylineitem',
            name='reservation_amortized_upfront_cost_for_usage',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='awscostentrylineitem',
            name='reservation_amortized_upfront_fee',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='awscostentrylineitem',
            name='reservation_recurring_fee_for_usage',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='awscostentrylineitem',
            name='reservation_unused_quantity',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='awscostentrylineitem',
            name='reservation_unused_recurring_fee',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='normalized_usage_amount',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='usage_amount',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryproduct',
            name='sku',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryreservation',
            name='units_per_reservation',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='awscostentryproduct',
            unique_together={('sku', 'product_name', 'region')},
        ),
    ]
