# Generated by Django 2.1.2 on 2018-10-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_awscostentrylineitemaggregates_account_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscostentrybill',
            name='provider_id',
            field=models.IntegerField(null=True),
        ),
    ]
