# Generated by Django 2.1 on 2018-08-24 00:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20180821_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSCostEntryLineItemAggregates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_scope_value', models.IntegerField()),
                ('report_type', models.CharField(max_length=50)),
                ('usage_account_id', models.CharField(max_length=50, null=True)),
                ('product_code', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50, null=True)),
                ('availability_zone', models.CharField(max_length=50, null=True)),
                ('usage_amount', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('unblended_cost', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('resource_count', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'reporting_awscostentrylineitem_aggregates',
            },
        ),
        migrations.CreateModel(
            name='AWSCostEntryLineItemDaily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_item_type', models.CharField(max_length=50)),
                ('usage_account_id', models.CharField(max_length=50)),
                ('usage_start', models.DateField()),
                ('product_code', models.CharField(max_length=50)),
                ('usage_type', models.CharField(max_length=50, null=True)),
                ('operation', models.CharField(max_length=50, null=True)),
                ('availability_zone', models.CharField(max_length=50, null=True)),
                ('resource_id', models.CharField(max_length=256, null=True)),
                ('usage_amount', models.FloatField(null=True)),
                ('normalization_factor', models.FloatField(null=True)),
                ('normalized_usage_amount', models.FloatField(null=True)),
                ('currency_code', models.CharField(max_length=10)),
                ('unblended_rate', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('unblended_cost', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('blended_rate', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('blended_cost', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('public_on_demand_cost', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('public_on_demand_rate', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('tax_type', models.TextField(null=True)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'db_table': 'reporting_awscostentrylineitem_daily',
            },
        ),
        migrations.CreateModel(
            name='AWSCostEntryLineItemDailySummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usage_start', models.DateField()),
                ('usage_account_id', models.CharField(max_length=50)),
                ('product_code', models.CharField(max_length=50)),
                ('product_family', models.CharField(max_length=150, null=True)),
                ('availability_zone', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=50, null=True)),
                ('instance_type', models.CharField(max_length=50, null=True)),
                ('unit', models.CharField(max_length=63, null=True)),
                ('resource_count', models.IntegerField(null=True)),
                ('usage_amount', models.FloatField(null=True)),
                ('normalization_factor', models.FloatField(null=True)),
                ('normalized_usage_amount', models.FloatField(null=True)),
                ('currency_code', models.CharField(max_length=10)),
                ('unblended_rate', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('unblended_cost', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('blended_rate', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('blended_cost', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('public_on_demand_cost', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('public_on_demand_rate', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('tax_type', models.TextField(null=True)),
            ],
            options={
                'db_table': 'reporting_awscostentrylineitem_daily_summary',
            },
        ),
        migrations.AddIndex(
            model_name='awscostentry',
            index=models.Index(fields=['interval_start'], name='interval_start_idx'),
        ),
        migrations.AddIndex(
            model_name='awscostentryproduct',
            index=models.Index(fields=['region'], name='region_idx'),
        ),
        migrations.AddIndex(
            model_name='awscostentrylineitemdailysummary',
            index=models.Index(fields=['usage_start'], name='summary_usage_start_idx'),
        ),
        migrations.AddIndex(
            model_name='awscostentrylineitemdailysummary',
            index=models.Index(fields=['product_code'], name='summary_product_code_idx'),
        ),
        migrations.AddIndex(
            model_name='awscostentrylineitemdailysummary',
            index=models.Index(fields=['usage_account_id'], name='summary_usage_account_id_idx'),
        ),
        migrations.AddField(
            model_name='awscostentrylineitemdaily',
            name='cost_entry_pricing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reporting.AWSCostEntryPricing'),
        ),
        migrations.AddField(
            model_name='awscostentrylineitemdaily',
            name='cost_entry_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reporting.AWSCostEntryProduct'),
        ),
        migrations.AddField(
            model_name='awscostentrylineitemdaily',
            name='cost_entry_reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reporting.AWSCostEntryReservation'),
        ),
        migrations.AddIndex(
            model_name='awscostentrylineitemdaily',
            index=models.Index(fields=['usage_start'], name='usage_start_idx'),
        ),
        migrations.AddIndex(
            model_name='awscostentrylineitemdaily',
            index=models.Index(fields=['product_code'], name='product_code_idx'),
        ),
        migrations.AddIndex(
            model_name='awscostentrylineitemdaily',
            index=models.Index(fields=['usage_account_id'], name='usage_account_id_idx'),
        ),
    ]
