# Generated by Django 2.1 on 2018-09-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_auto_20180824_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSAccountAlias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=50, unique=True)),
                ('account_alias', models.CharField(max_length=63)),
            ],
        ),
    ]
