# Generated by Django 2.1 on 2018-09-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_awsaccountalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscostentrylineitemdaily',
            name='usage_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='awscostentrylineitemdailysummary',
            name='usage_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdaily',
            name='usage_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdailysummary',
            name='usage_start',
            field=models.DateTimeField(),
        ),
    ]
