# Generated by Django 2.1 on 2018-09-25 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_awsaccountalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscostentrylineitemdailysummary',
            name='account_alias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reporting.AWSAccountAlias'),
        ),
    ]
