# Generated by Django 2.1.2 on 2018-10-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_auto_20181016_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocpusagelineitemaggregates',
            name='pod_limit_cpu_cores',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemaggregates',
            name='pod_limit_memory_bytes',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemaggregates',
            name='pod_request_cpu_core_seconds',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemaggregates',
            name='pod_request_memory_byte_seconds',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemaggregates',
            name='pod_usage_cpu_core_seconds',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemaggregates',
            name='pod_usage_memory_byte_seconds',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='pod_limit_cpu_cores',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='pod_limit_memory_bytes',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='pod_request_cpu_core_seconds',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='pod_request_memory_byte_seconds',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='pod_usage_cpu_core_seconds',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='pod_usage_memory_byte_seconds',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
    ]
