# Generated by Django 2.1.2 on 2018-11-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_auto_20181018_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_usage_cpu_cost',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_usage_memory_cost',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
    ]
