# Generated by Django 2.1.2 on 2018-11-02 16:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_auto_20181018_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timeunit', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=6, max_digits=25)),
                ('metric', models.CharField(max_length=100)),
            ],
        ),
    ]
