# Generated by Django 2.1.2 on 2018-11-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_auto_20181105_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocpusagelineitemdailysummary',
            old_name='pod_usage_cpu_cost',
            new_name='pod_usage_cpu_charge',
        ),
        migrations.RenameField(
            model_name='ocpusagelineitemdailysummary',
            old_name='pod_usage_memory_cost',
            new_name='pod_usage_memory_charge',
        ),
    ]
