# Generated by Django 2.1.2 on 2018-11-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_auto_20181106_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_usage_cpu_charge',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_usage_memory_charge',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
    ]
