# Generated by Django 2.1.2 on 2018-11-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0014_auto_20181108_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='timeunit',
            field=models.CharField(choices=[('hour', 'hour'), ('minute', 'minute'), ('second', 'second'), ('day', 'day'), ('month', 'month'), ('year', 'year'), ('onetime', 'onetime'), ('nil', 'nil')], default=('hour', 'hour'), max_length=100),
        ),
    ]
