# Generated by Django 2.1.2 on 2018-11-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0015_auto_20181109_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
