# Generated by Django 2.1.2 on 2018-11-13 18:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0016_delete_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_uuid', models.UUIDField()),
                ('metric', models.CharField(choices=[('cpu_core_per_hour', 'cpu_core_per_hour'), ('memory_bytes_per_hour', 'memory_bytes_per_hour')], default='cpu_core_per_hour', max_length=256)),
                ('rates', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
