# Generated by Django 2.1.2 on 2018-11-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0017_auto_20181120_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocpusagelineitem',
            old_name='pod_limit_memory_bytes',
            new_name='pod_limit_memory_byte_seconds',
        ),
        migrations.RenameField(
            model_name='ocpusagelineitemdaily',
            old_name='pod_limit_memory_bytes',
            new_name='pod_limit_memory_byte_seconds',
        ),
    ]
