# Generated by Django 2.1.2 on 2018-12-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0018_auto_20181129_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpusagelineitemdaily',
            name='cluster_capacity_cpu_core_seconds',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdaily',
            name='cluster_capacity_memory_byte_seconds',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='cluster_capacity_cpu_core_hours',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='cluster_capacity_memory_gigabyte_hours',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
    ]
