# Generated by Django 2.1.2 on 2018-12-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0019_auto_20181206_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_label_key',
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_label_value',
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddIndex(
            model_name='ocpusagelineitemdailysummary',
            index=models.Index(fields=['pod_label_key'], name='pod_label_key_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpusagelineitemdailysummary',
            index=models.Index(fields=['pod_label_value'], name='pod_label_value_idx'),
        ),
    ]
