# Generated by Django 2.1.2 on 2018-12-12 18:16

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0020_auto_20181211_1557'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ocpusagelineitemdailysummary',
            name='pod_label_key_idx',
        ),
        migrations.RemoveIndex(
            model_name='ocpusagelineitemdailysummary',
            name='pod_label_value_idx',
        ),
        migrations.RemoveField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_label_key',
        ),
        migrations.RemoveField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_label_value',
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddIndex(
            model_name='ocpusagelineitemdailysummary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['pod_labels'], name='pod_labels_idx'),
        ),
    ]
