# Generated by Django 2.1.2 on 2019-01-09 18:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0022_auto_20181221_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscostentrylineitemdailysummary',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
