# Generated by Django 2.1.5 on 2019-01-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0024_ocpusagepodlabelsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpusagelineitem',
            name='resource_id',
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemaggregates',
            name='resource_id',
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdaily',
            name='resource_id',
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='resource_id',
            field=models.CharField(max_length=253, null=True),
        ),
    ]
