# Generated by Django 2.1.2 on 2019-01-28 17:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0024_ocpusagepodlabelsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscostentrylineitemaggregates',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
