# Generated by Django 2.1.2 on 2019-01-29 15:17

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0025_auto_20190128_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSTagsSummary',
            fields=[
                ('key', models.CharField(max_length=253, primary_key=True, serialize=False)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None)),
            ],
            options={
                'db_table': 'reporting_awstags_summary',
            },
        ),
        migrations.AddField(
            model_name='awscostentrylineitemaggregates',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
