# Generated by Django 2.1.5 on 2019-02-06 22:00

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0028_auto_20190205_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCPStorageLineItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=253)),
                ('pod', models.CharField(max_length=253, null=True)),
                ('persistentvolumeclaim', models.CharField(max_length=253, null=True)),
                ('persistentvolume', models.CharField(max_length=253, null=True)),
                ('storageclass', models.CharField(max_length=50, null=True)),
                ('persistentvolumeclaim_capacity_bytes', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('persistentvolumeclaim_capacity_byte_seconds', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('volume_request_storage_byte_seconds', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('persistentvolumeclaim_usage_byte_seconds', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('persistentvolume_labels', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('persistentvolumeclaim_labels', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OCPStorageLineItemDailySummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cluster_id', models.CharField(max_length=50, null=True)),
                ('cluster_alias', models.CharField(max_length=256, null=True)),
                ('namespace', models.CharField(max_length=253)),
                ('pod', models.CharField(max_length=253)),
                ('usage_start', models.DateTimeField()),
                ('usage_end', models.DateTimeField()),
                ('persistentvolume_labels', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('persistentvolumeclaim_labels', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('persistentvolumeclaim_capacity_gigabyte', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('persistentvolumeclaim_capacity_gigabyte_hours', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('volume_request_storage_gigabyte_hours', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('persistentvolumeclaim_usage_gigabyte_hours', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
            ],
            options={
                'db_table': 'reporting_ocpstoragelineitem_daily_summary',
            },
        ),
        migrations.CreateModel(
            name='OCPUStorageLineItemDaily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cluster_id', models.CharField(max_length=50, null=True)),
                ('cluster_alias', models.CharField(max_length=256, null=True)),
                ('namespace', models.CharField(max_length=253)),
                ('pod', models.CharField(max_length=253, null=True)),
                ('usage_start', models.DateTimeField()),
                ('usage_end', models.DateTimeField()),
                ('persistentvolumeclaim_capacity_bytes', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('persistentvolumeclaim_capacity_byte_seconds', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('volume_request_storage_byte_seconds', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('persistentvolumeclaim_usage_byte_seconds', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('total_seconds', models.IntegerField()),
                ('persistentvolume_labels', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('persistentvolumeclaim_labels', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'db_table': 'reporting_ocpstoragelineitem_daily',
            },
        ),
        migrations.AddIndex(
            model_name='ocpustoragelineitemdaily',
            index=models.Index(fields=['usage_start'], name='ocp_storage_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpustoragelineitemdaily',
            index=models.Index(fields=['namespace'], name='namespace_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpustoragelineitemdaily',
            index=models.Index(fields=['pod'], name='pod_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpstoragelineitemdailysummary',
            index=models.Index(fields=['usage_start'], name='summary_ocp_usage_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpstoragelineitemdailysummary',
            index=models.Index(fields=['namespace'], name='summary_namespace_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpstoragelineitemdailysummary',
            index=models.Index(fields=['pod'], name='summary_pod_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpstoragelineitemdailysummary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['persistentvolume_labels'], name='persistentvolume_labels_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpstoragelineitemdailysummary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['persistentvolumeclaim_labels'], name='pvc_labels_idx'),
        ),
        migrations.AddField(
            model_name='ocpstoragelineitem',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.OCPUsageReport'),
        ),
        migrations.AddField(
            model_name='ocpstoragelineitem',
            name='report_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.OCPUsageReportPeriod'),
        ),
        migrations.AlterUniqueTogether(
            name='ocpstoragelineitem',
            unique_together={('report', 'namespace', 'pod')},
        ),
    ]
