# Generated by Django 2.1.5 on 2019-02-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0030_auto_20190208_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpawscostlineitemdailysummary',
            name='instance_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
