# Generated by Django 2.1.5 on 2019-02-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0030_auto_20190208_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpawscostlineitemdailysummary',
            name='currency_code',
            field=models.CharField(default='USD', max_length=10),
            preserve_default=False,
        ),
    ]
