# Generated by Django 2.1.5 on 2019-02-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0031_ocpawscostlineitemdailysummary_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpawscostlineitemdailysummary',
            name='instance_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ocpstoragelineitemdailysummary',
            name='persistentvolumeclaim_charge_gb_month',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
    ]
