# Generated by Django 2.1.7 on 2019-02-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0031_ocpawscostlineitemdailysummary_instance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpstoragelineitemdailysummary',
            name='pvc_charge_gb_request_per_month',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpstoragelineitemdailysummary',
            name='pvc_charge_gb_usage_per_month',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
    ]
