# Generated by Django 2.1.7 on 2019-02-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0032_auto_20190213_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocpstoragelineitemdailysummary',
            old_name='pvc_charge_gb_request_per_month',
            new_name='persistentvolumeclaim_charge_gb_month',
        ),
        migrations.RemoveField(
            model_name='ocpstoragelineitemdailysummary',
            name='pvc_charge_gb_usage_per_month',
        ),
    ]
