# Generated by Django 2.1.5 on 2019-02-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0033_auto_20190214_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocpstoragelineitemdailysummary',
            old_name='persistentvolumeclaim_capacity_gigabyte_hours',
            new_name='persistentvolumeclaim_capacity_gigabyte_months',
        ),
        migrations.RenameField(
            model_name='ocpstoragelineitemdailysummary',
            old_name='persistentvolumeclaim_usage_gigabyte_hours',
            new_name='persistentvolumeclaim_usage_gigabyte_months',
        ),
        migrations.RenameField(
            model_name='ocpstoragelineitemdailysummary',
            old_name='volume_request_storage_gigabyte_hours',
            new_name='volume_request_storage_gigabyte_months',
        ),
    ]
