# Generated by Django 2.1.7 on 2019-02-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0034_ocpstoragevolumeclaimlabelsummary_ocpstoragevolumelabelsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpawscostlineitemdailysummary',
            name='currency_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
