# Generated by Django 2.1.5 on 2019-02-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0035_ocpawscostlineitemdailysummary_currency_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocpstoragelineitemdailysummary',
            old_name='persistentvolumeclaim_capacity_gigabyte_hours',
            new_name='persistentvolumeclaim_capacity_gigabyte_months',
        ),
        migrations.RenameField(
            model_name='ocpstoragelineitemdailysummary',
            old_name='persistentvolumeclaim_usage_gigabyte_hours',
            new_name='persistentvolumeclaim_usage_gigabyte_months',
        ),
        migrations.RenameField(
            model_name='ocpstoragelineitemdailysummary',
            old_name='volume_request_storage_gigabyte_hours',
            new_name='volume_request_storage_gigabyte_months',
        ),
        migrations.AddField(
            model_name='ocpstoragelineitemdailysummary',
            name='node',
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name='ocpustoragelineitemdaily',
            name='node',
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AlterField(
            model_name='ocpstoragelineitemdailysummary',
            name='pod',
            field=models.CharField(max_length=253, null=True),
        ),
    ]
