# Generated by Django 2.1.5 on 2019-02-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0036_auto_20190215_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocpstoragelineitemdailysummary',
            old_name='persistentvolume_labels',
            new_name='volume_labels',
        ),
        migrations.RemoveField(
            model_name='ocpstoragelineitemdailysummary',
            name='persistentvolumeclaim_labels',
        ),
    ]
