# Generated by Django 2.1.5 on 2019-02-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0037_auto_20190218_2054'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS reporting_ocpawscostlineitem_daily;
            DROP VIEW IF EXISTS reporting_ocpaws_usagecostlineitem_daily;

            CREATE OR REPLACE VIEW reporting_ocpaws_usagelineitem_daily AS (
                WITH cte_usage_tag_matched as (
                    SELECT aws.id as aws_id,
                            ocp.id as ocp_id,
                            aws.usage_start,
                            ocp.namespace
                        FROM (
                        SELECT aws.id,
                            aws.usage_start,
                            LOWER(key) as key,
                            LOWER(value) as value
                            FROM reporting_awscostentrylineitem_daily as aws,
                                jsonb_each_text(aws.tags) labels
                        ) AS aws
                        JOIN (
                            SELECT ocp.id,
                                ocp.usage_start,
                                ocp.cluster_alias,
                                ocp.node,
                                ocp.namespace,
                                LOWER(key) as key,
                                LOWER(value) as value
                            FROM reporting_ocpusagelineitem_daily as ocp,
                                jsonb_each_text(ocp.pod_labels) labels
                        ) AS ocp
                            ON aws.usage_start::date = ocp.usage_start::date
                                AND (
                                    (aws.key = ocp.key AND aws.value = ocp.value)
                                    OR (aws.key = 'ocp_cluster' AND aws.value = ocp.cluster_alias)
                                    OR (aws.key = 'ocp_node' AND aws.value = ocp.node)
                                    OR (aws.key = 'ocp_project' AND aws.value = ocp.namespace)
                                )
                        GROUP BY aws.id, ocp.id, aws.usage_start, ocp.namespace
                ),
                cte_number_of_shared_projects AS (
                    SELECT usage_start,
                        aws_id,
                        count(DISTINCT namespace) as shared_projects
                    FROM cte_usage_tag_matched
                    GROUP BY usage_start, aws_id
                )
                SELECT ocp.cluster_id,
                    ocp.cluster_alias,
                    ocp.namespace,
                    ocp.pod,
                    ocp.node,
                    ocp.pod_labels,
                    ocp.pod_usage_cpu_core_seconds,
                    ocp.pod_request_cpu_core_seconds,
                    ocp.pod_limit_cpu_core_seconds,
                    ocp.pod_usage_memory_byte_seconds,
                    ocp.pod_request_memory_byte_seconds,
                    ocp.node_capacity_cpu_cores,
                    ocp.node_capacity_cpu_core_seconds,
                    ocp.node_capacity_memory_bytes,
                    ocp.node_capacity_memory_byte_seconds,
                    ocp.cluster_capacity_cpu_core_seconds,
                    ocp.cluster_capacity_memory_byte_seconds,
                    aws.cost_entry_product_id,
                    aws.cost_entry_pricing_id,
                    aws.cost_entry_reservation_id,
                    aws.line_item_type,
                    aws.usage_account_id,
                    aws.usage_start,
                    aws.usage_end,
                    aws.product_code,
                    aws.usage_type,
                    aws.operation,
                    aws.availability_zone,
                    aws.resource_id,
                    aws.usage_amount,
                    aws.normalization_factor,
                    aws.normalized_usage_amount,
                    aws.currency_code,
                    aws.unblended_rate,
                    aws.unblended_cost,
                    aws.blended_rate,
                    aws.blended_cost,
                    aws.public_on_demand_cost,
                    aws.public_on_demand_rate,
                    aws.tax_type,
                    aws.tags,
                    1::int as shared_projects
                FROM reporting_awscostentrylineitem_daily as aws
                JOIN reporting_ocpusagelineitem_daily as ocp
                    ON aws.resource_id = ocp.resource_id
                        AND aws.usage_start::date = ocp.usage_start::date

                UNION

                SELECT ocp.cluster_id,
                    ocp.cluster_alias,
                    ocp.namespace,
                    ocp.pod,
                    ocp.node,
                    ocp.pod_labels,
                    ocp.pod_usage_cpu_core_seconds,
                    ocp.pod_request_cpu_core_seconds,
                    ocp.pod_limit_cpu_core_seconds,
                    ocp.pod_usage_memory_byte_seconds,
                    ocp.pod_request_memory_byte_seconds,
                    ocp.node_capacity_cpu_cores,
                    ocp.node_capacity_cpu_core_seconds,
                    ocp.node_capacity_memory_bytes,
                    ocp.node_capacity_memory_byte_seconds,
                    ocp.cluster_capacity_cpu_core_seconds,
                    ocp.cluster_capacity_memory_byte_seconds,
                    aws.cost_entry_product_id,
                    aws.cost_entry_pricing_id,
                    aws.cost_entry_reservation_id,
                    aws.line_item_type,
                    aws.usage_account_id,
                    aws.usage_start,
                    aws.usage_end,
                    aws.product_code,
                    aws.usage_type,
                    aws.operation,
                    aws.availability_zone,
                    aws.resource_id,
                    aws.usage_amount,
                    aws.normalization_factor,
                    aws.normalized_usage_amount,
                    aws.currency_code,
                    aws.unblended_rate,
                    aws.unblended_cost,
                    aws.blended_rate,
                    aws.blended_cost,
                    aws.public_on_demand_cost,
                    aws.public_on_demand_rate,
                    aws.tax_type,
                    aws.tags,
                    tm.shared_projects
                FROM (
                    SELECT tm.usage_start,
                        tm.ocp_id,
                        tm.aws_id,
                        max(sp.shared_projects) as shared_projects
                    FROM cte_usage_tag_matched AS tm
                    LEFT JOIN cte_number_of_shared_projects AS sp
                        ON tm.aws_id = sp.aws_id
                    GROUP BY tm.usage_start, tm.ocp_id, tm.aws_id
                ) AS tm
                JOIN reporting_awscostentrylineitem_daily as aws
                    ON tm.aws_id = aws.id
                JOIN reporting_ocpusagelineitem_daily as ocp
                    ON tm.ocp_id = ocp.id
            );
            """
        ),
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS reporting_ocpaws_storagelineitem_daily;

            CREATE OR REPLACE VIEW reporting_ocpaws_storagelineitem_daily AS (
                WITH cte_storage_tag_matchted as (
                    SELECT aws.id as aws_id,
                            COALESCE(pvl.id, pvcl.id) as ocp_id,
                            aws.usage_start,
                            COALESCE(pvl.namespace, pvcl.namespace) as namespace
                        FROM (
                        SELECT aws.id,
                            aws.usage_start,
                            LOWER(key) as key,
                            LOWER(value) as value
                            FROM reporting_awscostentrylineitem_daily as aws,
                                jsonb_each_text(aws.tags) labels
                        ) AS aws
                        LEFT JOIN (
                            SELECT ocp.id,
                                ocp.usage_start,
                                ocp.cluster_alias,
                                ocp.node,
                                ocp.namespace,
                                LOWER(key) as key,
                                LOWER(value) as value
                            FROM reporting_ocpstoragelineitem_daily as ocp,
                                jsonb_each_text(ocp.persistentvolume_labels) labels
                        ) AS pvl
                            ON aws.usage_start::date = pvl.usage_start::date
                                AND (
                                    (aws.key = pvl.key AND aws.value = pvl.value)
                                    OR (aws.key = 'ocp_cluster' AND aws.value = pvl.cluster_alias)
                                    OR (aws.key = 'ocp_node' AND aws.value = pvl.node)
                                    OR (aws.key = 'ocp_project' AND aws.value = pvl.namespace)
                                )
                        LEFT JOIN (
                            SELECT ocp.id,
                                ocp.usage_start,
                                ocp.cluster_alias,
                                ocp.node,
                                ocp.namespace,
                                LOWER(key) as key,
                                LOWER(value) as value
                            FROM reporting_ocpstoragelineitem_daily as ocp,
                                jsonb_each_text(ocp.persistentvolumeclaim_labels) labels
                    ) AS pvcl
                            ON aws.usage_start::date = pvcl.usage_start::date
                                AND (
                                    (aws.key = pvcl.key AND aws.value = pvcl.value)
                                    OR (aws.key = 'ocp_cluster' AND aws.value = pvcl.cluster_alias)
                                    OR (aws.key = 'ocp_node' AND aws.value = pvcl.node)
                                    OR (aws.key = 'ocp_project' AND aws.value = pvcl.namespace)
                                )
                    WHERE (pvl.id IS NOT NULL OR pvcl.id IS NOT NULL) OR pvl.id = pvcl.id
                    GROUP BY aws.usage_start, aws.id, pvl.id, pvcl.id, pvl.namespace, pvcl.namespace
                ),
                cte_number_of_shared_projects AS (
                    SELECT usage_start,
                        aws_id,
                        count(DISTINCT namespace) as shared_projects
                    FROM cte_storage_tag_matchted
                    GROUP BY usage_start, aws_id
                )
                SELECT ocp.cluster_id,
                    ocp.cluster_alias,
                    ocp.namespace,
                    ocp.pod,
                    ocp.node,
                    ocp.persistentvolumeclaim,
                    ocp.persistentvolume,
                    ocp.storageclass,
                    ocp.persistentvolumeclaim_capacity_bytes,
                    ocp.persistentvolumeclaim_capacity_byte_seconds,
                    ocp.volume_request_storage_byte_seconds,
                    ocp.persistentvolumeclaim_usage_byte_seconds,
                    ocp.persistentvolume_labels,
                    ocp.persistentvolumeclaim_labels,
                    aws.cost_entry_product_id,
                    aws.cost_entry_pricing_id,
                    aws.cost_entry_reservation_id,
                    aws.line_item_type,
                    aws.usage_account_id,
                    aws.usage_start,
                    aws.usage_end,
                    aws.product_code,
                    aws.usage_type,
                    aws.operation,
                    aws.availability_zone,
                    aws.resource_id,
                    aws.usage_amount,
                    aws.normalization_factor,
                    aws.normalized_usage_amount,
                    aws.currency_code,
                    aws.unblended_rate,
                    aws.unblended_cost,
                    aws.blended_rate,
                    aws.blended_cost,
                    aws.public_on_demand_cost,
                    aws.public_on_demand_rate,
                    aws.tax_type,
                    aws.tags,
                    tm.shared_projects
                FROM (
                    SELECT tm.usage_start,
                        tm.ocp_id,
                        tm.aws_id,
                        max(sp.shared_projects) as shared_projects
                    FROM cte_storage_tag_matchted AS tm
                    LEFT JOIN cte_number_of_shared_projects AS sp
                        ON tm.aws_id = sp.aws_id
                    GROUP BY tm.usage_start, tm.ocp_id, tm.aws_id
                ) AS tm
                JOIN reporting_awscostentrylineitem_daily as aws
                    ON tm.aws_id = aws.id
                JOIN reporting_ocpstoragelineitem_daily as ocp
                    ON tm.ocp_id = ocp.id
            )
            ;
            """
        )


    ]
