# Generated by Django 2.1.5 on 2019-02-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0041_awscostentrylineitemdailysummary_resource_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awscostentrylineitemaggregates',
            name='account_alias',
        ),
        migrations.DeleteModel(
            name='OCPUsageLineItemAggregates',
        ),
        migrations.DeleteModel(
            name='AWSCostEntryLineItemAggregates',
        ),
    ]
