# Generated by Django 2.1.7 on 2019-03-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0044_costsummary'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS reporting_costs_summary;

            CREATE OR REPLACE VIEW reporting_costs_summary AS (
                SELECT usageli.usage_start,
                    usageli.usage_end,
                    usageli.cluster_id,
                    usageli.namespace,
                    usageli.pod,
                    COALESCE(usageli.pod_charge_cpu_core_hours, 0) AS pod_charge_cpu_core_hours,
                    COALESCE(usageli.pod_charge_memory_gigabyte_hours, 0) AS pod_charge_memory_gigabyte_hours,
                    COALESCE(storageli.persistentvolumeclaim_charge_gb_month, 0) AS persistentvolumeclaim_charge_gb_month
                FROM reporting_ocpusagelineitem_daily_summary as usageli
                LEFT JOIN reporting_ocpstoragelineitem_daily_summary as storageli
                    ON usageli.usage_start = storageli.usage_start
                        AND usageli.usage_end = storageli.usage_end
                        AND usageli.cluster_id = storageli.cluster_id
                        AND usageli.namespace = storageli.namespace
                        AND usageli.pod = storageli.pod
            )
            ;
            """
        )
    ]
