# Generated by Django 2.1.7 on 2019-03-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0046_auto_20190313_1533'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS reporting_costs_summary;
            DROP VIEW IF EXISTS reporting_ocpcosts_summary;

            CREATE OR REPLACE VIEW reporting_ocpcosts_summary AS (
                SELECT usageli.usage_start,
                    usageli.usage_end,
                    usageli.cluster_id,
                    usageli.cluster_alias,
                    usageli.namespace,
                    usageli.pod,
                    usageli.node,
                    COALESCE(usageli.pod_charge_cpu_core_hours, 0) AS pod_charge_cpu_core_hours,
                    COALESCE(usageli.pod_charge_memory_gigabyte_hours, 0) AS pod_charge_memory_gigabyte_hours,
                    COALESCE(storageli.persistentvolumeclaim_charge_gb_month, 0) AS persistentvolumeclaim_charge_gb_month,
                    COALESCE(ocp_aws.infra_cost, 0) as infra_cost,
                    COALESCE(ocp_aws.project_infra_cost, 0) as project_infra_cost
                FROM reporting_ocpusagelineitem_daily_summary as usageli
                LEFT JOIN reporting_ocpstoragelineitem_daily_summary as storageli
                    ON usageli.usage_start = storageli.usage_start
                        AND usageli.usage_end = storageli.usage_end
                        AND usageli.cluster_id = storageli.cluster_id
                        AND usageli.namespace = storageli.namespace
                        AND usageli.pod = storageli.pod
                LEFT JOIN (
                    SELECT cluster_id,
                        usage_start,
                        namespace,
                        pod,
                        node,
                        sum(ocp_aws.unblended_cost / ocp_aws.shared_projects) as infra_cost,
                        sum(ocp_aws.pod_cost) as project_infra_cost
                    FROM reporting_ocpawscostlineitem_daily_summary AS ocp_aws
                    GROUP BY cluster_id,
                            usage_start,
                            namespace,
                            pod,
                            node
                ) as ocp_aws
                    ON usageli.usage_start = ocp_aws.usage_start
                        AND usageli.cluster_id = ocp_aws.cluster_id
                        AND usageli.namespace = ocp_aws.namespace
                        AND usageli.pod = ocp_aws.pod
                        AND usageli.node = ocp_aws.node
            )
            ;
            """
        )
    ]
