# Generated by Django 2.1.7 on 2019-03-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0048_auto_20190313_1804'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='awscostentrybill',
            unique_together={('bill_type', 'payer_account_id', 'billing_period_start', 'provider_id')},
        ),
        migrations.AlterUniqueTogether(
            name='ocpusagereportperiod',
            unique_together={('cluster_id', 'report_period_start', 'provider_id')},
        ),
    ]
