# Generated by Django 2.1.7 on 2019-03-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0049_auto_20190314_2016'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='awscostentrylineitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='awscostentrylineitem',
            name='hash',
        ),
    ]
