# Generated by Django 2.1.7 on 2019-03-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0050_auto_20190315_1339'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='awscostentrylineitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='awscostentrylineitem',
            name='hash',
        ),
    ]
