# Generated by Django 2.2 on 2019-04-12 15:29

from django.db import migrations
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0052_auto_20190318_1741'),
    ]

    operations = [
        migrations.RunSQL(
        """
        DROP VIEW IF EXISTS reporting_ocpcosts_summary;
        """
        ),
        migrations.DeleteModel(
            name='CostSummary',
        ),
        migrations.CreateModel(
            name='CostSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.CharField(max_length=50, null=True)),
                ('cluster_alias', models.CharField(max_length=256, null=True)),
                ('namespace', models.CharField(max_length=253)),
                ('pod', models.CharField(max_length=253, null=True)),
                ('node', models.CharField(max_length=253, null=True)),
                ('usage_start', models.DateTimeField()),
                ('usage_end', models.DateTimeField()),
                ('pod_charge_cpu_core_hours', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('pod_charge_memory_gigabyte_hours', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('persistentvolumeclaim_charge_gb_month', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('infra_cost', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('project_infra_cost', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('pod_labels', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'db_table': 'reporting_ocpcosts_summary',
            },
        ),
    ]
