# Generated by Django 2.2 on 2019-04-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0053_auto_20190412_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OCPAWSCostLineItemDaily',
        ),
    ]
