# Generated by Django 2.2 on 2019-04-16 20:25

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0054_delete_ocpawscostlineitemdaily'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE reporting_ocpawscostlineitem_daily_summary
                SET namespace='{""}',
                    pod='{""}';
            """
        ),
        migrations.RemoveIndex(
            model_name='ocpawscostlineitemdailysummary',
            name='cost_labels_idx',
        ),
        migrations.RemoveField(
            model_name='ocpawscostlineitemdailysummary',
            name='openshift_labels',
        ),
        migrations.AlterField(
            model_name='ocpawscostlineitemdailysummary',
            name='namespace',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None),
        ),
        migrations.AlterField(
            model_name='ocpawscostlineitemdailysummary',
            name='pod',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None),
        ),
        migrations.AddIndex(
            model_name='ocpawscostlineitemdailysummary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='cost_tags_idx'),
        ),
        migrations.RemoveField(
            model_name='ocpawscostlineitemdailysummary',
            name='pod_cost',
        ),
        migrations.AddField(
            model_name='ocpawscostlineitemdailysummary',
            name='project_costs',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
