# Generated by Django 2.2 on 2019-04-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0056_auto_20190418_1850'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='awscostentrylineitemdailysummary',
            index=models.Index(fields=['product_family'], name='summary_product_family_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpawscostlineitemdailysummary',
            index=models.Index(fields=['product_family'], name='ocp_aws_product_family_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpawscostlineitemprojectdailysummary',
            index=models.Index(fields=['product_family'], name='ocp_aws_proj_prod_fam_idx'),
        ),
    ]
