# Generated by Django 2.2 on 2019-04-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0057_auto_20190422_1910'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='awscostentrylineitemdailysummary',
            index=models.Index(fields=['instance_type'], name='summary_instance_type_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpawscostlineitemdailysummary',
            index=models.Index(fields=['instance_type'], name='ocp_aws_instance_type_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpawscostlineitemprojectdailysummary',
            index=models.Index(fields=['instance_type'], name='ocp_aws_proj_inst_type_idx'),
        ),
    ]
