# Generated by Django 2.2 on 2019-04-22 19:24

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0058_auto_20190422_1915'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ocpstoragelineitemdailysummary',
            index=models.Index(fields=['usage_start'], name='storage_summary_ocp_usage_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpstoragelineitemdailysummary',
            index=models.Index(fields=['namespace'], name='storage_summary_namespace_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpstoragelineitemdailysummary',
            index=models.Index(fields=['node'], name='storage_summary_node_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpstoragelineitemdailysummary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['volume_labels'], name='storage_volume_labels_idx'),
        ),
        migrations.RemoveIndex(
            model_name='ocpusagelineitemdailysummary',
            name='summary_pod_idx',
        ),
    ]
