# Generated by Django 2.2.1 on 2019-06-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0061_auto_20190501_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscostentrybill',
            name='derived_cost_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ocpusagereportperiod',
            name='derived_cost_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
