# Generated by Django 2.2.4 on 2019-08-30 11:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0063_auto_20190826_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureCostEntryProductService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=512)),
                ('resource_location', models.CharField(max_length=50)),
                ('consumed_service', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_group', models.CharField(max_length=50)),
                ('additional_info', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('service_tier', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=50)),
                ('service_info1', models.TextField(null=True)),
                ('service_info2', models.TextField(null=True)),
            ],
            options={
                'unique_together': {('instance_id', 'service_name', 'service_tier')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='azureservice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='azurecostentrylineitemdaily',
            name='service',
        ),
        migrations.AlterField(
            model_name='azurecostentrylineitemdaily',
            name='cost_entry_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reporting.AzureCostEntryProductService'),
        ),
        migrations.DeleteModel(
            name='AzureCostEntryProduct',
        ),
        migrations.DeleteModel(
            name='AzureService',
        ),
    ]
