# Generated by Django 2.2.4 on 2019-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0065_auto_20190830_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='costsummary',
            name='markup_cost',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='costsummary',
            name='project_markup_cost',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
    ]
