# Generated by Django 2.2.4 on 2019-09-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0065_auto_20190830_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='azurecostentrylineitemdailysummary',
            old_name='usage_date_time',
            new_name='usage_start',
        ),
        migrations.AddField(
            model_name='azurecostentrylineitemdailysummary',
            name='usage_end',
            field=models.DateTimeField(null=True),
        ),
    ]
