# Generated by Django 2.2.4 on 2019-09-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0066_auto_20190909_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscostentrylineitemdailysummary',
            name='markup_cost',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
    ]
