# Generated by Django 2.2.4 on 2019-09-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0067_auto_20190913_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpawscostlineitemdailysummary',
            name='markup_cost',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='ocpawscostlineitemprojectdailysummary',
            name='project_markup_cost',
            field=models.DecimalField(decimal_places=9, max_digits=17, null=True),
        ),
    ]
