# Generated by Django 2.2.4 on 2019-09-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0068_auto_20190917_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurecostentrylineitemdaily',
            name='unit_of_measure',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='azurecostentrylineitemdailysummary',
            name='unit_of_measure',
            field=models.CharField(max_length=63, null=True),
        ),
    ]
