# Generated by Django 2.2.4 on 2019-10-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0069_auto_20190925_1327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='azurecostentrylineitemdaily',
            unique_together={('cost_entry_bill', 'cost_entry_product', 'meter', 'subscription_guid', 'tags', 'usage_date_time', 'offer_id')},
        ),
    ]
