# Generated by Django 2.2.4 on 2019-09-26 18:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0069_auto_20190925_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OCPStorageLineItemDailySummary',
        ),
        migrations.AddField(
            model_name='ocpawscostlineitemprojectdailysummary',
            name='data_source',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='data_source',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='infra_cost',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='markup_cost',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='persistentvolume',
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='persistentvolumeclaim',
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='persistentvolumeclaim_capacity_gigabyte',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='persistentvolumeclaim_capacity_gigabyte_months',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='persistentvolumeclaim_charge_gb_month',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='persistentvolumeclaim_usage_gigabyte_months',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='project_infra_cost',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='project_markup_cost',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='storageclass',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='volume_labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='volume_request_storage_gigabyte_months',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddIndex(
            model_name='ocpusagelineitemdailysummary',
            index=models.Index(fields=['data_source'], name='summary_data_source_idx'),
        ),
    ]
