# Generated by Django 2.2.4 on 2019-10-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0072_auto_20191011_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awscostentryproduct',
            name='memory',
            field=models.TextField(null=True),
        ),
    ]
