# Generated by Django 2.2.4 on 2019-10-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0072_auto_20191011_1735'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='azurecostentrylineitemdaily',
            unique_together=set(),
        ),
    ]
