# Generated by Django 2.2.4 on 2019-10-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20191022_1620'),
        ('reporting', '0074_auto_20191022_1602'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='awscostentrybill',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='azurecostentrybill',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ocpusagereportperiod',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='awscostentrybill',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='azurecostentrybill',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='ocpusagereportperiod',
            name='provider_id',
        ),
        migrations.AddField(
            model_name='awscostentrybill',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Provider'),
        ),
        migrations.AddField(
            model_name='azurecostentrybill',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Provider'),
        ),
        migrations.AddField(
            model_name='ocpusagereportperiod',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Provider'),
        ),
        migrations.RunSQL(
            """
                UPDATE reporting_awscostentrybill
                    SET provider_id = provider_uuid
            """
        ),
        migrations.RunSQL(
            """
                UPDATE reporting_azurecostentrybill
                    SET provider_id = provider_uuid
            """
        ),
        migrations.RunSQL(
            """
                UPDATE reporting_ocpusagereportperiod
                    SET provider_id = provider_uuid
            """
        ),
    ]
