# Generated by Django 2.2.4 on 2019-10-26 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0076_auto_20191022_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awscostentry',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.AWSCostEntryBill'),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='cost_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.AWSCostEntry'),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='cost_entry_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.AWSCostEntryBill'),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='cost_entry_pricing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.AWSCostEntryPricing'),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='cost_entry_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.AWSCostEntryProduct'),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='cost_entry_reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.AWSCostEntryReservation'),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdaily',
            name='cost_entry_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.AWSCostEntryBill'),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdaily',
            name='cost_entry_pricing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.AWSCostEntryPricing'),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdaily',
            name='cost_entry_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.AWSCostEntryProduct'),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdaily',
            name='cost_entry_reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.AWSCostEntryReservation'),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdailysummary',
            name='cost_entry_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.AWSCostEntryBill'),
        ),
        migrations.AlterField(
            model_name='azurecostentrylineitemdaily',
            name='cost_entry_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.AzureCostEntryBill'),
        ),
        migrations.AlterField(
            model_name='azurecostentrylineitemdaily',
            name='cost_entry_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.AzureCostEntryProductService'),
        ),
        migrations.AlterField(
            model_name='azurecostentrylineitemdaily',
            name='meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.AzureMeter'),
        ),
        migrations.AlterField(
            model_name='azurecostentrylineitemdailysummary',
            name='cost_entry_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.AzureCostEntryBill'),
        ),
        migrations.AlterField(
            model_name='azurecostentrylineitemdailysummary',
            name='meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.AzureMeter'),
        ),
        migrations.AlterField(
            model_name='ocpstoragelineitem',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.OCPUsageReport'),
        ),
        migrations.AlterField(
            model_name='ocpstoragelineitem',
            name='report_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.OCPUsageReportPeriod'),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitem',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.OCPUsageReport'),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitem',
            name='report_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.OCPUsageReportPeriod'),
        ),
        migrations.AlterField(
            model_name='ocpusagereport',
            name='report_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.OCPUsageReportPeriod'),
        ),
        migrations.AlterField(
            model_name='ocpawscostlineitemdailysummary',
            name='account_alias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.AWSAccountAlias'),
        ),
        migrations.AlterField(
            model_name='ocpawscostlineitemdailysummary',
            name='cost_entry_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.AWSCostEntryBill'),
        ),
        migrations.AlterField(
            model_name='ocpawscostlineitemprojectdailysummary',
            name='account_alias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.AWSAccountAlias'),
        ),
        migrations.AlterField(
            model_name='ocpawscostlineitemprojectdailysummary',
            name='cost_entry_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.AWSCostEntryBill'),
        ),
    ]
