# Generated by Django 2.2.4 on 2019-11-01 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0080_azurecostentryproductservice_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='costsummary',
            name='report_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.OCPUsageReportPeriod'),
        ),
        migrations.AddField(
            model_name='ocpawscostlineitemdailysummary',
            name='report_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.OCPUsageReportPeriod'),
        ),
        migrations.AddField(
            model_name='ocpawscostlineitemprojectdailysummary',
            name='report_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.OCPUsageReportPeriod'),
        ),
        migrations.AddField(
            model_name='ocpstoragelineitemdaily',
            name='report_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.OCPUsageReportPeriod'),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdaily',
            name='report_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.OCPUsageReportPeriod'),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='report_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.OCPUsageReportPeriod'),
        ),
    ]
