# Generated by Django 2.2.4 on 2019-11-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0081_auto_20191101_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='blended_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='blended_rate',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='normalized_usage_amount',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='public_on_demand_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='public_on_demand_rate',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='reservation_amortized_upfront_cost_for_usage',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='reservation_amortized_upfront_fee',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='reservation_recurring_fee_for_usage',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='reservation_unused_quantity',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='reservation_unused_recurring_fee',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='unblended_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='unblended_rate',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='usage_amount',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdaily',
            name='blended_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdaily',
            name='blended_rate',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdaily',
            name='public_on_demand_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdaily',
            name='public_on_demand_rate',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdaily',
            name='unblended_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdaily',
            name='unblended_rate',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdailysummary',
            name='blended_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdailysummary',
            name='blended_rate',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdailysummary',
            name='markup_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdailysummary',
            name='public_on_demand_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdailysummary',
            name='public_on_demand_rate',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdailysummary',
            name='unblended_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdailysummary',
            name='unblended_rate',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='awscostentryreservation',
            name='units_per_reservation',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='azurecostentrylineitemdaily',
            name='pretax_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='azurecostentrylineitemdailysummary',
            name='markup_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='azurecostentrylineitemdailysummary',
            name='pretax_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='azuremeter',
            name='resource_rate',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='costsummary',
            name='infra_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='costsummary',
            name='markup_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='costsummary',
            name='persistentvolumeclaim_charge_gb_month',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='costsummary',
            name='pod_charge_cpu_core_hours',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='costsummary',
            name='pod_charge_memory_gigabyte_hours',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='costsummary',
            name='project_infra_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='costsummary',
            name='project_markup_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='gcpcostentrylineitemdaily',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpawscostlineitemdailysummary',
            name='markup_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpawscostlineitemdailysummary',
            name='unblended_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpawscostlineitemprojectdailysummary',
            name='pod_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpawscostlineitemprojectdailysummary',
            name='project_markup_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpawscostlineitemprojectdailysummary',
            name='unblended_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ocpstoragelineitem',
            name='persistentvolumeclaim_capacity_byte_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpstoragelineitem',
            name='persistentvolumeclaim_capacity_bytes',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpstoragelineitem',
            name='persistentvolumeclaim_usage_byte_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpstoragelineitem',
            name='volume_request_storage_byte_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpstoragelineitemdaily',
            name='persistentvolumeclaim_capacity_byte_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpstoragelineitemdaily',
            name='persistentvolumeclaim_capacity_bytes',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpstoragelineitemdaily',
            name='persistentvolumeclaim_usage_byte_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpstoragelineitemdaily',
            name='volume_request_storage_byte_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitem',
            name='node_capacity_cpu_core_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitem',
            name='node_capacity_cpu_cores',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitem',
            name='node_capacity_memory_byte_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitem',
            name='node_capacity_memory_bytes',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitem',
            name='pod_limit_cpu_core_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitem',
            name='pod_limit_memory_byte_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitem',
            name='pod_request_cpu_core_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitem',
            name='pod_request_memory_byte_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitem',
            name='pod_usage_cpu_core_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitem',
            name='pod_usage_memory_byte_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='cluster_capacity_cpu_core_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='cluster_capacity_memory_byte_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='node_capacity_cpu_core_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='node_capacity_cpu_cores',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='node_capacity_memory_byte_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='node_capacity_memory_bytes',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='pod_limit_cpu_core_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='pod_limit_memory_byte_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='pod_request_cpu_core_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='pod_request_memory_byte_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='pod_usage_cpu_core_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='pod_usage_memory_byte_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='total_capacity_cpu_core_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdaily',
            name='total_capacity_memory_byte_seconds',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='cluster_capacity_cpu_core_hours',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='cluster_capacity_memory_gigabyte_hours',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='infra_cost',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='markup_cost',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='node_capacity_cpu_core_hours',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='node_capacity_cpu_cores',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='node_capacity_memory_gigabyte_hours',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='node_capacity_memory_gigabytes',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='persistentvolumeclaim_capacity_gigabyte',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='persistentvolumeclaim_capacity_gigabyte_months',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='persistentvolumeclaim_charge_gb_month',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='persistentvolumeclaim_usage_gigabyte_months',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_charge_cpu_core_hours',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_charge_memory_gigabyte_hours',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_limit_cpu_core_hours',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_limit_memory_gigabyte_hours',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_request_cpu_core_hours',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_request_memory_gigabyte_hours',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_usage_cpu_core_hours',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='pod_usage_memory_gigabyte_hours',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='project_infra_cost',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='project_markup_cost',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='total_capacity_cpu_core_hours',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='total_capacity_memory_gigabyte_hours',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='volume_request_storage_gigabyte_months',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
    ]
