# Generated by Django 2.2.4 on 2019-11-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0081_auto_20191101_1705'),
        ('reporting', '0081_auto_20191101_2338'),
    ]

    operations = [
    ]
