# Generated by Django 2.2.4 on 2019-11-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0083_auto_20191111_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costsummary',
            name='infra_cost',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name='costsummary',
            name='markup_cost',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='costsummary',
            name='persistentvolumeclaim_charge_gb_month',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='costsummary',
            name='pod_charge_cpu_core_hours',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='costsummary',
            name='pod_charge_memory_gigabyte_hours',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='costsummary',
            name='project_infra_cost',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name='costsummary',
            name='project_markup_cost',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
    ]
