# Generated by Django 2.2.4 on 2019-11-11 21:01

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0084_auto_20191111_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCPAzureCostLineItemProjectDailySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.CharField(max_length=50, null=True)),
                ('cluster_alias', models.CharField(max_length=256, null=True)),
                ('data_source', models.CharField(max_length=64, null=True)),
                ('namespace', models.CharField(max_length=253)),
                ('pod', models.CharField(max_length=253, null=True)),
                ('node', models.CharField(max_length=253)),
                ('pod_labels', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('resource_id', models.CharField(max_length=253, null=True)),
                ('usage_start', models.DateTimeField()),
                ('usage_end', models.DateTimeField()),
                ('subscription_guid', models.CharField(max_length=50)),
                ('instance_type', models.CharField(max_length=50, null=True)),
                ('service_name', models.CharField(max_length=50)),
                ('resource_location', models.CharField(max_length=50)),
                ('usage_quantity', models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ('unit_of_measure', models.CharField(max_length=63, null=True)),
                ('offer_id', models.PositiveIntegerField(null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('pretax_cost', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('project_markup_cost', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('pod_cost', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('cost_entry_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.AzureCostEntryBill')),
            ],
            options={
                'db_table': 'reporting_ocpazurecostlineitem_project_daily_summary',
            },
        ),
        migrations.CreateModel(
            name='OCPAzureCostLineItemDailySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.CharField(max_length=50, null=True)),
                ('cluster_alias', models.CharField(max_length=256, null=True)),
                ('namespace', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None)),
                ('pod', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None)),
                ('node', models.CharField(max_length=253)),
                ('resource_id', models.CharField(max_length=253, null=True)),
                ('usage_start', models.DateTimeField()),
                ('usage_end', models.DateTimeField()),
                ('subscription_guid', models.CharField(max_length=50)),
                ('instance_type', models.CharField(max_length=50, null=True)),
                ('service_name', models.CharField(max_length=50)),
                ('resource_location', models.CharField(max_length=50)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('usage_quantity', models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ('pretax_cost', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('markup_cost', models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ('offer_id', models.PositiveIntegerField(null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('unit_of_measure', models.CharField(max_length=63, null=True)),
                ('shared_projects', models.IntegerField(default=1)),
                ('project_costs', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('cost_entry_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.AzureCostEntryBill')),
            ],
            options={
                'db_table': 'reporting_ocpazurecostlineitem_daily_summary',
            },
        ),
        migrations.AddIndex(
            model_name='ocpazurecostlineitemprojectdailysummary',
            index=models.Index(fields=['usage_start'], name='ocpazure_proj_usage_start_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpazurecostlineitemprojectdailysummary',
            index=models.Index(fields=['namespace'], name='ocpazure_proj_namespace_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpazurecostlineitemprojectdailysummary',
            index=models.Index(fields=['node'], name='ocpazure_proj_node_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpazurecostlineitemprojectdailysummary',
            index=models.Index(fields=['resource_id'], name='ocpazure_proj_resource_id_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpazurecostlineitemprojectdailysummary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['pod_labels'], name='ocpazure_proj_pod_labels_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpazurecostlineitemprojectdailysummary',
            index=models.Index(fields=['service_name'], name='ocpazure_proj_service_name_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpazurecostlineitemprojectdailysummary',
            index=models.Index(fields=['instance_type'], name='ocpazure_proj_inst_type_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpazurecostlineitemdailysummary',
            index=models.Index(fields=['usage_start'], name='ocpazure_usage_start_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpazurecostlineitemdailysummary',
            index=models.Index(fields=['namespace'], name='ocpazure_namespace_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpazurecostlineitemdailysummary',
            index=models.Index(fields=['node'], name='ocpazure_node_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpazurecostlineitemdailysummary',
            index=models.Index(fields=['resource_id'], name='ocpazure_resource_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpazurecostlineitemdailysummary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='ocpazure_tags_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpazurecostlineitemdailysummary',
            index=models.Index(fields=['service_name'], name='ocpazure_service_name_idx'),
        ),
        migrations.AddIndex(
            model_name='ocpazurecostlineitemdailysummary',
            index=models.Index(fields=['instance_type'], name='ocpazure_instance_type_idx'),
        ),
    ]
