# Generated by Django 2.2.4 on 2019-11-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0085_auto_20191111_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='costsummary',
            name='monthly_cost',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='ocpusagelineitemdailysummary',
            name='monthly_cost',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name='costsummary',
            name='namespace',
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='namespace',
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='node',
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='pod',
            field=models.CharField(max_length=253, null=True),
        ),
    ]
