# Generated by Django 2.2.8 on 2019-12-17 20:24

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0089_awscomputesummary_awscomputesummarybyaccount_awscomputesummarybyregion_awscomputesummarybyservice_aw'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCPAllCostLineItemDailySummary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_type', models.TextField()),
                ('cluster_id', models.CharField(max_length=50, null=True)),
                ('cluster_alias', models.CharField(max_length=256, null=True)),
                ('namespace', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None)),
                ('node', models.CharField(max_length=253)),
                ('resource_id', models.CharField(max_length=253, null=True)),
                ('usage_start', models.DateTimeField()),
                ('usage_end', models.DateTimeField()),
                ('usage_account_id', models.CharField(max_length=50)),
                ('product_code', models.CharField(max_length=50)),
                ('product_family', models.CharField(max_length=150, null=True)),
                ('instance_type', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=50, null=True)),
                ('availability_zone', models.CharField(max_length=50, null=True)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('usage_amount', models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ('unit', models.CharField(max_length=63, null=True)),
                ('unblended_cost', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ('markup_cost', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ('currency_code', models.CharField(max_length=10, null=True)),
                ('shared_projects', models.IntegerField(default=1)),
                ('project_costs', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'db_table': 'reporting_ocpallcostlineitem_daily_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OCPAllCostLineItemProjectDailySummary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_type', models.TextField()),
                ('cluster_id', models.CharField(max_length=50, null=True)),
                ('cluster_alias', models.CharField(max_length=256, null=True)),
                ('data_source', models.CharField(max_length=64, null=True)),
                ('namespace', models.CharField(max_length=253)),
                ('node', models.CharField(max_length=253)),
                ('pod_labels', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('resource_id', models.CharField(max_length=253, null=True)),
                ('usage_start', models.DateTimeField()),
                ('usage_end', models.DateTimeField()),
                ('usage_account_id', models.CharField(max_length=50)),
                ('product_code', models.CharField(max_length=50)),
                ('product_family', models.CharField(max_length=150, null=True)),
                ('instance_type', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=50, null=True)),
                ('availability_zone', models.CharField(max_length=50, null=True)),
                ('usage_amount', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ('unit', models.CharField(max_length=63, null=True)),
                ('unblended_cost', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ('project_markup_cost', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ('pod_cost', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ('currency_code', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'reporting_ocpallcostlineitem_project_daily_summary',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW reporting_ocpallcostlineitem_daily_summary AS (
                SELECT row_number() OVER (),
                    lids.*
                FROM (
                    SELECT 'AWS' as source_type,
                        cluster_id,
                        cluster_alias,
                        namespace,
                        node,
                        resource_id,
                        usage_start,
                        usage_end,
                        usage_account_id,
                        account_alias_id,
                        product_code,
                        product_family,
                        instance_type,
                        region,
                        availability_zone,
                        tags,
                        usage_amount,
                        unit,
                        unblended_cost,
                        markup_cost,
                        currency_code,
                        shared_projects,
                        project_costs
                    FROM reporting_ocpawscostlineitem_daily_summary
                    WHERE usage_start >= date_trunc('month', date_trunc('month', now()) - INTERVAL '1' DAY)

                    UNION

                    SELECT 'Azure' as source_type,
                        cluster_id,
                        cluster_alias,
                        namespace,
                        node,
                        resource_id,
                        usage_start,
                        usage_end,
                        subscription_guid as usage_account_id,
                        NULL::int as account_alias_id,
                        service_name as product_code,
                        NULL as product_family,
                        instance_type,
                        resource_location as region,
                        NULL as availability_zone,
                        tags,
                        usage_quantity as usage_amount,
                        unit_of_measure as unit,
                        pretax_cost as unblended_cost,
                        markup_cost,
                        currency as currency_code,
                        shared_projects,
                        project_costs
                    FROM reporting_ocpazurecostlineitem_daily_summary
                    WHERE usage_start >= date_trunc('month', date_trunc('month', now()) - INTERVAL '1' DAY)
                ) AS lids
            )
            ;

            CREATE MATERIALIZED VIEW reporting_ocpallcostlineitem_project_daily_summary AS (
                SELECT row_number() OVER (),
                    lids.*
                FROM (
                    SELECT 'AWS' as source_type,
                        cluster_id,
                        cluster_alias,
                        data_source,
                        namespace,
                        node,
                        pod_labels,
                        resource_id,
                        usage_start,
                        usage_end,
                        usage_account_id,
                        account_alias_id,
                        product_code,
                        product_family,
                        instance_type,
                        region,
                        availability_zone,
                        usage_amount,
                        unit,
                        unblended_cost,
                        project_markup_cost,
                        pod_cost,
                        currency_code
                    FROM reporting_ocpawscostlineitem_project_daily_summary
                    WHERE usage_start >= date_trunc('month', date_trunc('month', now()) - INTERVAL '1' DAY)

                    UNION

                    SELECT 'Azure' as source_type,
                        cluster_id,
                        cluster_alias,
                        data_source,
                        namespace,
                        node,
                        pod_labels,
                        resource_id,
                        usage_start,
                        usage_end,
                        subscription_guid as usage_account_id,
                        NULL::int as account_alias_id,
                        service_name as product_code,
                        NULL as product_family,
                        instance_type,
                        resource_location as region,
                        NULL as availability_zone,
                        usage_quantity as usage_amount,
                        unit_of_measure as unit,
                        pretax_cost as unblended_cost,
                        project_markup_cost,
                        pod_cost,
                        currency as currency_code
                    FROM reporting_ocpazurecostlineitem_project_daily_summary
                    WHERE usage_start >= date_trunc('month', date_trunc('month', now()) - INTERVAL '1' DAY)
                ) AS lids
            )
            ;
            """
        )
    ]
