# Generated by Django 2.2.10 on 2020-02-11 14:49
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0093_auto_20200210_1920")]

    operations = [
        migrations.AlterField(model_name="ocpusagelineitemdaily", name="total_seconds", field=models.IntegerField()),
        migrations.CreateModel(
            name="OCPUsagePodLabelSummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=253)),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None),
                ),
                (
                    "report_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reporting.OCPUsageReportPeriod"
                    ),
                ),
            ],
            options={"db_table": "reporting_ocpusagepodlabel_summary", "unique_together": {("key", "report_period")}},
        ),
        migrations.CreateModel(
            name="OCPStorageVolumeLabelSummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=253)),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None),
                ),
                (
                    "report_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reporting.OCPUsageReportPeriod"
                    ),
                ),
            ],
            options={
                "db_table": "reporting_ocpstoragevolumelabel_summary",
                "unique_together": {("key", "report_period")},
            },
        ),
        migrations.CreateModel(
            name="OCPStorageVolumeClaimLabelSummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=253)),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None),
                ),
                (
                    "report_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reporting.OCPUsageReportPeriod"
                    ),
                ),
            ],
            options={
                "db_table": "reporting_ocpstoragevolumeclaimlabel_summary",
                "unique_together": {("key", "report_period")},
            },
        ),
        migrations.CreateModel(
            name="AzureTagsSummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=253)),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None),
                ),
                (
                    "cost_entry_bill",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.AzureCostEntryBill"),
                ),
            ],
            options={"db_table": "reporting_azuretags_summary", "unique_together": {("key", "cost_entry_bill")}},
        ),
        migrations.CreateModel(
            name="AWSTagsSummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=253)),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None),
                ),
                (
                    "cost_entry_bill",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.AWSCostEntryBill"),
                ),
            ],
            options={"db_table": "reporting_awstags_summary", "unique_together": {("key", "cost_entry_bill")}},
        ),
    ]
