# Generated by Django 2.2.10 on 2020-02-12 16:06
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0094_auto_20200211_1449")]

    operations = [
        migrations.RunSQL(
            """
            DELETE FROM reporting_awscostentrylineitem
            WHERE cost_entry_bill_id IS NULL;

            DELETE FROM reporting_awscostentrylineitem_daily
            WHERE cost_entry_bill_id IS NULL;

            DELETE FROM reporting_awscostentrylineitem_daily_summary
            WHERE cost_entry_bill_id IS NULL;

            DELETE FROM reporting_azurecostentrylineitem_daily
            WHERE cost_entry_bill_id IS NULL;

            DELETE FROM reporting_azurecostentrylineitem_daily_summary
            WHERE cost_entry_bill_id IS NULL;

            DELETE FROM reporting_ocpawscostlineitem_daily_summary
            WHERE cost_entry_bill_id IS NULL;

            DELETE FROM reporting_ocpawscostlineitem_project_daily_summary
            WHERE cost_entry_bill_id IS NULL;

            DELETE FROM reporting_ocpazurecostlineitem_daily_summary
            WHERE cost_entry_bill_id IS NULL;

            DELETE FROM reporting_ocpazurecostlineitem_project_daily_summary
            WHERE cost_entry_bill_id IS NULL;

            DELETE FROM reporting_ocpusagelineitem
            WHERE report_period_id IS NULL;

            DELETE FROM reporting_ocpusagelineitem_daily
            WHERE report_period_id IS NULL;

            DELETE FROM reporting_ocpusagelineitem_daily_summary
            WHERE report_period_id IS NULL;

            DELETE FROM reporting_ocpstoragelineitem
            WHERE report_period_id IS NULL;

            DELETE FROM reporting_ocpstoragelineitem_daily
            WHERE report_period_id IS NULL;

            DELETE FROM reporting_ocpawscostlineitem_daily_summary
            WHERE report_period_id IS NULL;

            DELETE FROM reporting_ocpawscostlineitem_project_daily_summary
            WHERE report_period_id IS NULL;

            DELETE FROM reporting_ocpazurecostlineitem_daily_summary
            WHERE report_period_id IS NULL;

            DELETE FROM reporting_ocpazurecostlineitem_project_daily_summary
            WHERE report_period_id IS NULL;

            DELETE FROM reporting_ocpcosts_summary
            WHERE report_period_id IS NULL;

            DELETE FROM reporting_ocpusagereport
            WHERE report_period_id IS NULL;
            """
        )
    ]
