# Generated by Django 2.2.10 on 2020-02-18 12:51
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0095_auto_20200212_1606")]

    operations = [
        migrations.RunSQL(
            """
create extension if not exists pg_trgm schema public;
            """
        ),
        # Create indexes to aid with text searching.
        # These cases will specifically help with case-insensitive
        # and contains (vs startswith) searches
        migrations.RunSQL(
            """
-- create index ___ on ___ (lower(___) X_pattern_ops);
-- create index ___ on ___ using gin (lower(___) gin_trgm_ops);
            """
        ),
    ]
