# Generated by Django 2.2.10 on 2020-02-18 12:51
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0095_auto_20200212_1606")]

    operations = []
