# Generated by Django 2.2.10 on 2020-02-18 22:27
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0095_auto_20200212_1606")]

    operations = [
        migrations.AddField(
            model_name="awstagssummary",
            name="accounts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=63), default="{}", size=None
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="azuretagssummary",
            name="subscription_guid",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), default="{}", size=None
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ocpstoragevolumeclaimlabelsummary",
            name="namespace",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=253), default="{}", size=None
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ocpstoragevolumelabelsummary",
            name="namespace",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=253), default="{}", size=None
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ocpusagepodlabelsummary",
            name="namespace",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=253), default="{}", size=None
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="OCPAzureTagsSummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=253)),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None),
                ),
                (
                    "subscription_guid",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
                ),
                (
                    "namespace",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None),
                ),
                (
                    "cost_entry_bill",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.AzureCostEntryBill"),
                ),
            ],
            options={"db_table": "reporting_ocpazuretags_summary", "unique_together": {("key", "cost_entry_bill")}},
        ),
        migrations.CreateModel(
            name="OCPAWSTagsSummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=253)),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None),
                ),
                (
                    "accounts",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=63), size=None),
                ),
                (
                    "namespace",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None),
                ),
                (
                    "cost_entry_bill",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.AWSCostEntryBill"),
                ),
            ],
            options={"db_table": "reporting_ocpawstags_summary", "unique_together": {("key", "cost_entry_bill")}},
        ),
    ]
