# Generated by Django 2.2.10 on 2020-02-21 13:31
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0096_auto_20200218_2227")]

    operations = [
        migrations.CreateModel(
            name="OCPNodeLabelLineItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("node", models.CharField(max_length=253, null=True)),
                ("node_labels", django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                (
                    "report",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.OCPUsageReport"),
                ),
                (
                    "report_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reporting.OCPUsageReportPeriod"
                    ),
                ),
            ],
            options={"db_table": "reporting_ocpnodelabellineitem", "unique_together": {("report", "node")}},
        )
    ]
