# Generated by Django 2.2.10 on 2020-03-10 19:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0100_aws_azure_query_perforance")]

    operations = [
        migrations.CreateModel(
            name="OCPEnabledTagKeys",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=253, unique=True)),
            ],
            options={"db_table": "reporting_ocpenabledtagkeys"},
        )
    ]
