# Generated by Django 2.2.11 on 2020-03-24 18:44
import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0101_ocpenabledtagkeys")]

    operations = [
        migrations.CreateModel(
            name="OCPComputeSummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                (
                    "resource_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), null=True, size=None
                    ),
                ),
                ("resource_count", models.IntegerField(null=True)),
                ("data_source", models.CharField(max_length=64, null=True)),
                ("namespace", models.CharField(max_length=253, null=True)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("pod_usage_cpu_core_hours", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                ("pod_request_cpu_core_hours", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                ("pod_limit_cpu_core_hours", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                ("pod_charge_cpu_core_hours", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                ("pod_usage_memory_gigabyte_hours", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                ("pod_request_memory_gigabyte_hours", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                ("pod_charge_memory_gigabyte_hours", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                ("pod_limit_memory_gigabyte_hours", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                ("node_capacity_cpu_cores", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                ("node_capacity_cpu_core_hours", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                ("node_capacity_memory_gigabytes", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                (
                    "node_capacity_memory_gigabyte_hours",
                    models.DecimalField(decimal_places=9, max_digits=27, null=True),
                ),
                ("cluster_capacity_cpu_core_hours", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                (
                    "cluster_capacity_memory_gigabyte_hours",
                    models.DecimalField(decimal_places=9, max_digits=27, null=True),
                ),
                ("total_capacity_cpu_core_hours", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                (
                    "total_capacity_memory_gigabyte_hours",
                    models.DecimalField(decimal_places=9, max_digits=27, null=True),
                ),
                ("infra_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("project_infra_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                ("project_markup_cost", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                ("monthly_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
            ],
            options={"db_table": "reporting_ocp_compute_summary", "managed": False},
        ),
        migrations.CreateModel(
            name="OCPVolumeSummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                (
                    "resource_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), null=True, size=None
                    ),
                ),
                ("resource_count", models.IntegerField(null=True)),
                ("data_source", models.CharField(max_length=64, null=True)),
                ("namespace", models.CharField(max_length=253, null=True)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                (
                    "persistentvolumeclaim_charge_gb_month",
                    models.DecimalField(decimal_places=9, max_digits=27, null=True),
                ),
                (
                    "persistentvolumeclaim_usage_gigabyte_months",
                    models.DecimalField(decimal_places=9, max_digits=27, null=True),
                ),
                (
                    "volume_request_storage_gigabyte_months",
                    models.DecimalField(decimal_places=9, max_digits=27, null=True),
                ),
                (
                    "persistentvolumeclaim_capacity_gigabyte_months",
                    models.DecimalField(decimal_places=9, max_digits=27, null=True),
                ),
                ("infra_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("project_infra_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                ("project_markup_cost", models.DecimalField(decimal_places=9, max_digits=27, null=True)),
                ("monthly_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
            ],
            options={"db_table": "reporting_ocp_volume_summary", "managed": False},
        ),
        migrations.RunSQL(
            sql="""
            CREATE MATERIALIZED VIEW reporting_ocp_compute_summary AS(
                SELECT row_number() OVER(ORDER BY date(usage_start)) as id,
                    date(usage_start) as usage_start,
                    date(usage_start) as usage_end,
                    cluster_id,
                    cluster_alias,
                    max(data_source) as data_source,
                    namespace,
                    array_agg(DISTINCT resource_id) as resource_ids,
                    count(DISTINCT resource_id) as resource_count,
                    sum(pod_usage_cpu_core_hours) as pod_usage_cpu_core_hours,
                    sum(pod_request_cpu_core_hours) as pod_request_cpu_core_hours,
                    sum(pod_limit_cpu_core_hours) as pod_limit_cpu_core_hours,
                    sum(pod_charge_cpu_core_hours) as pod_charge_cpu_core_hours,
                    sum(pod_usage_memory_gigabyte_hours) as pod_usage_memory_gigabyte_hours,
                    sum(pod_request_memory_gigabyte_hours) as pod_request_memory_gigabyte_hours,
                    sum(pod_charge_memory_gigabyte_hours) as pod_charge_memory_gigabyte_hours,
                    sum(pod_limit_memory_gigabyte_hours) as pod_limit_memory_gigabyte_hours,
                    sum(node_capacity_cpu_cores) as node_capacity_cpu_cores,
                    sum(node_capacity_cpu_core_hours) as node_capacity_cpu_core_hours,
                    sum(node_capacity_memory_gigabytes) as node_capacity_memory_gigabytes,
                    sum(node_capacity_memory_gigabyte_hours) as node_capacity_memory_gigabyte_hours,
                    sum(cluster_capacity_cpu_core_hours) as cluster_capacity_cpu_core_hours,
                    sum(cluster_capacity_memory_gigabyte_hours) as cluster_capacity_memory_gigabyte_hours,
                    sum(total_capacity_cpu_core_hours) as total_capacity_cpu_core_hours,
                    sum(total_capacity_memory_gigabyte_hours) as total_capacity_memory_gigabyte_hours,
                    sum(infra_cost) as infra_cost,
                    sum(project_infra_cost) as project_infra_cost,
                    sum(markup_cost) as markup_cost,
                    sum(project_markup_cost) as project_markup_cost,
                    sum(monthly_cost) as monthly_cost
                FROM reporting_ocpusagelineitem_daily_summary
                -- Get data for this month or last month
                WHERE date_trunc('month', usage_start) = date_trunc('month', now()) AND data_source = 'Pod'
                    OR date_trunc('month', usage_start) = date_trunc('month', date_trunc('month', now()) - INTERVAL '1' DAY) AND data_source = 'Pod'
                GROUP BY date(usage_start), cluster_id, cluster_alias, namespace
            )
            ;

            CREATE UNIQUE INDEX ocp_compute_summary
            ON reporting_ocp_compute_summary (usage_start)
            ;

            CREATE MATERIALIZED VIEW reporting_ocp_volume_summary AS(
                SELECT row_number() OVER(ORDER BY date(usage_start)) as id,
                    date(usage_start) as usage_start,
                    date(usage_start) as usage_end,
                    cluster_id,
                    cluster_alias,
                    namespace,
                    max(data_source) as data_source,
                    array_agg(DISTINCT resource_id) as resource_ids,
                    count(DISTINCT resource_id) as resource_count,
                    sum(persistentvolumeclaim_charge_gb_month) as persistentvolumeclaim_charge_gb_month,
                    sum(persistentvolumeclaim_usage_gigabyte_months) as persistentvolumeclaim_usage_gigabyte_months,
                    sum(volume_request_storage_gigabyte_months) as volume_request_storage_gigabyte_months,
                    sum(persistentvolumeclaim_capacity_gigabyte_months) as persistentvolumeclaim_capacity_gigabyte_months,
                    sum(infra_cost) as infra_cost,
                    sum(project_infra_cost) as project_infra_cost,
                    sum(markup_cost) as markup_cost,
                    sum(project_markup_cost) as project_markup_cost,
                    sum(monthly_cost) as monthly_cost
                FROM reporting_ocpusagelineitem_daily_summary
                -- Get data for this month or last month
                WHERE date_trunc('month', usage_start) = date_trunc('month', now()) AND data_source = 'Storage'
                    OR date_trunc('month', usage_start) = date_trunc('month', date_trunc('month', now()) - INTERVAL '1' DAY) AND data_source = 'Storage'
                GROUP BY date(usage_start), cluster_id, cluster_alias, namespace
            )
            ;

            CREATE UNIQUE INDEX ocp_volume_summary
            ON reporting_ocp_volume_summary (usage_start)
            ;
            """
        ),
    ]
