# Generated by Django 2.2.11 on 2020-03-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0101_ocpenabledtagkeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSOrganizationalUnit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('org_unit_name', models.CharField(max_length=50)),
                ('org_unit_path', models.TextField()),
                ('account_id', models.CharField(max_length=50, null=True)),
                ('created_timestamp', models.DateField()),
            ],
        ),
    ]
