# Generated by Django 2.2.11 on 2020-03-27 19:21
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reporting",
            "0103_azurecomputesummary_azurecostsummary_azurecostsummarybyaccount_azurecostsummarybylocation_azurecosts",
        )
    ]

    operations = [migrations.RemoveField(model_name="ocpusagelineitemdailysummary", name="pod")]
