# Generated by Django 2.2.11 on 2020-03-27 19:21
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reporting",
            "0107_ocpazurecomputesummary_ocpazurecostsummary_ocpazurecostsummarybyaccount_ocpazurecostsummarybylocatio",
        )
    ]

    operations = [migrations.RemoveField(model_name="ocpusagelineitemdailysummary", name="pod")]
