# Generated by Django 2.2.11 on 2020-04-06 17:48
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0108_auto_20200405_1316")]

    operations = [
        migrations.CreateModel(
            name="AWSOrganizationalUnit",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("org_unit_name", models.CharField(max_length=250)),
                ("org_unit_id", models.CharField(max_length=50)),
                ("org_unit_path", models.TextField()),
                ("account_id", models.CharField(max_length=50, null=True)),
                ("created_timestamp", models.DateField(null=True)),
            ],
        )
    ]
