# Generated by Django 2.2.11 on 2020-04-06 20:30
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0109_remove_ocpusagelineitemdailysummary_pod")]

    operations = [
        migrations.AddIndex(
            model_name="azurecostentrylineitemdailysummary",
            index=models.Index(fields=["usage_start"], name="ix_azurecstentrydlysumm_start"),
        ),
        migrations.RunSQL(
            sql="""
DROP INDEX IF EXISTS ocpall_product_code_ilike;
CREATE INDEX ocpall_product_code_ilike ON reporting_ocpallcostlineitem_daily_summary USING GIN (upper(product_code) gin_trgm_ops);

DROP INDEX IF EXISTS ocpall_product_family_ilike;
CREATE INDEX ocpall_product_family_ilike ON reporting_ocpallcostlineitem_daily_summary USING GIN (upper(product_family) gin_trgm_ops);
            """
        ),
        migrations.RunSQL(
            sql="""
DROP INDEX IF EXISTS aws_summ_usage_pfam_ilike;
CREATE INDEX aws_summ_usage_pfam_ilike ON reporting_awscostentrylineitem_daily_summary USING GIN (upper(product_family) gin_trgm_ops);
            """
        ),
        migrations.RunSQL(
            sql="""
DROP INDEX IF EXISTS ix_azure_costentrydlysumm_service_name;
CREATE INDEX ix_azure_costentrydlysumm_service_name ON reporting_azurecostentrylineitem_daily_summary USING GIN (upper(service_name) gin_trgm_ops);

DROP INDEX IF EXISTS ix_ocp_aws_product_family_ilike;
CREATE INDEX ix_ocp_aws_product_family_ilike ON reporting_ocpawscostlineitem_daily_summary USING GIN (upper(product_family) gin_trgm_ops);
            """
        ),
        migrations.RunSQL(
            sql="""
DROP INDEX IF EXISTS ix_ocp_aws_product_code_ilike;
CREATE INDEX ix_ocp_aws_product_code_ilike ON reporting_ocpawscostlineitem_daily_summary USING GIN (upper(product_code) gin_trgm_ops);

DROP INDEX IF EXISTS ix_ocpazure_service_name_ilike;
CREATE INDEX ix_ocpazure_service_name_ilike ON reporting_ocpazurecostlineitem_daily_summary USING GIN (upper(service_name) gin_trgm_ops);
            """
        ),
    ]
