# Generated by Django 2.2.11 on 2020-04-06 20:30
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0109_remove_ocpusagelineitemdailysummary_pod")]

    operations = [
        migrations.RunSQL(
            sql="""
DROP INDEX IF EXISTS ocpall_product_code_ilike;
CREATE INDEX ocpall_product_code_ilike ON reporting_ocpallcostlineitem_daily_summary USING GIN (upper(product_code) gin_trgm_ops);

DROP INDEX IF EXISTS ocpall_product_family_ilike;
CREATE INDEX ocpall_product_family_ilike ON reporting_ocpallcostlineitem_daily_summary USING GIN (upper(product_code) gin_trgm_ops);
            """
        )
    ]
