# Generated by Django 2.2.11 on 2020-04-15 18:29
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0109_remove_ocpusagelineitemdailysummary_pod")]

    operations = [
        migrations.CreateModel(
            name="AWSOrganizationalUnit",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("org_unit_name", models.CharField(max_length=250)),
                ("org_unit_id", models.CharField(max_length=50)),
                ("org_unit_path", models.TextField()),
                ("account_id", models.CharField(max_length=50, null=True)),
                ("created_timestamp", models.DateField(auto_now_add=True)),
                ("deleted_timestamp", models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="awscostentrylineitemdailysummary",
            name="organizational_unit",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.AWSOrganizationalUnit"
            ),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemdailysummary",
            name="organizational_unit",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.AWSOrganizationalUnit"
            ),
        ),
    ]
