# Generated by Django 2.2.11 on 2020-04-16 17:45
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0110_summary_indexes")]

    operations = [
        migrations.RemoveIndex(model_name="awscostentrylineitemdailysummary", name="aws_summ_usage_pcode_like"),
        migrations.RemoveIndex(model_name="awscostentrylineitemdailysummary", name="aws_summ_usage_pfam_like"),
    ]
