# Generated by Django 2.2.11 on 2020-04-08 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0110_awsorganizationalunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscostentrylineitemdailysummary',
            name='organizational_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.AWSOrganizationalUnit'),
        ),
        migrations.AddField(
            model_name='ocpawscostlineitemdailysummary',
            name='organizational_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.AWSOrganizationalUnit'),
        ),
    ]
