# Generated by Django 2.2.11 on 2020-04-23 13:47
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0111_auto_20200422_1451")]

    operations = [migrations.RemoveField(model_name="awsorganizationalunit", name="account_id")]
