# Generated by Django 2.2.11 on 2020-05-11 19:21
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0112_auto_20200416_1733")]

    operations = [
        migrations.CreateModel(
            name="AWSOrganizationalUnit",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("org_unit_name", models.CharField(max_length=250)),
                ("org_unit_id", models.CharField(max_length=50)),
                ("org_unit_path", models.TextField()),
                ("level", models.PositiveSmallIntegerField()),
                ("created_timestamp", models.DateField(auto_now_add=True)),
                ("deleted_timestamp", models.DateField(null=True)),
                (
                    "account_alias",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="reporting.AWSAccountAlias"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="awscostentrylineitemdailysummary",
            name="organizational_unit",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.AWSOrganizationalUnit"
            ),
        ),
    ]
