# Generated by Django 2.2.13 on 2020-06-15 20:27
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0114_adding_source_uuid")]

    operations = [
        migrations.RunSQL(
            sql="""
UPDATE reporting_awscostentrylineitem_daily_summary
    SET source_uuid = bill.provider_id
FROM reporting_awscostentrylineitem_daily_summary as aws
LEFT JOIN reporting_awscostentrybill as bill
    ON aws.cost_entry_bill_id = bill.id
WHERE aws.source_uuid is NULL;

UPDATE reporting_ocpawscostlineitem_daily_summary
    SET source_uuid = bill.provider_id
FROM reporting_ocpawscostlineitem_daily_summary as ocp_aws
LEFT JOIN reporting_awscostentrybill as bill
    ON ocp_aws.cost_entry_bill_id = bill.id
WHERE ocp_aws.source_uuid is NULL;

UPDATE reporting_ocpawscostlineitem_project_daily_summary
    SET source_uuid = bill.provider_id
FROM reporting_ocpawscostlineitem_project_daily_summary as ocp_aws_proj
LEFT JOIN reporting_awscostentrybill as bill
    ON ocp_aws_proj.cost_entry_bill_id = bill.id
WHERE ocp_aws_proj.source_uuid is NULL;

UPDATE reporting_azurecostentrylineitem_daily_summary
    SET source_uuid = bill.provider_id
FROM reporting_azurecostentrylineitem_daily_summary as az
LEFT JOIN reporting_azurecostentrybill as bill
    ON az.cost_entry_bill_id = bill.id
WHERE az.source_uuid is NULL;

UPDATE reporting_ocpazurecostlineitem_daily_summary
    SET source_uuid = bill.provider_id
FROM reporting_ocpazurecostlineitem_daily_summary as ocp_az
LEFT JOIN reporting_azurecostentrybill as bill
    ON ocp_az.cost_entry_bill_id = bill.id
WHERE ocp_az.source_uuid is NULL;

UPDATE reporting_ocpazurecostlineitem_project_daily_summary
    SET source_uuid = bill.provider_id
FROM reporting_ocpazurecostlineitem_project_daily_summary as ocp_az_proj
LEFT JOIN reporting_azurecostentrybill as bill
    ON ocp_az_proj.cost_entry_bill_id = bill.id
WHERE ocp_az_proj.source_uuid is NULL;

UPDATE acct10001.reporting_ocpusagelineitem_daily_summary as ocp
    SET source_uuid = rp.provider_id
FROM acct10001.reporting_ocpusagereportperiod as rp
WHERE ocp.source_uuid is NULL
AND ocp.report_period_id = rp.id
AND ocp.cluster_id = rp.cluster_id;
-- AND ocp.data_source = 'Pod' I am not sure if I need this line or not.
            """
        )
    ]
