# Generated by Django 2.2.12 on 2020-05-13 19:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0114_aws_adding_source_uuid")]

    operations = [
        migrations.RunSQL(
            # Got to drop these views as we are changing the type of a selected column
            # They will be recreated below
            sql="""
DROP INDEX IF EXISTS ocpall_storage_summary;
DROP MATERIALIZED VIEW IF EXISTS reporting_ocpall_storage_summary;

DROP INDEX IF EXISTS ocpall_network_summary;
DROP MATERIALIZED VIEW IF EXISTS reporting_ocpall_network_summary;

DROP INDEX IF EXISTS ocpall_database_summary;
DROP MATERIALIZED VIEW IF EXISTS reporting_ocpall_database_summary;

DROP INDEX IF EXISTS ocpall_compute_summary;
DROP MATERIALIZED VIEW IF EXISTS reporting_ocpall_compute_summary;

DROP INDEX IF EXISTS ocpall_cost_summary_region;
DROP MATERIALIZED VIEW IF EXISTS reporting_ocpall_cost_summary_by_region;

DROP INDEX IF EXISTS ocpall_cost_summary_service;
DROP MATERIALIZED VIEW IF EXISTS reporting_ocpall_cost_summary_by_service;

DROP INDEX IF EXISTS ocpall_cost_summary_account;
DROP MATERIALIZED VIEW IF EXISTS reporting_ocpall_cost_summary_by_account;

DROP INDEX IF EXISTS ocpall_cost_summary;
DROP MATERIALIZED VIEW IF EXISTS reporting_ocpall_cost_summary;

DROP INDEX IF EXISTS ocpallcstprjdlysumm_node;
DROP INDEX IF EXISTS ocpallcstprjdlysumm_nsp;
DROP INDEX IF EXISTS ocpallcstprjdlysumm_node_like;
DROP INDEX IF EXISTS ocpallcstprjdlysumm_nsp_like;
DROP INDEX IF EXISTS ocpall_product_family_ilike;
DROP MATERIALIZED VIEW IF EXISTS reporting_ocpallcostlineitem_project_daily_summary;

DROP INDEX IF EXISTS ocpallcstdlysumm_node;
DROP INDEX IF EXISTS ocpallcstdlysumm_node_like;
DROP INDEX IF EXISTS ocpallcstdlysumm_nsp;
DROP INDEX IF EXISTS ocpall_product_code_ilike;
DROP MATERIALIZED VIEW IF EXISTS reporting_ocpallcostlineitem_daily_summary;
            """
        ),
        migrations.RunSQL(
            # Got to drop these views as we are changing the type of a selected column
            # They will be recreated below
            sql="""

CREATE MATERIALIZED VIEW reporting_ocpallcostlineitem_daily_summary AS (
    SELECT row_number() OVER () as id,
        lids.*
    FROM (
        SELECT 'AWS' as source_type,
            cluster_id,
            cluster_alias,
            namespace,
            node::text as node,
            resource_id,
            usage_start,
            usage_end,
            usage_account_id,
            account_alias_id,
            product_code,
            product_family,
            instance_type,
            region,
            availability_zone,
            tags,
            usage_amount,
            unit,
            unblended_cost,
            markup_cost,
            currency_code,
            shared_projects,
            project_costs,
            source_uuid
        FROM reporting_ocpawscostlineitem_daily_summary
        WHERE usage_start >= DATE_TRUNC('month', NOW() - '1 month'::interval)::date

        UNION

        SELECT 'Azure' as source_type,
            cluster_id,
            cluster_alias,
            namespace,
            node::text as node,
            resource_id,
            usage_start,
            usage_end,
            subscription_guid as usage_account_id,
            NULL::int as account_alias_id,
            service_name as product_code,
            NULL as product_family,
            instance_type,
            resource_location as region,
            NULL as availability_zone,
            tags,
            usage_quantity as usage_amount,
            unit_of_measure as unit,
            pretax_cost as unblended_cost,
            markup_cost,
            currency as currency_code,
            shared_projects,
            project_costs,
            source_uuid
        FROM reporting_ocpazurecostlineitem_daily_summary
        WHERE usage_start >= DATE_TRUNC('month', NOW() - '1 month'::interval)::date
    ) AS lids
)
;

CREATE INDEX ocpallcstdlysumm_node on reporting_ocpallcostlineitem_daily_summary (node text_pattern_ops);
CREATE INDEX ocpallcstdlysumm_node_like on reporting_ocpallcostlineitem_daily_summary USING GIN (node gin_trgm_ops);
CREATE INDEX ocpallcstdlysumm_nsp on reporting_ocpallcostlineitem_daily_summary USING GIN (namespace);
CREATE INDEX ocpall_product_code_ilike ON reporting_ocpallcostlineitem_daily_summary USING GIN (upper(product_code) gin_trgm_ops);

CREATE MATERIALIZED VIEW reporting_ocpallcostlineitem_project_daily_summary AS (
    SELECT row_number() OVER () as id,
        lids.*
    FROM (
        SELECT 'AWS' as source_type,
            cluster_id,
            cluster_alias,
            data_source,
            namespace::text as namespace,
            node::text as node,
            pod_labels,
            resource_id,
            usage_start,
            usage_end,
            usage_account_id,
            account_alias_id,
            product_code,
            product_family,
            instance_type,
            region,
            availability_zone,
            usage_amount,
            unit,
            unblended_cost,
            project_markup_cost,
            pod_cost,
            currency_code,
            source_uuid
        FROM reporting_ocpawscostlineitem_project_daily_summary
        WHERE usage_start >= DATE_TRUNC('month', NOW() - '1 month'::interval)::date

        UNION

        SELECT 'Azure' as source_type,
            cluster_id,
            cluster_alias,
            data_source,
            namespace::text as namespace,
            node::text as node,
            pod_labels,
            resource_id,
            usage_start,
            usage_end,
            subscription_guid as usage_account_id,
            NULL::int as account_alias_id,
            service_name as product_code,
            NULL as product_family,
            instance_type,
            resource_location as region,
            NULL as availability_zone,
            usage_quantity as usage_amount,
            unit_of_measure as unit,
            pretax_cost as unblended_cost,
            project_markup_cost,
            pod_cost,
            currency as currency_code,
            source_uuid
        FROM reporting_ocpazurecostlineitem_project_daily_summary
        WHERE usage_start >= DATE_TRUNC('month', NOW() - '1 month'::interval)::date
    ) AS lids
)
;

CREATE INDEX ocpallcstprjdlysumm_node on reporting_ocpallcostlineitem_project_daily_summary (node text_pattern_ops);
CREATE INDEX ocpallcstprjdlysumm_nsp on reporting_ocpallcostlineitem_project_daily_summary (namespace text_pattern_ops);
CREATE INDEX ocpallcstprjdlysumm_node_like on reporting_ocpallcostlineitem_project_daily_summary USING GIN (node gin_trgm_ops);
CREATE INDEX ocpallcstprjdlysumm_nsp_like on reporting_ocpallcostlineitem_project_daily_summary USING GIN (namespace gin_trgm_ops);
CREATE INDEX ocpall_product_family_ilike ON reporting_ocpallcostlineitem_daily_summary USING GIN (upper(product_family) gin_trgm_ops);

CREATE MATERIALIZED VIEW reporting_ocpall_cost_summary AS(
    SELECT row_number() OVER(ORDER BY usage_start, cluster_id, cluster_alias) as id,
        usage_start as usage_start,
        usage_start as usage_end,
        cluster_id,
        cluster_alias,
        sum(unblended_cost) as unblended_cost,
        sum(markup_cost) as markup_cost,
        max(currency_code) as currency_code,
        ARRAY_AGG (DISTINCT source_uuid) source_uuid
    FROM reporting_ocpallcostlineitem_daily_summary
    -- Get data for this month or last month
    WHERE usage_start >= DATE_TRUNC('month', NOW() - '1 month'::interval)::date
    GROUP BY usage_start, cluster_id, cluster_alias
)
WITH DATA
;

CREATE UNIQUE INDEX ocpall_cost_summary
ON reporting_ocpall_cost_summary (usage_start, cluster_id, cluster_alias)
;

CREATE MATERIALIZED VIEW reporting_ocpall_cost_summary_by_account AS(
    SELECT row_number() OVER(ORDER BY usage_start, cluster_id, cluster_alias, usage_account_id, account_alias_id) as id,
        usage_start as usage_start,
        usage_start as usage_end,
        cluster_id,
        cluster_alias,
        usage_account_id,
        account_alias_id,
        sum(unblended_cost) as unblended_cost,
        sum(markup_cost) as markup_cost,
        max(currency_code) as currency_code,
        ARRAY_AGG (DISTINCT source_uuid) source_uuid
    FROM reporting_ocpallcostlineitem_daily_summary
    -- Get data for this month or last month
    WHERE usage_start >= DATE_TRUNC('month', NOW() - '1 month'::interval)::date
    GROUP BY usage_start, cluster_id, cluster_alias, usage_account_id, account_alias_id
)
WITH DATA
;

CREATE UNIQUE INDEX ocpall_cost_summary_account
ON reporting_ocpall_cost_summary_by_account (usage_start, cluster_id, cluster_alias, usage_account_id, account_alias_id)
;

CREATE MATERIALIZED VIEW reporting_ocpall_cost_summary_by_service AS(
    SELECT row_number() OVER(ORDER BY usage_start, cluster_id, cluster_alias, product_code, product_family) as id,
        usage_start as usage_start,
        usage_start as usage_end,
        cluster_id,
        cluster_alias,
        product_code,
        product_family,
        sum(unblended_cost) as unblended_cost,
        sum(markup_cost) as markup_cost,
        max(currency_code) as currency_code,
        ARRAY_AGG (DISTINCT source_uuid) source_uuid
    FROM reporting_ocpallcostlineitem_daily_summary
    -- Get data for this month or last month
    WHERE usage_start >= DATE_TRUNC('month', NOW() - '1 month'::interval)::date
    GROUP BY usage_start, cluster_id, cluster_alias, product_code, product_family
)
WITH DATA
;

CREATE UNIQUE INDEX ocpall_cost_summary_service
ON reporting_ocpall_cost_summary_by_service (usage_start, cluster_id, cluster_alias, product_code, product_family)
;

CREATE MATERIALIZED VIEW reporting_ocpall_cost_summary_by_region AS(
    SELECT row_number() OVER(ORDER BY usage_start, cluster_id, cluster_alias, region, availability_zone) as id,
        usage_start as usage_start,
        usage_start as usage_end,
        cluster_id,
        cluster_alias,
        region,
        availability_zone,
        sum(unblended_cost) as unblended_cost,
        sum(markup_cost) as markup_cost,
        max(currency_code) as currency_code,
        ARRAY_AGG (DISTINCT source_uuid) source_uuid
    FROM reporting_ocpallcostlineitem_daily_summary
    -- Get data for this month or last month
    WHERE usage_start >= DATE_TRUNC('month', NOW() - '1 month'::interval)::date
    GROUP BY usage_start, cluster_id, cluster_alias, region, availability_zone
)
WITH DATA
;

CREATE UNIQUE INDEX ocpall_cost_summary_region
ON reporting_ocpall_cost_summary_by_region (usage_start, cluster_id, cluster_alias, region, availability_zone)
;

CREATE MATERIALIZED VIEW reporting_ocpall_compute_summary AS (
    SELECT row_number() OVER (ORDER BY usage_start, cluster_id, cluster_alias, product_code) AS id,
        lids.usage_start,
        lids.usage_start as usage_end,
        lids.cluster_id,
        lids.cluster_alias,
        lids.product_code,
        lids.instance_type,
        lids.resource_id,
        sum(lids.usage_amount) as usage_amount,
        max(lids.unit) as unit,
        sum(lids.unblended_cost) as unblended_cost,
        sum(lids.markup_cost) as markup_cost,
        max(lids.currency_code) as currency_code,
        ARRAY_AGG (DISTINCT source_uuid) source_uuid
    FROM reporting_ocpallcostlineitem_daily_summary lids
    WHERE usage_start >= DATE_TRUNC('month', NOW() - '1 month'::interval)::date
        AND instance_type IS NOT NULL
    GROUP BY lids.usage_start,
        lids.cluster_id,
        lids.cluster_alias,
        lids.product_code,
        lids.instance_type,
        lids.resource_id
)
WITH DATA
;

CREATE UNIQUE INDEX ocpall_compute_summary
ON reporting_ocpall_compute_summary (usage_start, cluster_id, cluster_alias, product_code, instance_type, resource_id);

CREATE MATERIALIZED VIEW reporting_ocpall_database_summary AS (
    SELECT row_number() OVER (ORDER BY usage_start, cluster_id, cluster_alias, product_code) AS id,
        lids.usage_start,
        lids.usage_start as usage_end,
        lids.cluster_id,
        lids.cluster_alias,
        lids.product_code,
        sum(lids.usage_amount) as usage_amount,
        max(lids.unit) as unit,
        sum(lids.unblended_cost) as unblended_cost,
        sum(lids.markup_cost) as markup_cost,
        max(lids.currency_code) as currency_code,
        ARRAY_AGG (DISTINCT source_uuid) source_uuid
    FROM reporting_ocpallcostlineitem_daily_summary lids
    WHERE usage_start >= DATE_TRUNC('month', NOW() - '1 month'::interval)::date
        AND (
            product_code IN ('AmazonRDS','AmazonDynamoDB','AmazonElastiCache','AmazonNeptune','AmazonRedshift','AmazonDocumentDB','Cosmos DB','Cache for Redis')
                OR product_code LIKE '%Database%'
        )
    GROUP BY lids.usage_start,
        lids.cluster_id,
        lids.cluster_alias,
        lids.product_code
)
WITH DATA
;

CREATE UNIQUE INDEX ocpall_database_summary
ON reporting_ocpall_database_summary (usage_start, cluster_id, cluster_alias, product_code)
;

CREATE MATERIALIZED VIEW reporting_ocpall_network_summary AS (
    SELECT row_number() OVER (ORDER BY usage_start, cluster_id, cluster_alias, product_code) AS id,
        lids.cluster_id,
        lids.cluster_alias,
        lids.usage_start,
        lids.usage_start as usage_end,
        lids.product_code,
        sum(lids.usage_amount) as usage_amount,
        max(lids.unit) as unit,
        sum(lids.unblended_cost) as unblended_cost,
        sum(lids.markup_cost) as markup_cost,
        max(lids.currency_code) as currency_code,
        ARRAY_AGG (DISTINCT source_uuid) source_uuid
    FROM reporting_ocpallcostlineitem_daily_summary lids
    WHERE usage_start >= DATE_TRUNC('month', NOW() - '1 month'::interval)::date
        AND product_code IN ('AmazonVPC','AmazonCloudFront','AmazonRoute53','AmazonAPIGateway','Virtual Network','VPN','DNS','Traffic Manager','ExpressRoute','Load Balancer','Application Gateway')
    GROUP BY lids.usage_start,
        lids.cluster_id,
        lids.cluster_alias,
        lids.product_code
)
WITH DATA
;

CREATE UNIQUE INDEX ocpall_network_summary
ON reporting_ocpall_network_summary (usage_start, cluster_id, cluster_alias, product_code)
;

CREATE MATERIALIZED VIEW reporting_ocpall_storage_summary AS (
    SELECT row_number() OVER (ORDER BY usage_start, cluster_id, cluster_alias, product_family, product_code) AS id,
        cluster_id,
        cluster_alias,
        usage_start,
        usage_start as usage_end,
        product_family,
        product_code,
        sum(usage_amount) as usage_amount,
        max(unit) as unit,
        sum(unblended_cost) as unblended_cost,
        sum(markup_cost) as markup_cost,
        max(currency_code) as currency_code,
        ARRAY_AGG (DISTINCT source_uuid) source_uuid
    FROM reporting_ocpallcostlineitem_daily_summary
    WHERE usage_start >= DATE_TRUNC('month', NOW() - '1 month'::interval)::date
        AND (product_family LIKE '%Storage%' OR product_code LIKE '%Storage%')
    GROUP BY usage_start,
        cluster_id,
        cluster_alias,
        product_family,
        product_code
)
WITH DATA
;

CREATE INDEX ocpall_storage_summary
ON reporting_ocpall_storage_summary (usage_start, cluster_id, cluster_alias, product_family, product_code)
;
"""
        ),
    ]
