# Generated by Django 2.2.12 on 2020-06-19 17:37
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0114_adding_source_uuid")]

    operations = [
        migrations.AlterUniqueTogether(
            name="ocpusagepodlabelsummary", unique_together={("key", "report_period", "namespace")}
        )
    ]
