# Generated by Django 2.2.12 on 2020-06-18 12:47
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0115_populate_source_uuid")]

    operations = [
        migrations.RunSQL(
            """
            DROP INDEX IF EXISTS ocpall_cost_daily_summary;
            CREATE UNIQUE INDEX ocpall_cost_daily_summary
            ON reporting_ocpallcostlineitem_daily_summary (source_type, usage_start, cluster_id, namespace, node, usage_account_id, resource_id, product_code, product_family, instance_type, region, availability_zone, tags)
            ;
            DROP INDEX IF EXISTS ocpall_cost_project_daily_summary;
            CREATE UNIQUE INDEX ocpall_cost_project_daily_summary
            ON reporting_ocpallcostlineitem_project_daily_summary (source_type, usage_start, cluster_id, namespace, node, usage_account_id, resource_id, product_code, product_family, instance_type, region, availability_zone, pod_labels)
            ;
            DROP INDEX IF EXISTS ocpall_storage_summary;
            CREATE UNIQUE INDEX ocpall_storage_summary
            ON reporting_ocpall_storage_summary (usage_start, cluster_id, cluster_alias, product_family, product_code, source_uuid)
            ;
            """
        )
    ]
