# Generated by Django 2.2.13 on 2020-06-17 22:54
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0021_db_functions"), ("reporting", "0115_populate_source_uuid")]

    operations = [
        migrations.RunSQL(
            """
-- ===================================
--  Create tracking table
-- ===================================

CREATE TABLE IF NOT EXISTS partitioned_tables (
    id serial PRIMARY KEY,
    schema_name text NOT NULL default current_schema,
    table_name text NOT NULL,
    partition_of_table_name text NOT NULL,
    partition_type text NOT NULL,
    partition_col text NOT NULL,
    partition_parameters JSONB NOT NULL,
    CONSTRAINT table_partition_unique UNIQUE (schema_name, table_name)
 );

CREATE INDEX "partable_table"
    ON partitioned_tables (table_name, schema_name);

CREATE INDEX "partable_partition_parameters"
    ON partitioned_tables USING GIN (partition_parameters);

CREATE INDEX "partable_partition_type"
    ON partitioned_tables (partition_type);

-- ===================================
--   Create the new partitioned table
-- ===================================

-- Rename the original table's sequence object. Looks strange, but it ends up making things easier later
ALTER SEQUENCE reporting_ocpusagelineitem_daily_summary_id_seq
      RENAME TO __reporting_ocpusagelineitem_daily_summary_id_seq ;

CREATE TABLE IF NOT EXISTS p_reporting_ocpusagelineitem_daily_summary (
    id bigint ,
    cluster_id CHARACTER varying(50) ,
    namespace CHARACTER varying(253) ,
    node CHARACTER varying(253) ,
    usage_start date ,
    usage_end date NOT NULL,
    pod_usage_cpu_core_hours numeric(27,9) ,
    pod_request_cpu_core_hours numeric(27,9) ,
    pod_limit_cpu_core_hours numeric(27,9) ,
    pod_usage_memory_gigabyte_hours numeric(27,9) ,
    pod_request_memory_gigabyte_hours numeric(27,9) ,
    pod_limit_memory_gigabyte_hours numeric(27,9) ,
    node_capacity_cpu_core_hours numeric(27,9) ,
    node_capacity_cpu_cores numeric(27,9) ,
    node_capacity_memory_gigabyte_hours numeric(27,9) ,
    node_capacity_memory_gigabytes numeric(27,9) ,
    cluster_capacity_cpu_core_hours numeric(27,9) ,
    cluster_capacity_memory_gigabyte_hours numeric(27,9) ,
    pod_labels JSONB ,
    cluster_alias CHARACTER varying(256) ,
    resource_id CHARACTER varying(253) ,
    total_capacity_cpu_core_hours numeric(27,9) ,
    total_capacity_memory_gigabyte_hours numeric(27,9) ,
    data_source CHARACTER varying(64) ,
    persistentvolume CHARACTER varying(253) ,
    persistentvolumeclaim CHARACTER varying(253) ,
    persistentvolumeclaim_capacity_gigabyte numeric(27,9) ,
    persistentvolumeclaim_capacity_gigabyte_months numeric(27,9) ,
    persistentvolumeclaim_usage_gigabyte_months numeric(27,9) ,
    storageclass CHARACTER varying(50) ,
    volume_labels JSONB ,
    volume_request_storage_gigabyte_months numeric(27,9) ,
    report_period_id integer ,
    infrastructure_markup_cost numeric(33,15) ,
    infrastructure_monthly_cost numeric(33,15) ,
    infrastructure_project_markup_cost numeric(33,15) ,
    infrastructure_project_raw_cost numeric(33,15) ,
    infrastructure_raw_cost numeric(33,15) ,
    infrastructure_usage_cost JSONB ,
    monthly_cost_type text ,
    supplementary_monthly_cost numeric(33,15) ,
    supplementary_usage_cost JSONB ,
    source_uuid UUID
)
PARTITION BY RANGE (usage_start);

CREATE SEQUENCE reporting_ocpusagelineitem_daily_summary_id_seq AS bigint
       INCREMENT BY 1
       MINVALUE 1
       MAXVALUE 9223372036854775807
       START WITH 1
       CACHE 1
       NO CYCLE ;

ALTER TABLE p_reporting_ocpusagelineitem_daily_summary ALTER COLUMN id
   SET DEFAULT nextval('reporting_ocpusagelineitem_daily_summary_id_seq'::regclass) ;

ALTER SEQUENCE reporting_ocpusagelineitem_daily_summary_id_seq owned BY p_reporting_ocpusagelineitem_daily_summary.id ;

ALTER TABLE p_reporting_ocpusagelineitem_daily_summary ADD
CONSTRAINT p_reporting_ocpusagelineitem_daily_summary_pkey PRIMARY KEY (usage_start, id) ;

ALTER TABLE p_reporting_ocpusagelineitem_daily_summary ADD
CONSTRAINT p_reporting_ocpusageli_report_period_id_fc68baea_fk_reporting
FOREIGN KEY (report_period_id) REFERENCES reporting_ocpusagereportperiod(id) DEFERRABLE INITIALLY DEFERRED ;

CREATE INDEX p_pod_labels_idx
    ON p_reporting_ocpusagelineitem_daily_summary USING gin (pod_labels) ;

CREATE INDEX p_summary_data_source_idx
    ON p_reporting_ocpusagelineitem_daily_summary USING btree (data_source) ;

CREATE INDEX p_reporting_ocpusagelineitem_report_period_id_fc68baea
    ON p_reporting_ocpusagelineitem_daily_summary USING btree (report_period_id) ;

CREATE INDEX p_summary_ocp_usage_idx
    ON p_reporting_ocpusagelineitem_daily_summary USING btree (usage_start) ;

CREATE INDEX p_summary_namespace_idx
    ON p_reporting_ocpusagelineitem_daily_summary USING btree (namespace varchar_pattern_ops) ;

CREATE INDEX p_summary_node_idx
    ON p_reporting_ocpusagelineitem_daily_summary USING btree (node varchar_pattern_ops) ;

CREATE INDEX p_ocp_summary_namespace_like_idx
    ON p_reporting_ocpusagelineitem_daily_summary USING gin (upper((namespace)::text) gin_trgm_ops) ;

CREATE INDEX p_ocp_summary_node_like_idx
    ON p_reporting_ocpusagelineitem_daily_summary USING gin (upper((node)::text) gin_trgm_ops) ;


-- ===================================
--  Create default partition
-- ===================================
CREATE TABLE reporting_ocpusagelineitem_daily_summary_default
PARTITION OF p_reporting_ocpusagelineitem_daily_summary DEFAULT;

INSERT INTO partitioned_tables (
    schema_name,
    table_name,
    partition_of_table_name,
    partition_type,
    partition_col,
    partition_parameters
)
VALUES (
    current_schema,
    'reporting_ocpusagelineitem_daily_summary_default',
    'reporting_ocpusagelineitem_daily_summary',
    'default',
    'usage_start',
    '{"default": true}'::jsonb
);
            """
        )
    ]
