# Generated by Django 2.2.12 on 2020-06-19 17:57
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0116_ocpall_unique_index")]

    operations = [
        migrations.AlterUniqueTogether(
            name="ocpusagepodlabelsummary", unique_together={("key", "report_period", "namespace")}
        )
    ]
