# Generated by Django 2.2.12 on 2020-06-30 18:19
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0117_auto_20200617_1452")]

    operations = [
        migrations.AlterUniqueTogether(
            name="ocpawstagssummary", unique_together={("key", "cost_entry_bill", "namespace")}
        ),
        migrations.AlterUniqueTogether(
            name="ocpazuretagssummary", unique_together={("key", "cost_entry_bill", "namespace")}
        ),
        migrations.AlterUniqueTogether(
            name="ocpstoragevolumeclaimlabelsummary", unique_together={("key", "report_period", "namespace")}
        ),
        migrations.AlterUniqueTogether(
            name="ocpstoragevolumelabelsummary", unique_together={("key", "report_period", "namespace")}
        ),
        migrations.AlterUniqueTogether(
            name="ocpusagepodlabelsummary", unique_together={("key", "report_period", "namespace")}
        ),
    ]
