# Generated by Django 2.2.13 on 2020-06-17 22:54
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0117_partitioned_ocplineitemusage_daily_summary")]

    operations = [
        migrations.RunSQL(
            """
-- ============================================
--    Lock and rename objects
-- ============================================

LOCK TABLE reporting_ocpusagelineitem_daily_summary;

-- rename old objects
ALTER materialized VIEW reporting_ocp_cost_summary RENAME TO __reporting_ocp_cost_summary ;
ALTER INDEX ocp_cost_summary RENAME TO __ocp_cost_summary ;

ALTER materialized VIEW reporting_ocp_cost_summary_by_node RENAME TO __reporting_ocp_cost_summary_by_node ;
ALTER INDEX ocp_cost_summary_by_node RENAME TO __ocp_cost_summary_by_node ;

ALTER materialized VIEW reporting_ocp_cost_summary_by_project RENAME TO __reporting_ocp_cost_summary_by_project ;
ALTER INDEX ocp_cost_summary_by_project RENAME TO __ocp_cost_summary_by_project ;

ALTER materialized VIEW reporting_ocp_pod_summary RENAME TO __reporting_ocp_pod_summary ;
ALTER INDEX ocp_pod_summary RENAME TO __ocp_pod_summary ;

ALTER materialized VIEW reporting_ocp_pod_summary_by_project RENAME TO __reporting_ocp_pod_summary_by_project ;
ALTER INDEX ocp_pod_summary_by_project RENAME TO __ocp_pod_summary_by_project ;

ALTER materialized VIEW reporting_ocp_volume_summary RENAME TO __reporting_ocp_volume_summary ;
ALTER INDEX ocp_volume_summary RENAME TO __ocp_volume_summary ;

ALTER materialized VIEW reporting_ocp_volume_summary_by_project RENAME TO __reporting_ocp_volume_summary_by_project ;
ALTER INDEX ocp_volume_summary_by_project RENAME TO __ocp_volume_summary_by_project ;

-- Rename the tables so that the new partitioned table is named the original table's name
ALTER TABLE reporting_ocpusagelineitem_daily_summary RENAME TO __reporting_ocpusagelineitem_daily_summary;
ALTER TABLE p_reporting_ocpusagelineitem_daily_summary RENAME TO reporting_ocpusagelineitem_daily_summary;

-- Reflect tale change in the tracking table
UPDATE partitioned_tables
   SET partition_of_table_name = 'reporting_ocpusagelineitem_daily_summary'
 WHERE partition_of_table_name = 'p_reporting_ocpusagelineitem_daily_summary';
            """
        )
    ]
