# Generated by Django 2.2.13 on 2020-06-17 22:54
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0117_rename_ocplineitemusage_daily_summary")]

    operations = [
        migrations.RunSQL(
            """
-- ========================================
--    This procedure will scan the target table's target field for
--    distinct start-of-month dates and automagically create the
--    table partitions for the partitioned table
--    These new partitions will also be tracked like the default partition
-- ========================================
CALL public.create_date_partitions(
    '__reporting_ocpusagelineitem_daily_summary',
    'usage_start',
    current_schema,
    'reporting_ocpusagelineitem_daily_summary',
    'usage_start'
);
            """
        )
    ]
