# Generated by Django 2.2.12 on 2020-06-29 21:54
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0117_auto_20200617_1452")]

    operations = [
        migrations.AlterUniqueTogether(
            name="ocpstoragevolumelabelsummary", unique_together={("key", "report_period", "namespace")}
        ),
        migrations.AlterUniqueTogether(
            name="ocpusagepodlabelsummary", unique_together={("key", "report_period", "namespace")}
        ),
    ]
