# Generated by Django 2.2.12 on 2020-07-07 14:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0118_auto_20200630_1819")]

    operations = [
        migrations.AddField(
            model_name="ocpawstagssummary", name="cluster_id", field=models.CharField(max_length=50, null=True)
        ),
        migrations.AddField(
            model_name="ocpazuretagssummary", name="cluster_id", field=models.CharField(max_length=50, null=True)
        ),
    ]
