# Generated by Django 2.2.13 on 2020-08-06 18:37
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0119_auto_20200707_1934")]

    operations = [
        migrations.CreateModel(
            name="AWSTagsValues",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=253, unique=True)),
            ],
            options={"db_table": "reporting_awstags_values"},
        ),
        migrations.CreateModel(
            name="AzureTagsValues",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=253, unique=True)),
            ],
            options={"db_table": "reporting_azuretags_values"},
        ),
        migrations.AddField(
            model_name="awstagssummary", name="values_mtm", field=models.ManyToManyField(to="reporting.AWSTagsValues")
        ),
        migrations.AddField(
            model_name="azuretagssummary",
            name="values_mtm",
            field=models.ManyToManyField(to="reporting.AzureTagsValues"),
        ),
    ]
