# Generated by Django 2.2.13 on 2020-07-15 20:59
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0119_auto_20200707_1934")]

    operations = [
        migrations.CreateModel(
            name="AWSTagsValues",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=253)),
            ],
            options={"db_table": "reporting_awstags_values"},
        ),
        migrations.RemoveField(model_name="awstagssummary", name="values"),
        migrations.AddField(
            model_name="awstagssummary", name="values", field=models.ManyToManyField(to="reporting.AWSTagsValues")
        ),
    ]
