# Generated by Django 2.2.14 on 2020-07-24 13:54
import pkgutil

import django.contrib.postgres.fields
from django.db import connection
from django.db import migrations
from django.db import models

from reporting.provider.azure.models import VIEWS


def add_views(apps, schema_editor):
    """Create database VIEWS from files."""
    for view in VIEWS:
        view_sql = pkgutil.get_data("reporting.provider.azure", f"sql/views/{view}.sql")
        view_sql = view_sql.decode("utf-8")
        with connection.cursor() as cursor:
            cursor.execute(view_sql)


class Migration(migrations.Migration):

    dependencies = [("reporting", "0119_auto_20200707_1934")]

    operations = [
        migrations.RunSQL(
            """
                DROP INDEX IF EXISTS azure_database_summary;
                DROP MATERIALIZED VIEW IF EXISTS reporting_azure_database_summary;

                DROP INDEX IF EXISTS azure_compute_summary;
                DROP MATERIALIZED VIEW IF EXISTS reporting_azure_compute_summary;

                DROP INDEX IF EXISTS azure_cost_summary;
                DROP MATERIALIZED VIEW IF EXISTS reporting_azure_cost_summary;

                DROP INDEX IF EXISTS azure_cost_summary_account;
                DROP MATERIALIZED VIEW IF EXISTS reporting_azure_cost_summary_by_account;

                DROP INDEX IF EXISTS azure_cost_summary_location;
                DROP MATERIALIZED VIEW IF EXISTS reporting_azure_cost_summary_by_location;

                DROP INDEX IF EXISTS azure_cost_summary_service;
                DROP MATERIALIZED VIEW IF EXISTS reporting_azure_cost_summary_by_service;

                DROP INDEX IF EXISTS azure_network_summary;
                DROP MATERIALIZED VIEW IF EXISTS reporting_azure_network_summary;

                DROP INDEX IF EXISTS azure_storage_summary;
                DROP MATERIALIZED VIEW IF EXISTS reporting_azure_storage_summary;
            """
        ),
        migrations.AlterField(
            model_name="azurecostentrylineitemdaily", name="subscription_guid", field=models.TextField()
        ),
        migrations.AlterField(
            model_name="azurecostentrylineitemdailysummary", name="currency", field=models.TextField(default="USD")
        ),
        migrations.AlterField(
            model_name="azurecostentrylineitemdailysummary",
            name="instance_ids",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name="azurecostentrylineitemdailysummary", name="instance_type", field=models.TextField(null=True)
        ),
        migrations.AlterField(
            model_name="azurecostentrylineitemdailysummary",
            name="resource_location",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="azurecostentrylineitemdailysummary", name="service_name", field=models.TextField()
        ),
        migrations.AlterField(
            model_name="azurecostentrylineitemdailysummary", name="subscription_guid", field=models.TextField()
        ),
        migrations.AlterField(
            model_name="azurecostentrylineitemdailysummary", name="unit_of_measure", field=models.TextField(null=True)
        ),
        migrations.AlterField(
            model_name="azurecostentryproductservice", name="resource_location", field=models.TextField(null=True)
        ),
        migrations.AlterField(model_name="azuremeter", name="currency", field=models.TextField(null=True)),
        migrations.AlterField(model_name="azuremeter", name="meter_category", field=models.TextField(null=True)),
        migrations.AlterField(model_name="azuremeter", name="meter_name", field=models.TextField()),
        migrations.AlterField(model_name="azuremeter", name="meter_region", field=models.TextField(null=True)),
        migrations.AlterField(model_name="azuremeter", name="meter_subcategory", field=models.TextField(null=True)),
        migrations.AlterField(model_name="azuremeter", name="unit_of_measure", field=models.TextField(null=True)),
        migrations.AlterField(
            model_name="azurecostentrylineitemdailysummary", name="service_name", field=models.TextField(null=True)
        ),
        migrations.AlterField(
            model_name="azurecostentrylineitemdailysummary", name="currency", field=models.TextField(null=True)
        ),
        migrations.RunPython(add_views),
    ]
