# Generated by Django 2.2.13 on 2020-06-17 22:54
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0119_matview_ocplineitemusage_daily_summary")]

    operations = [
        migrations.RunSQL(
            """
TRUNCATE TABLE __reporting_ocpusagelineitem_daily_summary;
DROP TABLE __reporting_ocpusagelineitem_daily_summary CASCADE;
            """
        )
    ]
