# Generated by Django 2.2.12 on 2020-07-07 14:40
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0119_auto_20200707_1410")]

    operations = [
        migrations.AddField(
            model_name="ocpawstagssummary", name="cluster_alias", field=models.CharField(max_length=256, null=True)
        ),
        migrations.AddField(
            model_name="ocpazuretagssummary", name="cluster_alias", field=models.CharField(max_length=256, null=True)
        ),
        migrations.AddField(
            model_name="ocpusagereportperiod", name="cluster_alias", field=models.CharField(max_length=256, null=True)
        ),
    ]
