# Generated by Django 2.2.13 on 2020-07-17 20:08
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0120_auto_20200715_2303")]

    operations = [
        migrations.CreateModel(
            name="AzureTagsValues",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=253, unique=True)),
            ],
            options={"db_table": "reporting_azuretags_values"},
        ),
        migrations.RemoveField(model_name="azuretagssummary", name="values"),
        migrations.AddField(
            model_name="azuretagssummary", name="values", field=models.ManyToManyField(to="reporting.AzureTagsValues")
        ),
    ]
