# Generated by Django 2.2.13 on 2020-06-17 22:54
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations
from django.db import models

import reporting.partition.models
from migration_helpers import pg_partition as ppart


# Change reporting_ocpusagelineitem_daily_summary
# to a partitioned table with the same definition
def convert_ocpusage_lids_to_partitioned(apps, schema_editor):
    # Resolve the current schema name
    target_schema = ppart.resolve_schema(ppart.CURRENT_SCHEMA)
    # This is the table we will model from
    source_table = "reporting_awscostentrylineitem_daily_summary"
    # This is the target table's name (it will be renamed during the conversion to the source table name)
    target_table = f"p_{source_table}"
    # We'll want a new sequence copied from the original sequence
    new_seq = ppart.SequenceDefinition(
        target_schema,
        f"{target_table}_id_seq",
        copy_sequence={"schema_name": target_schema, "table_name": source_table, "column_name": "id"},
    )
    # We want to change the target tables's 'id' column default
    target_identity_col = ppart.ColumnDefinition(target_schema, target_table, "id", default=ppart.Default(new_seq))
    # We also need to include the identity col as part of the primary key definition
    new_pk = ppart.PKDefinition(f"{target_table}_pkey", ["usage_start", "id"])
    # Init the converter
    p_converter = ppart.ConvertToPartition(
        source_table,
        "usage_start",
        target_table_name=target_table,
        partition_type=ppart.PARTITION_RANGE,
        pk_def=new_pk,
        col_def=[target_identity_col],
        target_schema=target_schema,
        source_schema=target_schema,
    )
    # Push the button, Frank.
    p_converter.convert_to_partition()


class Migration(migrations.Migration):

    dependencies = [("api", "0021_db_functions"), ("reporting", "0119_auto_20200707_1934")]

    operations = [
        migrations.AlterModelOptions(name="ocpusagelineitemdailysummary", options={"managed": False}),
        migrations.CreateModel(
            name="PartitionedTable",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("schema_name", models.TextField(validators=[reporting.partition.models.validate_not_empty])),
                ("table_name", models.TextField(validators=[reporting.partition.models.validate_not_empty])),
                (
                    "partition_of_table_name",
                    models.TextField(validators=[reporting.partition.models.validate_not_empty]),
                ),
                ("partition_type", models.TextField(validators=[reporting.partition.models.validate_not_empty])),
                ("partition_col", models.TextField(validators=[reporting.partition.models.validate_not_empty])),
                (
                    "partition_parameters",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        validators=[reporting.partition.models.validate_not_empty]
                    ),
                ),
            ],
            options={"db_table": "partitioned_tables"},
        ),
        migrations.AddIndex(
            model_name="partitionedtable",
            index=models.Index(fields=["schema_name", "table_name"], name="partable_table"),
        ),
        migrations.AddIndex(
            model_name="partitionedtable",
            index=models.Index(fields=["partition_type"], name="partable_partition_type"),
        ),
        migrations.AddIndex(
            model_name="partitionedtable",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["partition_parameters"], name="partable_partition_parameters"
            ),
        ),
        migrations.AlterUniqueTogether(name="partitionedtable", unique_together={("schema_name", "table_name")}),
        migrations.RunPython(code=convert_ocpusage_lids_to_partitioned),
    ]
