# Generated by Django 2.2.14 on 2020-08-06 19:43
from decimal import Decimal

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0123_auto_20200727_2302")]

    operations = [
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="infrastructure_project_raw_cost",
            field=models.DecimalField(decimal_places=15, default=Decimal("0"), max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="infrastructure_raw_cost",
            field=models.DecimalField(decimal_places=15, default=Decimal("0"), max_digits=33, null=True),
        ),
        migrations.RunSQL(
            """
ALTER TABLE reporting_ocpusagelineitem_daily_summary
ALTER COLUMN infrastructure_project_raw_cost set default 0::numeric,
ALTER COLUMN infrastructure_raw_cost set default 0::numeric;
            """
        ),
    ]
