# Generated by Django 2.2.15 on 2020-08-26 18:19
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0129_partitioned_daily_summary")]

    operations = [
        migrations.AlterField(
            model_name="ocpstoragelineitem",
            name="persistentvolumeclaim_capacity_byte_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpstoragelineitem",
            name="persistentvolumeclaim_capacity_bytes",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpstoragelineitem",
            name="persistentvolumeclaim_usage_byte_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpstoragelineitem",
            name="volume_request_storage_byte_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpstoragelineitemdaily",
            name="persistentvolumeclaim_capacity_byte_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpstoragelineitemdaily",
            name="persistentvolumeclaim_capacity_bytes",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpstoragelineitemdaily",
            name="persistentvolumeclaim_usage_byte_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpstoragelineitemdaily",
            name="volume_request_storage_byte_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitem",
            name="node_capacity_cpu_core_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitem",
            name="node_capacity_cpu_cores",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitem",
            name="node_capacity_memory_byte_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitem",
            name="node_capacity_memory_bytes",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitem",
            name="pod_limit_cpu_core_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitem",
            name="pod_limit_memory_byte_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitem",
            name="pod_request_cpu_core_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitem",
            name="pod_request_memory_byte_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitem",
            name="pod_usage_cpu_core_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitem",
            name="pod_usage_memory_byte_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdaily",
            name="cluster_capacity_cpu_core_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdaily",
            name="cluster_capacity_memory_byte_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdaily",
            name="node_capacity_cpu_core_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdaily",
            name="node_capacity_cpu_cores",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdaily",
            name="node_capacity_memory_byte_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdaily",
            name="node_capacity_memory_bytes",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdaily",
            name="pod_limit_cpu_core_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdaily",
            name="pod_limit_memory_byte_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdaily",
            name="pod_request_cpu_core_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdaily",
            name="pod_request_memory_byte_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdaily",
            name="pod_usage_cpu_core_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdaily",
            name="pod_usage_memory_byte_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
    ]
