# Generated by Django 2.2.15 on 2020-08-25 18:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0129_partitioned_daily_summary")]

    operations = [
        migrations.CreateModel(
            name="AWSTagsValues",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=253, unique=True)),
            ],
            options={"db_table": "reporting_awstags_values"},
        ),
        migrations.CreateModel(
            name="AzureTagsValues",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=253, unique=True)),
            ],
            options={"db_table": "reporting_azuretags_values"},
        ),
        migrations.CreateModel(
            name="OCPAWSTagsValues",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=253, unique=True)),
            ],
            options={"db_table": "reporting_ocpawstags_values"},
        ),
        migrations.CreateModel(
            name="OCPAzureTagsValues",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=253, unique=True)),
            ],
            options={"db_table": "reporting_ocpazuretags_values"},
        ),
        migrations.CreateModel(
            name="OCPTagsValues",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=253, unique=True)),
            ],
            options={"db_table": "reporting_ocptags_values"},
        ),
        migrations.AddField(
            model_name="awstagssummary", name="values_mtm", field=models.ManyToManyField(to="reporting.AWSTagsValues")
        ),
        migrations.AddField(
            model_name="azuretagssummary",
            name="values_mtm",
            field=models.ManyToManyField(to="reporting.AzureTagsValues"),
        ),
        migrations.AddField(
            model_name="ocpawstagssummary",
            name="values_mtm",
            field=models.ManyToManyField(to="reporting.OCPAWSTagsValues"),
        ),
        migrations.AddField(
            model_name="ocpazuretagssummary",
            name="values_mtm",
            field=models.ManyToManyField(to="reporting.OCPAzureTagsValues"),
        ),
        migrations.AddField(
            model_name="ocpstoragevolumelabelsummary",
            name="values_mtm",
            field=models.ManyToManyField(to="reporting.OCPTagsValues"),
        ),
        migrations.AddField(
            model_name="ocpusagepodlabelsummary",
            name="values_mtm",
            field=models.ManyToManyField(to="reporting.OCPTagsValues"),
        ),
    ]
