# Generated by Django 2.2.15 on 2020-09-02 16:26
import os

from django.db import migrations

from koku import migration_sql_helpers as msh


def apply_partitioned_table_triggers(apps, schema_editor):
    path = msh.find_db_functions_dir()
    for funcfile in ("partitioned_tables_manage_trigger.sql", "partitioned_tables_active_trigger.sql"):
        msh.apply_sql_file(schema_editor, os.path.join(path, funcfile))


class Migration(migrations.Migration):

    dependencies = [("reporting", "0131_auto_20200827_1253")]

    operations = [migrations.RunPython(code=apply_partitioned_table_triggers)]
