# Generated by Django 2.2.15 on 2020-09-01 18:11
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0131_auto_20200827_1253")]

    operations = [
        migrations.AddField(
            model_name="awstagssummary",
            name="account_alias",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.AWSAccountAlias"
            ),
        ),
        migrations.AddField(
            model_name="awstagssummary", name="usage_account_id", field=models.CharField(max_length=50, null=True)
        ),
        migrations.AddField(
            model_name="ocpawstagssummary",
            name="account_alias",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.AWSAccountAlias"
            ),
        ),
        migrations.AddField(
            model_name="ocpawstagssummary", name="usage_account_id", field=models.CharField(max_length=50, null=True)
        ),
        migrations.AlterField(
            model_name="azuretagssummary", name="subscription_guid", field=models.TextField(null=True)
        ),
        migrations.AlterField(
            model_name="ocpawstagssummary", name="namespace", field=models.CharField(max_length=253, null=True)
        ),
        migrations.AlterField(
            model_name="ocpazuretagssummary", name="namespace", field=models.CharField(max_length=253, null=True)
        ),
        migrations.AlterField(
            model_name="ocpazuretagssummary", name="subscription_guid", field=models.TextField(null=True)
        ),
        migrations.AlterUniqueTogether(
            name="awstagssummary", unique_together={("key", "cost_entry_bill", "usage_account_id")}
        ),
        migrations.AlterUniqueTogether(
            name="azuretagssummary", unique_together={("key", "cost_entry_bill", "subscription_guid")}
        ),
        migrations.AlterUniqueTogether(
            name="ocpawstagssummary", unique_together={("key", "cost_entry_bill", "usage_account_id", "namespace")}
        ),
        migrations.AlterUniqueTogether(
            name="ocpazuretagssummary", unique_together={("key", "cost_entry_bill", "subscription_guid", "namespace")}
        ),
        migrations.RemoveField(model_name="awstagssummary", name="accounts"),
        migrations.RemoveField(model_name="ocpawstagssummary", name="accounts"),
    ]
