# Generated by Django 2.2.15 on 2020-09-01 22:45
import pkgutil

import django.db.models.deletion
from django.db import connection
from django.db import migrations
from django.db import models
from jinjasql import JinjaSql

from koku import pg_partition as ppart


class Migration(migrations.Migration):

    dependencies = [("reporting", "0132_auto_20200901_1811")]

    operations = [
        migrations.RunSQL(
            """
                DELETE FROM reporting_awstags_summary_values_mtm;
                DELETE FROM reporting_azuretags_summary_values_mtm;
                DELETE FROM reporting_ocpawstags_summary_values_mtm;
                DELETE FROM reporting_ocpazuretags_summary_values_mtm;

                DELETE FROM reporting_awstags_summary;
                DELETE FROM reporting_azuretags_summary;
                DELETE FROM reporting_ocpawstags_summary;
                DELETE FROM reporting_ocpazuretags_summary;

                DELETE FROM reporting_awstags_values;
                DELETE FROM reporting_azuretags_values;
                DELETE FROM reporting_ocpawstags_values;
                DELETE FROM reporting_ocpazuretags_values
            """
        )
    ]
