# Generated by Django 2.2.15 on 2020-09-02 16:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0133_auto_20200901_2245")]

    operations = [
        migrations.AlterField(
            model_name="ocpstoragevolumelabelsummary", name="namespace", field=models.CharField(max_length=253)
        ),
        migrations.AlterField(
            model_name="ocpusagepodlabelsummary", name="namespace", field=models.CharField(max_length=253)
        ),
    ]
