# Generated by Django 2.2.15 on 2020-09-02 16:26
import os

from django.db import migrations
from django.db import models

from koku import migration_sql_helpers as msh


def apply_partitioned_table_triggers(apps, schema_editor):
    path = msh.find_db_functions_dir()
    for funcfile in ("partitioned_tables_manage_trigger.sql", "partitioned_tables_active_trigger.sql"):
        msh.apply_sql_file(schema_editor, os.path.join(path, funcfile))


class Migration(migrations.Migration):

    dependencies = [("api", "0028_public_function_update"), ("reporting", "0136_auto_20200909_1400")]

    operations = [
        migrations.AddField(model_name="partitionedtable", name="active", field=models.BooleanField(default=True)),
        migrations.RunSQL(
            """
UPDATE partitioned_tables
   SET active = true
 WHERE active is null;
        """
        ),
        migrations.RunSQL(
            """
ALTER TABLE partitioned_tables
      ALTER COLUMN active SET DEFAULT true;
        """
        ),
        migrations.RunPython(code=apply_partitioned_table_triggers),
    ]
