# Generated by Django 2.2.15 on 2020-09-11 20:31
import pkgutil

from django.db import connection
from django.db import migrations


def add_views(apps, schema_editor):
    """Create database VIEWS from files."""

    for view in ("", "_by_account", "_by_service", "_by_region"):
        view_sql = pkgutil.get_data("reporting.provider.aws", f"sql/views/reporting_aws_compute_summary{view}.sql")
        view_sql = view_sql.decode("utf-8")
        with connection.cursor() as cursor:
            cursor.execute(view_sql)


class Migration(migrations.Migration):

    dependencies = [("reporting", "0138_auto_20200918_1724")]

    operations = [
        migrations.RunSQL(
            """
                DROP MATERIALIZED VIEW reporting_aws_compute_summary;
                DROP MATERIALIZED VIEW reporting_aws_compute_summary_by_account;
                DROP MATERIALIZED VIEW reporting_aws_compute_summary_by_service;
                DROP MATERIALIZED VIEW reporting_aws_compute_summary_by_region;

                ALTER TABLE reporting_awscostentrylineitem_daily_summary DROP COLUMN id;
                ALTER TABLE reporting_awscostentrylineitem_daily_summary ADD COLUMN uuid UUID;
                ALTER TABLE reporting_awscostentrylineitem_daily_summary ADD PRIMARY KEY (usage_start, uuid);
                ALTER TABLE reporting_awscostentrylineitem_daily_summary ALTER COLUMN resource_ids TYPE text[];

                ALTER TABLE reporting_azurecostentrylineitem_daily_summary DROP COLUMN id;
                ALTER TABLE reporting_azurecostentrylineitem_daily_summary ADD COLUMN uuid UUID;
                ALTER TABLE reporting_azurecostentrylineitem_daily_summary ADD PRIMARY KEY (usage_start, uuid);


                ALTER TABLE reporting_ocpusagelineitem_daily_summary DROP COLUMN id;
                ALTER TABLE reporting_ocpusagelineitem_daily_summary ADD COLUMN uuid UUID;
                ALTER TABLE reporting_ocpusagelineitem_daily_summary ADD PRIMARY KEY (usage_start, uuid);
            """
        ),
        migrations.RunPython(add_views),
    ]
