# Generated by Django 2.2.15 on 2020-09-25 13:14
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0138_auto_20200918_1724")]

    operations = [
        migrations.AlterUniqueTogether(
            name="ocpstoragevolumelabelsummary", unique_together={("key", "report_period", "namespace", "node")}
        ),
        migrations.AlterUniqueTogether(
            name="ocpusagepodlabelsummary", unique_together={("key", "report_period", "namespace", "node")}
        ),
    ]
