# Generated by Django 2.2.15 on 2020-09-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0138_auto_20200918_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azurecostentrylineitemdaily',
            name='offer_id',
        ),
        migrations.RemoveField(
            model_name='ocpazurecostlineitemdailysummary',
            name='offer_id',
        ),
        migrations.RemoveField(
            model_name='ocpazurecostlineitemprojectdailysummary',
            name='offer_id',
        ),
        migrations.RunSQL(
            """
            ALTER TABLE reporting_azurecostentrylineitem_daily_summary DROP COLUMN offer_id;
            """
        )
    ]
