# Generated by Django 2.2.15 on 2020-09-25 18:25
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0139_auto_20200925_1432")]

    operations = [
        migrations.RemoveField(model_name="azurecostentrylineitemdaily", name="offer_id"),
        migrations.RemoveField(model_name="ocpazurecostlineitemdailysummary", name="offer_id"),
        migrations.RemoveField(model_name="ocpazurecostlineitemprojectdailysummary", name="offer_id"),
        migrations.RunSQL(
            """
            ALTER TABLE reporting_azurecostentrylineitem_daily_summary DROP COLUMN offer_id;
            """
        ),
    ]
