# Generated by Django 2.2.16 on 2020-10-02 19:25
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0140_auto_20200925_1825")]

    operations = [
        migrations.AlterUniqueTogether(name="ocpstoragevolumelabelsummary", unique_together=set()),
        migrations.AlterUniqueTogether(name="ocpusagepodlabelsummary", unique_together=set()),
    ]
