# Generated by Django 2.2.16 on 2020-09-28 13:41
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0029_auto_20200921_2016"), ("reporting", "0140_auto_20200925_1825")]

    operations = [
        migrations.AddField(
            model_name="awsorganizationalunit",
            name="provider",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Provider"),
        )
    ]
