# Generated by Django 2.2.16 on 2020-10-02 18:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0141_auto_20200917_1448")]

    operations = [
        migrations.AlterField(
            model_name="awscostentrybill", name="bill_type", field=models.CharField(max_length=50, null=True)
        ),
        migrations.AlterField(
            model_name="awscostentrybill", name="payer_account_id", field=models.CharField(max_length=50, null=True)
        ),
    ]
