# Generated by Django 3.1.2 on 2020-10-05 15:08
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations
from django.db import models

import reporting.partition.models


class Migration(migrations.Migration):

    dependencies = [("api", "0029_auto_20200921_2016"), ("reporting", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="awsorganizationalunit",
            name="provider",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"),
        ),
        migrations.AlterField(
            model_name="partitionedtable",
            name="partition_parameters",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                validators=[reporting.partition.models.validate_not_empty]
            ),
        ),
    ]
