# Generated by Django 3.1.2 on 2020-10-19 01:30
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0144_auto_20201007_1441")]

    operations = [
        migrations.CreateModel(
            name="AWSEnabledTagKeys",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=253, unique=True)),
            ],
            options={"db_table": "reporting_awsenabledtagkeys"},
        ),
        migrations.CreateModel(
            name="AzureEnabledTagKeys",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=253, unique=True)),
            ],
            options={"db_table": "reporting_azureenabledtagkeys"},
        ),
    ]
