# Generated by Django 3.1.2 on 2020-10-26 18:45
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0145_awsenabledtagkeys_azureenabledtagkeys")]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO reporting_awsenabledtagkeys(key)
            SELECT DISTINCT(key)
            FROM reporting_awstags_summary
            ON CONFLICT (key) DO NOTHING;
            """
        )
    ]
