# Generated by Django 3.1.2 on 2020-10-28 13:05
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0146_auto_20200917_1448")]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO reporting_awsenabledtagkeys(key)
            SELECT DISTINCT(key)
            FROM reporting_awstags_summary
            ON CONFLICT (key) DO NOTHING;
            """
        )
    ]
