# Generated by Django 3.1.2 on 2020-10-30 19:22
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0147_auto_20201028_1305")]

    operations = [
        migrations.RunSQL(
            """
create table if not exists presto_pk_delete_wrapper_log (
    transaction_id text not null,
    action_ts timestamptz not null default now(),
    table_name text not null,
    pk_column text not null,
    pk_value text not null,
    pk_value_cast text not null
);

create index presto_pk_delete_wrapper_log_tx on presto_pk_delete_wrapper_log (transaction_id, table_name);
"""
        )
    ]
