# Generated by Django 3.1.3 on 2020-11-16 18:14
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0149_auto_20201112_1414")]

    operations = [
        migrations.RemoveField(model_name="gcpproject", name="project_number"),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="conversion_rate",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="cost_type",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="country",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="credits",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="export_time",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="invoice_month",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="labels",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="location",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="region",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="system_labels",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="usage_amount",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="usage_pricing_unit",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="usage_to_pricing_units",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="usage_unit",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="zone",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="gcpcostentrylineitemdaily",
            name="currency",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="gcpcostentrylineitemdaily",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="gcpcostentrylineitemdaily",
            name="line_item_type",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(name="gcpcostentrylineitemdaily", unique_together=set()),
        migrations.AlterModelTable(name="gcpcostentrylineitemdaily", table="reporting_gcpcostentrylineitemdaily"),
        migrations.CreateModel(
            name="GCPCostEntryProductService",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("service_id", models.CharField(max_length=256, null=True)),
                ("service_alias", models.CharField(blank=True, max_length=256, null=True)),
                ("sku_id", models.CharField(max_length=256, null=True)),
                ("sku_alias", models.CharField(max_length=256, null=True)),
            ],
            options={
                "db_table": "reporting_gcpcostentryproductservice",
                "unique_together": {("service_id", "service_alias", "sku_id", "sku_alias")},
            },
        ),
        migrations.RemoveField(model_name="gcpcostentrylineitemdaily", name="consumption"),
        migrations.RemoveField(model_name="gcpcostentrylineitemdaily", name="description"),
        migrations.RemoveField(model_name="gcpcostentrylineitemdaily", name="measurement_type"),
        migrations.RemoveField(model_name="gcpcostentrylineitemdaily", name="unit"),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="cost_entry_product",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.gcpcostentryproductservice"
            ),
        ),
    ]
