# Generated by Django 3.1.3 on 2020-11-17 21:03
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0154_auto_20201116_1855")]

    operations = [
        migrations.RemoveField(model_name="ocpawscostlineitemdailysummary", name="id"),
        migrations.RemoveField(model_name="ocpawscostlineitemdailysummary", name="pod"),
        migrations.RemoveField(model_name="ocpawscostlineitemprojectdailysummary", name="pod"),
        migrations.RemoveField(model_name="ocpazurecostlineitemdailysummary", name="id"),
        migrations.AddField(
            model_name="ocpawscostlineitemdailysummary",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="ocpazurecostlineitemdailysummary",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(model_name="ocpawscostlineitemprojectdailysummary", name="id"),
        migrations.RemoveField(model_name="ocpazurecostlineitemprojectdailysummary", name="id"),
        migrations.AddField(
            model_name="ocpawscostlineitemprojectdailysummary",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="ocpazurecostlineitemprojectdailysummary",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
