# Generated by Django 3.1.3 on 2020-11-20 19:01
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0159_gcp_cost_summary")]

    operations = [
        migrations.RemoveField(model_name="ocpazurecostlineitemdailysummary", name="pod"),
        migrations.RemoveField(model_name="ocpazurecostlineitemprojectdailysummary", name="pod"),
    ]
