# Generated by Django 3.1.3 on 2020-11-20 19:01
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0160_auto_20210114_1548")]

    operations = [
        migrations.RemoveField(model_name="ocpazurecostlineitemdailysummary", name="pod"),
        migrations.RemoveField(model_name="ocpazurecostlineitemprojectdailysummary", name="pod"),
    ]
