# Generated by Django 3.1.3 on 2021-01-18 21:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0160_auto_20210114_1548")]

    operations = [
        migrations.AlterField(
            model_name="gcpcostentrylineitemdaily",
            name="usage_amount",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        )
    ]
