# Generated by Django 3.1.5 on 2021-01-25 02:08
import os

from django.db import migrations

from koku import pg_partition as ppart


def partition_default_data(apps, schema_editor):
    template_schema = _TEMPLATE_SCHEMA = os.environ.get("TEMPLATE_SCHEMA", "template0")
    schema = ppart.resolve_schema(ppart.CURRENT_SCHEMA)

    # There should *never* be data in the template schema but we don't want to waste cycles there either
    if schema != template_schema:
        ppart.repartition_default_data(schema_name=schema)


class Migration(migrations.Migration):

    dependencies = [
        (
            "reporting",
            "0164_gcpcomputesummary_gcpcomputesummarybyaccount_gcpcomputesummarybyproject_gcpcomputesummarybyregion_gc",
        )
    ]

    operations = [migrations.RunPython(code=partition_default_data)]
