# Generated by Django 3.1.5 on 2021-01-21 18:08
import pkgutil

import django.contrib.postgres.fields
from django.db import connection
from django.db import migrations
from django.db import models


def add_gcp_storage_views(apps, schema_editor):
    """Create the GCP Materialized views from files."""

    for view in ("", "_by_project", "_by_account", "_by_service", "_by_region"):
        view_sql = pkgutil.get_data("reporting.provider.gcp", f"sql/views/reporting_gcp_storage_summary{view}.sql")
        view_sql = view_sql.decode("utf-8")
        with connection.cursor() as cursor:
            cursor.execute(view_sql)


class Migration(migrations.Migration):

    dependencies = [("reporting", "0165_repartition_default_data")]
    operations = [
        migrations.RunPython(add_gcp_storage_views),
        migrations.CreateModel(
            name="GCPStorageSummary",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
                ("source_uuid", models.UUIDField(null=True)),
            ],
            options={"db_table": "reporting_gcp_storage_summary", "managed": False},
        ),
        migrations.CreateModel(
            name="GCPStorageSummaryByAccount",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("instance_type", models.CharField(max_length=50, null=True)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
                ("source_uuid", models.UUIDField(null=True)),
                ("account_id", models.CharField(max_length=50)),
            ],
            options={"db_table": "reporting_gcp_storage_summary_by_account", "managed": False},
        ),
        migrations.CreateModel(
            name="GCPStorageSummaryByProject",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
                ("source_uuid", models.UUIDField(null=True)),
                ("project_id", models.CharField(max_length=256, unique=True)),
                ("project_name", models.CharField(max_length=256)),
                ("account_id", models.CharField(max_length=50)),
            ],
            options={"db_table": "reporting_gcp_storage_summary_by_project", "managed": False},
        ),
        migrations.CreateModel(
            name="GCPStorageSummaryByRegion",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("instance_type", models.CharField(max_length=50, null=True)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
                ("source_uuid", models.UUIDField(null=True)),
                ("account_id", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=50, null=True)),
            ],
            options={"db_table": "reporting_gcp_storage_summary_by_region", "managed": False},
        ),
        migrations.CreateModel(
            name="GCPStorageSummaryByService",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
                ("source_uuid", models.UUIDField(null=True)),
                ("service_id", models.CharField(max_length=256, null=True)),
                ("service_alias", models.CharField(blank=True, max_length=256, null=True)),
                ("account_id", models.CharField(max_length=50)),
            ],
            options={"db_table": "reporting_gcp_storage_summary_by_service", "managed": False},
        ),
    ]
