# Generated by Django 3.1.6 on 2021-02-08 15:18
import pkgutil

import django.contrib.postgres.fields
from django.db import connection
from django.db import migrations
from django.db import models


def add_gcp_views(apps, schema_editor):
    """Create the GCP Materialized views from files."""
    views = ("reporting_gcp_network_summary", "reporting_gcp_database_summary")
    for view in views:
        view_sql = pkgutil.get_data("reporting.provider.gcp", f"sql/views/{view}.sql")
        view_sql = view_sql.decode("utf-8")
        with connection.cursor() as cursor:
            cursor.execute(view_sql)


class Migration(migrations.Migration):

    dependencies = [("reporting", "0165_repartition_default_data")]

    operations = [
        migrations.CreateModel(
            name="GCPDatabaseSummary",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("account_id", models.CharField(max_length=50)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
                ("source_uuid", models.UUIDField(null=True)),
            ],
            options={"db_table": "reporting_gcp_database_summary", "managed": False},
        ),
        migrations.CreateModel(
            name="GCPNetworkSummary",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("account_id", models.CharField(max_length=50)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
                ("source_uuid", models.UUIDField(null=True)),
            ],
            options={"db_table": "reporting_gcp_network_summary", "managed": False},
        ),
        migrations.RunPython(add_gcp_views),
    ]
