# Generated by Django 3.1.6 on 2021-02-10 19:18
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0166_gcp_storage_summary")]

    operations = [
        migrations.RemoveField(model_name="gcpcostentrylineitem", name="usage_amount"),
        migrations.RemoveField(model_name="gcpcostentrylineitem", name="usage_unit"),
        migrations.RemoveField(model_name="gcpcostentrylineitemdaily", name="usage_amount"),
        migrations.RemoveField(model_name="gcpcostentrylineitemdaily", name="usage_unit"),
    ]
