# Generated by Django 3.1.6 on 2021-02-09 21:08
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0166_gcp_storage_summary")]

    operations = [
        migrations.AlterField(
            model_name="gcpcostentrylineitem",
            name="usage_amount",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        )
    ]
