# Generated by Django 3.1.6 on 2021-02-16 14:48
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0168_auto_20210211_2210")]

    operations = [
        migrations.RunSQL(
            """
                DROP INDEX gcp_cost_summary_project;

                CREATE UNIQUE INDEX gcp_cost_summary_project
                ON reporting_gcp_cost_summary_by_project (usage_start, project_id, project_name, account_id)
                ;
            """
        )
    ]
