# Generated by Django 3.1.6 on 2021-02-16 14:48
import pkgutil

from django.db import connection
from django.db import migrations


def add_gcp_views(apps, schema_editor):
    """Create the GCP Materialized views from files."""
    view_sql = pkgutil.get_data("reporting.provider.gcp", f"sql/views/reporting_gcp_cost_summary_by_project.sql")
    view_sql = view_sql.decode("utf-8")
    with connection.cursor() as cursor:
        cursor.execute(view_sql)


class Migration(migrations.Migration):

    dependencies = [("reporting", "0168_auto_20210211_2210")]

    operations = [migrations.RunPython(add_gcp_views)]
