# Generated by Django 3.1.7 on 2021-03-05 16:59
import pkgutil

from django.db import connection
from django.db import migrations


def update_ocp_all_view(apps, schema_editor):
    """Reload and account for change in ocp/all storage mat view SQL."""
    view_sql = pkgutil.get_data("reporting.provider.all.openshift", f"sql/views/reporting_ocpall_storage_summary.sql")
    view_sql = view_sql.decode("utf-8")
    with connection.cursor() as cursor:
        cursor.execute(view_sql)


class Migration(migrations.Migration):

    dependencies = [("reporting", "0169_auto_20210216_1448")]

    operations = [migrations.RunPython(update_ocp_all_view)]
