# Generated by Django 3.1.7 on 2021-04-19 18:03
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0042_reapply_clone_func"), ("reporting", "0175_auto_20210407_2043")]

    operations = [
        migrations.CreateModel(
            name="OCPCluster",
            fields=[
                ("cluster_id", models.TextField(primary_key=True, serialize=False)),
                ("cluster_alias", models.TextField(null=True)),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.provider")),
            ],
            options={"db_table": "reporting_ocp_clusters"},
        ),
        migrations.CreateModel(
            name="OCPPVC",
            fields=[
                ("pvc", models.TextField(primary_key=True, serialize=False)),
                ("cluster", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.ocpcluster")),
            ],
            options={"db_table": "reporting_ocp_pvcs"},
        ),
        migrations.CreateModel(
            name="OCPProject",
            fields=[
                ("project", models.TextField(primary_key=True, serialize=False)),
                ("cluster", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.ocpcluster")),
            ],
            options={"db_table": "reporting_ocp_projects"},
        ),
        migrations.CreateModel(
            name="OCPNode",
            fields=[
                ("node", models.TextField(primary_key=True, serialize=False)),
                ("resource_id", models.TextField(null=True)),
                ("cluster", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.ocpcluster")),
            ],
            options={"db_table": "reporting_ocp_nodes"},
        ),
    ]
