# Generated by Django 3.1.7 on 2021-04-13 15:23
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0175_auto_20210407_2043")]

    operations = [
        migrations.RemoveField(model_name="awsenabledtagkeys", name="id"),
        migrations.AddField(model_name="awsenabledtagkeys", name="enabled", field=models.BooleanField(default=True)),
        migrations.AlterField(
            model_name="awsenabledtagkeys",
            name="key",
            field=models.CharField(max_length=253, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name="awsenabledtagkeys", index=models.Index(fields=["key", "enabled"], name="aws_enabled_key_index")
        ),
        migrations.RunSQL(
            """
alter table reporting_awsenabledtagkeys alter column enabled set default true;
"""
        ),
    ]
