# Generated by Django 3.1.8 on 2021-04-22 19:42
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0176_update_aws_enabled_keys")]

    operations = [
        migrations.AddField(model_name="azureenabledtagkeys", name="enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="gcpenabledtagkeys", name="enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="ocpenabledtagkeys", name="enabled", field=models.BooleanField(default=True)),
        migrations.RunSQL(
            """
alter table reporting_azureenabledtagkeys
alter column enabled set default true;
"""
        ),
        migrations.RunSQL(
            """
alter table reporting_gcpenabledtagkeys
alter column enabled set default true;
"""
        ),
        migrations.RunSQL(
            """
alter table reporting_ocpenabledtagkeys
alter column enabled set default true;
"""
        ),
    ]
