# Generated by Django 3.1.7 on 2021-05-06 16:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0176_update_aws_enabled_keys")]

    operations = [
        migrations.AddField(
            model_name="ocpawscostlineitemprojectdailysummary",
            name="persistentvolume",
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemprojectdailysummary",
            name="persistentvolumeclaim",
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemprojectdailysummary",
            name="storageclass",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ocpazurecostlineitemprojectdailysummary",
            name="persistentvolume",
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name="ocpazurecostlineitemprojectdailysummary",
            name="persistentvolumeclaim",
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name="ocpazurecostlineitemprojectdailysummary",
            name="storageclass",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
