# Generated by Django 3.1.7 on 2021-05-11 18:51
# import pkgutil
from django.db import migrations

# from reporting.provider.all.openshift.models import VIEWS as OCP_ALL_VIEWS


# def add_views(apps, schema_editor):
#     """Create database VIEWS from files."""
#     connection = schema_editor.connection
#     for view in OCP_ALL_VIEWS:
#         view_sql = pkgutil.get_data("reporting.provider.all.openshift", f"sql/views/{view}.sql")
#         view_sql = view_sql.decode("utf-8")
#         with connection.cursor() as cursor:
#             cursor.execute(view_sql)


def no_op(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("reporting", "0177_auto_20210506_1650")]

    operations = [
        # migrations.RunSQL("""DROP MATERIALIZED VIEW reporting_ocpallcostlineitem_daily_summary CASCADE;"""),
        migrations.RunPython(no_op)
    ]
