# Generated by Django 3.1.10 on 2021-05-14 17:51
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0178_auto_20210511_1851")]

    operations = [
        migrations.RunSQL(
            """
DROP INDEX "ocpall_cost_daily_summary";

CREATE UNIQUE INDEX ocpall_cost_daily_summary ON reporting_ocpallcostlineitem_daily_summary (
   source_type, cluster_id, node, resource_id, usage_start, usage_account_id, product_code,
   product_family, instance_type, region, availability_zone, (jsonb_sha256_text(tags))
);
"""
        )
    ]
