# Generated by Django 3.1.7 on 2021-05-25 16:41
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0180_ocpcluster_ocpnode_ocpproject_ocppvc")]

    operations = [
        migrations.AddField(
            model_name="ocpawscostlineitemprojectdailysummary", name="tags", field=models.JSONField(null=True)
        ),
        migrations.AddField(
            model_name="ocpazurecostlineitemprojectdailysummary", name="tags", field=models.JSONField(null=True)
        ),
    ]
