# Generated by Django 3.1.12 on 2021-07-13 11:11
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0181_auto_20210525_1641")]

    operations = [
        migrations.AlterField(
            model_name="awscostentrylineitem",
            name="cost_entry",
            field=models.ForeignKey(
                db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="reporting.awscostentry"
            ),
        ),
        migrations.AlterField(
            model_name="awscostentrylineitem",
            name="cost_entry_bill",
            field=models.ForeignKey(
                db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="reporting.awscostentrybill"
            ),
        ),
        migrations.AlterField(
            model_name="awscostentrylineitem",
            name="cost_entry_pricing",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reporting.awscostentrypricing",
            ),
        ),
        migrations.AlterField(
            model_name="awscostentrylineitem",
            name="cost_entry_product",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reporting.awscostentryproduct",
            ),
        ),
        migrations.AlterField(
            model_name="awscostentrylineitem",
            name="cost_entry_reservation",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reporting.awscostentryreservation",
            ),
        ),
        migrations.AlterField(
            model_name="gcpcostentrylineitem",
            name="cost_entry_bill",
            field=models.ForeignKey(
                db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="reporting.gcpcostentrybill"
            ),
        ),
        migrations.AlterField(
            model_name="gcpcostentrylineitem",
            name="cost_entry_product",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.gcpcostentryproductservice",
            ),
        ),
        migrations.AlterField(
            model_name="gcpcostentrylineitem",
            name="project",
            field=models.ForeignKey(
                db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="reporting.gcpproject"
            ),
        ),
        migrations.AlterField(
            model_name="ocpnodelabellineitem",
            name="report",
            field=models.ForeignKey(
                db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="reporting.ocpusagereport"
            ),
        ),
        migrations.AlterField(
            model_name="ocpnodelabellineitem",
            name="report_period",
            field=models.ForeignKey(
                db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="reporting.ocpusagereportperiod"
            ),
        ),
        migrations.AlterField(
            model_name="ocpstoragelineitem",
            name="report",
            field=models.ForeignKey(
                db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="reporting.ocpusagereport"
            ),
        ),
        migrations.AlterField(
            model_name="ocpstoragelineitem",
            name="report_period",
            field=models.ForeignKey(
                db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="reporting.ocpusagereportperiod"
            ),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitem",
            name="report",
            field=models.ForeignKey(
                db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="reporting.ocpusagereport"
            ),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitem",
            name="report_period",
            field=models.ForeignKey(
                db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="reporting.ocpusagereportperiod"
            ),
        ),
    ]
