# Generated by Django 3.1.10 on 2021-05-13 16:46
import os

from django.db import migrations

from koku import migration_sql_helpers as msh


def update_partitioned_tables_trigger(apps, schema_editor):
    path = msh.find_db_functions_dir()
    for funcfile in ("partitioned_manage_trigger.sql",):
        msh.apply_sql_file(schema_editor, os.path.join(path, funcfile))


class Migration(migrations.Migration):

    dependencies = [("reporting", "0182_drop_constraints")]

    operations = [
        migrations.RunSQL(
            """
DROP TRIGGER IF EXISTS tr_attach_date_range_partition ON partitioned_tables;
DROP TRIGGER IF EXISTS tr_manage_date_range_partition ON partitioned_tables;
"""
        ),
        migrations.RunPython(code=update_partitioned_tables_trigger),
    ]
