# Generated by Django 3.1.12 on 2021-06-14 18:04
import pkgutil

import django.contrib.postgres.fields.jsonb
from django.db import connection
from django.db import migrations
from django.db import models


def add_ocp_cost_views(apps, schema_editor):
    """Create the OCP Materialized views from files."""
    version = "_20210615"
    views = {
        f"sql/views/{version}/reporting_ocp_cost_summary": ["", "_by_node", "_by_project"],
        f"sql/views/{version}/reporting_ocp_pod_summary": ["", "_by_project"],
        f"sql/views/{version}/reporting_ocp_volume_summary": ["", "_by_project"],
    }
    for base_path, view_tuple in views.items():
        for view in view_tuple:
            view_sql = pkgutil.get_data("reporting.provider.ocp", f"{base_path}{view}{version}.sql")
            view_sql = view_sql.decode("utf-8")
            with connection.cursor() as cursor:
                cursor.execute(view_sql)


class Migration(migrations.Migration):

    dependencies = [("reporting", "0182_drop_constraints")]

    operations = [
        migrations.RunSQL(
            """
                DROP INDEX IF EXISTS ocp_cost_summary;
                DROP MATERIALIZED VIEW IF EXISTS reporting_ocp_cost_summary;
                DROP INDEX IF EXISTS ocp_cost_summary_by_node;
                DROP MATERIALIZED VIEW IF EXISTS reporting_ocp_cost_summary_by_node;
                DROP INDEX IF EXISTS ocp_cost_summary_by_project;
                DROP MATERIALIZED VIEW IF EXISTS reporting_ocp_cost_summary_by_project;

                ALTER TABLE reporting_ocpusagelineitem_daily_summary ADD COLUMN supplementary_monthly_cost_json jsonb;
                ALTER TABLE reporting_ocpusagelineitem_daily_summary ADD COLUMN infrastructure_monthly_cost_json jsonb;
                ALTER TABLE reporting_ocpusagelineitem_daily_summary ADD COLUMN infrastructure_project_monthly_cost jsonb;
                ALTER TABLE reporting_ocpusagelineitem_daily_summary ADD COLUMN supplementary_project_monthly_cost jsonb;
            """
        ),
        migrations.RunPython(add_ocp_cost_views),
    ]
