#
# Copyright 2021 Red Hat Inc.
# SPDX-License-Identifier: Apache-2.0
#
# Generated by Django 3.1.10 on 2021-06-03 16:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0184_new_partition_manager_trigger")]

    operations = [
        migrations.AlterModelOptions(name="ocpazurecostlineitemdailysummary", options={"managed": False}),
        migrations.AddField(model_name="partitionedtable", name="subpartition_col", field=models.TextField(null=True)),
        migrations.AddField(
            model_name="partitionedtable", name="subpartition_type", field=models.TextField(null=True)
        ),
    ]
