#
# Copyright 2021 Red Hat Inc.
# SPDX-License-Identifier: Apache-2.0
#
# Generated by Django 3.1.10 on 2021-05-17 19:48
import logging

from django.db import migrations

LOG = logging.getLogger(__name__)


def deferred_message(apps, schema_editor):
    LOG.warning(f"MIGRATION 0186_partition_ocp_on_x_tables has beed deferred")


class Migration(migrations.Migration):

    dependencies = [("reporting", "0185_subpartition_cols")]

    operations = [migrations.RunPython(deferred_message)]
