# Generated by Django 3.1.13 on 2021-09-07 19:07
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0191_currencysettings")]

    operations = [
        migrations.CreateModel(
            name="GCPTopology",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("source_uuid", models.UUIDField(null=True)),
                ("account_id", models.TextField()),
                ("project_id", models.TextField()),
                ("project_name", models.TextField()),
                ("service_id", models.TextField()),
                ("service_alias", models.TextField()),
                ("region", models.TextField()),
            ],
            options={"db_table": "reporting_gcp_topology"},
        )
    ]
