# Generated by Django 3.1.12 on 2021-09-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0191_currencysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscostentrylineitemdailysummary',
            name='savingsplan_effective_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
    ]
