# Generated by Django 3.1.12 on 2021-06-25 13:16
import pkgutil

from django.db import connection
from django.db import migrations
from django.db import models


def add_gcp_views(apps, schema_editor):
    """Create the GCP Materialized views from files."""
    version = "_20210816"
    views = {
        f"sql/views/{version}/reporting_gcp_compute_summary": [
            "",
            "_by_account",
            "_by_project",
            "_by_region",
            "_by_service",
        ],
        f"sql/views/{version}/reporting_gcp_cost_summary": [
            "",
            "_by_account",
            "_by_project",
            "_by_region",
            "_by_service",
        ],
        f"sql/views/{version}/reporting_gcp_storage_summary": [
            "",
            "_by_account",
            "_by_project",
            "_by_region",
            "_by_service",
        ],
        f"sql/views/{version}/reporting_gcp_database_summary": [""],
        f"sql/views/{version}/reporting_gcp_network_summary": [""],
    }
    for base_path, view_tuple in views.items():
        for view in view_tuple:
            view_sql = pkgutil.get_data("reporting.provider.gcp", f"{base_path}{view}{version}.sql")
            view_sql = view_sql.decode("utf-8")
            with connection.cursor() as cursor:
                cursor.execute(view_sql)


class Migration(migrations.Migration):

    dependencies = [("reporting", "0191_currencysettings")]

    operations = [
        migrations.AddField(
            model_name="gcpcostentrylineitem", name="partition_date", field=models.DateTimeField(null=True)
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdailysummary",
            name="credit_amount",
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="credit_amount",
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=24, null=True),
        ),
        migrations.RunPython(add_gcp_views),
    ]
