# Generated by Django 3.1.12 on 2021-06-25 13:16
import pkgutil

from django.db import connection
from django.db import migrations
from django.db import models


def add_gcp_views(apps, schema_editor):
    """no-op."""
    pass


class Migration(migrations.Migration):

    dependencies = [("reporting", "0191_currencysettings")]

    operations = [
        migrations.AddField(
            model_name="gcpcostentrylineitem", name="partition_date", field=models.DateTimeField(null=True)
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdailysummary",
            name="credit_amount",
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="gcpcostentrylineitemdaily",
            name="credit_amount",
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=24, null=True),
        ),
        migrations.RunPython(add_gcp_views),
    ]
