# Generated by Django 3.1.13 on 2021-09-20 13:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0192_gcp_bigquery_partition")]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"))],
            options={"db_table": "user_settings"},
        )
    ]
