# Generated by Django 3.1.12 on 2021-09-09 14:23
import pkgutil

from django.db import connection
from django.db import migrations
from django.db import models


def add_aws_views(apps, schema_editor):
    """no-op"""
    pass


class Migration(migrations.Migration):

    dependencies = [("reporting", "0193_gcptopology")]

    operations = [
        migrations.AddField(
            model_name="awscostentrylineitemdailysummary",
            name="savingsplan_effective_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.RunPython(add_aws_views),
    ]
