# Generated by Django 3.1.13 on 2021-09-14 18:22

import logging
import os
from re import L

from django.conf import settings
from django.db import migrations
from django.db.utils import ProgrammingError
from psycopg2.errors import DuplicateObject
from psycopg2.errors import InsufficientPrivilege

import koku.presto_database as kpdb

LOG = logging.getLogger(__name__)

def migrate_presto(apps, schema_editor):
    db_password = settings.DATABASES.get("default").get("PASSWORD")
    table_names = ["aws_line_items", "aws_line_items_daily", "aws_openshift_daily"]
    column_name = "savingsplan_effective_cost"
    schema = "acct10001"
    presto_conn = False

    try:
        presto_conn = kpdb.connect(schema=schema)
        presto_cur = presto_conn.cursor()
        for table_name in table_names:
            try:
                LOG.info(f"Creating column {column_name} in {table_name}.")
                presto_cur.execute(f"""
                    ALTER TABLE "{table_name}" ADD COLUMNS "{column_name}";
                """, None)
            except (ProgrammingError, InsufficientPrivilege, DuplicateObject) as e:
                LOG.info(e)
    finally:
        if presto_conn:
            presto_conn.close()

class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0194_awscostentrylineitemdailysummary_savingsplan_effective_cost'),
    ]

    operations = [
        migrations.RunPython(migrate_presto)
    ]
