# Generated by Django 3.1.13 on 2021-10-01 22:48
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations
from django.db import models

from koku.database import set_pg_extended_mode
from koku.database import unset_pg_extended_mode


class Migration(migrations.Migration):

    dependencies = [("reporting", "0195_ocpall_add_source_fk")]

    operations = [
        migrations.RunPython(set_pg_extended_mode, reverse_code=unset_pg_extended_mode),
        migrations.CreateModel(
            name="OCPAllComputeSummaryPT",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("usage_account_id", models.CharField(max_length=50)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("product_code", models.CharField(max_length=50)),
                ("instance_type", models.CharField(max_length=50)),
                ("resource_id", models.CharField(max_length=253)),
                ("usage_amount", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("currency_code", models.CharField(max_length=10, null=True)),
                ("source_uuid", models.UUIDField(null=True)),
            ],
            options={"db_table": "reporting_ocpall_compute_summary_pt"},
        ),
        migrations.CreateModel(
            name="OCPAllCostSummaryByAccountPT",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("usage_account_id", models.CharField(max_length=50)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                ("source_uuid", models.UUIDField(null=True)),
            ],
            options={"db_table": "reporting_ocpall_cost_summary_by_account_pt"},
        ),
        migrations.CreateModel(
            name="OCPAllCostSummaryByRegionPT",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("usage_account_id", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=50, null=True)),
                ("availability_zone", models.CharField(max_length=50, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                ("source_uuid", models.UUIDField(null=True)),
            ],
            options={"db_table": "reporting_ocpall_cost_summary_by_region_pt"},
        ),
        migrations.CreateModel(
            name="OCPAllCostSummaryByServicePT",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("usage_account_id", models.CharField(max_length=50)),
                ("product_code", models.CharField(max_length=50)),
                ("product_family", models.CharField(max_length=150, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                ("source_uuid", models.UUIDField(null=True)),
            ],
            options={"db_table": "reporting_ocpall_cost_summary_by_service_pt"},
        ),
        migrations.CreateModel(
            name="OCPAllCostSummaryPT",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                ("source_uuid", models.UUIDField(null=True)),
            ],
            options={"db_table": "reporting_ocpall_cost_summary_pt"},
        ),
        migrations.CreateModel(
            name="OCPAllDatabaseSummaryPT",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("usage_account_id", models.CharField(max_length=50)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("product_code", models.CharField(max_length=50)),
                ("usage_amount", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("currency_code", models.CharField(max_length=10, null=True)),
                ("source_uuid", models.UUIDField(null=True)),
            ],
            options={"db_table": "reporting_ocpall_database_summary_pt"},
        ),
        migrations.CreateModel(
            name="OCPAllNetworkSummaryPT",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("usage_account_id", models.CharField(max_length=50)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("product_code", models.CharField(max_length=50)),
                ("usage_amount", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("currency_code", models.CharField(max_length=10, null=True)),
                ("source_uuid", models.UUIDField(null=True)),
            ],
            options={"db_table": "reporting_ocpall_network_summary_pt"},
        ),
        migrations.CreateModel(
            name="OCPAllStorageSummaryPT",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("usage_account_id", models.CharField(max_length=50)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("product_family", models.CharField(max_length=150, null=True)),
                ("product_code", models.CharField(max_length=50)),
                ("usage_amount", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("currency_code", models.CharField(max_length=10, null=True)),
                ("source_uuid", models.UUIDField(null=True)),
            ],
            options={"db_table": "reporting_ocpall_storage_summary_pt"},
        ),
        migrations.RemoveIndex(model_name="ocpallcostlineitemprojectdailysummaryp", name="ocpallp_p_proj_usage_idx"),
        migrations.RemoveIndex(
            model_name="ocpallcostlineitemprojectdailysummaryp", name="ocpallp_p_proj_namespace_idx"
        ),
        migrations.RemoveIndex(model_name="ocpallcostlineitemprojectdailysummaryp", name="ocpallp_p_proj_node_idx"),
        migrations.RemoveIndex(
            model_name="ocpallcostlineitemprojectdailysummaryp", name="ocpallp_p_proj_resource_idx"
        ),
        migrations.RemoveIndex(
            model_name="ocpallcostlineitemprojectdailysummaryp", name="ocpallp_p_proj_pod_labels_idx"
        ),
        migrations.RemoveIndex(
            model_name="ocpallcostlineitemprojectdailysummaryp", name="ocpallp_p_proj_prod_fam_idx"
        ),
        migrations.RemoveIndex(
            model_name="ocpallcostlineitemprojectdailysummaryp", name="ocpallp_p_proj_inst_type_idx"
        ),
        migrations.AddIndex(
            model_name="ocpallcostlineitemprojectdailysummaryp",
            index=models.Index(fields=["usage_start"], name="ocpap_p_proj_usage_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpallcostlineitemprojectdailysummaryp",
            index=models.Index(fields=["namespace"], name="ocpap_p_proj_namespace_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpallcostlineitemprojectdailysummaryp",
            index=models.Index(fields=["node"], name="ocpap_p_proj_node_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpallcostlineitemprojectdailysummaryp",
            index=models.Index(fields=["resource_id"], name="ocpap_p_proj_resource_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpallcostlineitemprojectdailysummaryp",
            index=django.contrib.postgres.indexes.GinIndex(fields=["pod_labels"], name="ocpap_p_proj_pod_labels_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpallcostlineitemprojectdailysummaryp",
            index=models.Index(fields=["product_family"], name="ocpap_p_proj_prod_fam_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpallcostlineitemprojectdailysummaryp",
            index=models.Index(fields=["instance_type"], name="ocpap_p_proj_inst_type_idx"),
        ),
        migrations.AddField(
            model_name="ocpallstoragesummarypt",
            name="account_alias",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="reporting.awsaccountalias"
            ),
        ),
        migrations.AddField(
            model_name="ocpallnetworksummarypt",
            name="account_alias",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="reporting.awsaccountalias"
            ),
        ),
        migrations.AddField(
            model_name="ocpalldatabasesummarypt",
            name="account_alias",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="reporting.awsaccountalias"
            ),
        ),
        migrations.AddIndex(
            model_name="ocpallcostsummarypt", index=models.Index(fields=["cluster_id"], name="ocpap_costsumm_clust_ix")
        ),
        migrations.AddField(
            model_name="ocpallcostsummarybyservicept",
            name="account_alias",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="reporting.awsaccountalias"
            ),
        ),
        migrations.AddField(
            model_name="ocpallcostsummarybyregionpt",
            name="account_alias",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="reporting.awsaccountalias"
            ),
        ),
        migrations.AddField(
            model_name="ocpallcostsummarybyaccountpt",
            name="account_alias",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="reporting.awsaccountalias"
            ),
        ),
        migrations.AddField(
            model_name="ocpallcomputesummarypt",
            name="account_alias",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="reporting.awsaccountalias"
            ),
        ),
        migrations.AddIndex(
            model_name="ocpallstoragesummarypt",
            index=models.Index(fields=["cluster_id"], name="ocpap_cmpsumm_stor_clust_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallstoragesummarypt",
            index=models.Index(fields=["usage_account_id"], name="ocpap_cmpsumm_stor_acctid_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallstoragesummarypt",
            index=models.Index(fields=["product_code"], name="ocpap_cmpsumm_stor_procode_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallstoragesummarypt",
            index=models.Index(fields=["product_family"], name="ocpap_cmpsumm_stor_profam_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallnetworksummarypt",
            index=models.Index(fields=["cluster_id"], name="ocpap_cmpsumm_net_clust_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallnetworksummarypt",
            index=models.Index(fields=["usage_account_id"], name="ocpap_cmpsumm_net_acctid_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallnetworksummarypt",
            index=models.Index(fields=["product_code"], name="ocpap_cmpsumm_net_procode_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpalldatabasesummarypt",
            index=models.Index(fields=["cluster_id"], name="ocpap_cmpsumm_db_clust_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpalldatabasesummarypt",
            index=models.Index(fields=["usage_account_id"], name="ocpap_cmpsumm_db_acctid_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpalldatabasesummarypt",
            index=models.Index(fields=["product_code"], name="ocpap_cmpsumm_db_procode_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallcostsummarybyservicept",
            index=models.Index(fields=["cluster_id"], name="ocpap_costsumm_srv_clust_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallcostsummarybyservicept",
            index=models.Index(fields=["usage_account_id"], name="ocpap_costsumm_srv_acctid_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallcostsummarybyservicept",
            index=models.Index(fields=["product_code"], name="ocpap_costsumm_srv_procode_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallcostsummarybyservicept",
            index=models.Index(fields=["product_family"], name="ocpap_costsumm_srv_profam_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallcostsummarybyregionpt",
            index=models.Index(fields=["cluster_id"], name="ocpap_costsumm_rgn_clust_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallcostsummarybyregionpt",
            index=models.Index(fields=["usage_account_id"], name="ocpap_costsumm_rgn_acctid_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallcostsummarybyregionpt",
            index=models.Index(fields=["region"], name="ocpap_costsumm_rgn_region_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallcostsummarybyregionpt",
            index=models.Index(fields=["availability_zone"], name="ocpap_costsumm_rgn_avail_zn_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallcostsummarybyaccountpt",
            index=models.Index(fields=["cluster_id"], name="ocpap_costsumm_acct_clust_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallcostsummarybyaccountpt",
            index=models.Index(fields=["usage_account_id"], name="ocpap_costsumm_acct_acctid_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallcomputesummarypt",
            index=models.Index(fields=["cluster_id"], name="ocpap_cmpsumm_clust_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallcomputesummarypt",
            index=models.Index(fields=["usage_account_id"], name="ocpap_cmpsumm_acctid_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallcomputesummarypt",
            index=models.Index(fields=["product_code"], name="ocpap_cmpsumm_procode_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallcomputesummarypt",
            index=models.Index(fields=["instance_type"], name="ocpap_cmpsumm_inst_typ_ix"),
        ),
        migrations.AddIndex(
            model_name="ocpallcomputesummarypt",
            index=models.Index(fields=["resource_id"], name="ocpap_cmpsumm_rsrc_id_ix"),
        ),
        migrations.RunPython(unset_pg_extended_mode, reverse_code=set_pg_extended_mode),
    ]
