# Generated by Django 3.1.13 on 2021-10-20 21:05
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0050_exchangerates"), ("reporting", "0198_aws_matviews_to_partables")]

    operations = [
        migrations.AddField(
            model_name="awscomputesummarybyaccountp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="awscomputesummarybyregionp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="awscomputesummarybyservicep",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="awscomputesummaryp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="awscostsummarybyaccountp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="awscostsummarybyregionp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="awscostsummarybyservicep",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="awscostsummaryp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="awsdatabasesummaryp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="awsnetworksummaryp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="awsstoragesummarybyaccountp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="awsstoragesummarybyregionp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="awsstoragesummarybyservicep",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="awsstoragesummaryp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name="awscomputesummarybyaccountp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="awscomputesummarybyregionp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="awscomputesummarybyservicep",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="awscomputesummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="awscostsummarybyaccountp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="awscostsummarybyregionp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="awscostsummarybyservicep",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="awscostsummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="awsdatabasesummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="awsnetworksummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="awsstoragesummarybyaccountp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="awsstoragesummarybyregionp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="awsstoragesummarybyservicep",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="awsstoragesummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AddIndex(
            model_name="awscomputesummarybyaccountp",
            index=models.Index(fields=["usage_start"], name="awscompsumm_acct_usage_start"),
        ),
        migrations.AddIndex(
            model_name="awscomputesummarybyaccountp",
            index=models.Index(fields=["instance_type"], name="awscompsumm_acct_insttyp"),
        ),
        migrations.AddIndex(
            model_name="awscomputesummarybyregionp",
            index=models.Index(fields=["usage_start"], name="awscompsumm_reg_usage_start"),
        ),
        migrations.AddIndex(
            model_name="awscomputesummarybyregionp",
            index=models.Index(fields=["region"], name="awscompsumm_reg_region"),
        ),
        migrations.AddIndex(
            model_name="awscomputesummarybyregionp",
            index=models.Index(fields=["availability_zone"], name="awscompsumm_reg_zone"),
        ),
        migrations.AddIndex(
            model_name="awscomputesummarybyregionp",
            index=models.Index(fields=["instance_type"], name="awscompsumm_reg_insttyp"),
        ),
        migrations.AddIndex(
            model_name="awscomputesummarybyservicep",
            index=models.Index(fields=["usage_start"], name="awscompsumm_svc_usage_start"),
        ),
        migrations.AddIndex(
            model_name="awscomputesummarybyservicep",
            index=models.Index(fields=["instance_type"], name="awscompsumm_svc_insttyp"),
        ),
        migrations.AddIndex(
            model_name="awscomputesummaryp", index=models.Index(fields=["usage_start"], name="awscompsumm_usage_start")
        ),
        migrations.AddIndex(
            model_name="awscomputesummaryp", index=models.Index(fields=["instance_type"], name="awscompsumm_insttyp")
        ),
        migrations.AddIndex(
            model_name="awscostsummarybyaccountp",
            index=models.Index(fields=["usage_start"], name="awscostsumm_acct_usage_start"),
        ),
        migrations.AddIndex(
            model_name="awscostsummarybyregionp",
            index=models.Index(fields=["usage_start"], name="awscostsumm_reg_usage_start"),
        ),
        migrations.AddIndex(
            model_name="awscostsummarybyregionp", index=models.Index(fields=["region"], name="awscostsumm_reg_region")
        ),
        migrations.AddIndex(
            model_name="awscostsummarybyregionp",
            index=models.Index(fields=["availability_zone"], name="awscostsumm_reg_zone"),
        ),
        migrations.AddIndex(
            model_name="awscostsummarybyservicep",
            index=models.Index(fields=["usage_start"], name="awscostsumm_svc_usage_start"),
        ),
        migrations.AddIndex(
            model_name="awscostsummarybyservicep",
            index=models.Index(fields=["product_code"], name="awscostsumm_svc_prod_cd"),
        ),
        migrations.AddIndex(
            model_name="awscostsummaryp", index=models.Index(fields=["usage_start"], name="awscostsumm_usage_start")
        ),
        migrations.AddIndex(
            model_name="awsdatabasesummaryp", index=models.Index(fields=["usage_start"], name="awsdbsumm_usage_start")
        ),
        migrations.AddIndex(
            model_name="awsdatabasesummaryp", index=models.Index(fields=["product_code"], name="awsdbsumm_product_cd")
        ),
        migrations.AddIndex(
            model_name="awsnetworksummaryp", index=models.Index(fields=["usage_start"], name="awsnetsumm_usage_start")
        ),
        migrations.AddIndex(
            model_name="awsnetworksummaryp", index=models.Index(fields=["product_code"], name="awsnetsumm_product_cd")
        ),
        migrations.AddIndex(
            model_name="awsstoragesummarybyaccountp",
            index=models.Index(fields=["usage_start"], name="awsstorsumm_acct_usage_start"),
        ),
        migrations.AddIndex(
            model_name="awsstoragesummarybyaccountp",
            index=models.Index(fields=["product_family"], name="awsstorsumm_product_acct_fam"),
        ),
        migrations.AddIndex(
            model_name="awsstoragesummarybyregionp",
            index=models.Index(fields=["usage_start"], name="awsstorsumm_reg_usage_start"),
        ),
        migrations.AddIndex(
            model_name="awsstoragesummarybyregionp",
            index=models.Index(fields=["region"], name="awsstorsumm_reg_region"),
        ),
        migrations.AddIndex(
            model_name="awsstoragesummarybyregionp",
            index=models.Index(fields=["availability_zone"], name="awsstorsumm_reg_zone"),
        ),
        migrations.AddIndex(
            model_name="awsstoragesummarybyregionp",
            index=models.Index(fields=["product_family"], name="awsstorsumm_reg_product_fam"),
        ),
        migrations.AddIndex(
            model_name="awsstoragesummarybyservicep",
            index=models.Index(fields=["usage_start"], name="awsstorsumm_svc_usage_start"),
        ),
        migrations.AddIndex(
            model_name="awsstoragesummarybyservicep",
            index=models.Index(fields=["product_family"], name="awsstorsumm_product_svc_fam"),
        ),
        migrations.AddIndex(
            model_name="awsstoragesummaryp", index=models.Index(fields=["usage_start"], name="awsstorsumm_usage_start")
        ),
        migrations.AddIndex(
            model_name="awsstoragesummaryp",
            index=models.Index(fields=["product_family"], name="awsstorsumm_product_fam"),
        ),
    ]
