# Generated by Django 3.1.13 on 2021-11-04 01:04
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models

from koku.database import set_partition_mode
from koku.database import unset_partition_mode


class Migration(migrations.Migration):

    dependencies = [("api", "0050_exchangerates"), ("reporting", "0201_ocp_partables")]

    operations = [
        migrations.RunPython(code=set_partition_mode, reverse_code=unset_partition_mode),
        migrations.CreateModel(
            name="AzureStorageSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("subscription_guid", models.TextField()),
                ("service_name", models.TextField()),
                ("usage_quantity", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit_of_measure", models.TextField(null=True)),
                ("pretax_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.TextField(null=True)),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_azure_storage_summary_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_azure_storage_summary_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="AzureNetworkSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("subscription_guid", models.TextField()),
                ("service_name", models.TextField()),
                ("usage_quantity", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit_of_measure", models.TextField(null=True)),
                ("pretax_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.TextField(null=True)),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_azure_network_summary_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_azure_network_summary_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="AzureDatabaseSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("subscription_guid", models.TextField()),
                ("service_name", models.TextField()),
                ("usage_quantity", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit_of_measure", models.TextField(null=True)),
                ("pretax_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.TextField(null=True)),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_azure_database_summary_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_azure_database_summary_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="AzureCostSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("pretax_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.TextField(null=True)),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_azure_cost_summary_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_azure_cost_summary_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="AzureCostSummaryByServiceP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("subscription_guid", models.TextField()),
                ("service_name", models.TextField()),
                ("pretax_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.TextField(null=True)),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_azure_cost_summary_by_service_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_azure_cost_summary_by_service_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="AzureCostSummaryByLocationP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("subscription_guid", models.TextField()),
                ("resource_location", models.TextField(null=True)),
                ("pretax_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.TextField(null=True)),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_azure_cost_summary_by_location_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_azure_cost_summary_by_location_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="AzureCostSummaryByAccountP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("subscription_guid", models.TextField()),
                ("pretax_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.TextField(null=True)),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_azure_cost_summary_by_account_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_azure_cost_summary_by_account_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="AzureComputeSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("subscription_guid", models.TextField()),
                ("instance_type", models.TextField(null=True)),
                (
                    "instance_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
                ),
                ("instance_count", models.IntegerField(null=True)),
                ("usage_quantity", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit_of_measure", models.TextField(null=True)),
                ("pretax_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.TextField(null=True)),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_azure_compute_summary_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_azure_compute_summary_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.AddIndex(
            model_name="azurestoragesummaryp",
            index=models.Index(fields=["usage_start"], name="azurestorsumm_usage_start"),
        ),
        migrations.AddIndex(
            model_name="azurestoragesummaryp",
            index=models.Index(fields=["service_name"], name="azurestorsumm_svc_name"),
        ),
        migrations.AddIndex(
            model_name="azurenetworksummaryp",
            index=models.Index(fields=["usage_start"], name="azurenetsumm_usage_start"),
        ),
        migrations.AddIndex(
            model_name="azurenetworksummaryp",
            index=models.Index(fields=["service_name"], name="azurenetsumm_svc_name"),
        ),
        migrations.AddIndex(
            model_name="azuredatabasesummaryp",
            index=models.Index(fields=["usage_start"], name="azuredbsumm_usage_start"),
        ),
        migrations.AddIndex(
            model_name="azuredatabasesummaryp",
            index=models.Index(fields=["service_name"], name="azuredbsumm_svc_name"),
        ),
        migrations.AddIndex(
            model_name="azurecostsummaryp",
            index=models.Index(fields=["usage_start"], name="azurecostsumm_usage_start"),
        ),
        migrations.AddIndex(
            model_name="azurecostsummarybyservicep",
            index=models.Index(fields=["usage_start"], name="azurecostsumm_svc_usage_start"),
        ),
        migrations.AddIndex(
            model_name="azurecostsummarybyservicep",
            index=models.Index(fields=["service_name"], name="azurecostsumm_svc_svc_name"),
        ),
        migrations.AddIndex(
            model_name="azurecostsummarybylocationp",
            index=models.Index(fields=["usage_start"], name="azurecostsumm_loc_usage_start"),
        ),
        migrations.AddIndex(
            model_name="azurecostsummarybylocationp",
            index=models.Index(fields=["resource_location"], name="azurecostsumm_loc_res_loc"),
        ),
        migrations.AddIndex(
            model_name="azurecostsummarybyaccountp",
            index=models.Index(fields=["usage_start"], name="azurecostsumm_acc_usage_start"),
        ),
        migrations.AddIndex(
            model_name="azurecostsummarybyaccountp",
            index=models.Index(fields=["subscription_guid"], name="azurecostsumm_acc_sub_guid"),
        ),
        migrations.AddIndex(
            model_name="azurecomputesummaryp",
            index=models.Index(fields=["usage_start"], name="azurecompsumm_usage_start"),
        ),
        migrations.AddIndex(
            model_name="azurecomputesummaryp",
            index=models.Index(fields=["instance_type"], name="azurecompsumm_insttyp"),
        ),
        migrations.RunPython(code=unset_partition_mode, reverse_code=set_partition_mode),
    ]
