# Generated by Django 3.1.13 on 2021-11-04 19:55
from decimal import Decimal

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0201_ocp_partables")]

    operations = [
        migrations.AddField(
            model_name="awscostentrylineitem",
            name="savingsplan_effective_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="awscostentrylineitemdaily",
            name="savingsplan_effective_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemdailysummary",
            name="blended_cost",
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemdailysummary",
            name="markup_cost_savingsplan",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemdailysummary",
            name="markup_cost_blended",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemdailysummary",
            name="savingsplan_effective_cost",
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemprojectdailysummary",
            name="blended_cost",
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemprojectdailysummary",
            name="markup_cost_savingsplan",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemprojectdailysummary",
            name="markup_cost_blended",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemprojectdailysummary",
            name="savingsplan_effective_cost",
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name="ocpusagelineitemdailysummary",
            name="infrastructure_raw_cost_savingsplan_effective_cost",
            field=models.DecimalField(decimal_places=15, default=Decimal("0"), max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpusagelineitemdailysummary",
            name="infrastructure_raw_cost_blended",
            field=models.DecimalField(decimal_places=15, default=Decimal("0"), max_digits=33, null=True),
        ),
    ]
