# Generated by Django 3.1.13 on 2021-11-08 16:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0202_azure_partables")]

    operations = [
        migrations.AlterField(
            model_name="ocpcostsummarybynodep", name="node", field=models.CharField(max_length=253, null=True)
        ),
        migrations.AlterField(
            model_name="ocpcostsummarybyprojectp", name="namespace", field=models.CharField(max_length=253, null=True)
        ),
    ]
