# Generated by Django 3.1.13 on 2021-11-10 21:18
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0203_auto_20211108_1626")]

    operations = [
        migrations.AlterField(
            model_name="ocppodsummarybyprojectp",
            name="cluster_capacity_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummarybyprojectp",
            name="cluster_capacity_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummarybyprojectp",
            name="pod_limit_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummarybyprojectp",
            name="pod_limit_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummarybyprojectp",
            name="pod_request_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummarybyprojectp",
            name="pod_request_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummarybyprojectp",
            name="pod_usage_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummarybyprojectp",
            name="pod_usage_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummaryp",
            name="cluster_capacity_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummaryp",
            name="cluster_capacity_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummaryp",
            name="pod_limit_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummaryp",
            name="pod_limit_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummaryp",
            name="pod_request_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummaryp",
            name="pod_request_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummaryp",
            name="pod_usage_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummaryp",
            name="pod_usage_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpvolumesummarybyprojectp",
            name="persistentvolumeclaim_capacity_gigabyte_months",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpvolumesummarybyprojectp",
            name="persistentvolumeclaim_usage_gigabyte_months",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpvolumesummarybyprojectp",
            name="volume_request_storage_gigabyte_months",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpvolumesummaryp",
            name="persistentvolumeclaim_capacity_gigabyte_months",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpvolumesummaryp",
            name="persistentvolumeclaim_usage_gigabyte_months",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpvolumesummaryp",
            name="volume_request_storage_gigabyte_months",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
    ]
