# Generated by Django 3.1.13 on 2021-11-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0203_auto_20211108_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscostentrylineitem',
            name='savingsplan_effective_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='awscostentrylineitemdaily',
            name='savingsplan_effective_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
    ]
