# Generated by Django 3.1.13 on 2021-11-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0203_auto_20211104_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpawscostlineitemdailysummary',
            name='blended_cost',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='ocpawscostlineitemdailysummary',
            name='savingsplan_effective_cost',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='ocpawscostlineitemprojectdailysummary',
            name='blended_cost',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='ocpawscostlineitemprojectdailysummary',
            name='savingsplan_effective_cost',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
    ]
