# Generated by Django 3.1.13 on 2021-11-10 21:18
import logging
import os

from django.db import migrations
from django.db import models


LOG = logging.getLogger(__name__)


def apply_bulk_alter_table(apps, schema_editor):
    conn = schema_editor.connection
    ocp_ui_tables_sql = """
select table_schema,
       table_name,
       array_agg(column_name order by ordinal_position)::text[] as short_cols
  from information_schema.columns
 where table_schema = current_schema
   and table_name ~ '^reporting_ocp_.+_p$'
   and data_type = 'numeric'
   and numeric_precision is not null
   and numeric_precision < 33
 group
    by 1, 2;
"""
    alter_table_sql = "ALTER TABLE {} "
    alter_column_sql = "      ALTER COLUMN {} SET DATA TYPE numeric(33,15) "
    alter_column_sep = ", " + os.linesep
    ocp_ui_table_targets = None

    with conn.cursor() as cur:
        cur.execute(ocp_ui_tables_sql)
        ocp_ui_table_targets = cur.fetchall()

    if ocp_ui_table_targets:
        LOG.info(f"SCHEMA: {ocp_ui_table_targets[0][0]}")

        for target in ocp_ui_table_targets:
            alter_columns = [alter_column_sql.format(col) for col in target[2]]
            sql = f"{alter_table_sql.format(target[1])}{os.linesep}{alter_column_sep.join(alter_columns)} ;"
            LOG.info(f"EXEC SQL:{os.linesep}{sql}")
            with conn.cursor() as cur:
                cur.execute(sql)


class Migration(migrations.Migration):

    dependencies = [("reporting", "0203_auto_20211108_1626")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # For local DB init -- Prod should have already been done.
                migrations.RunPython(code=apply_bulk_alter_table, reverse_code=migrations.RunPython.noop)
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="ocppodsummarybyprojectp",
                    name="cluster_capacity_cpu_core_hours",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocppodsummarybyprojectp",
                    name="cluster_capacity_memory_gigabyte_hours",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocppodsummarybyprojectp",
                    name="pod_limit_cpu_core_hours",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocppodsummarybyprojectp",
                    name="pod_limit_memory_gigabyte_hours",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocppodsummarybyprojectp",
                    name="pod_request_cpu_core_hours",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocppodsummarybyprojectp",
                    name="pod_request_memory_gigabyte_hours",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocppodsummarybyprojectp",
                    name="pod_usage_cpu_core_hours",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocppodsummarybyprojectp",
                    name="pod_usage_memory_gigabyte_hours",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocppodsummaryp",
                    name="cluster_capacity_cpu_core_hours",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocppodsummaryp",
                    name="cluster_capacity_memory_gigabyte_hours",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocppodsummaryp",
                    name="pod_limit_cpu_core_hours",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocppodsummaryp",
                    name="pod_limit_memory_gigabyte_hours",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocppodsummaryp",
                    name="pod_request_cpu_core_hours",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocppodsummaryp",
                    name="pod_request_memory_gigabyte_hours",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocppodsummaryp",
                    name="pod_usage_cpu_core_hours",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocppodsummaryp",
                    name="pod_usage_memory_gigabyte_hours",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocpvolumesummarybyprojectp",
                    name="persistentvolumeclaim_capacity_gigabyte_months",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocpvolumesummarybyprojectp",
                    name="persistentvolumeclaim_usage_gigabyte_months",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocpvolumesummarybyprojectp",
                    name="volume_request_storage_gigabyte_months",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocpvolumesummaryp",
                    name="persistentvolumeclaim_capacity_gigabyte_months",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocpvolumesummaryp",
                    name="persistentvolumeclaim_usage_gigabyte_months",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AlterField(
                    model_name="ocpvolumesummaryp",
                    name="volume_request_storage_gigabyte_months",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
            ],
        )
    ]
