# Generated by Django 3.1.13 on 2021-11-08 15:20
import pkgutil
from decimal import Decimal

from django.db import connection
from django.db import migrations


def add_awsocp_views(apps, schema_editor):
    """Create the OCP AWS Materialized views from files."""
    version = "_20211108"
    views = {
        f"sql/views/{version}/reporting_ocpaws_compute_summary": [""],
        f"sql/views/{version}/reporting_ocpaws_cost_summary": ["", "_by_account", "_by_region", "_by_service"],
        f"sql/views/{version}/reporting_ocpaws_storage_summary": [""],
        f"sql/views/{version}/reporting_ocpaws_database_summary": [""],
        f"sql/views/{version}/reporting_ocpaws_network_summary": [""],
    }
    for base_path, view_tuple in views.items():
        for view in view_tuple:
            view_sql = pkgutil.get_data("reporting.provider.aws.openshift", f"{base_path}{view}{version}.sql")
            view_sql = view_sql.decode("utf-8")
            with connection.cursor() as cursor:
                cursor.execute(view_sql)


class Migration(migrations.Migration):

    dependencies = [("reporting", "0203_savingsplan")]

    operations = [migrations.RunPython(add_awsocp_views)]
