# Generated by Django 3.1.13 on 2021-11-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0204_auto_20211104_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpawscostlineitemdailysummary',
            name='markup_cost_amortized',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpawscostlineitemdailysummary',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpawscostlineitemprojectdailysummary',
            name='markup_cost_amortized',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='ocpawscostlineitemprojectdailysummary',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
    ]
