# Generated by Django 3.1.13 on 2021-11-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0205_ocpall_perspective_db_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscomputesummarybyaccountp',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscomputesummarybyaccountp',
            name='markup_cost_savingsplan',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscomputesummarybyregionp',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscomputesummarybyregionp',
            name='markup_cost_savingsplan',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscomputesummarybyservicep',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscomputesummarybyservicep',
            name='markup_cost_savingsplan',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscomputesummaryp',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscomputesummaryp',
            name='markup_cost_savingsplan',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscostentrylineitem',
            name='savingsplan_effective_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='awscostentrylineitemdaily',
            name='savingsplan_effective_cost',
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='awscostentrylineitemdailysummary',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscostentrylineitemdailysummary',
            name='markup_cost_savingsplan',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscostsummarybyaccountp',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscostsummarybyaccountp',
            name='markup_cost_savingsplan',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscostsummarybyregionp',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscostsummarybyregionp',
            name='markup_cost_savingsplan',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscostsummarybyservicep',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscostsummarybyservicep',
            name='markup_cost_savingsplan',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscostsummaryp',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awscostsummaryp',
            name='markup_cost_savingsplan',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awsdatabasesummaryp',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awsdatabasesummaryp',
            name='markup_cost_savingsplan',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awsnetworksummaryp',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awsnetworksummaryp',
            name='markup_cost_savingsplan',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awsstoragesummarybyaccountp',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awsstoragesummarybyaccountp',
            name='markup_cost_savingsplan',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awsstoragesummarybyregionp',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awsstoragesummarybyregionp',
            name='markup_cost_savingsplan',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awsstoragesummarybyservicep',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awsstoragesummarybyservicep',
            name='markup_cost_savingsplan',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awsstoragesummaryp',
            name='markup_cost_blended',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='awsstoragesummaryp',
            name='markup_cost_savingsplan',
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
    ]
