# Generated by Django 3.1.13 on 2021-11-15 14:26
import logging

import django.db.models.deletion
from django.db import migrations
from django.db import models

from koku.database import get_model


LOG = logging.getLogger(__name__)

TABLES = (
    get_model("ocpallcomputesummarypt")._meta.db_table,
    get_model("ocpallcostsummarybyaccountpt")._meta.db_table,
    get_model("ocpallcostsummarybyregionpt")._meta.db_table,
    get_model("ocpallcostsummarybyservicept")._meta.db_table,
    get_model("ocpallcostsummarypt")._meta.db_table,
    get_model("ocpalldatabasesummarypt")._meta.db_table,
    get_model("ocpallnetworksummarypt")._meta.db_table,
    get_model("ocpallstoragesummarypt")._meta.db_table,
)

DELETE_DATA_SQL = """
DELETE
  FROM {} x
 WHERE NOT EXISTS (
                      SELECT p."uuid"
                        FROM public.api_provider p
                       WHERE p."uuid" = x.source_uuid
                  );
"""


def delete_orphaned_data(apps, schema_editor):
    conn = schema_editor.connection
    with conn.cursor() as cur:
        for table in TABLES:
            sql = DELETE_DATA_SQL.format(table)
            LOG.debug(f"SQL = {sql}")
            LOG.info(f"Deleting orphaned source_uuid data from {table}")
            cur.execute(sql)


class Migration(migrations.Migration):

    dependencies = [("api", "0050_exchangerates"), ("reporting", "0205_ocpall_perspective_db_defaults")]

    operations = [
        migrations.RunPython(code=delete_orphaned_data, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="ocpallcomputesummarypt",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="ocpallcostsummarybyaccountpt",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="ocpallcostsummarybyregionpt",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="ocpallcostsummarybyservicept",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="ocpallcostsummarypt",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="ocpalldatabasesummarypt",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="ocpallnetworksummarypt",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterField(
            model_name="ocpallstoragesummarypt",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
    ]
