# Generated by Django 3.1.13 on 2021-11-18 04:49
import django.db.models.deletion
from django.db import migrations
from django.db import models

from koku.database import set_pg_extended_mode
from koku.database import unset_pg_extended_mode


class Migration(migrations.Migration):

    dependencies = [("api", "0050_exchangerates"), ("reporting", "0209_gcp_partables")]

    operations = [
        migrations.RunPython(code=set_pg_extended_mode, reverse_code=unset_pg_extended_mode),
        migrations.CreateModel(
            name="OCPAWSStorageSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("usage_account_id", models.CharField(max_length=50)),
                ("product_family", models.CharField(max_length=150, null=True)),
                ("usage_amount", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                (
                    "account_alias",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="reporting.awsaccountalias"
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_ocpaws_storage_summary_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_ocpaws_storage_summary_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCPAWSNetworkSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("usage_account_id", models.CharField(max_length=50)),
                ("product_code", models.CharField(max_length=50)),
                ("usage_amount", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                (
                    "account_alias",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="reporting.awsaccountalias"
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_ocpaws_network_summary_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_ocpaws_network_summary_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCPAWSDatabaseSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("usage_account_id", models.CharField(max_length=50)),
                ("product_code", models.CharField(max_length=50)),
                ("usage_amount", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                (
                    "account_alias",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="reporting.awsaccountalias"
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_ocpaws_database_summary_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_ocpaws_database_summary_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCPAWSCostSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_ocpaws_cost_summary_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_ocpaws_cost_summary_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCPAWSCostSummaryByServiceP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("usage_account_id", models.CharField(max_length=50)),
                ("product_code", models.CharField(max_length=50)),
                ("product_family", models.CharField(max_length=150, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                (
                    "account_alias",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="reporting.awsaccountalias"
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_ocpaws_cost_summary_by_service_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_ocpaws_cost_summary_by_service_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCPAWSCostSummaryByRegionP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("usage_account_id", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=50, null=True)),
                ("availability_zone", models.CharField(max_length=50, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                (
                    "account_alias",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="reporting.awsaccountalias"
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_ocpaws_cost_summary_by_region_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_ocpaws_cost_summary_by_region_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCPAWSCostSummaryByAccountP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("usage_account_id", models.CharField(max_length=50)),
                ("unblended_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                (
                    "account_alias",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="reporting.awsaccountalias"
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_ocpaws_cost_summary_by_account_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_ocpaws_cost_summary_by_account_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCPAWSComputeSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("usage_account_id", models.CharField(max_length=50)),
                ("instance_type", models.CharField(max_length=50, null=True)),
                ("resource_id", models.CharField(max_length=253, null=True)),
                ("usage_amount", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                (
                    "account_alias",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="reporting.awsaccountalias"
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_ocpaws_compute_summary_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_ocpaws_compute_summary_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.AddIndex(
            model_name="ocpawsstoragesummaryp", index=models.Index(fields=["usage_start"], name="ocpawsstorsumm_usst")
        ),
        migrations.AddIndex(
            model_name="ocpawsstoragesummaryp",
            index=models.Index(fields=["product_family"], name="ocpawsstorsumm_product_fam"),
        ),
        migrations.AddIndex(
            model_name="ocpawsnetworksummaryp", index=models.Index(fields=["usage_start"], name="ocpawsnetsumm_usst")
        ),
        migrations.AddIndex(
            model_name="ocpawsnetworksummaryp",
            index=models.Index(fields=["product_code"], name="ocpawsnetsumm_product_cd"),
        ),
        migrations.AddIndex(
            model_name="ocpawsdatabasesummaryp", index=models.Index(fields=["usage_start"], name="ocpawsdbsumm_usst")
        ),
        migrations.AddIndex(
            model_name="ocpawsdatabasesummaryp",
            index=models.Index(fields=["product_code"], name="ocpawsdbsumm_product_cd"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostsummaryp", index=models.Index(fields=["usage_start"], name="ocpawscostsumm_usst")
        ),
        migrations.AddIndex(
            model_name="ocpawscostsummarybyservicep",
            index=models.Index(fields=["usage_start"], name="ocpawscostsumm_svc_usst"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostsummarybyservicep",
            index=models.Index(fields=["product_code"], name="ocpawscostsumm_svc_prod_cd"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostsummarybyregionp",
            index=models.Index(fields=["usage_start"], name="ocpawscostsumm_reg_usst"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostsummarybyregionp",
            index=models.Index(fields=["region"], name="ocpawscostsumm_reg_region"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostsummarybyregionp",
            index=models.Index(fields=["availability_zone"], name="ocpawscostsumm_reg_zone"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostsummarybyaccountp",
            index=models.Index(fields=["usage_start"], name="ocpawscostsumm_acct_usst"),
        ),
        migrations.AddIndex(
            model_name="ocpawscomputesummaryp", index=models.Index(fields=["usage_start"], name="ocpawscompsumm_usst")
        ),
        migrations.AddIndex(
            model_name="ocpawscomputesummaryp",
            index=models.Index(fields=["instance_type"], name="ocpawscompsumm_insttyp"),
        ),
        migrations.RunPython(code=unset_pg_extended_mode, reverse_code=set_pg_extended_mode),
    ]
