# Generated by Django 3.1.13 on 2021-12-08 18:38
from django.db import migrations


SQL_TMPL = """DROP MATERIALIZED VIEW IF EXISTS {} CASCADE ;"""


def drop_matview_sql(model_str):
    return SQL_TMPL.format(model_str)


class Migration(migrations.Migration):

    dependencies = [("reporting", "0212_auto_20211203_1640")]

    operations = [
        migrations.RunSQL(sql=drop_matview_sql("AWSComputeSummary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="reporting_aws_compute_summary"),
        migrations.RunSQL(sql=drop_matview_sql("AWSComputeSummaryByAccount"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="reporting_aws_compute_summary_by_account"),
        migrations.RunSQL(sql=drop_matview_sql("AWSComputeSummaryByRegion"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="reporting_aws_compute_summary_by_region"),
        migrations.RunSQL(sql=drop_matview_sql("AWSComputeSummaryByService"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="reporting_aws_compute_summary_by_service"),
        migrations.RunSQL(sql=drop_matview_sql("AWSCostSummary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="reporting_aws_cost_summary"),
        migrations.RunSQL(sql=drop_matview_sql("AWSCostSummaryByAccount"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="reporting_aws_cost_summary_by_account"),
        migrations.RunSQL(sql=drop_matview_sql("AWSCostSummaryByRegion"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="reporting_aws_cost_summary_by_region"),
        migrations.RunSQL(sql=drop_matview_sql("AWSCostSummaryByService"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="reporting_aws_cost_summary_by_service"),
        migrations.RunSQL(sql=drop_matview_sql("AWSDatabaseSummary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="AWSDatabaseSummary"),
        migrations.RunSQL(sql=drop_matview_sql("AWSNetworkSummary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="AWSNetworkSummary"),
        migrations.RunSQL(sql=drop_matview_sql("AWSStorageSummary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="reporting_aws_storage_summary"),
        migrations.RunSQL(sql=drop_matview_sql("AWSStorageSummaryByAccount"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="reporting_aws_storage_summary_by_account"),
        migrations.RunSQL(sql=drop_matview_sql("AWSStorageSummaryByRegion"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="reporting_aws_storage_summary_by_region"),
        migrations.RunSQL(sql=drop_matview_sql("AWSStorageSummaryByService"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="reporting_aws_storage_summary_by_service"),
    ]
