# Generated by Django 3.1.13 on 2022-01-07 16:14
import logging

from django.db import migrations


LOG = logging.getLogger(__name__)

SQL_TMPL = "DROP MATERIALIZED VIEW IF EXISTS {} CASCADE;"
OCPALL_MATVIEWS = (
    "reporting_ocpall_compute_summary_p",
    "reporting_ocpall_storage_summary_p",
    "reporting_ocpall_cost_summary_p",
    "reporting_ocpall_cost_summary_by_account_p",
    "reporting_ocpall_cost_summary_by_region_p",
    "reporting_ocpall_cost_summary_by_service_p",
    "reporting_ocpall_database_summary_p",
    "reporting_ocpall_network_summary_p",
)


def drop_ocpall_views(app, schema_editor):
    conn = schema_editor.connection

    for mview in OCPALL_MATVIEWS:
        with conn.cursor() as cur:
            LOG.info(f"Dropping materialized view {mview}")
            cur.execute(SQL_TMPL.format(mview))


class Migration(migrations.Migration):

    dependencies = [("reporting", "0212_auto_20211203_1640")]

    operations = [migrations.RunPython(drop_ocpall_views, reverse_code=migrations.RunPython.noop)]
