# Generated by Django 3.1.13 on 2021-12-08 18:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0212_auto_20211203_1640")]

    operations = [
        migrations.DeleteModel(name="AWSComputeSummary"),
        migrations.DeleteModel(name="AWSComputeSummaryByAccount"),
        migrations.DeleteModel(name="AWSComputeSummaryByRegion"),
        migrations.DeleteModel(name="AWSComputeSummaryByService"),
        migrations.DeleteModel(name="AWSCostSummary"),
        migrations.DeleteModel(name="AWSCostSummaryByAccount"),
        migrations.DeleteModel(name="AWSCostSummaryByRegion"),
        migrations.DeleteModel(name="AWSCostSummaryByService"),
        migrations.DeleteModel(name="AWSDatabaseSummary"),
        migrations.DeleteModel(name="AWSNetworkSummary"),
        migrations.DeleteModel(name="AWSStorageSummary"),
        migrations.DeleteModel(name="AWSStorageSummaryByAccount"),
        migrations.DeleteModel(name="AWSStorageSummaryByRegion"),
        migrations.DeleteModel(name="AWSStorageSummaryByService"),
    ]
