# Generated by Django 3.1.13 on 2022-01-07 01:46
from django.db import migrations


SQL_TMPL = """DROP MATERIALIZED VIEW IF EXISTS {} CASCADE ;"""


def drop_matview_sql(model_str):
    return SQL_TMPL.format(model_str)


class Migration(migrations.Migration):

    dependencies = [("reporting", "0212_auto_20211203_1640")]

    operations = [
        migrations.RunSQL(sql=drop_matview_sql("reporting_aws_compute_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="AWSComputeSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_aws_compute_summary_by_account"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="AWSComputeSummaryByAccount"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_aws_compute_summary_by_region"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="AWSComputeSummaryByRegion"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_aws_compute_summary_by_service"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="AWSComputeSummaryByService"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_aws_cost_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="AWSCostSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_aws_cost_summary_by_account"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="AWSCostSummaryByAccount"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_aws_cost_summary_by_region"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="AWSCostSummaryByRegion"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_aws_cost_summary_by_service"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="AWSCostSummaryByService"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_aws_database_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="AWSDatabaseSummary"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_aws_network_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="AWSNetworkSummary"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_aws_storage_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="AWSStorageSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_aws_storage_summary_by_account"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="AWSStorageSummaryByAccount"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_aws_storage_summary_by_region"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="AWSStorageSummaryByRegion"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_aws_storage_summary_by_service"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="AWSStorageSummaryByService"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_azure_compute_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="AzureComputeSummary"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_azure_cost_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="AzureCostSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_azure_cost_summary_by_account"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="AzureCostSummaryByAccount"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_azure_cost_summary_by_location"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="AzureCostSummaryByLocation"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_azure_cost_summary_by_service"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="AzureCostSummaryByService"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_azure_database_summary"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="AzureDatabaseSummary"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_azure_network_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="AzureNetworkSummary"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_azure_storage_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="AzureStorageSummary"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_gcp_compute_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="GCPComputeSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_gcp_compute_summary_by_account"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="GCPComputeSummaryByAccount"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_gcp_compute_summary_by_project"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="GCPComputeSummaryByProject"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_gcp_compute_summary_by_region"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="GCPComputeSummaryByRegion"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_gcp_compute_summary_by_service"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="GCPComputeSummaryByService"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_gcp_cost_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="GCPCostSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_gcp_cost_summary_by_account"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="GCPCostSummaryByAccount"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_gcp_cost_summary_by_project"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="GCPCostSummaryByProject"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_gcp_cost_summary_by_region"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="GCPCostSummaryByRegion"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_gcp_cost_summary_by_service"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="GCPCostSummaryByService"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_gcp_database_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="GCPDatabaseSummary"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_gcp_network_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="GCPNetworkSummary"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_gcp_storage_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="GCPStorageSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_gcp_storage_summary_by_account"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="GCPStorageSummaryByAccount"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_gcp_storage_summary_by_project"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="GCPStorageSummaryByProject"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_gcp_storage_summary_by_region"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="GCPStorageSummaryByRegion"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_gcp_storage_summary_by_service"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="GCPStorageSummaryByService"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpall_compute_summary"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAllComputeSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpall_compute_summary_p"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAllComputeSummaryP"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_ocpall_cost_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="OCPAllCostSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpall_cost_summary_by_account"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAllCostSummaryByAccount"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpall_cost_summary_by_account_p"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAllCostSummaryByAccountP"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpall_cost_summary_by_region"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAllCostSummaryByRegion"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpall_cost_summary_by_region_p"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAllCostSummaryByRegionP"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpall_cost_summary_by_service"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAllCostSummaryByService"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpall_cost_summary_by_service_p"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAllCostSummaryByServiceP"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_ocpall_cost_summary_p"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="OCPAllCostSummaryP"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpall_database_summary"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAllDatabaseSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpall_database_summary_p"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAllDatabaseSummaryP"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpall_network_summary"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAllNetworkSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpall_network_summary_p"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAllNetworkSummaryP"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpall_storage_summary"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAllStorageSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpall_storage_summary_p"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAllStorageSummaryP"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpaws_compute_summary"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAWSComputeSummary"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_ocpaws_cost_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="OCPAWSCostSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpaws_cost_summary_by_account"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAWSCostSummaryByAccount"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpaws_cost_summary_by_region"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAWSCostSummaryByRegion"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpaws_cost_summary_by_service"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAWSCostSummaryByService"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpaws_database_summary"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAWSDatabaseSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpaws_network_summary"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAWSNetworkSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpaws_storage_summary"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAWSStorageSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpazure_compute_summary"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAzureComputeSummary"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_ocpazure_cost_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="OCPAzureCostSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpazure_cost_summary_by_account"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAzureCostSummaryByAccount"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpazure_cost_summary_by_location"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAzureCostSummaryByLocation"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpazure_cost_summary_by_service"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAzureCostSummaryByService"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpazure_database_summary"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAzureDatabaseSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpazure_network_summary"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAzureNetworkSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocpazure_storage_summary"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPAzureStorageSummary"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_ocp_cost_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="OCPCostSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocp_cost_summary_by_node"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPCostSummaryByNode"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocp_cost_summary_by_project"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPCostSummaryByProject"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_ocp_pod_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="OCPPodSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocp_pod_summary_by_project"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPPodSummaryByProject"),
        migrations.RunSQL(sql=drop_matview_sql("reporting_ocp_volume_summary"), reverse_sql=migrations.RunSQL.noop),
        migrations.DeleteModel(name="OCPVolumeSummary"),
        migrations.RunSQL(
            sql=drop_matview_sql("reporting_ocp_volume_summary_by_project"), reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(name="OCPVolumeSummaryByProject"),
    ]
