# Generated by Django 3.1.13 on 2022-01-05 20:47
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0212_auto_20211203_1640")]

    operations = [
        migrations.RemoveField(model_name="awscomputesummarybyservicep", name="account_alias"),
        migrations.RemoveField(model_name="awscomputesummarybyservicep", name="organizational_unit"),
        migrations.RemoveField(model_name="awscomputesummarybyservicep", name="source_uuid"),
        migrations.RemoveField(model_name="awsstoragesummarybyregionp", name="account_alias"),
        migrations.RemoveField(model_name="awsstoragesummarybyregionp", name="organizational_unit"),
        migrations.RemoveField(model_name="awsstoragesummarybyregionp", name="source_uuid"),
        migrations.RemoveField(model_name="awsstoragesummarybyservicep", name="account_alias"),
        migrations.RemoveField(model_name="awsstoragesummarybyservicep", name="organizational_unit"),
        migrations.RemoveField(model_name="awsstoragesummarybyservicep", name="source_uuid"),
        migrations.DeleteModel(name="AWSComputeSummaryByRegionP"),
        migrations.DeleteModel(name="AWSComputeSummaryByServiceP"),
        migrations.DeleteModel(name="AWSStorageSummaryByRegionP"),
        migrations.DeleteModel(name="AWSStorageSummaryByServiceP"),
    ]
