# Generated by Django 3.1.13 on 2021-12-10 17:44
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0050_exchangerates"), ("reporting", "0213_auto_20211210_1732")]

    operations = [
        migrations.CreateModel(
            name="AWSComputeSummaryByRegion",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("usage_account_id", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=50, null=True)),
                ("availability_zone", models.CharField(max_length=50, null=True)),
                ("instance_type", models.CharField(max_length=50, null=True)),
                (
                    "resource_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), null=True, size=None
                    ),
                ),
                ("resource_count", models.IntegerField(null=True)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("blended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("savingsplan_effective_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                ("source_uuid", models.UUIDField(null=True)),
            ],
            options={"db_table": "reporting_aws_compute_summary_by_region", "managed": False},
        ),
        migrations.CreateModel(
            name="AWSComputeSummaryByService",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("usage_account_id", models.CharField(max_length=50)),
                ("product_code", models.CharField(max_length=50)),
                ("product_family", models.CharField(max_length=150, null=True)),
                ("instance_type", models.CharField(max_length=50, null=True)),
                (
                    "resource_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), null=True, size=None
                    ),
                ),
                ("resource_count", models.IntegerField(null=True)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("blended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("savingsplan_effective_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                ("source_uuid", models.UUIDField(null=True)),
            ],
            options={"db_table": "reporting_aws_compute_summary_by_service", "managed": False},
        ),
        migrations.CreateModel(
            name="AWSStorageSummaryByServiceP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("usage_account_id", models.CharField(max_length=50)),
                ("product_code", models.CharField(max_length=50)),
                ("product_family", models.CharField(max_length=150, null=True)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("blended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("savingsplan_effective_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost_blended", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("markup_cost_savingsplan", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                (
                    "account_alias",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.awsaccountalias"
                    ),
                ),
                (
                    "organizational_unit",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.awsorganizationalunit"
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_aws_storage_summary_by_service_p"},
        ),
        migrations.CreateModel(
            name="AWSStorageSummaryByRegionP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("usage_account_id", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=50, null=True)),
                ("availability_zone", models.CharField(max_length=50, null=True)),
                ("product_family", models.CharField(max_length=150, null=True)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("blended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("savingsplan_effective_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost_blended", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("markup_cost_savingsplan", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                (
                    "account_alias",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.awsaccountalias"
                    ),
                ),
                (
                    "organizational_unit",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.awsorganizationalunit"
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_aws_storage_summary_by_region_p"},
        ),
        migrations.CreateModel(
            name="AWSComputeSummaryByServiceP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("usage_account_id", models.CharField(max_length=50)),
                ("product_code", models.CharField(max_length=50)),
                ("product_family", models.CharField(max_length=150, null=True)),
                ("instance_type", models.CharField(max_length=50, null=True)),
                (
                    "resource_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), null=True, size=None
                    ),
                ),
                ("resource_count", models.IntegerField(null=True)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("blended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("savingsplan_effective_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost_blended", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("markup_cost_savingsplan", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                (
                    "account_alias",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.awsaccountalias"
                    ),
                ),
                (
                    "organizational_unit",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.awsorganizationalunit"
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_aws_compute_summary_by_service_p"},
        ),
        migrations.CreateModel(
            name="AWSComputeSummaryByRegionP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("usage_account_id", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=50, null=True)),
                ("availability_zone", models.CharField(max_length=50, null=True)),
                ("instance_type", models.CharField(max_length=50, null=True)),
                (
                    "resource_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), null=True, size=None
                    ),
                ),
                ("resource_count", models.IntegerField(null=True)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("blended_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("savingsplan_effective_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost_blended", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("markup_cost_savingsplan", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("currency_code", models.CharField(max_length=10)),
                (
                    "account_alias",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.awsaccountalias"
                    ),
                ),
                (
                    "organizational_unit",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.awsorganizationalunit"
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provider",
                    ),
                ),
            ],
            options={"db_table": "reporting_aws_compute_summary_by_region_p"},
        ),
        migrations.AddIndex(
            model_name="awsstoragesummarybyservicep",
            index=models.Index(fields=["usage_start"], name="awsstorsumm_svc_usage_start"),
        ),
        migrations.AddIndex(
            model_name="awsstoragesummarybyservicep",
            index=models.Index(fields=["product_family"], name="awsstorsumm_product_svc_fam"),
        ),
        migrations.AddIndex(
            model_name="awsstoragesummarybyregionp",
            index=models.Index(fields=["usage_start"], name="awsstorsumm_reg_usage_start"),
        ),
        migrations.AddIndex(
            model_name="awsstoragesummarybyregionp",
            index=models.Index(fields=["region"], name="awsstorsumm_reg_region"),
        ),
        migrations.AddIndex(
            model_name="awsstoragesummarybyregionp",
            index=models.Index(fields=["availability_zone"], name="awsstorsumm_reg_zone"),
        ),
        migrations.AddIndex(
            model_name="awsstoragesummarybyregionp",
            index=models.Index(fields=["product_family"], name="awsstorsumm_reg_product_fam"),
        ),
        migrations.AddIndex(
            model_name="awscomputesummarybyservicep",
            index=models.Index(fields=["usage_start"], name="awscompsumm_svc_usage_start"),
        ),
        migrations.AddIndex(
            model_name="awscomputesummarybyservicep",
            index=models.Index(fields=["instance_type"], name="awscompsumm_svc_insttyp"),
        ),
        migrations.AddIndex(
            model_name="awscomputesummarybyregionp",
            index=models.Index(fields=["usage_start"], name="awscompsumm_reg_usage_start"),
        ),
        migrations.AddIndex(
            model_name="awscomputesummarybyregionp",
            index=models.Index(fields=["region"], name="awscompsumm_reg_region"),
        ),
        migrations.AddIndex(
            model_name="awscomputesummarybyregionp",
            index=models.Index(fields=["availability_zone"], name="awscompsumm_reg_zone"),
        ),
        migrations.AddIndex(
            model_name="awscomputesummarybyregionp",
            index=models.Index(fields=["instance_type"], name="awscompsumm_reg_insttyp"),
        ),
    ]
