# Generated by Django 3.2.11 on 2022-01-12 02:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0213_delete_mat_views")]

    operations = [
        migrations.AlterField(
            model_name="azurecomputesummaryp", name="currency", field=models.CharField(max_length=10, null=True)
        ),
        migrations.AlterField(
            model_name="azurecomputesummaryp", name="unit_of_measure", field=models.CharField(max_length=20, null=True)
        ),
        migrations.AlterField(
            model_name="azurecostentrylineitemdailysummary",
            name="currency",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="azurecostentrylineitemdailysummary",
            name="unit_of_measure",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="azurecostsummarybyaccountp", name="currency", field=models.CharField(max_length=10, null=True)
        ),
        migrations.AlterField(
            model_name="azurecostsummarybylocationp", name="currency", field=models.CharField(max_length=10, null=True)
        ),
        migrations.AlterField(
            model_name="azurecostsummarybyservicep", name="currency", field=models.CharField(max_length=10, null=True)
        ),
        migrations.AlterField(
            model_name="azurecostsummaryp", name="currency", field=models.CharField(max_length=10, null=True)
        ),
        migrations.AlterField(
            model_name="azuredatabasesummaryp", name="currency", field=models.CharField(max_length=10, null=True)
        ),
        migrations.AlterField(
            model_name="azuredatabasesummaryp",
            name="unit_of_measure",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="azuremeter", name="currency", field=models.CharField(max_length=10, null=True)
        ),
        migrations.AlterField(
            model_name="azuremeter", name="unit_of_measure", field=models.CharField(max_length=20, null=True)
        ),
        migrations.AlterField(
            model_name="azurenetworksummaryp", name="currency", field=models.CharField(max_length=10, null=True)
        ),
        migrations.AlterField(
            model_name="azurenetworksummaryp", name="unit_of_measure", field=models.CharField(max_length=20, null=True)
        ),
        migrations.AlterField(
            model_name="azurestoragesummaryp", name="currency", field=models.CharField(max_length=10, null=True)
        ),
        migrations.AlterField(
            model_name="azurestoragesummaryp", name="unit_of_measure", field=models.CharField(max_length=20, null=True)
        ),
        migrations.AlterField(
            model_name="ocpazurecomputesummaryp", name="currency", field=models.CharField(max_length=10, null=True)
        ),
        migrations.AlterField(
            model_name="ocpazurecomputesummaryp",
            name="unit_of_measure",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ocpazurecostlineitemdailysummary",
            name="currency",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="ocpazurecostlineitemdailysummary",
            name="unit_of_measure",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ocpazurecostlineitemprojectdailysummary",
            name="currency",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="ocpazurecostlineitemprojectdailysummary",
            name="unit_of_measure",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ocpazurecostsummarybyaccountp",
            name="currency",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="ocpazurecostsummarybylocationp",
            name="currency",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="ocpazurecostsummarybyservicep",
            name="currency",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="ocpazurecostsummaryp", name="currency", field=models.CharField(max_length=10, null=True)
        ),
        migrations.AlterField(
            model_name="ocpazuredatabasesummaryp", name="currency", field=models.CharField(max_length=10, null=True)
        ),
        migrations.AlterField(
            model_name="ocpazuredatabasesummaryp",
            name="unit_of_measure",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ocpazurenetworksummaryp", name="currency", field=models.CharField(max_length=10, null=True)
        ),
        migrations.AlterField(
            model_name="ocpazurenetworksummaryp",
            name="unit_of_measure",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ocpazurestoragesummaryp", name="currency", field=models.CharField(max_length=10, null=True)
        ),
        migrations.AlterField(
            model_name="ocpazurestoragesummaryp",
            name="unit_of_measure",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
