# Generated by Django 3.1.14 on 2022-01-12 19:59
from django.db import migrations

from koku.database import get_model

PartitionedTables = get_model("partitioned_tables")
TARGET_PARTABLES = (
    "reporting_gcp_compute_summary_by_project_p",
    "reporting_gcp_compute_summary_by_service_p",
    "reporting_gcp_compute_summary_by_region_p",
)


def drop_partitions(app, schema_editor):
    PartitionedTables.objects.filter(partition_of_table_name__in=TARGET_PARTABLES).delete()


class Migration(migrations.Migration):

    dependencies = [("reporting", "0213_delete_mat_views")]

    operations = [
        migrations.RemoveField(model_name="gcpcomputesummarybyregionp", name="source_uuid"),
        migrations.RemoveField(model_name="gcpcomputesummarybyservicep", name="source_uuid"),
        migrations.RunPython(code=drop_partitions, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(name="GCPComputeSummaryByProjectP"),
        migrations.DeleteModel(name="GCPComputeSummaryByRegionP"),
        migrations.DeleteModel(name="GCPComputeSummaryByServiceP"),
    ]
