# Generated by Django 3.1.13 on 2021-12-13 15:13
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0214_auto_20211210_1744")]

    operations = [
        migrations.RemoveField(model_name="awscomputesummarybyservicep", name="account_alias"),
        migrations.RemoveField(model_name="awscomputesummarybyservicep", name="organizational_unit"),
        migrations.RemoveField(model_name="awscomputesummarybyservicep", name="source_uuid"),
        migrations.RemoveField(model_name="awsstoragesummarybyregionp", name="account_alias"),
        migrations.RemoveField(model_name="awsstoragesummarybyregionp", name="organizational_unit"),
        migrations.RemoveField(model_name="awsstoragesummarybyregionp", name="source_uuid"),
        migrations.RemoveField(model_name="awsstoragesummarybyservicep", name="account_alias"),
        migrations.RemoveField(model_name="awsstoragesummarybyservicep", name="organizational_unit"),
        migrations.RemoveField(model_name="awsstoragesummarybyservicep", name="source_uuid"),
        migrations.DeleteModel(name="AWSComputeSummaryByService"),
        migrations.DeleteModel(name="AWSStorageSummaryByService"),
        migrations.DeleteModel(name="AWSComputeSummaryByServiceP"),
        migrations.DeleteModel(name="AWSStorageSummaryByRegionP"),
        migrations.DeleteModel(name="AWSStorageSummaryByServiceP"),
    ]
