# Generated by Django 3.1.13 on 2022-01-07 20:44
import uuid

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations
from django.db import models

from koku.database import set_pg_extended_mode
from koku.database import unset_pg_extended_mode


class Migration(migrations.Migration):

    dependencies = [("reporting", "0214_ocpgcp_unitusage")]

    operations = [
        migrations.RunPython(code=set_pg_extended_mode, reverse_code=unset_pg_extended_mode),
        migrations.CreateModel(
            name="OCPAzureCostLineItemProjectDailySummaryP",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("data_source", models.CharField(max_length=64, null=True)),
                ("namespace", models.CharField(max_length=253)),
                ("node", models.CharField(max_length=253, null=True)),
                ("persistentvolumeclaim", models.CharField(max_length=253, null=True)),
                ("persistentvolume", models.CharField(max_length=253, null=True)),
                ("storageclass", models.CharField(max_length=50, null=True)),
                ("pod_labels", models.JSONField(null=True)),
                ("resource_id", models.CharField(max_length=253, null=True)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("subscription_guid", models.TextField()),
                ("instance_type", models.TextField(null=True)),
                ("service_name", models.TextField(null=True)),
                ("resource_location", models.TextField(null=True)),
                ("usage_quantity", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit_of_measure", models.TextField(null=True)),
                ("currency", models.TextField(null=True)),
                ("pretax_cost", models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ("project_markup_cost", models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ("pod_cost", models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ("tags", models.JSONField(null=True)),
                ("source_uuid", models.UUIDField(null=True)),
                (
                    "cost_entry_bill",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.azurecostentrybill"),
                ),
                (
                    "report_period",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.ocpusagereportperiod"
                    ),
                ),
            ],
            options={"db_table": "reporting_ocpazurecostlineitem_project_daily_summary_p"},
        ),
        migrations.RunSQL(
            sql="""ALTER TABLE reporting_ocpazurecostlineitem_project_daily_summary_p ALTER COLUMN "uuid" SET DEFAULT uuid_generate_v4()""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="OCPAzureCostLineItemDailySummaryP",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                (
                    "namespace",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None),
                ),
                ("node", models.CharField(max_length=253, null=True)),
                ("resource_id", models.CharField(max_length=253, null=True)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("subscription_guid", models.TextField()),
                ("instance_type", models.TextField(null=True)),
                ("service_name", models.TextField(null=True)),
                ("resource_location", models.TextField(null=True)),
                ("tags", models.JSONField(null=True)),
                ("usage_quantity", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("pretax_cost", models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=17, null=True)),
                ("currency", models.TextField(null=True)),
                ("unit_of_measure", models.TextField(null=True)),
                ("shared_projects", models.IntegerField(default=1)),
                ("project_costs", models.JSONField(null=True)),
                ("source_uuid", models.UUIDField(null=True)),
                (
                    "cost_entry_bill",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.azurecostentrybill"),
                ),
                (
                    "report_period",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.ocpusagereportperiod"
                    ),
                ),
            ],
            options={"db_table": "reporting_ocpazurecostlineitem_daily_summary_p"},
        ),
        migrations.RunSQL(
            sql="""ALTER TABLE reporting_ocpazurecostlineitem_daily_summary_p ALTER COLUMN "uuid" SET DEFAULT uuid_generate_v4()""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="OCPAWSCostLineItemProjectDailySummaryP",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                ("data_source", models.CharField(max_length=64, null=True)),
                ("namespace", models.CharField(max_length=253)),
                ("node", models.CharField(max_length=253, null=True)),
                ("persistentvolumeclaim", models.CharField(max_length=253, null=True)),
                ("persistentvolume", models.CharField(max_length=253, null=True)),
                ("storageclass", models.CharField(max_length=50, null=True)),
                ("pod_labels", models.JSONField(null=True)),
                ("resource_id", models.CharField(max_length=253, null=True)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("product_code", models.CharField(max_length=50)),
                ("product_family", models.CharField(max_length=150, null=True)),
                ("instance_type", models.CharField(max_length=50, null=True)),
                ("usage_account_id", models.CharField(max_length=50)),
                ("availability_zone", models.CharField(max_length=50, null=True)),
                ("region", models.CharField(max_length=50, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("usage_amount", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("normalized_usage_amount", models.FloatField(null=True)),
                ("currency_code", models.CharField(max_length=10, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("project_markup_cost", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("pod_cost", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("tags", models.JSONField(null=True)),
                ("source_uuid", models.UUIDField(null=True)),
                (
                    "account_alias",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.awsaccountalias"
                    ),
                ),
                (
                    "cost_entry_bill",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.awscostentrybill"
                    ),
                ),
                (
                    "report_period",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.ocpusagereportperiod"
                    ),
                ),
            ],
            options={"db_table": "reporting_ocpawscostlineitem_project_daily_summary_p"},
        ),
        migrations.RunSQL(
            sql="""ALTER TABLE reporting_ocpawscostlineitem_project_daily_summary_p ALTER COLUMN "uuid" SET DEFAULT uuid_generate_v4()""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="OCPAWSCostLineItemDailySummaryP",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("cluster_id", models.CharField(max_length=50, null=True)),
                ("cluster_alias", models.CharField(max_length=256, null=True)),
                (
                    "namespace",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), size=None),
                ),
                ("node", models.CharField(max_length=253, null=True)),
                ("resource_id", models.CharField(max_length=253, null=True)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("product_code", models.CharField(max_length=50)),
                ("product_family", models.CharField(max_length=150, null=True)),
                ("instance_type", models.CharField(max_length=50, null=True)),
                ("usage_account_id", models.CharField(max_length=50)),
                ("availability_zone", models.CharField(max_length=50, null=True)),
                ("region", models.CharField(max_length=50, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("tags", models.JSONField(null=True)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("normalized_usage_amount", models.FloatField(null=True)),
                ("currency_code", models.CharField(max_length=10, null=True)),
                ("unblended_cost", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ("shared_projects", models.IntegerField(default=1)),
                ("project_costs", models.JSONField(null=True)),
                ("source_uuid", models.UUIDField(null=True)),
                (
                    "account_alias",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.awsaccountalias"
                    ),
                ),
                (
                    "cost_entry_bill",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.awscostentrybill"
                    ),
                ),
                (
                    "report_period",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.ocpusagereportperiod"
                    ),
                ),
            ],
            options={"db_table": "reporting_ocpawscostlineitem_daily_summary_p"},
        ),
        migrations.RunSQL(
            sql="""ALTER TABLE reporting_ocpawscostlineitem_daily_summary_p ALTER COLUMN "uuid" SET DEFAULT uuid_generate_v4()""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name="ocpazurecostlineitemprojectdailysummaryp",
            index=models.Index(fields=["usage_start"], name="p_ocpaz_prj_use_strt_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpazurecostlineitemprojectdailysummaryp",
            index=models.Index(fields=["namespace"], name="p_ocpaz_prj_nspc_idx", opclasses=["varchar_pattern_ops"]),
        ),
        migrations.AddIndex(
            model_name="ocpazurecostlineitemprojectdailysummaryp",
            index=models.Index(fields=["node"], name="p_ocpaz_prj_nde_idx", opclasses=["varchar_pattern_ops"]),
        ),
        migrations.AddIndex(
            model_name="ocpazurecostlineitemprojectdailysummaryp",
            index=models.Index(fields=["resource_id"], name="p_ocpaz_prj_rsrc_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpazurecostlineitemprojectdailysummaryp",
            index=django.contrib.postgres.indexes.GinIndex(fields=["pod_labels"], name="p_ocpaz_prj_pod_lbl_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpazurecostlineitemprojectdailysummaryp",
            index=models.Index(fields=["service_name"], name="p_ocpaz_prj_srvc_name_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpazurecostlineitemprojectdailysummaryp",
            index=models.Index(fields=["instance_type"], name="p_ocpaz_prj_inst_typ_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpazurecostlineitemdailysummaryp",
            index=models.Index(fields=["usage_start"], name="p_ocpaz_use_strt_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpazurecostlineitemdailysummaryp",
            index=models.Index(fields=["namespace"], name="p_ocpaz_nspc_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpazurecostlineitemdailysummaryp",
            index=models.Index(fields=["node"], name="p_ocpaz_nde_idx", opclasses=["varchar_pattern_ops"]),
        ),
        migrations.AddIndex(
            model_name="ocpazurecostlineitemdailysummaryp",
            index=models.Index(fields=["resource_id"], name="p_ocpaz_rsrc_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpazurecostlineitemdailysummaryp",
            index=django.contrib.postgres.indexes.GinIndex(fields=["tags"], name="p_ocpaz_tags_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpazurecostlineitemdailysummaryp",
            index=models.Index(fields=["service_name"], name="p_ocpaz_svc_name_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpazurecostlineitemdailysummaryp",
            index=models.Index(fields=["instance_type"], name="p_ocpaz_inst_typ_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            index=models.Index(fields=["usage_start"], name="p_cost_prj_sum_ocp_use_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            index=models.Index(
                fields=["namespace"], name="p_cost_prj_sum_nspc_idx", opclasses=["varchar_pattern_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            index=models.Index(fields=["node"], name="p_cost_prj_sum_nd_idx", opclasses=["varchar_pattern_ops"]),
        ),
        migrations.AddIndex(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            index=models.Index(fields=["resource_id"], name="p_cost_prj_sum_rsrc_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            index=django.contrib.postgres.indexes.GinIndex(fields=["pod_labels"], name="p_cost_prj_pod_lbls_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            index=models.Index(fields=["product_family"], name="p_ocpaws_prj_prd_fam_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            index=models.Index(fields=["instance_type"], name="p_ocpaws_prj_inst_typ_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostlineitemdailysummaryp",
            index=models.Index(fields=["usage_start"], name="p_cost_sum_ocpaws_use_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostlineitemdailysummaryp",
            index=models.Index(fields=["namespace"], name="p_cost_sum_ocpaws_nspc_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostlineitemdailysummaryp",
            index=models.Index(fields=["node"], name="p_cost_sum_ocpaws_nde_idx", opclasses=["varchar_pattern_ops"]),
        ),
        migrations.AddIndex(
            model_name="ocpawscostlineitemdailysummaryp",
            index=models.Index(fields=["resource_id"], name="p_cost_sum_ocpaws_rsrc_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostlineitemdailysummaryp",
            index=django.contrib.postgres.indexes.GinIndex(fields=["tags"], name="p_cost_ocpaws_tags_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostlineitemdailysummaryp",
            index=models.Index(fields=["product_family"], name="p_ocpaws_prod_fam_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostlineitemdailysummaryp",
            index=models.Index(fields=["instance_type"], name="p_ocpaws_inst_typ_idx"),
        ),
        migrations.RunPython(code=unset_pg_extended_mode, reverse_code=set_pg_extended_mode),
    ]
