# Generated by Django 3.1.13 on 2022-01-05 20:47
from django.db import migrations

from koku.database import set_pg_extended_mode
from koku.database import unset_pg_extended_mode


class Migration(migrations.Migration):

    dependencies = [("reporting", "0215_ocpaws_ocpazure_summary_partables")]

    operations = [
        migrations.RunPython(code=set_pg_extended_mode, reverse_code=unset_pg_extended_mode),
        # migrations.RemoveField(model_name="awscomputesummarybyservicep", name="account_alias"),
        # migrations.RemoveField(model_name="awscomputesummarybyservicep", name="organizational_unit"),
        # migrations.RemoveField(model_name="awscomputesummarybyservicep", name="source_uuid"),
        # migrations.RemoveField(model_name="awsstoragesummarybyregionp", name="account_alias"),
        # migrations.RemoveField(model_name="awsstoragesummarybyregionp", name="organizational_unit"),
        # migrations.RemoveField(model_name="awsstoragesummarybyregionp", name="source_uuid"),
        # migrations.RemoveField(model_name="awsstoragesummarybyservicep", name="account_alias"),
        # migrations.RemoveField(model_name="awsstoragesummarybyservicep", name="organizational_unit"),
        # migrations.RemoveField(model_name="awsstoragesummarybyservicep", name="source_uuid"),
        migrations.DeleteModel(name="AWSComputeSummaryByRegionP"),
        migrations.DeleteModel(name="AWSComputeSummaryByServiceP"),
        migrations.DeleteModel(name="AWSStorageSummaryByRegionP"),
        migrations.DeleteModel(name="AWSStorageSummaryByServiceP"),
        migrations.RunPython(code=unset_pg_extended_mode, reverse_code=set_pg_extended_mode),
    ]
