# Generated by Django 3.1.13 on 2022-01-05 20:47
from django.db import migrations

from koku.database import get_model

PartitionedTables = get_model("partitioned_tables")
TARGET_PARTABLES = (
    "reporting_aws_compute_summary_by_region_p",
    "reporting_aws_compute_summary_by_service_p",
    "reporting_aws_storage_summary_by_region_p",
    "reporting_aws_storage_summary_by_service_p",
)


def drop_partitions(app, schema_editor):
    PartitionedTables.objects.filter(partition_of_table_name__in=TARGET_PARTABLES).delete()


class Migration(migrations.Migration):

    dependencies = [("reporting", "0215_ocpaws_ocpazure_summary_partables")]

    operations = [
        migrations.RemoveField(model_name="awscomputesummarybyservicep", name="account_alias"),
        migrations.RemoveField(model_name="awscomputesummarybyservicep", name="organizational_unit"),
        migrations.RemoveField(model_name="awscomputesummarybyservicep", name="source_uuid"),
        migrations.RemoveField(model_name="awsstoragesummarybyregionp", name="account_alias"),
        migrations.RemoveField(model_name="awsstoragesummarybyregionp", name="organizational_unit"),
        migrations.RemoveField(model_name="awsstoragesummarybyregionp", name="source_uuid"),
        migrations.RemoveField(model_name="awsstoragesummarybyservicep", name="account_alias"),
        migrations.RemoveField(model_name="awsstoragesummarybyservicep", name="organizational_unit"),
        migrations.RemoveField(model_name="awsstoragesummarybyservicep", name="source_uuid"),
        migrations.RunPython(code=drop_partitions, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(name="AWSComputeSummaryByRegionP"),
        migrations.DeleteModel(name="AWSComputeSummaryByServiceP"),
        migrations.DeleteModel(name="AWSStorageSummaryByRegionP"),
        migrations.DeleteModel(name="AWSStorageSummaryByServiceP"),
    ]
