# Generated by Django 3.1.13 on 2022-01-24 16:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0216_drop_old_aws_partables")]

    operations = [
        migrations.AddField(
            model_name="ocppodsummarybyprojectp",
            name="pod_effective_usage_cpu_core_hours",
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="ocppodsummarybyprojectp",
            name="pod_effective_usage_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="ocppodsummaryp",
            name="pod_effective_usage_cpu_core_hours",
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="ocppodsummaryp",
            name="pod_effective_usage_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="ocpusagelineitemdailysummary",
            name="pod_effective_usage_cpu_core_hours",
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="ocpusagelineitemdailysummary",
            name="pod_effective_usage_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
    ]
