# Generated by Django 3.1.14 on 2022-01-12 19:59
from django.db import migrations

from koku.database import set_pg_extended_mode
from koku.database import unset_pg_extended_mode


class Migration(migrations.Migration):

    dependencies = [("reporting", "0217_auto_20220124_1634")]

    operations = [
        migrations.RunPython(code=set_pg_extended_mode, reverse_code=unset_pg_extended_mode),
        migrations.RemoveField(model_name="gcpcomputesummarybyregionp", name="source_uuid"),
        migrations.RemoveField(model_name="gcpcomputesummarybyservicep", name="source_uuid"),
        migrations.DeleteModel(name="GCPComputeSummaryByProjectP"),
        migrations.DeleteModel(name="GCPComputeSummaryByRegionP"),
        migrations.DeleteModel(name="GCPComputeSummaryByServiceP"),
        migrations.RunPython(code=unset_pg_extended_mode, reverse_code=set_pg_extended_mode),
    ]
