# Generated by Django 3.1.14 on 2022-01-28 12:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0218_rm_unused_gcp_partables")]

    operations = [
        migrations.AddField(
            model_name="ocpusagelineitemdaily",
            name="pod_effective_usage_cpu_core_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
        migrations.AddField(
            model_name="ocpusagelineitemdaily",
            name="pod_effective_usage_memory_byte_seconds",
            field=models.DecimalField(decimal_places=9, max_digits=73, null=True),
        ),
    ]
