# Generated by Django 3.2.12 on 2022-02-28 16:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0218_rm_unused_gcp_partables")]

    operations = [
        migrations.RunSQL("DROP VIEW IF EXISTS reporting_ocpusagelineitem_daily_summary_presto;"),
        migrations.AlterField(
            model_name="ocppodsummarybyprojectp",
            name="pod_effective_usage_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummarybyprojectp",
            name="pod_effective_usage_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummaryp",
            name="pod_effective_usage_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocppodsummaryp",
            name="pod_effective_usage_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="cluster_capacity_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="cluster_capacity_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="node_capacity_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="node_capacity_cpu_cores",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="node_capacity_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="node_capacity_memory_gigabytes",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="persistentvolumeclaim_capacity_gigabyte",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="persistentvolumeclaim_capacity_gigabyte_months",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="persistentvolumeclaim_usage_gigabyte_months",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="pod_effective_usage_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="pod_effective_usage_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="pod_limit_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="pod_limit_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="pod_request_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="pod_request_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="pod_usage_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="pod_usage_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="volume_request_storage_gigabyte_months",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
    ]
