# Generated by Django 3.2.12 on 2022-03-10 13:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0250_squash")]

    operations = [
        migrations.AlterField(
            model_name="ocpstoragelineitem", name="storageclass", field=models.CharField(max_length=253, null=True)
        ),
        migrations.AlterField(
            model_name="ocpstoragelineitemdaily",
            name="storageclass",
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="storageclass",
            field=models.CharField(max_length=253, null=True),
        ),
    ]
