# Generated by Django 3.2.12 on 2022-04-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0252_alter_ocpusagelineitemdailysummary_monthly_cost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocpusagereportperiod',
            name='ocp_on_cloud_updated_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
