# Generated by Django 3.2.12 on 2022-03-23 11:31
import uuid

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations
from django.db import models

from koku.database import set_pg_extended_mode
from koku.database import unset_pg_extended_mode


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_install_pg_stat_statements"),
        ("reporting", "0253_ocpusagereportperiod_ocp_on_cloud_updated_datetime"),
    ]

    operations = [
        migrations.RunPython(code=set_pg_extended_mode, reverse_code=unset_pg_extended_mode),
        migrations.CreateModel(
            name="OCIComputeSummaryByAccountP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("payer_tenant_id", models.CharField(max_length=80)),
                ("instance_type", models.CharField(max_length=50, null=True)),
                (
                    "resource_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), null=True, size=None
                    ),
                ),
                ("resource_count", models.IntegerField(null=True)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
            ],
            options={"db_table": "reporting_oci_compute_summary_by_account_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_oci_compute_summary_by_account_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCIComputeSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("instance_type", models.CharField(max_length=50, null=True)),
                (
                    "resource_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), null=True, size=None
                    ),
                ),
                ("resource_count", models.IntegerField(null=True)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
            ],
            options={"db_table": "reporting_oci_compute_summary_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_oci_compute_summary_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCICostEntry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("interval_start", models.DateTimeField()),
                ("interval_end", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="OCICostEntryBill",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("billing_resource", models.CharField(default="oci", max_length=80)),
                ("bill_type", models.CharField(max_length=50, null=True)),
                ("payer_tenant_id", models.CharField(max_length=80, null=True)),
                ("billing_period_start", models.DateTimeField()),
                ("billing_period_end", models.DateTimeField()),
                ("summary_data_creation_datetime", models.DateTimeField(null=True)),
                ("summary_data_updated_datetime", models.DateTimeField(null=True)),
                ("finalized_datetime", models.DateTimeField(null=True)),
                ("derived_cost_datetime", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OCICostEntryLineItemDailySummary",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField(null=True)),
                ("payer_tenant_id", models.CharField(max_length=80)),
                ("product_service", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=50, null=True)),
                ("instance_type", models.CharField(max_length=50, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                (
                    "resource_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
                ),
                ("resource_count", models.IntegerField(null=True)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
                ("cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("tags", models.JSONField(null=True)),
                ("source_uuid", models.UUIDField(null=True)),
            ],
            options={"db_table": "reporting_ocicostentrylineitem_daily_summary"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_ocicostentrylineitem_daily_summary ALTER COLUMN uuid SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCICostSummaryByAccountP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("payer_tenant_id", models.CharField(max_length=80)),
                ("cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
            ],
            options={"db_table": "reporting_oci_cost_summary_by_account_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_oci_cost_summary_by_account_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCICostSummaryByRegionP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("payer_tenant_id", models.CharField(max_length=80)),
                ("region", models.CharField(max_length=50, null=True)),
                ("cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
            ],
            options={"db_table": "reporting_oci_cost_summary_by_region_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_oci_cost_summary_by_region_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCICostSummaryByServiceP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("payer_tenant_id", models.CharField(max_length=80)),
                ("product_service", models.CharField(max_length=50)),
                ("cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
            ],
            options={"db_table": "reporting_oci_cost_summary_by_service_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_oci_cost_summary_by_service_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCICostSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
            ],
            options={"db_table": "reporting_oci_cost_summary_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_oci_cost_summary_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCIDatabaseSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("payer_tenant_id", models.CharField(max_length=80)),
                ("product_service", models.CharField(max_length=50)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
            ],
            options={"db_table": "reporting_oci_database_summary_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_oci_database_summary_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCIEnabledTagKeys",
            fields=[
                ("key", models.CharField(max_length=253, primary_key=True, serialize=False)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={"db_table": "reporting_ocienabledtagkeys"},
        ),
        migrations.CreateModel(
            name="OCINetworkSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("payer_tenant_id", models.CharField(max_length=80)),
                ("product_service", models.CharField(max_length=50)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
            ],
            options={"db_table": "reporting_oci_network_summary_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_oci_network_summary_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCIStorageSummaryByAccountP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("payer_tenant_id", models.CharField(max_length=80)),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("product_service", models.CharField(max_length=50)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
            ],
            options={"db_table": "reporting_oci_storage_summary_by_account_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_oci_storage_summary_by_account_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCIStorageSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("usage_amount", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("product_service", models.CharField(max_length=50)),
                ("unit", models.CharField(max_length=63, null=True)),
                ("cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("markup_cost", models.DecimalField(decimal_places=9, max_digits=24, null=True)),
                ("currency", models.CharField(max_length=10)),
            ],
            options={"db_table": "reporting_oci_storage_summary_p"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_oci_storage_summary_p ALTER COLUMN id SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCITagsSummary",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("key", models.TextField()),
                ("values", django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ("payer_tenant_id", models.TextField(null=True)),
            ],
            options={"db_table": "reporting_ocitags_summary"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_ocitags_summary ALTER COLUMN uuid SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.CreateModel(
            name="OCITagsValues",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("key", models.TextField()),
                ("value", models.TextField()),
                (
                    "payer_tenant_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
                ),
            ],
            options={"db_table": "reporting_ocitags_values"},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE reporting_ocitags_values ALTER COLUMN uuid SET DEFAULT uuid_generate_v4()",
            reverse_sql="select 1",
        ),
        migrations.AddIndex(
            model_name="ocitagsvalues", index=models.Index(fields=["key"], name="oci_tags_value_key_idx")
        ),
        migrations.AlterUniqueTogether(name="ocitagsvalues", unique_together={("key", "value")}),
        migrations.AddField(
            model_name="ocitagssummary",
            name="cost_entry_bill",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.ocicostentrybill"),
        ),
        migrations.AddField(
            model_name="ocistoragesummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AddField(
            model_name="ocistoragesummarybyaccountp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AddField(
            model_name="ocinetworksummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AddIndex(
            model_name="ocienabledtagkeys", index=models.Index(fields=["key", "enabled"], name="oci_enabled_key_index")
        ),
        migrations.AddField(
            model_name="ocidatabasesummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AddField(
            model_name="ocicostsummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AddField(
            model_name="ocicostsummarybyservicep",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AddField(
            model_name="ocicostsummarybyregionp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AddField(
            model_name="ocicostsummarybyaccountp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AddField(
            model_name="ocicostentrylineitemdailysummary",
            name="cost_entry_bill",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.ocicostentrybill"
            ),
        ),
        migrations.AddField(
            model_name="ocicostentrybill",
            name="provider",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.provider"),
        ),
        migrations.AddField(
            model_name="ocicostentry",
            name="bill",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.ocicostentrybill"),
        ),
        migrations.AddField(
            model_name="ocicomputesummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AddField(
            model_name="ocicomputesummarybyaccountp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid", null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ocitagssummary", unique_together={("key", "cost_entry_bill", "payer_tenant_id")}
        ),
        migrations.AddIndex(
            model_name="ocistoragesummaryp", index=models.Index(fields=["usage_start"], name="ocistorsumm_usage_start")
        ),
        migrations.AddIndex(
            model_name="ocistoragesummarybyaccountp",
            index=models.Index(fields=["usage_start"], name="ocistorsumm_acct_usage_start"),
        ),
        migrations.AddIndex(
            model_name="ocinetworksummaryp", index=models.Index(fields=["usage_start"], name="ocinetsumm_usage_start")
        ),
        migrations.AddIndex(
            model_name="ocinetworksummaryp",
            index=models.Index(fields=["product_service"], name="ocinetsumm_product_cd"),
        ),
        migrations.AddIndex(
            model_name="ocidatabasesummaryp", index=models.Index(fields=["usage_start"], name="ocidbsumm_usage_start")
        ),
        migrations.AddIndex(
            model_name="ocidatabasesummaryp",
            index=models.Index(fields=["product_service"], name="ocidbsumm_product_cd"),
        ),
        migrations.AddIndex(
            model_name="ocicostsummaryp", index=models.Index(fields=["usage_start"], name="ocicostsumm_usage_start")
        ),
        migrations.AddIndex(
            model_name="ocicostsummarybyservicep",
            index=models.Index(fields=["usage_start"], name="ocicostsumm_svc_usage_start"),
        ),
        migrations.AddIndex(
            model_name="ocicostsummarybyservicep",
            index=models.Index(fields=["product_service"], name="ocicostsumm_svc_prod_cd"),
        ),
        migrations.AddIndex(
            model_name="ocicostsummarybyregionp",
            index=models.Index(fields=["usage_start"], name="ocicostsumm_reg_usage_start"),
        ),
        migrations.AddIndex(
            model_name="ocicostsummarybyregionp", index=models.Index(fields=["region"], name="ocicostsumm_reg_region")
        ),
        migrations.AddIndex(
            model_name="ocicostsummarybyaccountp",
            index=models.Index(fields=["usage_start"], name="ocicostsumm_acct_usage_start"),
        ),
        migrations.AddIndex(
            model_name="ocicostentrylineitemdailysummary",
            index=models.Index(fields=["usage_start"], name="summary_oci_usage_start_idx"),
        ),
        migrations.AddIndex(
            model_name="ocicostentrylineitemdailysummary",
            index=models.Index(fields=["product_service"], name="summary_oci_product_code_idx"),
        ),
        migrations.AddIndex(
            model_name="ocicostentrylineitemdailysummary",
            index=models.Index(fields=["payer_tenant_id"], name="summary_oci_payer_tenant_idx"),
        ),
        migrations.AddIndex(
            model_name="ocicostentrylineitemdailysummary",
            index=django.contrib.postgres.indexes.GinIndex(fields=["tags"], name="tags_tags_idx"),
        ),
        migrations.AddIndex(
            model_name="ocicostentrylineitemdailysummary",
            index=models.Index(fields=["instance_type"], name="summary_oci_instance_type_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="ocicostentrybill",
            unique_together={("bill_type", "payer_tenant_id", "billing_period_start", "provider")},
        ),
        migrations.AddIndex(
            model_name="ocicostentry", index=models.Index(fields=["interval_start"], name="oci_interval_start_idx")
        ),
        migrations.AddIndex(
            model_name="ocicomputesummaryp", index=models.Index(fields=["usage_start"], name="ocicompsumm_usage_start")
        ),
        migrations.AddIndex(
            model_name="ocicomputesummaryp", index=models.Index(fields=["instance_type"], name="ocicompsumm_insttyp")
        ),
        migrations.AddIndex(
            model_name="ocicomputesummarybyaccountp",
            index=models.Index(fields=["usage_start"], name="ocicompsumm_acct_usage_start"),
        ),
        migrations.AddIndex(
            model_name="ocicomputesummarybyaccountp",
            index=models.Index(fields=["instance_type"], name="ocicompsumm_acct_insttyp"),
        ),
        migrations.RunPython(code=unset_pg_extended_mode, reverse_code=set_pg_extended_mode),
    ]
