# Generated by Django 3.2.13 on 2022-05-19 21:22
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reporting", "0254_oci_models")]

    operations = [
        # AWSCostEntryLineItem
        migrations.RunSQL(
            sql="""
TRUNCATE TABLE reporting_awscostentrylineitem ;
""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
DROP TABLE reporting_awscostentrylineitem
""",
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[migrations.DeleteModel("AWSCostEntryLineItem")],
        ),
        # AWSCostEntryLineItemDaily
        migrations.RunSQL(
            sql="""
TRUNCATE TABLE reporting_awscostentrylineitem_daily ;
""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
DROP TABLE reporting_awscostentrylineitem_daily ;
""",
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[migrations.DeleteModel("AWSCostEntryLineItemDaily")],
        ),
        # AzureCostEntryLineItemDaily
        migrations.RunSQL(
            sql="""
TRUNCATE TABLE reporting_azurecostentrylineitem_daily ;
""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
DROP TABLE reporting_azurecostentrylineitem_daily ;
""",
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[migrations.DeleteModel("AzureCostEntryLineItemDaily")],
        ),
        # GCPCostEntryLineItem
        migrations.RunSQL(
            sql="""
TRUNCATE TABLE reporting_gcpcostentrylineitem ;
""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
DROP TABLE reporting_gcpcostentrylineitem ;
""",
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[migrations.DeleteModel("GCPCostEntryLineItem")],
        ),
        # GCPCostEntryLineItemDaily
        migrations.RunSQL(
            sql="""
TRUNCATE TABLE reporting_gcpcostentrylineitem_daily ;
""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
DROP TABLE reporting_gcpcostentrylineitem_daily ;
""",
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[migrations.DeleteModel("GCPCostEntryLineItemDaily")],
        ),
        # OCPUsageLineItem
        migrations.RunSQL(
            sql="""
TRUNCATE TABLE reporting_ocpusagelineitem ;
""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
DROP TABLE reporting_ocpusagelineitem ;
""",
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[migrations.DeleteModel("OCPUsageLineItem")],
        ),
        # OCPUsageLineItemDaily
        migrations.RunSQL(
            sql="""
TRUNCATE TABLE reporting_ocpusagelineitem_daily ;
""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
DROP TABLE reporting_ocpusagelineitem_daily ;
""",
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[migrations.DeleteModel("OCPUsageLineItemDaily")],
        ),
        # OCPStorageLineItem
        migrations.RunSQL(
            sql="""
TRUNCATE TABLE reporting_ocpstoragelineitem ;
""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
DROP TABLE reporting_ocpstoragelineitem ;
""",
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[migrations.DeleteModel("OCPStorageLineItem")],
        ),
        # OCPStorageLineItemDaily
        migrations.RunSQL(
            sql="""
TRUNCATE TABLE reporting_ocpstoragelineitem_daily ;
""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
DROP TABLE reporting_ocpstoragelineitem_daily ;
""",
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[migrations.DeleteModel("OCPStorageLineItemDaily")],
        ),
    ]
