# Generated by Django 3.2.13 on 2022-06-17 19:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("reporting", "0255_ocp_label_indices")]

    operations = [
        mygrations.RunSQL(
            sql="""
alter table reporting_azureenabledtagkeys
        add column enabled boolean not null default true using true;
create index azure_enabled_covering_ix
    on reporting_azureenabledtagkeys (key, enabled);
            """,
            reverse_sql="""
drop index azure_enabled_covering_ix;
alter table reporting_azureenabledtagkeys
       drop column enabled;
            """,
            state_operations=[
                migrations.AddField(
                    model_name="azureenabledtagkeys",
                    name="enabled",
                    field=models.BooleanField(default=True),
                ),
                migrations.AddIndex(
                    model_name="azureenabledtagkeys",
                    index=models.Index(fields=["key", "enabled"], name="azure_enabled_covering_ix"),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
alter table reporting_gcpenabledtagkeys
        add column enabled boolean not null default true using true;
create index gcp_enabled_covering_ix
    on reporting_gcpenabledtagkeys (key, enabled);
            """,
            reverse_sql="""
drop index gcp_enabled_covering_ix;
alter table reporting_gcpenabledtagkeys
       drop column enabled;
            """,
            state_operations=[
                migrations.AddField(
                    model_name="gcpenabledtagkeys",
                    name="enabled",
                    field=models.BooleanField(default=True),
                ),
                migrations.AddIndex(
                    model_name="gcpenabledtagkeys",
                    index=models.Index(fields=["key", "enabled"], name="gcp_enabled_covering_ix"),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
alter table reporting_ocpenabledtagkeys
        add column enabled boolean not null default true using true;
create index ocp_enabled_covering_ix
    on reporting_ocpenabledtagkeys (key, enabled);
            """,
            reverse_sql="""
drop index ocp_enabled_covering_ix;
alter table reporting_ocpenabledtagkeys
       drop column enabled;
            """,
            state_operations=[
                migrations.AddField(
                    model_name="ocpenabledtagkeys",
                    name="enabled",
                    field=models.BooleanField(default=True),
                ),
                migrations.AddIndex(
                    model_name="ocpenabledtagkeys",
                    index=models.Index(fields=["key", "enabled"], name="ocp_enabled_covering_ix"),
                ),
            ],
        ),
    ]
