# Generated by Django 3.2.13 on 2022-06-10 23:01
from django.db import migrations

ALTER_ADD_SQL = """
alter table reporting_azureenabledtagkeys
        add column if not exists enabled boolean not null default true
;
"""
ALTER_DROP_SQL = """
alter table reporting_azureenabledtagkeys
       drop column if exists enabled
;
"""
CREATE_INDEX_SQL = """
create index if not exists reporting_azureenabled_tag_keys_key_enabled
    on reporting_azureenabledtagkeys (key, enabled)
;
"""
DROP_INDEX_SQL = """
drop index if exists reporting_azureenabled_tag_keys_key_enabled
;
"""


class Migration(migrations.Migration):

    dependencies = [("reporting", "0255_ocp_label_indices")]

    operations = [
        migrations.RunSQL(
            sql=ALTER_ADD_SQL,
            reverse_sql=ALTER_DROP_SQL,
            state_operations=[None],
        ),
        migrations.RunSQL(
            sql=CREATE_INDEX_SQL,
            reverse_sql=DROP_INDEX_SQL,
            state_operations=[None],
        ),
    ]
