# Generated by Django 3.2.12 on 2022-06-28 14:37
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0256_enabled_keys_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocpcostsummarybynodep",
            name="raw_currency",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ocpcostsummarybyprojectp",
            name="raw_currency",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ocpcostsummaryp",
            name="raw_currency",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ocppodsummarybyprojectp",
            name="raw_currency",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ocppodsummaryp",
            name="raw_currency",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ocpusagelineitemdailysummary",
            name="raw_currency",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ocpvolumesummarybyprojectp",
            name="raw_currency",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ocpvolumesummaryp",
            name="raw_currency",
            field=models.TextField(null=True),
        ),
    ]
