# Generated by Django 3.2.15 on 2022-09-12 18:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0257_raw_currency_ocp_on_cloud"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocpnode",
            name="node_role",
            field=models.TextField(null=True),
        ),
    ]
