# Generated by Django 3.2.15 on 2022-09-21 12:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0257_raw_currency_ocp_on_cloud"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="awscostentrylineitemdailysummary",
            index=models.Index(fields=["region"], name="summary_region_idx"),
        ),
        migrations.AddIndex(
            model_name="awscostentrylineitemdailysummary",
            index=models.Index(fields=["availability_zone"], name="summary_zone_idx"),
        ),
        migrations.AddIndex(
            model_name="azurecostentrylineitemdailysummary",
            index=models.Index(fields=["resource_location"], name="ix_azurecstentrydlysumm_svc"),
        ),
        migrations.AddIndex(
            model_name="azurecostentrylineitemdailysummary",
            index=models.Index(fields=["subscription_guid"], name="ix_azurecstentrydlysumm_sub_id"),
        ),
        migrations.AddIndex(
            model_name="azurecostentrylineitemdailysummary",
            index=models.Index(fields=["instance_type"], name="ix_azurecstentrydlysumm_instyp"),
        ),
    ]
