# Generated by Django 3.2.16 on 2022-10-13 17:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0259_ocpnode_node_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awscostentrylineitem",
            name="product_code",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="awscostentrylineitemdaily",
            name="product_code",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="awscostentrylineitemdailysummary",
            name="product_code",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="awscostsummarybyservicep",
            name="product_code",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="awsdatabasesummaryp",
            name="product_code",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="awsnetworksummaryp",
            name="product_code",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="ocpawscostlineitemdailysummaryp",
            name="product_code",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            name="product_code",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="ocpawscostsummarybyservicep",
            name="product_code",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="ocpawsdatabasesummaryp",
            name="product_code",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="ocpawsnetworksummaryp",
            name="product_code",
            field=models.TextField(),
        ),
    ]
