# Generated by Cody 3.2.15 on 2022-10-05 15:40
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0261_ocpgcpcostlineitemprojectdailysummaryp_pod_credit"),
    ]

    operations = [
        migrations.RunSQL("""select 1;"""),
    ]
