# Generated by Django 3.2.15 on 2022-11-02 11:20
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


def add_platform_category(apps, schema_editor):
    OpenshiftCostCategory = apps.get_model("reporting", "OpenshiftCostCategory")
    category = OpenshiftCostCategory(
        name="platform",
        description="Default OpenShift projects bucketed into a Platform group",
        source_type="OCP",
        system_default=True,
        namespace=["openshift-%", "kube-%", "Platform Unallocated Capacity"],
        label=[],
    )
    category.save()


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0262_standard_numeric_on_calculated_feilds"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenshiftCostCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField()),
                ("source_type", models.TextField()),
                ("system_default", models.BooleanField(default=False)),
                ("namespace", django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ("label", django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            options={
                "db_table": "reporting_ocp_cost_category",
            },
        ),
        migrations.AddField(
            model_name="ocpcostsummarybynodep",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpcostsummarybyprojectp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpcostsummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocppodsummarybyprojectp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocppodsummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpusagelineitemdailysummary",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpvolumesummarybyprojectp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpvolumesummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpallcomputesummarypt",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpallcostlineitemdailysummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpallcostlineitemprojectdailysummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpallcostsummarybyaccountpt",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpallcostsummarybyregionpt",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpallcostsummarybyservicept",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpallcostsummarypt",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpalldatabasesummarypt",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpallnetworksummarypt",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpallstoragesummarypt",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpawscomputesummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemdailysummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyaccountp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyregionp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyservicep",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpawscostsummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpawsdatabasesummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpawsnetworksummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpawsstoragesummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpazurecomputesummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpazurecostlineitemdailysummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpazurecostlineitemprojectdailysummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpazurecostsummarybyaccountp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpazurecostsummarybylocationp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpazurecostsummarybyservicep",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpazurecostsummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpazuredatabasesummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpazurenetworksummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpazurestoragesummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpgcpcomputesummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpgcpcostlineitemdailysummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpgcpcostlineitemprojectdailysummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpgcpcostsummarybyaccountp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpgcpcostsummarybygcpprojectp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpgcpcostsummarybyregionp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpgcpcostsummarybyservicep",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpgcpcostsummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpgcpdatabasesummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpgcpnetworksummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpgcpstoragesummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
            ),
        ),
        migrations.RunPython(add_platform_category),
    ]
