# Generated by Django 3.2.15 on 2022-11-01 16:03
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0262_standard_numeric_on_calculated_feilds"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField()),
                ("source_type", models.TextField()),
                ("system_default", models.BooleanField(default=True)),
                ("namespace", django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ("label", django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            options={
                "db_table": "reporting_ocp_cost_category",
            },
        ),
        migrations.AddField(
            model_name="ocpcostsummarybynodep",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpcostsummarybyprojectp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpcostsummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpnamespacelabellineitem",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpnode",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpnodelabellineitem",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpnodelabellineitemdaily",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocppodsummarybyprojectp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocppodsummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpproject",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocppvc",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpstoragelineitem",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpstoragelineitemdaily",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpstoragevolumelabelsummary",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpusagelineitem",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpusagelineitemdaily",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpusagelineitemdailysummary",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpusagepodlabelsummary",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpusagereport",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpvolumesummarybyprojectp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
        migrations.AddField(
            model_name="ocpvolumesummaryp",
            name="cost_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.costcategory"
            ),
        ),
    ]
