# Generated by Django 3.2.16 on 2022-11-10 13:28
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0263_add_cost_categroy"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocpawscomputesummaryp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscomputesummaryp",
            name="markup_cost_blended",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscomputesummaryp",
            name="markup_cost_savingsplan",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscomputesummaryp",
            name="savingsplan_effective_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemdailysummaryp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemdailysummaryp",
            name="markup_cost_blended",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemdailysummaryp",
            name="markup_cost_savingsplan",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemdailysummaryp",
            name="savingsplan_effective_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            name="markup_cost_blended",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            name="markup_cost_savingsplan",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            name="savingsplan_effective_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyaccountp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyaccountp",
            name="markup_cost_blended",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyaccountp",
            name="markup_cost_savingsplan",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyaccountp",
            name="savingsplan_effective_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyregionp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyregionp",
            name="markup_cost_blended",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyregionp",
            name="markup_cost_savingsplan",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyregionp",
            name="savingsplan_effective_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyservicep",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyservicep",
            name="markup_cost_blended",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyservicep",
            name="markup_cost_savingsplan",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyservicep",
            name="savingsplan_effective_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummaryp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummaryp",
            name="markup_cost_blended",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummaryp",
            name="markup_cost_savingsplan",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummaryp",
            name="savingsplan_effective_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawsdatabasesummaryp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawsdatabasesummaryp",
            name="markup_cost_blended",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawsdatabasesummaryp",
            name="markup_cost_savingsplan",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawsdatabasesummaryp",
            name="savingsplan_effective_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawsnetworksummaryp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawsnetworksummaryp",
            name="markup_cost_blended",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawsnetworksummaryp",
            name="markup_cost_savingsplan",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawsnetworksummaryp",
            name="savingsplan_effective_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawsstoragesummaryp",
            name="blended_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="ocpawsstoragesummaryp",
            name="markup_cost_blended",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawsstoragesummaryp",
            name="markup_cost_savingsplan",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawsstoragesummaryp",
            name="savingsplan_effective_cost",
            field=models.DecimalField(decimal_places=9, max_digits=24, null=True),
        ),
    ]
