# Generated by Django 3.2.15 on 2022-11-14 18:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0264_ocpaws_cost_fields"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocp_cost_summary_by_node_p
                    ADD COLUMN IF NOT EXISTS cost_model_cpu_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_memory_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_volume_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_rate_type text
            """,
            state_operations=[
                migrations.AddField(
                    model_name="ocpcostsummarybynodep",
                    name="cost_model_cpu_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AddField(
                    model_name="ocpcostsummarybynodep",
                    name="cost_model_memory_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AddField(
                    model_name="ocpcostsummarybynodep",
                    name="cost_model_rate_type",
                    field=models.TextField(null=True),
                ),
                migrations.AddField(
                    model_name="ocpcostsummarybynodep",
                    name="cost_model_volume_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocp_cost_summary_by_project_p
                    ADD COLUMN IF NOT EXISTS cost_model_cpu_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_memory_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_volume_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_rate_type text
            """,
            state_operations=[
                migrations.AddField(
                    model_name="ocpcostsummarybyprojectp",
                    name="cost_model_cpu_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AddField(
                    model_name="ocpcostsummarybyprojectp",
                    name="cost_model_memory_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AddField(
                    model_name="ocpcostsummarybyprojectp",
                    name="cost_model_rate_type",
                    field=models.TextField(null=True),
                ),
                migrations.AddField(
                    model_name="ocpcostsummarybyprojectp",
                    name="cost_model_volume_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocp_cost_summary_p
                    ADD COLUMN IF NOT EXISTS cost_model_cpu_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_memory_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_volume_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_rate_type text
            """,
            state_operations=[
                migrations.AddField(
                    model_name="ocpcostsummaryp",
                    name="cost_model_cpu_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AddField(
                    model_name="ocpcostsummaryp",
                    name="cost_model_memory_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AddField(
                    model_name="ocpcostsummaryp",
                    name="cost_model_rate_type",
                    field=models.TextField(null=True),
                ),
                migrations.AddField(
                    model_name="ocpcostsummaryp",
                    name="cost_model_volume_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocp_pod_summary_by_project_p
                    ADD COLUMN IF NOT EXISTS cost_model_cpu_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_memory_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_volume_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_rate_type text
            """,
            state_operations=[
                migrations.AddField(
                    model_name="ocppodsummarybyprojectp",
                    name="cost_model_cpu_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AddField(
                    model_name="ocppodsummarybyprojectp",
                    name="cost_model_memory_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AddField(
                    model_name="ocppodsummarybyprojectp",
                    name="cost_model_rate_type",
                    field=models.TextField(null=True),
                ),
                migrations.AddField(
                    model_name="ocppodsummarybyprojectp",
                    name="cost_model_volume_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocp_pod_summary_p
                    ADD COLUMN IF NOT EXISTS cost_model_cpu_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_memory_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_volume_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_rate_type text
            """,
            state_operations=[
                migrations.AddField(
                    model_name="ocppodsummaryp",
                    name="cost_model_cpu_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AddField(
                    model_name="ocppodsummaryp",
                    name="cost_model_memory_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AddField(
                    model_name="ocppodsummaryp",
                    name="cost_model_rate_type",
                    field=models.TextField(null=True),
                ),
                migrations.AddField(
                    model_name="ocppodsummaryp",
                    name="cost_model_volume_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocpusagelineitem_daily_summary
                    ADD COLUMN IF NOT EXISTS cost_model_cpu_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_memory_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_volume_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_rate_type text
            """,
            state_operations=[
                migrations.AddField(
                    model_name="ocpusagelineitemdailysummary",
                    name="cost_model_cpu_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AddField(
                    model_name="ocpusagelineitemdailysummary",
                    name="cost_model_memory_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AddField(
                    model_name="ocpusagelineitemdailysummary",
                    name="cost_model_rate_type",
                    field=models.TextField(null=True),
                ),
                migrations.AddField(
                    model_name="ocpusagelineitemdailysummary",
                    name="cost_model_volume_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocp_volume_summary_by_project_p
                    ADD COLUMN IF NOT EXISTS cost_model_cpu_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_memory_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_volume_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_rate_type text
            """,
            state_operations=[
                migrations.AddField(
                    model_name="ocpvolumesummarybyprojectp",
                    name="cost_model_cpu_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AddField(
                    model_name="ocpvolumesummarybyprojectp",
                    name="cost_model_memory_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AddField(
                    model_name="ocpvolumesummarybyprojectp",
                    name="cost_model_rate_type",
                    field=models.TextField(null=True),
                ),
                migrations.AddField(
                    model_name="ocpvolumesummarybyprojectp",
                    name="cost_model_volume_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocp_volume_summary_p
                    ADD COLUMN IF NOT EXISTS cost_model_cpu_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_memory_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_volume_cost NUMERIC(33, 15),
                    ADD COLUMN IF NOT EXISTS cost_model_rate_type text
            """,
            state_operations=[
                migrations.AddField(
                    model_name="ocpvolumesummaryp",
                    name="cost_model_cpu_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AddField(
                    model_name="ocpvolumesummaryp",
                    name="cost_model_memory_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                migrations.AddField(
                    model_name="ocpvolumesummaryp",
                    name="cost_model_rate_type",
                    field=models.TextField(null=True),
                ),
                migrations.AddField(
                    model_name="ocpvolumesummaryp",
                    name="cost_model_volume_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="ocpusagelineitemdailysummary",
            index=models.Index(fields=["cost_model_rate_type"], name="cost_model_rate_type_idx"),
        ),
    ]
