# Generated by Django 3.2.15 on 2022-12-07 14:43
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0265_auto_20221114_1806"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocpgcp_compute_summary_p
                    ALTER COLUMN markup_cost TYPE NUMERIC(30, 15),
                    ALTER COLUMN unblended_cost TYPE NUMERIC(30, 15)
            """,
            state_operations=[
                migrations.AlterField(
                    model_name="ocpgcpcomputesummaryp",
                    name="markup_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
                migrations.AlterField(
                    model_name="ocpgcpcomputesummaryp",
                    name="unblended_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocpgcp_cost_summary_by_account_p
                    ALTER COLUMN markup_cost TYPE NUMERIC(30, 15),
                    ALTER COLUMN unblended_cost TYPE NUMERIC(30, 15)
            """,
            state_operations=[
                migrations.AlterField(
                    model_name="ocpgcpcostsummarybyaccountp",
                    name="markup_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
                migrations.AlterField(
                    model_name="ocpgcpcostsummarybyaccountp",
                    name="unblended_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocpgcp_cost_summary_by_gcp_project_p
                    ALTER COLUMN markup_cost TYPE NUMERIC(30, 15),
                    ALTER COLUMN unblended_cost TYPE NUMERIC(30, 15)
            """,
            state_operations=[
                migrations.AlterField(
                    model_name="ocpgcpcostsummarybygcpprojectp",
                    name="markup_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
                migrations.AlterField(
                    model_name="ocpgcpcostsummarybygcpprojectp",
                    name="unblended_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocpgcp_cost_summary_by_region_p
                    ALTER COLUMN markup_cost TYPE NUMERIC(30, 15),
                    ALTER COLUMN unblended_cost TYPE NUMERIC(30, 15)
            """,
            state_operations=[
                migrations.AlterField(
                    model_name="ocpgcpcostsummarybyregionp",
                    name="markup_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
                migrations.AlterField(
                    model_name="ocpgcpcostsummarybyregionp",
                    name="unblended_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocpgcp_cost_summary_by_service_p
                    ALTER COLUMN markup_cost TYPE NUMERIC(30, 15),
                    ALTER COLUMN unblended_cost TYPE NUMERIC(30, 15)
            """,
            state_operations=[
                migrations.AlterField(
                    model_name="ocpgcpcostsummarybyservicep",
                    name="markup_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
                migrations.AlterField(
                    model_name="ocpgcpcostsummarybyservicep",
                    name="unblended_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocpgcp_cost_summary_p
                    ALTER COLUMN markup_cost TYPE NUMERIC(30, 15),
                    ALTER COLUMN unblended_cost TYPE NUMERIC(30, 15)
            """,
            state_operations=[
                migrations.AlterField(
                    model_name="ocpgcpcostsummaryp",
                    name="markup_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
                migrations.AlterField(
                    model_name="ocpgcpcostsummaryp",
                    name="unblended_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocpgcp_database_summary_p
                    ALTER COLUMN markup_cost TYPE NUMERIC(30, 15),
                    ALTER COLUMN unblended_cost TYPE NUMERIC(30, 15)
            """,
            state_operations=[
                migrations.AlterField(
                    model_name="ocpgcpdatabasesummaryp",
                    name="markup_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
                migrations.AlterField(
                    model_name="ocpgcpdatabasesummaryp",
                    name="unblended_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocpgcp_network_summary_p
                    ALTER COLUMN markup_cost TYPE NUMERIC(30, 15),
                    ALTER COLUMN unblended_cost TYPE NUMERIC(30, 15)
            """,
            state_operations=[
                migrations.AlterField(
                    model_name="ocpgcpnetworksummaryp",
                    name="markup_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
                migrations.AlterField(
                    model_name="ocpgcpnetworksummaryp",
                    name="unblended_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE reporting_ocpgcp_storage_summary_p
                    ALTER COLUMN markup_cost TYPE NUMERIC(30, 15),
                    ALTER COLUMN unblended_cost TYPE NUMERIC(30, 15)
            """,
            state_operations=[
                migrations.AlterField(
                    model_name="ocpgcpstoragesummaryp",
                    name="markup_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
                migrations.AlterField(
                    model_name="ocpgcpstoragesummaryp",
                    name="unblended_cost",
                    field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
                ),
            ],
        ),
    ]
