# Generated by Django 3.2.15 on 2023-01-23 17:48
import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_exchangeratedictionary"),
        ("reporting", "0267_update_cost_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinimalReport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("completed_timestamp", models.DateTimeField(null=True)),
                (
                    "reports_list",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None),
                ),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.provider")),
            ],
        ),
    ]
