# Generated by Django 3.2.15 on 2023-01-10 15:23
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_exchangeratedictionary"),
        ("reporting", "0267_update_cost_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="HCSReport",
            fields=[
                ("task_uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("completed_timestamp", models.DateTimeField(null=True)),
                ("report_location", models.CharField(max_length=256)),
                (
                    "provider",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="api.provider"),
                ),
            ],
        ),
    ]
