# Generated by Django 3.2.16 on 2023-01-27 16:27
import django.contrib.postgres.indexes
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0268_ingressreports"),
    ]

    operations = [
        migrations.AddField(
            model_name="awscostentrylineitemdailysummary",
            name="cost_category",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            name="aws_cost_category",
            field=models.JSONField(null=True),
        ),
        migrations.AddIndex(
            model_name="awscostentrylineitemdailysummary",
            index=django.contrib.postgres.indexes.GinIndex(fields=["cost_category"], name="cost_category_idx"),
        ),
        migrations.AddIndex(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            index=django.contrib.postgres.indexes.GinIndex(fields=["aws_cost_category"], name="aws_cost_category_idx"),
        ),
    ]
