# Generated by Django 3.2.18 on 2023-03-01 16:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0269_auto_20230127_1627"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocpcostsummarybynodep",
            name="distributed_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpcostsummarybyprojectp",
            name="distributed_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpcostsummaryp",
            name="distributed_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocppodsummarybyprojectp",
            name="distributed_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocppodsummaryp",
            name="distributed_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpusagelineitemdailysummary",
            name="distributed_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpvolumesummarybyprojectp",
            name="distributed_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpvolumesummaryp",
            name="distributed_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
    ]
