# Generated by Django 3.2.18 on 2023-03-03 19:47
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0269_auto_20230127_1627"),
    ]
    operations = [
        migrations.RemoveField(
            model_name="azurecostentrylineitemdailysummary",
            name="meter",
        ),
        migrations.RunSQL(
            sql="""
            -- AWS
            TRUNCATE TABLE reporting_awscostentrylineitem_daily;
            DROP TABLE reporting_awscostentrylineitem_daily;
            TRUNCATE TABLE reporting_awscostentrylineitem;
            DROP TABLE reporting_awscostentrylineitem;
            TRUNCATE TABLE reporting_awscostentry;
            DROP TABLE reporting_awscostentry;
            TRUNCATE TABLE reporting_awscostentrypricing;
            DROP TABLE reporting_awscostentrypricing;
            TRUNCATE TABLE reporting_awscostentryreservation;
            DROP TABLE reporting_awscostentryreservation;
            TRUNCATE TABLE reporting_awscostentryproduct;
            DROP TABLE reporting_awscostentryproduct;
            -- Azure
            TRUNCATE TABLE reporting_azurecostentrylineitem_daily;
            DROP TABLE reporting_azurecostentrylineitem_daily;
            TRUNCATE TABLE reporting_azurecostentryproductservice;
            DROP TABLE reporting_azurecostentryproductservice;
            TRUNCATE TABLE reporting_azuremeter;
            DROP TABLE reporting_azuremeter;
            -- GCP
            TRUNCATE TABLE reporting_gcpcostentrylineitem;
            DROP TABLE reporting_gcpcostentrylineitem;
            TRUNCATE TABLE reporting_gcpcostentrylineitem_daily;
            DROP TABLE reporting_gcpcostentrylineitem_daily;
            TRUNCATE TABLE reporting_gcpcostentryproductservice;
            DROP TABLE reporting_gcpcostentryproductservice;
            TRUNCATE TABLE reporting_gcpproject;
            DROP TABLE reporting_gcpproject;
            -- OCP
            TRUNCATE TABLE reporting_ocpnamespacelabellineitem;
            DROP TABLE reporting_ocpnamespacelabellineitem;
            TRUNCATE TABLE reporting_ocpnodelabellineitem;
            DROP TABLE reporting_ocpnodelabellineitem;
            TRUNCATE TABLE reporting_ocpnodelabellineitem_daily;
            DROP TABLE reporting_ocpnodelabellineitem_daily;
            TRUNCATE TABLE reporting_ocpstoragelineitem;
            DROP TABLE reporting_ocpstoragelineitem;
            TRUNCATE TABLE reporting_ocpstoragelineitem_daily;
            DROP TABLE reporting_ocpstoragelineitem_daily;
            TRUNCATE TABLE reporting_ocpusagelineitem;
            DROP TABLE reporting_ocpusagelineitem;
            TRUNCATE TABLE reporting_ocpusagelineitem_daily;
            DROP TABLE reporting_ocpusagelineitem_daily;
            TRUNCATE TABLE reporting_ocpusagereport;
            DROP TABLE reporting_ocpusagereport;
            """,
            state_operations=[
                migrations.RemoveField(
                    model_name="awscostentrylineitem",
                    name="cost_entry",
                ),
                migrations.RemoveField(
                    model_name="awscostentrylineitem",
                    name="cost_entry_bill",
                ),
                migrations.RemoveField(
                    model_name="awscostentrylineitem",
                    name="cost_entry_pricing",
                ),
                migrations.RemoveField(
                    model_name="awscostentrylineitem",
                    name="cost_entry_product",
                ),
                migrations.RemoveField(
                    model_name="awscostentrylineitem",
                    name="cost_entry_reservation",
                ),
                migrations.RemoveField(
                    model_name="awscostentrylineitemdaily",
                    name="cost_entry_bill",
                ),
                migrations.RemoveField(
                    model_name="awscostentrylineitemdaily",
                    name="cost_entry_pricing",
                ),
                migrations.RemoveField(
                    model_name="awscostentrylineitemdaily",
                    name="cost_entry_product",
                ),
                migrations.RemoveField(
                    model_name="awscostentrylineitemdaily",
                    name="cost_entry_reservation",
                ),
                migrations.AlterUniqueTogether(
                    name="awscostentrypricing",
                    unique_together=None,
                ),
                migrations.AlterUniqueTogether(
                    name="awscostentryproduct",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="azurecostentrylineitemdaily",
                    name="cost_entry_bill",
                ),
                migrations.RemoveField(
                    model_name="azurecostentrylineitemdaily",
                    name="cost_entry_product",
                ),
                migrations.RemoveField(
                    model_name="azurecostentrylineitemdaily",
                    name="meter",
                ),
                migrations.AlterUniqueTogether(
                    name="azurecostentryproductservice",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="azurecostentryproductservice",
                    name="provider",
                ),
                migrations.RemoveField(
                    model_name="azuremeter",
                    name="provider",
                ),
                migrations.RemoveField(
                    model_name="gcpcostentrylineitem",
                    name="cost_entry_bill",
                ),
                migrations.RemoveField(
                    model_name="gcpcostentrylineitem",
                    name="cost_entry_product",
                ),
                migrations.RemoveField(
                    model_name="gcpcostentrylineitem",
                    name="project",
                ),
                migrations.RemoveField(
                    model_name="gcpcostentrylineitemdaily",
                    name="cost_entry_bill",
                ),
                migrations.RemoveField(
                    model_name="gcpcostentrylineitemdaily",
                    name="cost_entry_product",
                ),
                migrations.RemoveField(
                    model_name="gcpcostentrylineitemdaily",
                    name="project",
                ),
                migrations.AlterUniqueTogether(
                    name="gcpcostentryproductservice",
                    unique_together=None,
                ),
                migrations.AlterUniqueTogether(
                    name="ocpnamespacelabellineitem",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="ocpnamespacelabellineitem",
                    name="report",
                ),
                migrations.RemoveField(
                    model_name="ocpnamespacelabellineitem",
                    name="report_period",
                ),
                migrations.AlterUniqueTogether(
                    name="ocpnodelabellineitem",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="ocpnodelabellineitem",
                    name="report",
                ),
                migrations.RemoveField(
                    model_name="ocpnodelabellineitem",
                    name="report_period",
                ),
                migrations.RemoveField(
                    model_name="ocpnodelabellineitemdaily",
                    name="report_period",
                ),
                migrations.AlterUniqueTogether(
                    name="ocpstoragelineitem",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="ocpstoragelineitem",
                    name="report",
                ),
                migrations.RemoveField(
                    model_name="ocpstoragelineitem",
                    name="report_period",
                ),
                migrations.RemoveField(
                    model_name="ocpstoragelineitemdaily",
                    name="report_period",
                ),
                migrations.AlterUniqueTogether(
                    name="ocpusagelineitem",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="ocpusagelineitem",
                    name="report",
                ),
                migrations.RemoveField(
                    model_name="ocpusagelineitem",
                    name="report_period",
                ),
                migrations.RemoveField(
                    model_name="ocpusagelineitemdaily",
                    name="report_period",
                ),
                migrations.AlterUniqueTogether(
                    name="ocpusagereport",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="ocpusagereport",
                    name="report_period",
                ),
                migrations.DeleteModel(
                    name="AWSCostEntry",
                ),
                migrations.DeleteModel(
                    name="AWSCostEntryLineItem",
                ),
                migrations.DeleteModel(
                    name="AWSCostEntryLineItemDaily",
                ),
                migrations.DeleteModel(
                    name="AWSCostEntryPricing",
                ),
                migrations.DeleteModel(
                    name="AWSCostEntryProduct",
                ),
                migrations.DeleteModel(
                    name="AWSCostEntryReservation",
                ),
                migrations.DeleteModel(
                    name="AzureCostEntryLineItemDaily",
                ),
                migrations.DeleteModel(
                    name="AzureCostEntryProductService",
                ),
                migrations.DeleteModel(
                    name="AzureMeter",
                ),
                migrations.DeleteModel(
                    name="GCPCostEntryLineItem",
                ),
                migrations.DeleteModel(
                    name="GCPCostEntryLineItemDaily",
                ),
                migrations.DeleteModel(
                    name="GCPCostEntryProductService",
                ),
                migrations.DeleteModel(
                    name="GCPProject",
                ),
                migrations.DeleteModel(
                    name="OCPNamespaceLabelLineItem",
                ),
                migrations.DeleteModel(
                    name="OCPNodeLabelLineItem",
                ),
                migrations.DeleteModel(
                    name="OCPNodeLabelLineItemDaily",
                ),
                migrations.DeleteModel(
                    name="OCPStorageLineItem",
                ),
                migrations.DeleteModel(
                    name="OCPStorageLineItemDaily",
                ),
                migrations.DeleteModel(
                    name="OCPUsageLineItem",
                ),
                migrations.DeleteModel(
                    name="OCPUsageLineItemDaily",
                ),
                migrations.DeleteModel(
                    name="OCPUsageReport",
                ),
            ],
        ),
    ]
