# Generated by Django 3.2.18 on 2023-02-22 00:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0269_auto_20230127_1627"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocpenabledtagkeys",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL("ALTER TABLE reporting_ocpenabledtagkeys ALTER COLUMN enabled SET DEFAULT false"),
    ]
