# Generated by Django 3.2.18 on 2023-03-09 19:24
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0271_alter_ocpenabledtagkeys_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingressreports",
            name="sources_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="ingressreports",
            name="status",
            field=models.TextField(default="pending"),
        ),
    ]
