# Generated by Django 3.2.18 on 2023-03-15 15:07
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0272_auto_20230309_1924"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            name="namespace",
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AlterField(
            model_name="ocpazurecostlineitemprojectdailysummaryp",
            name="namespace",
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AlterField(
            model_name="ocpgcpcostlineitemprojectdailysummaryp",
            name="namespace",
            field=models.CharField(max_length=253, null=True),
        ),
    ]
