# Generated by Django 3.2.18 on 2023-03-31 15:32
import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0274_alter_ocpallcostlineitemprojectdailysummaryp_namespace"),
    ]

    operations = [
        migrations.CreateModel(
            name="AWSCategorySummary",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("key", models.TextField()),
                ("values", django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ("usage_account_id", models.TextField(null=True)),
            ],
            options={
                "db_table": "reporting_awscategory_summary",
            },
        ),
        migrations.CreateModel(
            name="AWSEnabledCategoryKeys",
            fields=[
                ("key", models.CharField(max_length=253, primary_key=True, serialize=False)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "reporting_awsenabledcategorykeys",
            },
        ),
        migrations.AddIndex(
            model_name="awsenabledcategorykeys",
            index=models.Index(fields=["key", "enabled"], name="aws_enabled_category_key_index"),
        ),
        migrations.AddField(
            model_name="awscategorysummary",
            name="account_alias",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.awsaccountalias"
            ),
        ),
        migrations.AddField(
            model_name="awscategorysummary",
            name="cost_entry_bill",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.awscostentrybill"),
        ),
        migrations.AlterUniqueTogether(
            name="awscategorysummary",
            unique_together={("key", "cost_entry_bill", "usage_account_id")},
        ),
    ]
