# Generated by Django 3.2.18 on 2023-03-23 16:08
import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0274_alter_ocpallcostlineitemprojectdailysummaryp_namespace"),
    ]

    operations = [
        migrations.CreateModel(
            name="AWSCategorySummary",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("key", models.TextField()),
                ("values", django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ("usage_account_id", models.TextField(null=True)),
                (
                    "account_alias",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="reporting.awsaccountalias"
                    ),
                ),
                (
                    "cost_entry_bill",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.awscostentrybill"),
                ),
            ],
            options={
                "db_table": "reporting_awscategory_summary",
                "unique_together": {("key", "cost_entry_bill", "usage_account_id")},
            },
        ),
    ]
