# Generated by Django 3.2.18 on 2023-04-26 17:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0276_auto_20230303_1947"),
    ]

    operations = [
        migrations.AddField(
            model_name="awscomputesummarybyaccountp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="awscomputesummaryp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="awscostentrylineitemdailysummary",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="awscostsummarybyaccountp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="awscostsummarybyregionp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="awscostsummarybyservicep",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="awscostsummaryp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="awsdatabasesummaryp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="awsnetworksummaryp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="awsstoragesummarybyaccountp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="awsstoragesummaryp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscomputesummaryp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemdailysummaryp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyaccountp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyregionp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummarybyservicep",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawscostsummaryp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawsdatabasesummaryp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawsnetworksummaryp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpawsstoragesummaryp",
            name="calculated_amortized_cost",
            field=models.DecimalField(decimal_places=9, max_digits=33, null=True),
        ),
    ]
