# Generated by Django 3.2.18 on 2023-05-08 18:48
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_exchangeratedictionary"),
        ("reporting", "0277_store_aws_amoritized_cost"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ocpcluster",
            unique_together={("cluster_id", "cluster_alias", "provider")},
        ),
    ]
