# Generated by Django 3.2.19 on 2023-05-23 01:34
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_alter_tenant_schema"),
        ("reporting", "0278_ocpcluster_remove_duplicates"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ocpcluster",
            unique_together={("cluster_id", "cluster_alias", "provider")},
        ),
        migrations.AlterUniqueTogether(
            name="ocpproject",
            unique_together={("project", "cluster")},
        ),
        migrations.AlterUniqueTogether(
            name="ocppvc",
            unique_together={("persistent_volume", "persistent_volume_claim", "cluster")},
        ),
    ]
