# Generated by Django 3.2.18 on 2023-05-11 18:58
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_exchangeratedictionary"),
        ("reporting", "0278_ocpcluster_remove_duplicates"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ocpcluster",
            unique_together={("cluster_id", "cluster_alias", "provider")},
        ),
    ]
