# Generated by Django 3.2.19 on 2023-06-01 15:44
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0281_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="awscomputesummarybyaccountp",
            name="reporting_provider",
            field=models.ForeignKey(
                db_column="provider_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.provider",
            ),
        ),
        migrations.AddField(
            model_name="awscomputesummaryp",
            name="reporting_provider",
            field=models.ForeignKey(
                db_column="provider_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.provider",
            ),
        ),
        migrations.AddField(
            model_name="awscostentrybill",
            name="reporting_provider",
            field=models.ForeignKey(
                db_column="provider_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.provider",
            ),
        ),
        migrations.AddField(
            model_name="awscostsummarybyaccountp",
            name="reporting_provider",
            field=models.ForeignKey(
                db_column="provider_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.provider",
            ),
        ),
        migrations.AddField(
            model_name="awscostsummarybyregionp",
            name="reporting_provider",
            field=models.ForeignKey(
                db_column="provider_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.provider",
            ),
        ),
        migrations.AddField(
            model_name="awscostsummarybyservicep",
            name="reporting_provider",
            field=models.ForeignKey(
                db_column="provider_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.provider",
            ),
        ),
        migrations.AddField(
            model_name="awscostsummaryp",
            name="reporting_provider",
            field=models.ForeignKey(
                db_column="provider_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.provider",
            ),
        ),
        migrations.AddField(
            model_name="awsdatabasesummaryp",
            name="reporting_provider",
            field=models.ForeignKey(
                db_column="provider_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.provider",
            ),
        ),
        migrations.AddField(
            model_name="awsnetworksummaryp",
            name="reporting_provider",
            field=models.ForeignKey(
                db_column="provider_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.provider",
            ),
        ),
        migrations.AddField(
            model_name="awsorganizationalunit",
            name="reporting_provider",
            field=models.ForeignKey(
                db_column="provider_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.provider",
            ),
        ),
        migrations.AddField(
            model_name="awsstoragesummarybyaccountp",
            name="reporting_provider",
            field=models.ForeignKey(
                db_column="provider_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.provider",
            ),
        ),
        migrations.AddField(
            model_name="awsstoragesummaryp",
            name="reporting_provider",
            field=models.ForeignKey(
                db_column="provider_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.provider",
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE reporting_aws_compute_summary_p SET provider_uuid=source_uuid;
                UPDATE reporting_aws_compute_summary_by_account_p SET provider_uuid=source_uuid;
                UPDATE reporting_awscostentrybill SET provider_uuid=provider_id;
                UPDATE reporting_aws_cost_summary_by_account_p SET provider_uuid=source_uuid;
                UPDATE reporting_aws_cost_summary_by_region_p SET provider_uuid=source_uuid;
                UPDATE reporting_aws_cost_summary_by_service_p SET provider_uuid=source_uuid;
                UPDATE reporting_aws_cost_summary_p SET provider_uuid=source_uuid;
                UPDATE reporting_aws_database_summary_p SET provider_uuid=source_uuid;
                UPDATE reporting_aws_network_summary_p SET provider_uuid=source_uuid;
                UPDATE reporting_awsorganizationalunit SET provider_uuid=provider_id;
                UPDATE reporting_aws_storage_summary_by_account_p SET provider_uuid=source_uuid;
                UPDATE reporting_aws_storage_summary_p SET provider_uuid=source_uuid;
            """
        ),
    ]
