# Generated by Django 3.2.19 on 2023-06-08 18:19
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0281_tenantapiprovider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awscostentrybill",
            name="provider",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.tenantapiprovider"),
        ),
        migrations.AlterField(
            model_name="azurecostentrybill",
            name="provider",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.tenantapiprovider"),
        ),
        migrations.AlterField(
            model_name="gcpcostentrybill",
            name="provider",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.tenantapiprovider"),
        ),
        migrations.AlterField(
            model_name="ocicostentrybill",
            name="provider",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.tenantapiprovider"),
        ),
        migrations.AlterField(
            model_name="ocpcluster",
            name="provider",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.tenantapiprovider"),
        ),
        migrations.AlterField(
            model_name="ocpusagereportperiod",
            name="provider",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reporting.tenantapiprovider"),
        ),
    ]
