# Generated by Django 3.2.19 on 2023-06-13 16:24
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0283_auto_20230612_1841"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocpawscomputesummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.tenantapiprovider",
            ),
        ),
        migrations.AlterField(
            model_name="ocpawscostsummarybyaccountp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.tenantapiprovider",
            ),
        ),
        migrations.AlterField(
            model_name="ocpawscostsummarybyregionp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.tenantapiprovider",
            ),
        ),
        migrations.AlterField(
            model_name="ocpawscostsummarybyservicep",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.tenantapiprovider",
            ),
        ),
        migrations.AlterField(
            model_name="ocpawscostsummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.tenantapiprovider",
            ),
        ),
        migrations.AlterField(
            model_name="ocpawsdatabasesummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.tenantapiprovider",
            ),
        ),
        migrations.AlterField(
            model_name="ocpawsnetworksummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.tenantapiprovider",
            ),
        ),
        migrations.AlterField(
            model_name="ocpawsstoragesummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.tenantapiprovider",
            ),
        ),
    ]
