# Generated by Django 3.2.19 on 2023-05-25 11:36
# NOTE: This migration is only added to this branch for testing purposes
# TODO: remove this migration before merge
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0283_auto_20230612_1841"),
    ]

    operations = [
        migrations.AddField(
            model_name="awsenabledcategorykeys",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunSQL("UPDATE reporting_awsenabledcategorykeys SET uuid = uuid_generate_v4();"),
        migrations.AlterField(
            model_name="awsenabledcategorykeys",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=False, unique=True),
        ),
    ]
