# Generated by Django 3.2.19 on 2023-06-14 13:38
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0284_auto_20230613_1624"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocpcostsummarybynodep",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.tenantapiprovider",
            ),
        ),
        migrations.AlterField(
            model_name="ocpcostsummarybyprojectp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.tenantapiprovider",
            ),
        ),
        migrations.AlterField(
            model_name="ocpcostsummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.tenantapiprovider",
            ),
        ),
        migrations.AlterField(
            model_name="ocppodsummarybyprojectp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.tenantapiprovider",
            ),
        ),
        migrations.AlterField(
            model_name="ocppodsummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.tenantapiprovider",
            ),
        ),
        migrations.AlterField(
            model_name="ocpvolumesummarybyprojectp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.tenantapiprovider",
            ),
        ),
        migrations.AlterField(
            model_name="ocpvolumesummaryp",
            name="source_uuid",
            field=models.ForeignKey(
                db_column="source_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.tenantapiprovider",
            ),
        ),
    ]
