# Generated by Django 3.2.19 on 2023-06-20 19:04
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0286_auto_20230614_2202"),
    ]

    operations = [
        migrations.CreateModel(
            name="AWSEnabledCategoryKeys_TMP",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=253, unique=True)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "reporting_awsenabledcategorykeys_tmp",
            },
        ),
        migrations.RemoveIndex(
            model_name="awsenabledcategorykeys",
            name="aws_enabled_category_key_index",
        ),
        migrations.AddIndex(
            model_name="awsenabledcategorykeys_tmp",
            index=models.Index(fields=["key", "enabled"], name="aws_enabled_category_key_index"),
        ),
        migrations.RunSQL(
            sql="INSERT INTO reporting_awsenabledcategorykeys_tmp(uuid, key, enabled) SELECT uuid_generate_v4(), key, enabled FROM reporting_awsenabledcategorykeys;",
            reverse_sql="DELETE FROM reporting_awsenabledcategorykeys_tmp WHERE 1 = 1;",
        ),
        migrations.DeleteModel(
            name="AWSEnabledCategoryKeys",
        ),
        migrations.RenameModel(
            old_name="AWSEnabledCategoryKeys_TMP",
            new_name="AWSEnabledCategoryKeys",
        ),
        migrations.AlterModelTable(
            name="awsenabledcategorykeys",
            table="reporting_awsenabledcategorykeys",
        ),
    ]
