# Generated by Django 3.2.19 on 2023-05-25 11:36
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0286_insert_awscatkey_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awsenabledcategorykeys",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=False, unique=True),
        ),
    ]
