# Generated by Django 3.2.19 on 2023-06-17 01:49
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0288_auto_20230615_1658"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awsorganizationalunit",
            name="provider",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.tenantapiprovider"
            ),
        ),
    ]
