# Generated by Django 3.2.19 on 2023-06-28 23:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0291_awsenabledcategorykeys_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="azurecomputesummaryp",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="azurecostentrylineitemdailysummary",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="azurecostsummarybyaccountp",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="azurecostsummarybylocationp",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="azurecostsummarybyservicep",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="azuredatabasesummaryp",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="azurenetworksummaryp",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="azurestoragesummaryp",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
        migrations.AddIndex(
            model_name="azurecostentrylineitemdailysummary",
            index=models.Index(fields=["subscription_name"], name="ix_azurecstentrydlysumm_sub_na"),
        ),
        migrations.AddIndex(
            model_name="azurecostsummarybyaccountp",
            index=models.Index(fields=["subscription_name"], name="azurecostsumm_acc_sub_name"),
        ),
    ]
