# Generated by Django 3.2.20 on 2023-07-13 16:56
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0300_squash"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCPPodSummaryByNodeP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("cluster_id", models.TextField()),
                ("cluster_alias", models.TextField(null=True)),
                ("node", models.CharField(max_length=253, null=True)),
                (
                    "resource_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), null=True, size=None
                    ),
                ),
                ("resource_count", models.IntegerField(null=True)),
                ("data_source", models.CharField(max_length=64, null=True)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("infrastructure_raw_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("infrastructure_usage_cost", models.JSONField(null=True)),
                ("infrastructure_markup_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("infrastructure_monthly_cost_json", models.JSONField(null=True)),
                ("supplementary_usage_cost", models.JSONField(null=True)),
                ("supplementary_monthly_cost_json", models.JSONField(null=True)),
                ("pod_usage_cpu_core_hours", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("pod_request_cpu_core_hours", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                (
                    "pod_effective_usage_cpu_core_hours",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                ("pod_limit_cpu_core_hours", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("pod_usage_memory_gigabyte_hours", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                (
                    "pod_request_memory_gigabyte_hours",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                (
                    "pod_effective_usage_memory_gigabyte_hours",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                ("pod_limit_memory_gigabyte_hours", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("cluster_capacity_cpu_core_hours", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                (
                    "cluster_capacity_memory_gigabyte_hours",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                ("raw_currency", models.TextField(null=True)),
                ("distributed_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("cost_model_cpu_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("cost_model_memory_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("cost_model_volume_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("cost_model_rate_type", models.TextField(null=True)),
                (
                    "cost_category",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.tenantapiprovider",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_ocp_pod_summary_by_node_p",
            },
        ),
        migrations.RunSQL(
            "alter table reporting_ocp_pod_summary_by_node_p alter column id set default uuid_generate_v4();",
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="ocppodsummarybynodep",
            index=models.Index(fields=["usage_start"], name="ocppodsummnode_usage_start"),
        ),
        migrations.AddIndex(
            model_name="ocppodsummarybynodep",
            index=models.Index(fields=["node"], name="ocppodsummnode_node"),
        ),
    ]
