# Generated by Django 3.2.20 on 2023-07-13 16:56
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0300_squash"),
    ]

    operations = []
