# Generated by Django 3.2.20 on 2023-07-13 16:56
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0300_squash"),
    ]

    # This migration is replaced by 0312
    operations = []
