# Generated by Django 3.2.20 on 2023-07-23 17:09
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0301_create_ocppod_by_node_p"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubsLastProcessed",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.CharField(max_length=4)),
                ("month", models.CharField(max_length=2)),
                ("latest_processed_time", models.DateTimeField(null=True)),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.tenantapiprovider",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_subs_last_processed_time",
                "unique_together": {("source_uuid", "year", "month")},
            },
        ),
    ]
