# Generated by Django 3.2.19 on 2023-07-31 19:40
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0303_tags_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocpvolumesummarybyprojectp",
            name="persistentvolumeclaim",
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name="ocpvolumesummarybyprojectp",
            name="storageclass",
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name="ocpvolumesummaryp",
            name="persistentvolumeclaim",
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name="ocpvolumesummaryp",
            name="storageclass",
            field=models.CharField(max_length=253, null=True),
        ),
    ]
