# Generated by Django 3.2.21 on 2023-09-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_provider_polling_timestamp'),
        ('reporting', '0305_pvc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingressreports',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.customer'),
        ),
    ]
