# Generated by Django 3.2.21 on 2023-10-04 10:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0308_ocpusagelineitemdailysummary_all_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="subslastprocessed",
            name="resource_id",
            field=models.TextField(default=""),
        ),
        migrations.AlterUniqueTogether(
            name="subslastprocessed",
            unique_together={("source_uuid", "resource_id", "year", "month")},
        ),
    ]
