# Generated by Django 3.2.22 on 2023-10-16 18:52
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0310_delete_ocppodsummarybynodep"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OCPPodSummaryByNodeP",
        ),
    ]
