# Generated by Django 3.2.20 on 2023-10-17 21:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0312_create_ocppod_by_node_p"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestParitionCheck",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("usage_start", models.DateField()),
            ],
            options={
                "db_table": "test_partition_check",
            },
        ),
    ]
