# Generated by Django 3.2.22 on 2023-11-06 23:01
from django.db import migrations

# from koku.pg_partition import PartitionHandlerMixin
# from masu.database.ocp_report_db_accessor import OCPReportDBAccessor


# LOG = logging.getLogger(__name__)
# TABLES_P = ["reporting_ocp_pod_summary_by_node_p"]


# def migrate_node_date(apps, schema_editor):
#     provider_table = apps.get_model("reporting", "TenantAPIProvider")
#     schema_name = schema_editor.connection.schema_name
#     if schema_name in {"default", "template0"}:
#         return

#     LOG.info(f"populating reporting_ocp_pod_summary_by_node_p for {schema_name}")

#     providers = provider_table.objects.using(schema_editor.connection.alias).filter(type="OCP")

#     start_date = "2023-07-01"
#     end_date = "2023-10-30"

#     PartitionHandlerMixin()._handle_partitions(schema_name, TABLES_P, start_date, end_date)
#     for provider in providers:
#         with OCPReportDBAccessor(schema_name) as accessor:
#             accessor.populate_ui_summary_tables(start_date, end_date, str(provider.uuid), tables=TABLES_P)

#     LOG.info(f"done populating reporting_ocp_pod_summary_by_node_p for {schema_name}")


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0313_remove_deprecated_tags"),
    ]

    operations = [
        # this was a 1-time data migration, so now this is a no-op
        # migrations.RunPython(code=migrate_node_date, reverse_code=migrations.RunPython.noop),
    ]
