# Generated by Django 3.2.22 on 2023-11-16 13:41
import django.db.models.deletion
from django.db import migrations
from django.db import models

PLATFORM_NAMESPACES = ["openshift-%", "kube-%", "Platform unallocated", "openshift"]


def insert_default_namespaces(apps, schema_editor):
    """This function grabs the data out of our current model
    structure and inserts into our new model."""
    OpenshiftCostCategory = apps.get_model("reporting", "OpenshiftCostCategory")
    OpenshiftCostCategoryNamespace = apps.get_model("reporting", "OpenshiftCostCategoryNamespace")

    platform_category = OpenshiftCostCategory.objects.get(name="Platform")
    if platform_category:
        for namespace in PLATFORM_NAMESPACES:
            OpenshiftCostCategoryNamespace.objects.create(
                namespace=namespace, system_default=True, cost_category=platform_category
            )


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0314_ocppod_by_node_p_data_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenshiftCostCategoryNamespace",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("namespace", models.TextField(unique=True)),
                ("system_default", models.BooleanField(default=False)),
                (
                    "cost_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
                    ),
                ),
            ],
            options={
                "db_table": "reporting_ocp_cost_category_namespace",
            },
        ),
        migrations.RunPython(insert_default_namespaces),
    ]
