# Generated by Django 3.2.22 on 2023-12-11 16:55
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0316_remove_openshiftcostcategory_namespace"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentTagKeys",
            fields=[
                (
                    "parent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="reporting.enabledtagkeys",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildTagKeys",
            fields=[
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="reporting.enabledtagkeys",
                    ),
                ),
                (
                    "parent",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="reporting.parenttagkeys"),
                ),
            ],
            options={
                "unique_together": {("parent", "child")},
            },
        ),
    ]
