# Generated by Django 3.2.23 on 2024-01-18 18:09
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0316_remove_openshiftcostcategory_namespace"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagMapping",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child",
                        to="reporting.enabledtagkeys",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent",
                        to="reporting.enabledtagkeys",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_tagmapping",
                "unique_together": {("parent", "child")},
            },
        ),
    ]
