# Generated by Django 4.2.10 on 2024-02-21 11:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0317_tagmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocpazurecomputesummaryp",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ocpazurecostlineitemdailysummaryp",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ocpazurecostlineitemprojectdailysummaryp",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ocpazurecostsummarybyaccountp",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ocpazurecostsummarybylocationp",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ocpazurecostsummarybyservicep",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ocpazuredatabasesummaryp",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ocpazurenetworksummaryp",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ocpazurestoragesummaryp",
            name="subscription_name",
            field=models.TextField(null=True),
        ),
    ]
