# Generated by Django 4.2.10 on 2024-03-25 21:01
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0318_ocpazurecomputesummaryp_subscription_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocpusagelineitemdailysummary",
            name="infrastructure_data_in_gigabytes",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpusagelineitemdailysummary",
            name="infrastructure_data_out_gigabytes",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.CreateModel(
            name="OCPNetworkSummaryByNodeP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("cluster_alias", models.TextField(null=True)),
                ("cluster_id", models.TextField()),
                ("cost_model_cpu_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("cost_model_memory_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("cost_model_rate_type", models.TextField(null=True)),
                ("cost_model_volume_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("data_source", models.CharField(max_length=64, null=True)),
                ("distributed_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("infrastructure_data_in_gigabytes", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                (
                    "infrastructure_data_out_gigabytes",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                ("infrastructure_markup_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("infrastructure_raw_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("node", models.CharField(max_length=253, null=True)),
                ("raw_currency", models.TextField(null=True)),
                ("resource_count", models.IntegerField(null=True)),
                (
                    "resource_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), null=True, size=None
                    ),
                ),
                ("usage_end", models.DateField()),
                ("usage_start", models.DateField()),
                (
                    "cost_category",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.tenantapiprovider",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_ocp_network_summary_by_node_p",
                "indexes": [
                    models.Index(fields=["usage_start"], name="ocp_net_summ_node_usage_start"),
                    models.Index(fields=["node"], name="ocp_net_summ_node_node"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OCPNetworkSummaryByProjectP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("cluster_alias", models.TextField(null=True)),
                ("cluster_id", models.TextField()),
                ("cost_model_cpu_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("cost_model_memory_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("cost_model_rate_type", models.TextField(null=True)),
                ("cost_model_volume_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("data_source", models.CharField(max_length=64, null=True)),
                ("distributed_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("infrastructure_data_in_gigabytes", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                (
                    "infrastructure_data_out_gigabytes",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                ("infrastructure_markup_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("infrastructure_raw_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("namespace", models.CharField(max_length=253, null=True)),
                ("raw_currency", models.TextField(null=True)),
                ("resource_count", models.IntegerField(null=True)),
                (
                    "resource_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), null=True, size=None
                    ),
                ),
                ("usage_end", models.DateField()),
                ("usage_start", models.DateField()),
                (
                    "cost_category",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.tenantapiprovider",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_ocp_network_summary_by_project_p",
                "indexes": [
                    models.Index(fields=["usage_start"], name="ocp_net_summ_proj_usage_start"),
                    models.Index(fields=["namespace"], name="ocp_net_summ_proj_namespace"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OCPNetworkSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("cluster_alias", models.TextField(null=True)),
                ("cluster_id", models.TextField()),
                ("cost_model_cpu_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("cost_model_memory_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("cost_model_rate_type", models.TextField(null=True)),
                ("cost_model_volume_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("data_source", models.CharField(max_length=64, null=True)),
                ("distributed_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("infrastructure_data_in_gigabytes", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                (
                    "infrastructure_data_out_gigabytes",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                ("infrastructure_markup_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("infrastructure_raw_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("raw_currency", models.TextField(null=True)),
                ("resource_count", models.IntegerField(null=True)),
                (
                    "resource_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), null=True, size=None
                    ),
                ),
                ("usage_end", models.DateField()),
                ("usage_start", models.DateField()),
                (
                    "cost_category",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.tenantapiprovider",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_ocp_network_summary_p",
                "indexes": [models.Index(fields=["usage_start"], name="ocp_net_summ_usage_start")],
            },
        ),
    ]
