# Generated by Django 4.2.10 on 2024-03-07 01:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0319_node_network_costs"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocpnode",
            name="architecture",
            field=models.TextField(null=True),
        ),
    ]
