# Generated by Django 4.2.11 on 2024-05-21 16:05
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0321_awscostentrylineitemsummarybyec2compute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awscostentrylineitemsummarybyec2compute",
            name="instance_name",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
