# Generated by Django 4.2.11 on 2024-05-20 13:56
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0322_alter_awscostentrylineitemsummarybyec2compute_instance_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awscostentrylineitemsummarybyec2compute",
            name="availability_zone",
        ),
        migrations.RemoveField(
            model_name="awscostentrylineitemsummarybyec2compute",
            name="organizational_unit",
        ),
    ]
