# Generated by Django 4.2.14 on 2024-09-20 09:42
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0324_ocppvc_csi_volume_handle"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AWSCostEntryLineItemSummaryByEC2Compute",
        ),
    ]
