# Generated by Django 4.2.14 on 2024-09-20 09:42
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0325_awscostentrylineitemsummarybyec2compute"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AWSCostEntryLineItemSummaryByEC2Compute",
        ),
    ]
