# Generated by Django 4.2.14 on 2024-09-24 09:11
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0325_awscostentrylineitemsummarybyec2computep"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AWSCostEntryLineItemSummaryByEC2Compute",
        ),
    ]
