# Generated by Django 4.2.15 on 2024-10-29 18:06
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations
from django.db import models

from koku.database import set_pg_extended_mode
from koku.database import unset_pg_extended_mode


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0326_delete_awscostentrylineitemsummarybyec2compute"),
    ]

    operations = [
        migrations.RunPython(code=set_pg_extended_mode, reverse_code=unset_pg_extended_mode),
        migrations.CreateModel(
            name="OCPVirtualMachineSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("cluster_alias", models.TextField(null=True)),
                ("cluster_id", models.TextField(null=True)),
                ("namespace", models.CharField(max_length=253, null=True)),
                ("node", models.CharField(max_length=253, null=True)),
                ("vm_name", models.TextField(null=True)),
                (
                    "cost_model_cpu_cost",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                (
                    "cost_model_memory_cost",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                ("cost_model_rate_type", models.TextField(null=True)),
                (
                    "cost_model_volume_cost",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                (
                    "distributed_cost",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                ("pod_labels", models.JSONField(null=True)),
                (
                    "pod_request_cpu_core_hours",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                (
                    "pod_request_memory_gigabyte_hours",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                (
                    "infrastructure_markup_cost",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                (
                    "infrastructure_raw_cost",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                ("raw_currency", models.TextField(null=True)),
                (
                    "resource_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256),
                        null=True,
                        size=None,
                    ),
                ),
                ("usage_end", models.DateField()),
                ("usage_start", models.DateField()),
                (
                    "cost_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.openshiftcostcategory",
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.tenantapiprovider",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_ocp_vm_summary_p",
                "indexes": [
                    models.Index(fields=["usage_start"], name="ocp_vm_summ_usage_start"),
                    models.Index(fields=["cluster_id"], name="ocp_vm_summ_cluster_id"),
                    models.Index(fields=["namespace"], name="ocp_vm_summ_namespace"),
                    models.Index(fields=["node"], name="ocp_vm_summ_node"),
                    models.Index(fields=["vm_name"], name="ocp_vm_summ_vm_name"),
                    django.contrib.postgres.indexes.GinIndex(fields=["pod_labels"], name="ocp_vm_summ_pod_labels_idx"),
                ],
                "unique_together": {
                    ("usage_start", "cluster_id", "namespace", "node", "vm_name", "cost_model_rate_type")
                },
            },
        ),
        migrations.RunPython(code=unset_pg_extended_mode, reverse_code=set_pg_extended_mode),
    ]
