# Generated by Django 4.2.18 on 2025-02-17 17:33
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0327_ocpvirtualmachinesummaryp"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocpvirtualmachinesummaryp",
            name="persistentvolumeclaim",
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name="ocpvirtualmachinesummaryp",
            name="persistentvolumeclaim_capacity_gigabyte_months",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpvirtualmachinesummaryp",
            name="persistentvolumeclaim_usage_gigabyte_months",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpvirtualmachinesummaryp",
            name="storageclass",
            field=models.CharField(max_length=253, null=True),
        ),
    ]
