# Generated by Django 4.2.15 on 2025-02-20 12:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0327_ocpvirtualmachinesummaryp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="monthly_cost_type",
            field=models.TextField(
                choices=[
                    ("Node", "Node"),
                    ("Node-Core-Hour", "Node-Core-Hour"),
                    ("Node-Core-Month", "Node-Core-Month"),
                    ("Cluster", "Cluster"),
                    ("PVC", "PVC"),
                    ("Tag", "Tag"),
                ],
                null=True,
            ),
        ),
    ]
