# Generated by Django 4.2.15 on 2025-02-17 21:12
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0328_ocpvirtualmachinesummaryp_persistentvolumeclaim_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ocpvirtualmachinesummaryp",
            unique_together={
                (
                    "usage_start",
                    "cluster_id",
                    "namespace",
                    "node",
                    "vm_name",
                    "cost_model_rate_type",
                    "persistentvolumeclaim",
                )
            },
        ),
    ]
