# Generated by Django 4.2.19 on 2025-03-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0329_ocp_vm_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocpusagelineitemdailysummary',
            name='monthly_cost_type',
            field=models.TextField(choices=[('Node', 'Node'), ('Node_Core_Month', 'Node_Core_Month'), ('Cluster', 'Cluster'), ('PVC', 'PVC'), ('Tag', 'Tag'), ('OCP_VM', 'OCP_VM'), ('OCP_VM_Core_Month', 'OCP_VM_Core_Month')], null=True),
        ),
    ]
