# Generated by Django 4.2.19 on 2025-04-14 10:01
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0330_alter_ocpusagelineitemdailysummary_monthly_cost_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            name="pod_cost",
        ),
        migrations.RemoveField(
            model_name="ocpawscostlineitemprojectdailysummaryp",
            name="project_markup_cost",
        ),
    ]
