# Generated by Django 4.2.19 on 2025-04-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0330_alter_ocpusagelineitemdailysummary_monthly_cost_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costsummary',
            name='project_markup_cost',
        ),
        migrations.RemoveField(
            model_name='ocpallcostlineitemprojectdailysummaryp',
            name='pod_cost',
        ),
        migrations.RemoveField(
            model_name='ocpallcostlineitemprojectdailysummaryp',
            name='project_markup_cost',
        ),
    ]
