# Generated by Django 4.2.19 on 2025-04-16 10:31
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reporting",
            "0331_remove_ocpgcpcostlineitemprojectdailysummaryp_pod_cost_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="ocpcostsummarybyprojectp",
            old_name="infrastructure_project_markup_cost",
            new_name="infrastructure_markup_cost",
        ),
        migrations.RenameField(
            model_name="ocpcostsummarybyprojectp",
            old_name="infrastructure_project_raw_cost",
            new_name="infrastructure_raw_cost",
        ),
        migrations.RemoveField(
            model_name="ocpusagelineitemdailysummary",
            name="infrastructure_project_markup_cost",
        ),
        migrations.RemoveField(
            model_name="ocpusagelineitemdailysummary",
            name="infrastructure_project_raw_cost",
        ),
    ]
