# Generated by Django 4.2.20 on 2025-05-08 16:35
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0331_remove_costsummary_project_markup_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocicomputesummarybyaccountp",
            name="source_uuid",
        ),
        migrations.RemoveField(
            model_name="ocicomputesummaryp",
            name="source_uuid",
        ),
        migrations.AlterUniqueTogether(
            name="ocicostentrybill",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="ocicostentrybill",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="ocicostentrylineitemdailysummary",
            name="cost_entry_bill",
        ),
        migrations.RemoveField(
            model_name="ocicostsummarybyaccountp",
            name="source_uuid",
        ),
        migrations.RemoveField(
            model_name="ocicostsummarybyregionp",
            name="source_uuid",
        ),
        migrations.RemoveField(
            model_name="ocicostsummarybyservicep",
            name="source_uuid",
        ),
        migrations.RemoveField(
            model_name="ocicostsummaryp",
            name="source_uuid",
        ),
        migrations.RemoveField(
            model_name="ocidatabasesummaryp",
            name="source_uuid",
        ),
        migrations.RemoveField(
            model_name="ocinetworksummaryp",
            name="source_uuid",
        ),
        migrations.RemoveField(
            model_name="ocistoragesummarybyaccountp",
            name="source_uuid",
        ),
        migrations.RemoveField(
            model_name="ocistoragesummaryp",
            name="source_uuid",
        ),
        migrations.AlterUniqueTogether(
            name="ocitagssummary",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="ocitagssummary",
            name="cost_entry_bill",
        ),
        migrations.DeleteModel(
            name="OCITagsValues",
        ),
        migrations.AlterField(
            model_name="enabledtagkeys",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("AWS", "AWS"),
                    ("OCP", "OCP"),
                    ("Azure", "Azure"),
                    ("GCP", "GCP"),
                    ("IBM", "IBM"),
                    ("AWS-local", "AWS-local"),
                    ("Azure-local", "Azure-local"),
                    ("GCP-local", "GCP-local"),
                    ("IBM-local", "IBM-local"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="OCIComputeSummaryByAccountP",
        ),
        migrations.DeleteModel(
            name="OCIComputeSummaryP",
        ),
        migrations.DeleteModel(
            name="OCICostEntryBill",
        ),
        migrations.DeleteModel(
            name="OCICostEntryLineItemDailySummary",
        ),
        migrations.DeleteModel(
            name="OCICostSummaryByAccountP",
        ),
        migrations.DeleteModel(
            name="OCICostSummaryByRegionP",
        ),
        migrations.DeleteModel(
            name="OCICostSummaryByServiceP",
        ),
        migrations.DeleteModel(
            name="OCICostSummaryP",
        ),
        migrations.DeleteModel(
            name="OCIDatabaseSummaryP",
        ),
        migrations.DeleteModel(
            name="OCINetworkSummaryP",
        ),
        migrations.DeleteModel(
            name="OCIStorageSummaryByAccountP",
        ),
        migrations.DeleteModel(
            name="OCIStorageSummaryP",
        ),
        migrations.DeleteModel(
            name="OCITagsSummary",
        ),
    ]
