# Generated by Django 4.2.20 on 2025-04-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0331_remove_costsummary_project_markup_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocpusagelineitemdailysummary',
            name='infrastructure_project_markup_cost',
        ),
        migrations.RemoveField(
            model_name='ocpusagelineitemdailysummary',
            name='infrastructure_project_raw_cost',
        ),
    ]
