# Generated by Django 4.2.19 on 2025-04-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0331_remove_costsummary_project_markup_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costsummary',
            name='project_markup_cost',
            field=models.DecimalField(decimal_places=9, max_digits=27, null=True),
        ),
        migrations.AddField(
            model_name='ocpallcostlineitemprojectdailysummaryp',
            name='project_markup_cost',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
    ]
