# Generated by Django 4.2.19 on 2025-04-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0331_remove_ocpallcostlineitemprojectdailysummaryp_pod_cost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ocpallcostlineitemprojectdailysummaryp",
            old_name="project_markup_cost",
            new_name="markup_cost",
        ),
        migrations.RemoveField(
            model_name="costsummary",
            name="project_markup_cost",
        ),
    ]
