# Generated by Django 4.2.20 on 2025-05-06 09:46
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0331_remove_costsummary_project_markup_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enabledtagkeys",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("AWS", "AWS"),
                    ("OCP", "OCP"),
                    ("Azure", "Azure"),
                    ("GCP", "GCP"),
                    ("AWS-local", "AWS-local"),
                    ("Azure-local", "Azure-local"),
                    ("GCP-local", "GCP-local"),
                ],
                max_length=50,
            ),
        ),
    ]
