# Generated by Django 4.2.20 on 2025-05-07 10:05
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0331_remove_costsummary_project_markup_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocpcostsummarybyprojectp",
            name="infrastructure_markup_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpcostsummarybyprojectp",
            name="infrastructure_raw_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
    ]
