# Generated by Django 4.2.19 on 2025-04-30 17:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0332_remove_ocicomputesummarybyaccountp_source_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subslastprocessed",
            name="latest_event_sent",
            field=models.DateTimeField(null=True),
        ),
    ]
