# Generated by Django 4.2.20 on 2025-04-17 10:24
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0333_merge_20250416_1451"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costsummary",
            name="project_infra_cost",
        ),
    ]
