# Generated by Django 4.2.15 on 2025-05-16 11:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0333_ocpcostsummarybyprojectp_infrastructure_markup_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subslastprocessed",
            name="latest_event_sent",
            field=models.DateTimeField(null=True),
        ),
    ]
