# Generated by Django 4.2.21 on 2025-06-13 13:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0335_alter_ocpusagelineitemdailysummary_monthly_cost_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enabledtagkeys",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("AWS", "AWS"),
                    ("OCP", "OCP"),
                    ("Azure", "Azure"),
                    ("GCP", "GCP"),
                    ("AWS-local", "AWS-local"),
                    ("Azure-local", "Azure-local"),
                    ("GCP-local", "GCP-local"),
                ],
                max_length=50,
            ),
        ),
    ]
