# Generated by Django 4.2.21 on 2025-06-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0335_alter_enabledtagkeys_provider_type'),
        ('reporting', '0335_alter_ocpusagelineitemdailysummary_monthly_cost_type'),
    ]

    operations = [
    ]
