# Generated by Django 4.2.23 on 2025-09-12 13:08
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0336_alter_enabledtagkeys_provider_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocpcostsummarybyprojectp",
            name="infrastructure_project_markup_cost",
        ),
        migrations.RemoveField(
            model_name="ocpcostsummarybyprojectp",
            name="infrastructure_project_raw_cost",
        ),
    ]
