# Generated by Django 4.2.24 on 2025-09-29 19:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0337_remove_ocpcostsummarybyprojectp_infrastructure_project_markup_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocpnode",
            name="architecture",
            field=models.TextField(null=True),
        ),
    ]
