# Generated by Django 4.2.25 on 2025-11-10 19:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0338_ocpnode_architecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocpusagelineitemdailysummary",
            name="cost_model_gpu_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
    ]
