# Generated by Django 4.2.25 on 2025-11-07 09:29
import django.db.models.deletion
from django.db import migrations
from django.db import models

from koku.database import set_pg_extended_mode
from koku.database import unset_pg_extended_mode


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0338_ocpnode_architecture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocpusagelineitemdailysummary",
            name="monthly_cost_type",
            field=models.TextField(
                choices=[
                    ("Node", "Node"),
                    ("Node_Core_Month", "Node_Core_Month"),
                    ("Cluster", "Cluster"),
                    ("PVC", "PVC"),
                    ("Tag", "Tag"),
                    ("OCP_VM", "OCP_VM"),
                    ("OCP_VM_CORE", "OCP_VM_CORE"),
                    ("GPU", "GPU"),
                ],
                null=True,
            ),
        ),
        migrations.RunPython(code=set_pg_extended_mode, reverse_code=unset_pg_extended_mode),
        migrations.CreateModel(
            name="OCPGpuSummaryP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("cluster_id", models.TextField()),
                ("cluster_alias", models.TextField(null=True)),
                ("namespace", models.CharField(max_length=253, null=True)),
                ("node", models.CharField(max_length=253, null=True)),
                ("pod", models.CharField(max_length=253, null=True)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("gpu_vendor_name", models.CharField(max_length=128, null=True)),
                ("gpu_model_name", models.CharField(max_length=128, null=True)),
                ("gpu_memory_capacity_mib", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("gpu_pod_uptime", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("gpu_count", models.IntegerField(null=True)),
                ("gpu_cost", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("cost_model_rate_type", models.TextField(null=True)),
                (
                    "cost_category",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.openshiftcostcategory"
                    ),
                ),
                (
                    "report_period",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="reporting.ocpusagereportperiod"
                    ),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.tenantapiprovider",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_ocp_gpu_summary_p",
                "indexes": [
                    models.Index(fields=["usage_start"], name="ocpgpusumm_usage_start"),
                    models.Index(fields=["cluster_id"], name="ocpgpusumm_cluster_idx"),
                    models.Index(fields=["namespace"], name="ocpgpusumm_namespace_idx"),
                    models.Index(fields=["node"], name="ocpgpusumm_node_idx"),
                    models.Index(fields=["gpu_vendor_name"], name="ocpgpusumm_vendor_idx"),
                    models.Index(fields=["gpu_model_name"], name="ocpgpusumm_model_idx"),
                ],
            },
        ),
        migrations.RunPython(code=unset_pg_extended_mode, reverse_code=set_pg_extended_mode),
    ]
