# Generated by Django 4.2.25 on 2025-11-19 19:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0340_gpu_support"),
    ]

    operations = [
        # Cost Summary tables
        migrations.AddField(
            model_name="ocpcostsummaryp",
            name="cost_model_gpu_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpcostsummarybyprojectp",
            name="cost_model_gpu_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpcostsummarybynodep",
            name="cost_model_gpu_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        # Network Summary tables
        migrations.AddField(
            model_name="ocpnetworksummaryp",
            name="cost_model_gpu_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpnetworksummarybynodep",
            name="cost_model_gpu_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpnetworksummarybyprojectp",
            name="cost_model_gpu_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        # VM Summary table
        migrations.AddField(
            model_name="ocpvirtualmachinesummaryp",
            name="cost_model_gpu_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        # Pod Summary tables
        migrations.AddField(
            model_name="ocppodsummaryp",
            name="cost_model_gpu_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocppodsummarybyprojectp",
            name="cost_model_gpu_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocppodsummarybynodep",
            name="cost_model_gpu_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        # Volume Summary tables
        migrations.AddField(
            model_name="ocpvolumesummaryp",
            name="cost_model_gpu_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpvolumesummarybyprojectp",
            name="cost_model_gpu_cost",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
    ]
