# Generated by Django 5.2.12 on 2026-03-16 18:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0343_ocp_line_item_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocpgpusummaryp",
            name="gpu_max_slices",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="ocpgpusummaryp",
            name="gpu_mode",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="ocpgpusummaryp",
            name="mig_memory_capacity_gb",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ocpgpusummaryp",
            name="mig_profile",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="ocpgpusummaryp",
            name="mig_slice_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="ocpgpusummaryp",
            name="mig_strategy",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ocpgpuusagelineitem",
            name="gpu_max_slices",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="ocpgpuusagelineitem",
            name="mig_instance_id",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="ocpgpuusagelineitem",
            name="mig_memory_capacity_mib",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="ocpgpuusagelineitem",
            name="mig_profile",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="ocpgpuusagelineitem",
            name="mig_slice_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="ocpgpuusagelineitem",
            name="mig_strategy",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ocpgpuusagelineitemdaily",
            name="gpu_max_slices",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="ocpgpuusagelineitemdaily",
            name="mig_instance_id",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="ocpgpuusagelineitemdaily",
            name="mig_memory_capacity_mib",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="ocpgpuusagelineitemdaily",
            name="mig_profile",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="ocpgpuusagelineitemdaily",
            name="mig_slice_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="ocpgpuusagelineitemdaily",
            name="mig_strategy",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name="ocpgpusummaryp",
            index=models.Index(fields=["mig_profile"], name="ocpgpusumm_mig_profile_idx"),
        ),
    ]
