# Generated by Django 5.2.11 on 2026-03-09 01:10
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0343_ocp_line_item_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCPPodSummaryByPodP",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("cluster_id", models.TextField()),
                ("cluster_alias", models.TextField(null=True)),
                ("namespace", models.CharField(max_length=253, null=True)),
                ("node", models.CharField(max_length=253, null=True)),
                ("pod", models.CharField(max_length=253, null=True)),
                ("usage_start", models.DateField()),
                ("usage_end", models.DateField()),
                ("pod_usage_cpu_core_hours", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("pod_request_cpu_core_hours", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                (
                    "pod_effective_usage_cpu_core_hours",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                ("pod_limit_cpu_core_hours", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("pod_usage_memory_gigabyte_hours", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                (
                    "pod_request_memory_gigabyte_hours",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                (
                    "pod_effective_usage_memory_gigabyte_hours",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                ("pod_limit_memory_gigabyte_hours", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                ("cluster_capacity_cpu_core_hours", models.DecimalField(decimal_places=15, max_digits=33, null=True)),
                (
                    "cluster_capacity_memory_gigabyte_hours",
                    models.DecimalField(decimal_places=15, max_digits=33, null=True),
                ),
                (
                    "source_uuid",
                    models.ForeignKey(
                        db_column="source_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.tenantapiprovider",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_ocp_pod_summary_by_pod_p",
                "indexes": [
                    models.Index(fields=["usage_start"], name="ocppodsumm_pod_usage_start"),
                    models.Index(fields=["namespace"], name="ocppodsumm_pod_namespace"),
                    models.Index(fields=["node"], name="ocppodsumm_pod_node"),
                    models.Index(fields=["pod"], name="ocppodsumm_pod_pod"),
                ],
            },
        ),
    ]
