# Generated manually for AWS self-hosted line item tables
# Modified to support PostgreSQL partitioning for on-prem deployment
import uuid

from django.db import migrations
from django.db import models

from koku.database import set_pg_extended_mode
from koku.database import unset_pg_extended_mode


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0343_ocp_line_item_models"),
    ]

    operations = [
        # Enable PostgreSQL partitioning support via extended schema editor
        migrations.RunPython(code=set_pg_extended_mode, reverse_code=unset_pg_extended_mode),
        migrations.CreateModel(
            name="AWSLineItemDaily",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("usage_start", models.DateField(db_index=True, null=True)),
                ("source", models.CharField(db_index=True, max_length=64, null=True)),
                ("year", models.CharField(max_length=4, null=True)),
                ("month", models.CharField(max_length=2, null=True)),
                ("manifestid", models.CharField(max_length=256, null=True)),
                ("bill_payeraccountid", models.CharField(max_length=50, null=True)),
                ("bill_billingentity", models.CharField(max_length=50, null=True)),
                ("bill_billingperiodstartdate", models.DateTimeField(null=True)),
                ("bill_billingperiodenddate", models.DateTimeField(null=True)),
                ("bill_billtype", models.TextField(null=True)),
                ("bill_invoiceid", models.TextField(null=True)),
                ("identity_timeinterval", models.TextField(null=True)),
                ("lineitem_usagestartdate", models.DateTimeField(db_index=True, null=True)),
                ("lineitem_usageenddate", models.DateTimeField(null=True)),
                ("lineitem_productcode", models.CharField(max_length=256, null=True)),
                ("lineitem_usageaccountid", models.CharField(max_length=50, null=True)),
                ("lineitem_availabilityzone", models.CharField(max_length=50, null=True)),
                ("lineitem_resourceid", models.CharField(max_length=256, null=True)),
                ("lineitem_lineitemtype", models.CharField(max_length=50, null=True)),
                ("lineitem_lineitemdescription", models.TextField(null=True)),
                ("lineitem_legalentity", models.CharField(max_length=256, null=True)),
                ("lineitem_usagetype", models.TextField(null=True)),
                ("lineitem_operation", models.TextField(null=True)),
                ("lineitem_taxtype", models.TextField(null=True)),
                ("lineitem_usageamount", models.FloatField(null=True)),
                ("lineitem_normalizationfactor", models.FloatField(null=True)),
                ("lineitem_normalizedusageamount", models.FloatField(null=True)),
                ("lineitem_currencycode", models.CharField(max_length=10, null=True)),
                ("lineitem_unblendedrate", models.FloatField(null=True)),
                ("lineitem_unblendedcost", models.FloatField(null=True)),
                ("lineitem_blendedrate", models.FloatField(null=True)),
                ("lineitem_blendedcost", models.FloatField(null=True)),
                ("product_productfamily", models.CharField(max_length=150, null=True)),
                ("product_region", models.CharField(max_length=50, null=True)),
                ("product_instancetype", models.CharField(max_length=50, null=True)),
                ("product_productname", models.CharField(max_length=256, null=True)),
                ("product_physicalcores", models.CharField(max_length=50, null=True)),
                ("product_vcpu", models.CharField(max_length=50, null=True)),
                ("product_memory", models.TextField(null=True)),
                ("product_operatingsystem", models.TextField(null=True)),
                ("product_servicecode", models.TextField(null=True)),
                ("product_sku", models.TextField(null=True)),
                ("pricing_unit", models.TextField(null=True)),
                ("pricing_publicondemandcost", models.FloatField(null=True)),
                ("pricing_publicondemandrate", models.FloatField(null=True)),
                ("pricing_term", models.TextField(null=True)),
                ("savingsplan_savingsplaneffectivecost", models.FloatField(null=True)),
                ("reservation_amortizedupfrontcostforusage", models.TextField(null=True)),
                ("reservation_amortizedupfrontfeeforbillingperiod", models.TextField(null=True)),
                ("reservation_endtime", models.TextField(null=True)),
                ("reservation_numberofreservations", models.TextField(null=True)),
                ("reservation_recurringfeeforusage", models.TextField(null=True)),
                ("reservation_starttime", models.TextField(null=True)),
                ("reservation_unitsperreservation", models.TextField(null=True)),
                ("reservation_unusedquantity", models.TextField(null=True)),
                ("reservation_unusedrecurringfee", models.TextField(null=True)),
                ("resourcetags", models.TextField(null=True)),
                ("costcategory", models.TextField(null=True)),
                ("row_uuid", models.TextField(null=True)),
            ],
            options={
                "db_table": "aws_line_items_daily",
                "indexes": [models.Index(fields=["source", "year", "month"], name="aws_li_daily_src_yr_mo_idx")],
            },
        ),
        migrations.CreateModel(
            name="AWSLineItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("usage_start", models.DateField(db_index=True, null=True)),
                ("source", models.CharField(db_index=True, max_length=64, null=True)),
                ("year", models.CharField(max_length=4, null=True)),
                ("month", models.CharField(max_length=2, null=True)),
                ("manifestid", models.CharField(max_length=256, null=True)),
                ("bill_payeraccountid", models.CharField(max_length=50, null=True)),
                ("bill_billingentity", models.CharField(max_length=50, null=True)),
                ("bill_billingperiodstartdate", models.DateTimeField(null=True)),
                ("bill_billingperiodenddate", models.DateTimeField(null=True)),
                ("bill_billtype", models.TextField(null=True)),
                ("bill_invoiceid", models.TextField(null=True)),
                ("identity_timeinterval", models.TextField(null=True)),
                ("lineitem_usagestartdate", models.DateTimeField(db_index=True, null=True)),
                ("lineitem_usageenddate", models.DateTimeField(null=True)),
                ("lineitem_productcode", models.CharField(max_length=256, null=True)),
                ("lineitem_usageaccountid", models.CharField(max_length=50, null=True)),
                ("lineitem_availabilityzone", models.CharField(max_length=50, null=True)),
                ("lineitem_resourceid", models.CharField(max_length=256, null=True)),
                ("lineitem_lineitemtype", models.CharField(max_length=50, null=True)),
                ("lineitem_lineitemdescription", models.TextField(null=True)),
                ("lineitem_legalentity", models.CharField(max_length=256, null=True)),
                ("lineitem_usagetype", models.TextField(null=True)),
                ("lineitem_operation", models.TextField(null=True)),
                ("lineitem_taxtype", models.TextField(null=True)),
                ("lineitem_usageamount", models.FloatField(null=True)),
                ("lineitem_normalizationfactor", models.FloatField(null=True)),
                ("lineitem_normalizedusageamount", models.FloatField(null=True)),
                ("lineitem_currencycode", models.CharField(max_length=10, null=True)),
                ("lineitem_unblendedrate", models.FloatField(null=True)),
                ("lineitem_unblendedcost", models.FloatField(null=True)),
                ("lineitem_blendedrate", models.FloatField(null=True)),
                ("lineitem_blendedcost", models.FloatField(null=True)),
                ("product_productfamily", models.CharField(max_length=150, null=True)),
                ("product_region", models.CharField(max_length=50, null=True)),
                ("product_instancetype", models.CharField(max_length=50, null=True)),
                ("product_productname", models.CharField(max_length=256, null=True)),
                ("product_physicalcores", models.CharField(max_length=50, null=True)),
                ("product_vcpu", models.CharField(max_length=50, null=True)),
                ("product_memory", models.TextField(null=True)),
                ("product_operatingsystem", models.TextField(null=True)),
                ("product_servicecode", models.TextField(null=True)),
                ("product_sku", models.TextField(null=True)),
                ("pricing_unit", models.TextField(null=True)),
                ("pricing_publicondemandcost", models.FloatField(null=True)),
                ("pricing_publicondemandrate", models.FloatField(null=True)),
                ("pricing_term", models.TextField(null=True)),
                ("savingsplan_savingsplaneffectivecost", models.FloatField(null=True)),
                ("reservation_amortizedupfrontcostforusage", models.TextField(null=True)),
                ("reservation_amortizedupfrontfeeforbillingperiod", models.TextField(null=True)),
                ("reservation_endtime", models.TextField(null=True)),
                ("reservation_numberofreservations", models.TextField(null=True)),
                ("reservation_recurringfeeforusage", models.TextField(null=True)),
                ("reservation_starttime", models.TextField(null=True)),
                ("reservation_unitsperreservation", models.TextField(null=True)),
                ("reservation_unusedquantity", models.TextField(null=True)),
                ("reservation_unusedrecurringfee", models.TextField(null=True)),
                ("resourcetags", models.TextField(null=True)),
                ("costcategory", models.TextField(null=True)),
                ("row_uuid", models.TextField(null=True)),
            ],
            options={
                "db_table": "aws_line_items",
                "indexes": [models.Index(fields=["source", "year", "month"], name="aws_li_src_yr_mo_idx")],
            },
        ),
        # Disable extended mode after creating partitioned tables
        migrations.RunPython(code=unset_pg_extended_mode, reverse_code=set_pg_extended_mode),
    ]
