# Generated by Django 5.2.12 on 2026-04-09 19:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0344_add_mig_fields_to_gpu_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocpgpusummaryp",
            name="mig_instance_id",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="ocpgpusummaryp",
            name="gpu_uuid",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
