# Generated by Django 4.2.28 on 2026-03-27 11:36
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0344_add_mig_fields_to_gpu_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_retention_months",
                    models.IntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "tenant_settings",
            },
        ),
    ]
