# Generated by Django 4.2.28 on 2026-04-01 03:03
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0345_tenantsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="singleton",
            field=models.BooleanField(default=True, unique=True),
        ),
    ]
