# Generated by Django 5.2.15 on 2026-07-11 10:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0351_create_ocp_cost_breakdown_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSACUsageLineItemDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('report_period_start', models.DateTimeField(null=True)),
                ('report_period_end', models.DateTimeField(null=True)),
                ('interval_start', models.DateTimeField(db_index=True, null=True)),
                ('interval_end', models.DateTimeField(null=True)),
                ('usage_start', models.DateField(db_index=True, null=True)),
                ('source', models.CharField(db_index=True, max_length=64, null=True)),
                ('year', models.CharField(max_length=4, null=True)),
                ('month', models.CharField(max_length=2, null=True)),
                ('manifestid', models.CharField(max_length=256, null=True)),
                ('reportnumhours', models.IntegerField(null=True)),
                ('resource_type', models.CharField(max_length=64, null=True)),
                ('resource_id', models.CharField(max_length=256, null=True)),
                ('tenant_id', models.CharField(max_length=256, null=True)),
                ('project_id', models.CharField(max_length=256, null=True)),
                ('meter_name', models.CharField(max_length=128, null=True)),
                ('value', models.FloatField(null=True)),
                ('unit', models.CharField(max_length=64, null=True)),
                ('cost_type', models.CharField(max_length=32, null=True)),
                ('koku_metric', models.CharField(max_length=128, null=True)),
                ('cost_amount', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=8, null=True)),
            ],
            options={
                'db_table': 'openshift_osac_usage_line_items_daily',
                'indexes': [models.Index(fields=['source', 'year', 'month'], name='osac_daily_src_yr_mo_idx')],
            },
        ),
    ]
