# Generated by Django 5.2.15 on 2026-07-01 13:04
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_models", "0015_static_exchange_rate"),
        ("reporting", "0353_rtu_schema_improvements"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratestousage",
            name="cluster_capacity_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ratestousage",
            name="cluster_capacity_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ratestousage",
            name="node_capacity_cpu_core_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ratestousage",
            name="node_capacity_cpu_cores",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ratestousage",
            name="node_capacity_memory_gigabyte_hours",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ratestousage",
            name="node_capacity_memory_gigabytes",
            field=models.DecimalField(decimal_places=15, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name="ratestousage",
            name="persistentvolume",
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name="ratestousage",
            name="resource_id",
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name="ratestousage",
            name="storageclass",
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddIndex(
            model_name="ratestousage",
            index=models.Index(
                fields=[
                    "source_uuid",
                    "report_period_id",
                    "usage_start",
                    "monthly_cost_type",
                ],
                name="ratestousage_src_rp_mct_idx",
            ),
        ),
    ]
