# Generated by Django 3.2.19 on 2023-06-06 12:00
# Generated by Django 3.2.19 on 2023-06-01 13:41
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0300_squash"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnabledTagKeys",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("key", models.CharField(max_length=253)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("AWS", "AWS"),
                            ("OCP", "OCP"),
                            ("Azure", "Azure"),
                            ("GCP", "GCP"),
                            ("IBM", "IBM"),
                            ("OCI", "OCI"),
                            ("AWS-local", "AWS-local"),
                            ("Azure-local", "Azure-local"),
                            ("GCP-local", "GCP-local"),
                            ("IBM-local", "IBM-local"),
                            ("OCI-local", "OCI-local"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "reporting_enabledtagkeys",
            },
        ),
        migrations.AddIndex(
            model_name="enabledtagkeys",
            index=models.Index(fields=["key", "enabled"], name="tag_enabled_key_index"),
        ),
        migrations.AddIndex(
            model_name="enabledtagkeys",
            index=models.Index(fields=["provider_type"], name="tag_provider_type_index"),
        ),
        migrations.RunSQL(
            sql="INSERT INTO reporting_enabledtagkeys (uuid, key, enabled, provider_type) SELECT uuid_generate_v4(), key, enabled, 'AWS' as provider_type FROM reporting_awsenabledtagkeys;",
            reverse_sql="DELETE FROM reporting_enabledtagkeys WHERE provider_type = 'AWS'",
        ),
        migrations.RunSQL(
            sql="INSERT INTO reporting_enabledtagkeys (uuid, key, enabled, provider_type) SELECT uuid_generate_v4(), key, enabled, 'Azure' as provider_type FROM reporting_azureenabledtagkeys;",
            reverse_sql="DELETE FROM reporting_enabledtagkeys WHERE provider_type = 'Azure'",
        ),
        migrations.RunSQL(
            sql="INSERT INTO reporting_enabledtagkeys (uuid, key, enabled, provider_type) SELECT uuid_generate_v4(), key, enabled, 'GCP' as provider_type FROM reporting_gcpenabledtagkeys;",
            reverse_sql="DELETE FROM reporting_enabledtagkeys WHERE provider_type = 'GCP'",
        ),
        migrations.RunSQL(
            sql="INSERT INTO reporting_enabledtagkeys (uuid, key, enabled, provider_type) SELECT uuid_generate_v4(), key, enabled, 'OCI' as provider_type FROM reporting_ocienabledtagkeys;",
            reverse_sql="DELETE FROM reporting_enabledtagkeys WHERE provider_type = 'OCI'",
        ),
        migrations.RunSQL(
            sql="INSERT INTO reporting_enabledtagkeys (uuid, key, enabled, provider_type) SELECT uuid_generate_v4(), key, enabled, 'OCP' as provider_type FROM reporting_ocpenabledtagkeys;",
            reverse_sql="DELETE FROM reporting_enabledtagkeys WHERE provider_type = 'OCP'",
        ),
    ]
