DB_USER=$1
DB_ADMIN=$2

psql ${DATABASE_NAME} -p ${POSTGRES_SQL_SERVICE_PORT} -h ${POSTGRES_SQL_SERVICE_HOST} -U ${DB_ADMIN} -c "DROP DATABASE IF EXISTS test_${DATABASE_NAME};" || true

psql ${DATABASE_NAME} -p ${POSTGRES_SQL_SERVICE_PORT} -h ${POSTGRES_SQL_SERVICE_HOST} -U ${DB_ADMIN} -c "DROP USER ${DB_USER};" || true

psql ${DATABASE_NAME} -p ${POSTGRES_SQL_SERVICE_PORT} -h ${POSTGRES_SQL_SERVICE_HOST} -U ${DB_ADMIN} -c "CREATE USER ${DB_USER} WITH SUPERUSER LOGIN PASSWORD '${DATABASE_PASSWORD}';"
