- op: add
  path: /objects/0/spec/deployments/-
  value:
    name: clowder-scheduler
    minReplicas: ${{SCHEDULER_MIN_REPLICAS}}
    webServices:
      public:
        enabled: false
      private:
        enabled: false
      metrics:
        enabled: false
    podSpec:
      image: ${IMAGE}:${IMAGE_TAG}
      command:  # this `command` overrides haberdasher; when implementing haberdasher, change this to `args`
        - /bin/bash
        - -c
        - >
          PYTHONPATH=/opt/app-root/src/koku
          celery -A koku beat -l $LOG_LEVEL
      env:
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws-access-key-id
              name: koku-aws
              optional: false
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws-secret-access-key
              name: koku-aws
              optional: false
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: ${GOOGLE_APPLICATION_CREDENTIALS}
        - name: APP_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DEVELOPMENT
          value: ${DEVELOPMENT}
        - name: LOG_LEVEL
          value: ${LOG_LEVEL}
        - name: KOKU_LOG_LEVEL
          value: ${KOKU_LOG_LEVEL}
        - name: prometheus_multiproc_dir
          value: ${PROMETHEUS_DIR}
        - name: REQUESTED_BUCKET
          value: ${S3_BUCKET_NAME}
        - name: ENABLE_S3_ARCHIVING
          value: ${ENABLE_S3_ARCHIVING}
        - name: ENABLE_PARQUET_PROCESSING
          value: ${ENABLE_PARQUET_PROCESSING}
        - name: PARQUET_PROCESSING_BATCH_SIZE
          value: ${PARQUET_PROCESSING_BATCH_SIZE}
        - name: ENABLE_TRINO_SOURCES
          value: ${ENABLE_TRINO_SOURCES}
        - name: ENABLE_TRINO_ACCOUNTS
          value: ${ENABLE_TRINO_ACCOUNTS}
        - name: ENABLE_TRINO_SOURCE_TYPE
          value: ${ENABLE_TRINO_SOURCE_TYPE}
        - name: TRINO_DATE_STEP
          value: ${TRINO_DATE_STEP}
        - name: KOKU_CELERY_ENABLE_SENTRY
          value: ${ENABLE_CELERY_SENTRY}
        - name: KOKU_SENTRY_ENVIRONMENT
          value: ${KOKU_SENTRY_ENV}
        - name: KOKU_CELERY_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              key: celery-sentry-dsn
              name: koku-sentry
              optional: true
        - name: DEMO_ACCOUNTS
          value: ${DEMO_ACCOUNTS}
        - name: WORKER_QUEUES
          value: ${SCHEDULER_WORKER_QUEUE}
        - name: SCHEDULE_CHECK_INTERVAL
          value: ${SCHEDULE_CHECK_INTERVAL}
        - name: SCHEDULE_REPORT_CHECKS
          value: ${SCHEDULE_REPORT_CHECKS}
        - name: SOURCE_STATUS_FREQUENCY_MINUTES
          value: ${SOURCE_STATUS_FREQUENCY_MINUTES}
        - name: REMOVE_EXPIRED_REPORT_DATA_ON_DAY
          value: ${REMOVE_EXPIRED_REPORT_DATA_ON_DAY}
        - name: REMOVE_EXPIRED_REPORT_UTC_TIME
          value: ${REMOVE_EXPIRED_REPORT_UTC_TIME}
        - name: VACUUM_DATA_DAY_OF_WEEK
          value: ${VACUUM_DATA_DAY_OF_WEEK}
        - name: VACUUM_DATA_UTC_TIME
          value: ${VACUUM_DATA_UTC_TIME}
        - name: VOLUME_FILE_RETENTION
          value: ${VOLUME_FILE_RETENTION}
        - name: CLEAN_VOLUME_DAY_OF_WEEK
          value: ${CLEAN_VOLUME_DAY_OF_WEEK}
        - name: CLEAN_VOLUME_UTC_TIME
          value: ${CLEAN_VOLUME_UTC_TIME}
        - name: DATE_OVERRIDE
          value: ${DATE_OVERRIDE}
        - name: RETAIN_NUM_MONTHS
          value: ${RETAIN_NUM_MONTHS}
        - name: INITIAL_INGEST_NUM_MONTHS
          value: ${INITIAL_INGEST_NUM_MONTHS}
        - name: INITIAL_INGEST_OVERRIDE
          value: ${INITIAL_INGEST_OVERRIDE}
        - name: PRESTO_HOST
          value: ${PRESTO_HOST}
        - name: PRESTO_PORT
          value: ${PRESTO_PORT}
        - name: AUTO_DATA_INGEST
          value: ${AUTO_DATA_INGEST}
        - name: REPORT_PROCESSING_BATCH_SIZE
          value: ${REPORT_PROCESSING_BATCH_SIZE}
        - name: PROMETHEUS_PUSHGATEWAY
          value: ${PROMETHEUS_PUSHGATEWAY}
        - name: USE_RABBIT
          value: ${USE_RABBIT}
        - name: RABBITMQ_HOST
          value: ${RABBITMQ_HOST}
        - name: RABBITMQ_PORT
          value: ${RABBITMQ_PORT}
      resources:
        limits:
          cpu: ${SCHEDULER_CPU_LIMIT}
          memory: ${SCHEDULER_MEMORY_LIMIT}
        requests:
          cpu: ${SCHEDULER_CPU_REQUEST}
          memory: ${SCHEDULER_MEMORY_REQUEST}
      volumeMounts:
      - name: gcp-credentials
        mountPath: /etc/gcp
        readOnly: true
      volumes:
      - name: gcp-credentials
        secret:
          secretName: koku-gcp
          items:
            - key: gcp-credentials
              path: gcp-credentials.json

- op: add
  path: /parameters/-
  value:
    displayName: Minimum replicas
    name: SCHEDULER_MIN_REPLICAS
    required: true
    value: '1'
- op: add
  path: /parameters/-
  value:
    displayName: Memory Request
    name: SCHEDULER_MEMORY_REQUEST
    required: true
    value: 128Mi
- op: add
  path: /parameters/-
  value:
    displayName: Memory Limit
    name: SCHEDULER_MEMORY_LIMIT
    required: true
    value: 256Mi
- op: add
  path: /parameters/-
  value:
    displayName: CPU Request
    name: SCHEDULER_CPU_REQUEST
    required: true
    value: 100m
- op: add
  path: /parameters/-
  value:
    displayName: CPU Limit
    name: SCHEDULER_CPU_LIMIT
    required: true
    value: 200m
- op: add
  path: /parameters/-
  value:
    displayName: Worker Queue
    name: SCHEDULER_WORKER_QUEUE
    required: true
    value: 'cost_model,download,ocp,priority,refresh,summary'
- op: add
  path: /parameters/-
  value:
    displayName: Scheduler report checks
    name: SCHEDULE_REPORT_CHECKS
    value: "True"
- op: add
  path: /parameters/-
  value:
    displayName: Frequency to check sources availability (minutes)
    name: SOURCE_STATUS_FREQUENCY_MINUTES
    value: '60'
