- op: add
  path: /objects/0/spec/deployments/-
  value:
    name: clowder-sources-client
    metadata:
      annotations:
        ignore-check.kube-linter.io/minimum-three-replicas: This deployment uses 1 pod at times for cost saving purposes
    replicas: ${{SOURCES_CLIENT_REPLICAS}}
    webServices:
      public:
        enabled: false
      private:
        enabled: true
    podSpec:
      metadata:
        annotations:
          ignore-check.kube-linter.io/minimum-three-replicas: This deployment uses 1 pod at times for cost saving purposes
      image: ${IMAGE}:${IMAGE_TAG}
      env:
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        - name: SOURCES
          value: "true"
        - name: SOURCES_PROBE_HEADER
          value: ${SOURCES_PROBE_HEADER}
        - name: SOURCES_PSK
          valueFrom:
            secretKeyRef:
              key: psk
              name: ${SOURCES_PSK_SECRET_NAME}
              optional: true
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: django-secret-key
              name: koku-secret
              optional: false
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: ${AWS_SHARED_CREDENTIALS_FILE}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: ${GOOGLE_APPLICATION_CREDENTIALS}
        - name: OCI_SHARED_CREDENTIALS_FILE
          value: ${OCI_SHARED_CREDENTIALS_FILE}
        - name: OCI_CLI_KEY_FILE
          value: ${OCI_CLI_KEY_FILE}
        - name: OCI_PYTHON_SDK_NO_SERVICE_IMPORTS
          value: "true"
        - name: APP_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: API_PATH_PREFIX
          value: ${API_PATH_PREFIX}
        - name: APP_DOMAIN
          value: ${APP_DOMAIN}
        - name: DEVELOPMENT
          value: ${DEVELOPMENT}
        - name: GUNICORN_LOG_LEVEL
          value: ${GUNICORN_LOG_LEVEL}
        - name: GUNICORN_WORKERS
          value: ${GUNICORN_WORKERS}
        - name: KOKU_LOG_LEVEL
          value: ${SOURCES_CLIENT_KOKU_LOG_LEVEL}
        - name: UNLEASH_LOG_LEVEL
          value: ${UNLEASH_LOG_LEVEL}
        - name: DJANGO_LOG_LEVEL
          value: ${DJANGO_LOG_LEVEL}
        - name: DJANGO_LOG_FORMATTER
          value: ${DJANGO_LOG_FORMATTER}
        - name: DJANGO_LOG_HANDLERS
          value: ${DJANGO_LOG_HANDLERS}
        - name: DJANGO_LOG_DIRECTORY
          value: ${DJANGO_LOG_DIRECTORY}
        - name: DJANGO_LOGGING_FILE
          value: ${DJANGO_LOG_FILE}
        - name: SOURCES_API_PREFIX
          value: ${SOURCES_API_PREFIX}
        - name: RBAC_SERVICE_PATH
          value: ${RBAC_SERVICE_PATH}
        - name: RBAC_CACHE_TTL
          value: ${RBAC_CACHE_TTL}
        - name: PROMETHEUS_MULTIPROC_DIR
          value: ${PROMETHEUS_DIR}
        - name: KOKU_ENABLE_SENTRY
          value: ${KOKU_ENABLE_SENTRY}
        - name: KOKU_SENTRY_ENVIRONMENT
          value: ${KOKU_SENTRY_ENV}
        - name: KOKU_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              key: ${GLITCHTIP_KEY_NAME}
              name: ${GLITCHTIP_SECRET_NAME}
              optional: true
        - name: DEMO_ACCOUNTS
          value: ${DEMO_ACCOUNTS}
        - name: UNLEASH_CACHE_DIR
          value: ${UNLEASH_CACHE_DIR}
        - name: QE_SCHEMA
          value: ${QE_SCHEMA}
        - name: ENHANCED_ORG_ADMIN
          value: ${ENHANCED_ORG_ADMIN}
      livenessProbe:
        httpGet:
          path: ${API_PATH_PREFIX}/v1/status/?liveness
          port: private
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 20
        successThreshold: 1
        failureThreshold: 5
        timeoutSeconds: 10
      readinessProbe:
        httpGet:
          path: ${API_PATH_PREFIX}/v1/status/
          port: private
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 20
        successThreshold: 1
        failureThreshold: 5
        timeoutSeconds: 10
      resources:
        requests:
          cpu: ${CPU_REQUEST_SOURCES_CLIENT}
          memory: ${MEMORY_REQUEST_SOURCES_CLIENT}
        limits:
          cpu: ${CPU_LIMIT_SOURCES_CLIENT}
          memory: ${MEMORY_LIMIT_SOURCES_CLIENT}
      volumeMounts:
      - name: aws-credentials
        mountPath: /etc/aws
        readOnly: true
      - name: gcp-credentials
        mountPath: /etc/gcp
        readOnly: true
      - name: oci-credentials
        mountPath: /etc/oci
        readOnly: true
      - name: tmp-data
        mountPath: ${TMP_DIR}
      volumes:
      - name: tmp-data
        emptyDir: {}
      - name: aws-credentials
        secret:
          items:
          - key: aws-credentials
            path: aws-credentials
          secretName: koku-aws
      - name: gcp-credentials
        secret:
          secretName: koku-gcp
          items:
            - key: gcp-credentials
              path: gcp-credentials.json
      - name: oci-credentials
        secret:
          secretName: koku-oci
          items:
            - key: oci-credentials
              path: oci-credentials.pem
            - key: oci-config
              path: oci-config

- op: add
  path: /parameters/-
  value:
    displayName: Minimum replicas
    name: SOURCES_CLIENT_REPLICAS
    required: true
    value: '1'
- op: add
  path: /parameters/-
  value:
    displayName: Memory Request
    name: MEMORY_REQUEST_SOURCES_CLIENT
    required: true
    value: 650Mi
- op: add
  path: /parameters/-
  value:
    displayName: Memory Limit
    name: MEMORY_LIMIT_SOURCES_CLIENT
    required: true
    value: 768Mi
- op: add
  path: /parameters/-
  value:
    displayName: CPU Request
    name: CPU_REQUEST_SOURCES_CLIENT
    required: true
    value: 50m
- op: add
  path: /parameters/-
  value:
    displayName: CPU Limit
    name: CPU_LIMIT_SOURCES_CLIENT
    required: true
    value: 100m
- op: add
  path: /parameters/-
  value:
    displayName: Log Level for sources client
    name: SOURCES_CLIENT_KOKU_LOG_LEVEL
    required: true
    value: INFO
