- op: add
  path: /objects/0/spec/deployments/-
  value:
    name: worker-priority
    minReplicas: ${{WORKER_PRIORITY_MIN_REPLICAS}}
    webServices:
      public:
        enabled: false
      private:
        enabled: false
      metrics:
        enabled: true
    podSpec:
      image: ${IMAGE}:${IMAGE_TAG}
      command:  # this `command` overrides haberdasher; when implementing haberdasher, change this to `args`
        - /bin/bash
        - -c
        - >
          PYTHONPATH=/opt/app-root/src/koku
          celery -A koku worker -E -l $LOG_LEVEL -Q $WORKER_QUEUES
      env:
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws-access-key-id
              name: koku-aws
              optional: false
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws-secret-access-key
              name: koku-aws
              optional: false
        - name: GOOGLE_APPLICATION_CREDENTIALS
          valueFrom:
            secretKeyRef:
              key: gcp-credentials
              name: koku-gcp
              optional: false
        - name: APP_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DEVELOPMENT
          value: ${DEVELOPMENT}
        - name: LOG_LEVEL
          value: ${LOG_LEVEL}
        - name: KOKU_LOG_LEVEL
          value: ${KOKU_LOG_LEVEL}
        - name: prometheus_multiproc_dir
          value: ${PROMETHEUS_DIR}
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              key: db.endpoint
              name: elasticache-redis
              optional: true
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              key: db.port
              name: elasticache-redis
              optional: true
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws_access_key_id
              name: hccm-s3
              optional: true
        - name: S3_SECRET
          valueFrom:
            secretKeyRef:
              key: aws_secret_access_key
              name: hccm-s3
              optional: true
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              key: bucket
              name: hccm-s3
              optional: true
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: endpoint
              name: hccm-s3
              optional: true
        - name: ENABLE_S3_ARCHIVING
          value: ${ENABLE_S3_ARCHIVING}
        - name: ENABLE_PARQUET_PROCESSING
          value: ${ENABLE_PARQUET_PROCESSING}
        - name: PARQUET_PROCESSING_BATCH_SIZE
          value: ${PARQUET_PROCESSING_BATCH_SIZE}
        - name: ENABLE_TRINO_SOURCES
          value: ${ENABLE_TRINO_SOURCES}
        - name: ENABLE_TRINO_ACCOUNTS
          value: ${ENABLE_TRINO_ACCOUNTS}
        - name: ENABLE_TRINO_SOURCE_TYPE
          value: ${ENABLE_TRINO_SOURCE_TYPE}
        - name: TRINO_DATE_STEP
          value: ${TRINO_DATE_STEP}
        - name: KOKU_CELERY_ENABLE_SENTRY
          value: ${ENABLE_CELERY_SENTRY}
        - name: KOKU_SENTRY_ENVIRONMENT
          value: ${KOKU_SENTRY_ENV}
        - name: KOKU_CELERY_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              key: celery-sentry-dsn
              name: koku-sentry
              optional: true
        - name: DEMO_ACCOUNTS
          value: ${DEMO_ACCOUNTS}
        - name: WORKER_QUEUES
          value: ${WORKER_PRIORITY_WORKER_QUEUE}
        - name: SCHEDULE_CHECK_INTERVAL
          value: ${SCHEDULE_CHECK_INTERVAL}
        - name: REMOVE_EXPIRED_REPORT_DATA_ON_DAY
          value: ${REMOVE_EXPIRED_REPORT_DATA_ON_DAY}
        - name: REMOVE_EXPIRED_REPORT_UTC_TIME
          value: ${REMOVE_EXPIRED_REPORT_UTC_TIME}
        - name: VACUUM_DATA_DAY_OF_WEEK
          value: ${VACUUM_DATA_DAY_OF_WEEK}
        - name: VACUUM_DATA_UTC_TIME
          value: ${VACUUM_DATA_UTC_TIME}
        - name: VOLUME_FILE_RETENTION
          value: ${VOLUME_FILE_RETENTION}
        - name: CLEAN_VOLUME_DAY_OF_WEEK
          value: ${CLEAN_VOLUME_DAY_OF_WEEK}
        - name: CLEAN_VOLUME_UTC_TIME
          value: ${CLEAN_VOLUME_UTC_TIME}
        - name: DATE_OVERRIDE
          value: ${DATE_OVERRIDE}
        - name: RETAIN_NUM_MONTHS
          value: ${RETAIN_NUM_MONTHS}
        - name: INITIAL_INGEST_NUM_MONTHS
          value: ${INITIAL_INGEST_NUM_MONTHS}
        - name: INITIAL_INGEST_OVERRIDE
          value: ${INITIAL_INGEST_OVERRIDE}
        - name: PRESTO_HOST
          value: ${PRESTO_HOST}
        - name: PRESTO_PORT
          value: ${PRESTO_PORT}
        - name: AUTO_DATA_INGEST
          value: ${AUTO_DATA_INGEST}
        - name: REPORT_PROCESSING_BATCH_SIZE
          value: ${REPORT_PROCESSING_BATCH_SIZE}
        - name: PROMETHEUS_PUSHGATEWAY
          value: ${PROMETHEUS_PUSHGATEWAY}
        - name: USE_RABBIT
          value: ${USE_RABBIT}
        - name: RABBITMQ_HOST
          value: ${RABBITMQ_HOST}
        - name: RABBITMQ_PORT
          value: ${RABBITMQ_PORT}
        - name: SOURCES_API_PREFIX
          value: ${SOURCES_API_PREFIX}
      resources:
        limits:
          cpu: ${WORKER_PRIORITY_CPU_LIMIT}
          memory: ${WORKER_PRIORITY_MEMORY_LIMIT}
        requests:
          cpu: ${WORKER_PRIORITY_CPU_REQUEST}
          memory: ${WORKER_PRIORITY_MEMORY_REQUEST}
      volumeMounts:
      - mountPath: /var/tmp/masu/
        name: koku-worker-data
      volumes:
      - name: koku-worker-data
        emptyDir: {}

- op: add
  path: /parameters/-
  value:
    displayName: Minimum replicas
    name: WORKER_PRIORITY_MIN_REPLICAS
    required: true
    value: '2'
- op: add
  path: /parameters/-
  value:
    displayName: Memory Request
    name: WORKER_PRIORITY_MEMORY_REQUEST
    required: true
    value: 256Mi
- op: add
  path: /parameters/-
  value:
    displayName: Memory Limit
    name: WORKER_PRIORITY_MEMORY_LIMIT
    required: true
    value: 512Mi
- op: add
  path: /parameters/-
  value:
    displayName: CPU Request
    name: WORKER_PRIORITY_CPU_REQUEST
    required: true
    value: 100m
- op: add
  path: /parameters/-
  value:
    displayName: CPU Limit
    name: WORKER_PRIORITY_CPU_LIMIT
    required: true
    value: 200m
- op: add
  path: /parameters/-
  value:
    displayName: Worker Queue
    name: WORKER_PRIORITY_WORKER_QUEUE
    required: true
    value: 'priority'
