- op: add
  path: /objects/0/spec/deployments/-
  value:
    name: clowder-worker-download-xl
    metadata:
      annotations:
        ignore-check.kube-linter.io/minimum-three-replicas: This deployment uses 1 pod at times for cost saving purposes
    replicas: ${{WORKER_DOWNLOAD_XL_REPLICAS}}
    webServices:
      public:
        enabled: false
      private:
        enabled: false
    podSpec:
      metadata:
        annotations:
          ignore-check.kube-linter.io/minimum-three-replicas: This deployment uses 1 pod at times for cost saving purposes
      image: ${IMAGE}:${IMAGE_TAG}
      command:
        - /bin/bash
        - -c
        - > # ${APP_HOME} is `/opt/koku/koku` which is defined in the Dockerfile
          PYTHONPATH=${APP_HOME}
          celery -A koku worker --without-gossip -E -l $CELERY_LOG_LEVEL -Q $WORKER_QUEUES
      env:
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: ${AWS_SHARED_CREDENTIALS_FILE}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: ${GOOGLE_APPLICATION_CREDENTIALS}
        - name: OCI_SHARED_CREDENTIALS_FILE
          value: ${OCI_SHARED_CREDENTIALS_FILE}
        - name: OCI_CLI_KEY_FILE
          value: ${OCI_CLI_KEY_FILE}
        - name: OCI_PYTHON_SDK_NO_SERVICE_IMPORTS
          value: "true"
        - name: SOURCES_PSK
          valueFrom:
            secretKeyRef:
              key: psk
              name: ${SOURCES_PSK_SECRET_NAME}
              optional: true
        - name: APP_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DEVELOPMENT
          value: ${DEVELOPMENT}
        - name: CELERY_LOG_LEVEL
          value: ${CELERY_LOG_LEVEL}
        - name: KOKU_LOG_LEVEL
          value: ${KOKU_LOG_LEVEL}
        - name: UNLEASH_LOG_LEVEL
          value: ${UNLEASH_LOG_LEVEL}
        - name: PROMETHEUS_MULTIPROC_DIR
          value: ${PROMETHEUS_DIR}
        - name: REQUESTED_BUCKET
          value: ${S3_BUCKET_NAME}
        - name: ENABLE_S3_ARCHIVING
          value: ${ENABLE_S3_ARCHIVING}
        - name: PARQUET_PROCESSING_BATCH_SIZE
          value: ${PARQUET_PROCESSING_BATCH_SIZE}
        - name: PANDAS_COLUMN_BATCH_SIZE
          value: ${PANDAS_COLUMN_BATCH_SIZE}
        - name: TRINO_DATE_STEP
          value: ${TRINO_DATE_STEP}
        - name: KOKU_ENABLE_SENTRY
          value: ${KOKU_ENABLE_SENTRY}
        - name: KOKU_SENTRY_ENVIRONMENT
          value: ${KOKU_SENTRY_ENV}
        - name: KOKU_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              key: ${GLITCHTIP_KEY_NAME}
              name: ${GLITCHTIP_SECRET_NAME}
              optional: true
        - name: DEMO_ACCOUNTS
          value: ${DEMO_ACCOUNTS}
        - name: WORKER_QUEUES
          value: ${WORKER_DOWNLOAD_XL_WORKER_QUEUE}
        - name: WORKER_PROC_ALIVE_TIMEOUT
          value: ${WORKER_PROC_ALIVE_TIMEOUT}
        - name: DATE_OVERRIDE
          value: ${DATE_OVERRIDE}
        - name: RETAIN_NUM_MONTHS
          value: ${RETAIN_NUM_MONTHS}
        - name: INITIAL_INGEST_NUM_MONTHS
          value: ${INITIAL_INGEST_NUM_MONTHS}
        - name: INITIAL_INGEST_OVERRIDE
          value: ${INITIAL_INGEST_OVERRIDE}
        - name: POLLING_TIMER
          value: ${POLLING_TIMER}
        - name: POLLING_BATCH_SIZE
          value: ${POLLING_BATCH_SIZE}
        - name: PROCESSING_WAIT_TIMER
          value: ${PROCESSING_WAIT_TIMER}
        - name: LARGE_PROCESSING_WAIT_TIMER
          value: ${LARGE_PROCESSING_WAIT_TIMER}
        - name: TAG_ENABLED_LIMIT
          value: ${TAG_ENABLED_LIMIT}
        - name: TRINO_HOST
          value: ${TRINO_HOST}
        - name: TRINO_PORT
          value: ${TRINO_PORT}
        - name: AUTO_DATA_INGEST
          value: ${AUTO_DATA_INGEST}
        - name: REPORT_PROCESSING_BATCH_SIZE
          value: ${REPORT_PROCESSING_BATCH_SIZE}
        - name: PROMETHEUS_PUSHGATEWAY
          value: ${PROMETHEUS_PUSHGATEWAY}
        - name: SOURCES_API_PREFIX
          value: ${SOURCES_API_PREFIX}
        - name: UNLEASH_CACHE_DIR
          value: ${UNLEASH_CACHE_DIR}
        - name: WORKER_CACHE_TIMEOUT
          value: ${WORKER_CACHE_TIMEOUT}
        - name: WORKER_CACHE_LARGE_CUSTOMER_TIMEOUT
          value: ${WORKER_CACHE_LARGE_CUSTOMER_TIMEOUT}
        - name: WORKER_CACHE_LARGE_CUSTOMER_CONCURRENT_TASKS
          value: ${WORKER_CACHE_LARGE_CUSTOMER_CONCURRENT_TASKS}
        - name: QE_SCHEMA
          value: ${QE_SCHEMA}
        - name: ENHANCED_ORG_ADMIN
          value: ${ENHANCED_ORG_ADMIN}
      livenessProbe:
        httpGet:
          path: /livez
          port: metrics
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 20
        successThreshold: 1
        failureThreshold: 5
        timeoutSeconds: 10
      readinessProbe:
        httpGet:
          path: /readyz
          port: metrics
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 20
        successThreshold: 1
        failureThreshold: 5
        timeoutSeconds: 10
      terminationGracePeriodSeconds: 3600
      resources:
        limits:
          cpu: ${WORKER_DOWNLOAD_XL_CPU_LIMIT}
          memory: ${WORKER_DOWNLOAD_XL_MEMORY_LIMIT}
        requests:
          cpu: ${WORKER_DOWNLOAD_XL_CPU_REQUEST}
          memory: ${WORKER_DOWNLOAD_XL_MEMORY_REQUEST}
      volumeMounts:
      - name: aws-credentials
        mountPath: /etc/aws
        readOnly: true
      - mountPath: /var/tmp/masu/
        name: koku-worker-data
      - name: gcp-credentials
        mountPath: /etc/gcp
        readOnly: true
      - name: oci-credentials
        mountPath: /etc/oci
        readOnly: true
      - name: tmp-data
        mountPath: ${TMP_DIR}
      volumes:
      - name: tmp-data
        emptyDir: {}
      - name: koku-worker-data
        emptyDir: {}
      - name: aws-credentials
        secret:
          items:
          - key: aws-credentials
            path: aws-credentials
          secretName: koku-aws
      - name: gcp-credentials
        secret:
          secretName: koku-gcp
          items:
            - key: gcp-credentials
              path: gcp-credentials.json
      - name: oci-credentials
        secret:
          secretName: koku-oci
          items:
            - key: oci-credentials
              path: oci-credentials.pem
            - key: oci-config
              path: oci-config

- op: add
  path: /parameters/-
  value:
    displayName: Minimum replicas
    name: WORKER_DOWNLOAD_XL_REPLICAS
    required: true
    value: '2'
- op: add
  path: /parameters/-
  value:
    displayName: Memory Request
    name: WORKER_DOWNLOAD_XL_MEMORY_REQUEST
    required: true
    value: 512Mi
- op: add
  path: /parameters/-
  value:
    displayName: Memory Limit
    name: WORKER_DOWNLOAD_XL_MEMORY_LIMIT
    required: true
    value: 1Gi
- op: add
  path: /parameters/-
  value:
    displayName: CPU Request
    name: WORKER_DOWNLOAD_XL_CPU_REQUEST
    required: true
    value: 200m
- op: add
  path: /parameters/-
  value:
    displayName: CPU Limit
    name: WORKER_DOWNLOAD_XL_CPU_LIMIT
    required: true
    value: 400m
- op: add
  path: /parameters/-
  value:
    displayName: Worker Queue
    name: WORKER_DOWNLOAD_XL_WORKER_QUEUE
    required: true
    value: 'download_xl'
