#
# This template defines resources used to deploy the Celery scheduler.
#
kind: Template
apiVersion: v1
metadata:
  name: celery-scheduler-template
  annotations:
    openshift.io/display-name: "Masu"
    description: "Scheduler for data ingestion engine for Koku"
    tags: "python,flask"
    iconClass: "icon-python"
    openshift.io/long-description: "This template defines resources needed to deploy the Celery scheduler for Masu."
    openshift.io/provider-display-name: "Red Hat, Inc."
    openshift.io/documentation-url: "https://koku.readthedocs.io/en/latest/"
labels:
  app: koku
  template: koku-celery-scheduler
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    annotations:
      description: Defines how to deploy the celery scheduler
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}-scheduler
  spec:
    replicas: ${{REPLICAS}}
    selector:
      name: ${NAME}-scheduler
    resources:
      requests:
        cpu: ${CPU_REQUEST}
        memory: ${MEMORY_REQUEST}
      limits:
        cpu: ${CPU_LIMIT}
        memory: ${MEMORY_LIMIT}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${NAME}
          name: ${NAME}-scheduler
        name: ${NAME}-scheduler
      spec:
        containers:
        - name: ${NAME}-scheduler
          image: ${NAME}-scheduler
          command:
            - /bin/bash
            - -c
            - >
              PYTHONPATH=. scl enable rh-python36 --
              celery --pidfile=/opt/celeryd.pid -A koku beat -l $LOG_LEVEL
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: ${NAME}-db
                  optional: false
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: ${NAME}-db
                  optional: false
            - name: MASU_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: masu-secret-key
                  name: ${NAME}-masu
                  optional: false
            - name: DATABASE_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}-db
                  key: database-engine
                  optional: false
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}-db
                  key: database-name
                  optional: false
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}-db
                  key: database-host
                  optional: false
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}-db
                  key: database-port
                  optional: false
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}-messaging
                  key: rabbitmq-host
                  optional: false
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}-logging
                  key: masu-log-level
                  optional: false
            - name: SCHEDULE_CHECK_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}-processor
                  key: schedule-check-interval
                  optional: false
            - name: REMOVE_EXPIRED_REPORT_DATA_ON_DAY
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}-processor
                  key: remove-expired-data-on-day
                  optional: false
            - name: REMOVE_EXPIRED_REPORT_UTC_TIME
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}-processor
                  key: remove-expired-data-utc-time
                  optional: false
            - name: prometheus_multiproc_dir
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}-monitoring
                  key: prometheus-dir
                  optional: false
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}-debug
                  key: debug
                  optional: true
            - name: NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: masu-app
                  key: app-namespace
                  optional: true
            - name: CW_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: cloudwatch-aws-access-key-id
                  name: ${NAME}-aws
                  optional: true
            - name: CW_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: cloudwatch-aws-secret-access-key
                  name: ${NAME}-aws
                  optional: true
            - name: CW_AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: cloudwatch-aws-region
                  name: ${NAME}-aws
                  optional: true
            - name: CW_LOG_GROUP
              valueFrom:
                secretKeyRef:
                  key: cloudwatch-log-group
                  name: ${NAME}-aws
                  optional: true
          resources:
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - ${NAME}-scheduler
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
      type: ImageChange

parameters:
- description: The name assigned to all frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: koku
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: koku
- description: Initial amount of CPU the Flower container will request.
  displayName: Celery Flower CPU Resource Request
  name: CPU_REQUEST
  required: true
  value: 100m
- description: Maximum amount of CPU the Flower container can use.
  displayName: CPU Limit
  name: CPU_LIMIT
  required: true
  value: 300m
- description: Initial amount of memory the Flower container will request.
  displayName: Celery Flower Memory Resource Request
  name: MEMORY_REQUEST
  required: true
  value: 256Mi
- description: Maximum amount of memory the Flower container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: Number of Celery scheduler replicas
  displayName: Celery scheduler replica count
  name: REPLICAS
  required: true
  value: '1'
