name: Check Clowdapp

on:
  pull_request:
    branches:
      - main

jobs:
  check-clowdapp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check manifest
      run: bash .github/scripts/check_clowdapp.sh
