name: Regular base image update check
on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install skopeo
        run: sudo apt-get install -y skopeo

      - name: Check change
        run: |
          skopeo inspect "docker://registry.access.redhat.com/ubi9-minimal:latest" | grep -Po '(?<="Digest": ")([^"]+)' > .baseimagedigest
          docker run --rm --entrypoint sh -u 0 quay.io/cloudservices/koku:latest -c \
            'yum upgrade -y --security > /dev/null; rpm -qa | sort | sha256sum' \
            >> .baseimagedigest

      - name: Do change if the digest changed
        run: |
          git config user.name 'Update-a-Bot'
          git config user.email 'insights@redhat.com'
          git add .baseimagedigest
          git commit -m "chore(image): update and rebuild image" || echo "No new changes"

      - name: Create pull request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
        with:
          title: 'chore(image): update base image'
