name: Check Clowdapp

on:
  pull_request:
    branches:
      - main

jobs:
  check-clowdapp:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 0

    - name: Check manifest
      run: bash .github/scripts/check_clowdapp.sh
