name: Sanity

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Install Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.8'

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0
        env:
          SETUPTOOLS_USE_DISTUTILS: stdlib

  check-clowdapp:
    name: Clowdapp
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Check manifest
        run: bash .github/scripts/check_clowdapp.sh
