name: SonarCloud

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
    sonarcloud:
      name: SonarCloud
      runs-on: ubuntu-20.04
      if: github.event.workflow_run.conclusion == 'success'
      steps:
        - name: Checkout
          # this checkout is required for the coverage report. If we don't do this, then
          # the uploaded report is invalid and codecov doesn't know how to process it.
          uses: actions/checkout@v3.1.0
          with:
            repository: ${{ github.event.workflow_run.head_repository.full_name }}
            ref: ${{ github.event.workflow_run.head_branch }}
            fetch-depth: 0

        - name: Download coverage result from units
          # The offical actions/download-artifact action does not allow downloading
          # artifacits from other workflow runs.
          uses: dawidd6/action-download-artifact@v2.27.0
          with:
            name: coverage
            github_token: ${{ secrets.GITHUB_TOKEN }}
            commit: ${{ github.event.workflow_run.pull_request[0].head.sha }}
            run_id: ${{ github.event.workflow_run.id }}

        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@v1.9.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            args: >
              -Dsonar.scm.revision=${{ github.event.workflow_run.head_sha }}
              -Dsonar.pullrequest.key=${{ github.event.workflow_run.pull_requests[0].number }}
              -Dsonar.pullrequest.branch=${{ github.event.workflow_run.pull_requests[0].head.ref }}
              -Dsonar.pullrequest.base=${{ github.event.workflow_run.pull_requests[0].base.ref }}
