name: Smoke Test traffic light

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: get Docker image files
        id: docker-files
        run: .github/scripts/dockerignore_files.sh >> docker-files.txt

      - run: cat docker-files.txt

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v13
        with:
          files_from_source_file: docker-files.txt

      - id: check-files
        run: |
          if [ ! -z "${{ steps.changed-files.outputs.all_changed_and_modified_files }}" ]; then
            echo "::set-output name=run-tests::true"
          fi
    outputs:
      run-tests: ${{ steps.check-files-or-fork.outputs.run-tests }}

  traffic-light:
    runs-on: ubuntu-20.04
    steps:
      - name: "Setting smokes-required label"
        uses: actions/github-script@v3
        if: ${{ needs.setup.outputs.run-tests == 'true' }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [ 'smokes-required' ]
            })
